### ISSUE TITLE
Add CSS to make display less ugly

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#10]
The entire application needs to be styled with CSS.

**Comment by gvwilson** [comment]
See also #99.

**Comment by pbanaszkiewicz** [comment]
We're already using Bootstrap v3, but we can use it wiser.  This issue is directly connected to #99 and #170 and should be deferred as well.

**Comment by pbanaszkiewicz** [comment]
Amy's looking pretty good, so I think this can be closed now.
