### ISSUE TITLE
Allow pre-population of Group in training request form

### ISSUE THREAD

**Issue by jduckles** [swcarpentry/amy#1005]
It would be nice to be able to allow a pass through of the group_name in order to pre-populate the form with the appropriate group name. I have a group that would like to open up applications in their organization and then be able to go through a process in conjunction with us to help select the instructors who will be trained.

This feature would allow us to sent out a URL which is something like:
`https://amy.software-carpentry.org/workshops/request_training/?id_group_name=Thisisatest`

From my read of [this stackoverflow](http://stackoverflow.com/questions/25173991/how-to-pre-populate-django-form-with-part-of-url) topic I think it would be a slight tweak to the View to make it happen.

**Comment by gvwilson** [comment]
See also #877.
