### ISSUE TITLE
Small improvements to training request workflow

### ISSUE THREAD

**Issue by chrismedrela** [swcarpentry/amy#1007]
In the training requests list view:

- [x] Display dates in "created at" column using "yyyy-mm-dd" format to make the column compact.
- [ ] ~~Let users filter by state using multichoice widget (three checkboxes instead of one drop-down).~~
- [x] Display only pending and accepted requests by default.
- [x] Display email in `submitter` column.
- [x] Display email in `submitter` and `matched trainee` columns in a new line, below full name, so that the columns don't take too much space.

Other stuff:

- [x] Change validation rules so that a request is accepted when it's matched to a training (now it's accepted when it's matched with an account)
- [x] Change title of training request edit view to something meaningful (from `TrainingRequest object` to `Training request #11`)

**Comment by chrismedrela** [comment]
@gvwilson, do you want me to enforce in validation rules that a pending request cannot be matched to a training and an accepted one must be matched to a training?

**Comment by gvwilson** [comment]
Pending cannot be matched to training.

Accepted doesn't necessarily have to be matched to training: the use 
case is:

1. We have several training events coming up.

2. We score applications and accept those that are to be distributed 
amongst the events.

3. We then assign them to training events.

In this case, "accepted" is being used to filter/select applications.

**Comment by chrismedrela** [comment]
@gvwilson, do you want any other choices (like "all")?
![image](https://cloud.githubusercontent.com/assets/1645996/18919005/ed59dce0-859c-11e6-803f-ee03b10367af.png)
I think that a drop-down is faster to use than three checkboxes. And definitively easier to implement. Is it fine?

**Comment by gvwilson** [comment]
Sure, and thanks.

**Comment by chrismedrela** [comment]
PR #1030
