### ISSUE TITLE
In bulk add person, interpret "role" column and use <select>.

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#1015]
In bulk add persons (https://amy.software-carpentry.org/workshops/persons/bulkadd/) we are given a csv template which is useful.

However, the names of roles as they display to the end user are not the same as the names of roles as stored in the database.  Can we either have instructions on what the roles need to be or have the csv importer translate this?

**Comment by chrismedrela** [comment]
@maneesha, here is the translation:

| name in db | verbose name |
| --- | --- |
| contributor | Contributed to lesson materials |
| organizer | Workshop organizer |
| learner |	Learner |
| host | Workshop host |
| instructor | Instructor |
| helper | Helper |

Where could I put the instructions you asked for?

**Comment by pbanaszkiewicz** [comment]
We should:

1. match any-case 
2. provide a `<select>` to choose from for roles when editing a role in the table

**Comment by maneesha** [comment]
@chrismedrela The instructions should go on the Bulk Import page.  I also like @pbanaszkiewicz idea to match case and select to edit.

**Comment by pbanaszkiewicz** [comment]
This wasn't completely fixed in #1023.
