### ISSUE TITLE
Display SWC or DC tag next to workshop slug in "Current" list

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#1016]
On the main page  -  it would be useful to see at a glance whether the workshops listed as "Current" were SWC or DC. 

If you need room for this, the "Uninvoiced" column can be narrower.  The "ID" column in the "Unpublished" column can also be removed - this is unnecessary.

**Comment by chrismedrela** [comment]
Something like that? Do you want the labels to be on the left side or maybe somewhere else?
![image](https://cloud.githubusercontent.com/assets/1645996/18809672/63949ed6-8282-11e6-9552-0b80250b6474.png)

**Comment by maneesha** [comment]
@chrismedrela - Yes, that's along the lines of what I was thinking of.  
Could we have the labels and slug text aligned?  See sample:
![63949ed6-8282-11e6-9552-0b80250b6474](https://cloud.githubusercontent.com/assets/829690/18878860/30c1e084-84a0-11e6-8e4a-1969c857cb18.png)

**Comment by chrismedrela** [comment]
PR #1025
