### ISSUE TITLE
Enable filtering by multiple partnership levels on organizations.

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#1032]
We should be able to filter organizations according to their partnership level.  User should be able to select multiple partnership levels, which should be combined with 'or' (i.e., show me silver or bronze).  For now, don't worry about temporal nature of partnerships: show all organizations that have, or have ever had, a particular partnership level.

**Comment by chrismedrela** [comment]
@gvwilson, when you say partnership, do you mean `Membership`? 

Also, I don't think we track partnership levels (silver, bronze etc.) -- we only track variant (partner/affiliate/sponsor) and contribution type (financial/person-days/other).

**Comment by chrismedrela** [comment]
Ahh, ok, I've just had a look at #1034 and I see there are new variants (bronze, silver etc.).

**Comment by gvwilson** [comment]
Yes, sorry, Membership, and I've added the new levels.
