### ISSUE TITLE
Display current partnership level in organization display.

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#1035]
Related to #1032, the "all organizations" page should have a column to show current membership status (if any).  Note "current": this page doesn't need to show memberships that are out of date.

**Comment by chrismedrela** [comment]
@gvwilson, what exactly should be displayed in the column? `Membership.variant` (partner/affiliate/other) and `Membership.contribution_type` (financial/person-days/other)?

**Comment by gvwilson** [comment]
Just `Membership.variant` will be enough - that tells us what our 
training obligations are.
