### ISSUE TITLE
Remove invoicing link

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#1040]
Please remove the invoicing button from the event page - this is not ready to go live.
The invoicing form (in case anyone has bookmarked it) should not be displayed. That page should read:

> Please contact admin@software-carpentry.org if you need to submit an invoice.  Include the following information in your email: 
> * Link to workshop page in AMY
> * Purpose of invoice
> * Amount of invoice in US Dollars
> * Name, email, phone, and mailing address of person who should receive in invoice
>

**Comment by pbanaszkiewicz** [comment]
@maneesha you want to disable the admin-only part of AMY that handles invoice requests, correct?

**Comment by maneesha** [comment]
Correct.
