### ISSUE TITLE
Connect instructor training sessions to partnership agreements

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#1055]
We need a way to say "this event satisfies or partially satisfies our obligations for that partnership agreement".  (Right now, I'm storing that as free text.)  A many-to-many between events and partnership agreements (_not_ partners) would do this.

**Comment by chrismedrela** [comment]
> A many-to-many between events and **partnership agreements** (not partners) would do this.

@gvwilson, do you mean `Membership`?

**Comment by gvwilson** [comment]
Yes, sorry.

**Comment by jduckles** [comment]
The mechanics for this exist for tracking workshops. We should track the number of instructors we commit to in the agreement and the number trained. This way we can report on it to the partner organization when we have periodic meetings with them. The mechanics of this should already exist for how we're doing "imposed/completed/remaining" for two classes of workshops. Rather than workshops this would be people attending a special workshop (a ttt).

**Comment by chrismedrela** [comment]
@gvwilson does it solve this issue? If yes, please close this issue.

**Comment by gvwilson** [comment]
I don't think so - the many-to-many between a specific membership agreement (rather than a specific institution) and specific training events still isn't there.  We'll tackle this after we get v1.9 out of the way.

**Comment by chrismedrela** [comment]
> We need a way to say "this event satisfies or partially satisfies our obligations for that partnership agreement". (Right now, I'm storing that as free text.) 

@gvwilson, why storing this kind of information in `notes` is not enough?

**Comment by gvwilson** [comment]
Because then there's no easy way to find out what the status of our 
obligations to partners is - right now, if I want to know that 
2016-10-20-ttt-online fulfilled our commitment to Michigan State 
University, I have to... well, I just have to know.

**Comment by chrismedrela** [comment]
OK, so what about a simpler approach:
- adding `Membership.obligation_status` which can be 1) not fulfilled, 2) partially fulfilled or 3) fulfilled
- continuing to store more details in `notes`?

That lets you filter memberships (or even organizations) by our obligation status.

**Comment by gvwilson** [comment]
Let's discuss this after v1.9.

**Comment by chrismedrela** [comment]
@maneesha do you want this feature in v1.10 or can we move it to the backlog? If you want this feature, what do you think about the simpler approach I proposed?

**Comment by ErinBecker** [comment]
I'm reactivating this discussion based on conversations that the Instructor Training team (@maneesha, @karenword, and myself) and @tracykteal and @sheraaron have been having about changes to how we allow members to divide up their seats in instructor training events. 

When an institution signs on as a member, they receive a certain number of seats in instructor training. Currently (at least in theory), all of those seats are supposed to be in a single event, making it possible to do this binary "fulfills"/"doesn't fulfill" tracking. 

However, we are moving to a system where we allow members to divide their seats across multiple instructor training events. To accommodate this, we need to be able to record for a particular member institution:
1) how many seats in instructor training they have for a particular time period, 
2) how many trainees they have had assigned to an instructor training event already. 

Together, these will allow us to calculate:
3) how many seats they have remaining.

The number in (1) is the number of seats in their membership contract PLUS (potentially) any additional seats they have purchased in instructor training. This means that number needs to be editable.

The number in (2) should be calculated by assigning trainees to a member institution as well as a training event. We already assign trainees to events, if we can assign to a member institution, then we can do this math.

Currently, for tracking membership information we have the following: 

![screen shot 2018-08-24 at 12 50 38 pm](https://user-images.githubusercontent.com/19176319/44605226-5aceb380-a79d-11e8-9b81-e192f7669388.png)

We would need to add a field to the membership category that tracks (1), (2), and (3) above. I know it's too late to get this change into the Aug 31 release. Can you please take a look at what we're requesting and let me know if it's possible to get it into the release after this one? What is the timeline for the subsequent release? I'm happy to provide any more information that is needed, just let me know.

**Comment by maneesha** [comment]
We currently track the number of workshops run under a membership agreement. We also need to track the number of instructors allowed and the number trained under each agreement.  [Here](https://docs.google.com/document/d/1uz8J5vr3aApxQ_mlsgCh-yTEpqI-nU9VqQXu8SfgyH0/edit) is a draft of what I thought this may look like.

**Comment by pbanaszkiewicz** [comment]
@maneesha the draft looks doable. Just one question to make sure I understand it correctly:
this change means that memberships will not be about "regular" (non-TTT) workshops, but about seats in TTT workshops, correct?

**Comment by maneesha** [comment]
@pbanaszkiewicz  Yes this refers only to TTT workshops.

**Comment by pbanaszkiewicz** [comment]
@maneesha so "workshops w/o fee per agreement" and "self-org. workshops per agreement" will not change?

**Comment by ErinBecker** [comment]
@pbanaszkiewicz  - That's correct. Those fields would continue to be tracked as they are currently. There would be a new field (or fields) to track the information about number of seats in TTT events.

**Comment by pbanaszkiewicz** [comment]
@maneesha @ErinBecker @karenword @sheraaron @tracykteal  I have it almost complete now. We should schedule a video conference this week so that I can present it to you (it's faster than setting up a AMY development instance server).

**Comment by ErinBecker** [comment]
👍 🎉
