### ISSUE TITLE
Allow null family name

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#1076]
Sometimes people identify themselves by only one name.
It looks like this was historically allowed as we do have people without a family name in the database, but new records require a family name.

**Comment by gvwilson** [comment]
Apologies for the regression - @chrismedrela can you please add a test 
for this and then wind us back?  @maneesha how is this showing up - are 
we seeing error messages in AMY in production?

**Comment by chrismedrela** [comment]
Although `Person.family` never allowed blank values, this may happened when you bulk upload people. The codebase from 2015-10-02 contains this line:
```python
Person.objects.get_or_create(email__iexact=..., defaults={whatever you provided in csv file}).
```
This successfully works even if you provide `defaults={'personal': 'Bob', 'family': ''}`.

So what needs to be done:
- [ ] Make `Person.family` optional.
- [ ] Add regression test for adding single person without family name.
- [ ] Add regression test for editing single person without family name.
- [ ] Add regression test for bulk add people without family names.
- [ ] Add test to make sure that bulk add people doesn't accept people without first name.

**Comment by maneesha** [comment]
Sorry - meant to respond to this sooner.  Currently, the family name field is required both for Bulk Add Persons and for creating an individual person (https://amy.software-carpentry.org/workshops/persons/add/).
