### ISSUE TITLE
Revision webpages are messed up

### ISSUE THREAD

**Issue by chrismedrela** [swcarpentry/amy#1083]
1. Go to https://amy.software-carpentry.org/workshops/person/9963/
2. Click links next to "Created on" and "Last modified on".
3. You can see that both revisions have nothing in common with the person.

**Comment by chrismedrela** [comment]
This is due to an assumption [here](https://github.com/swcarpentry/amy/blob/develop/workshops/views.py#L2166) that each revision consists of only one version. (Version is a change to one record. Revision is a bunch of versions.)

**Comment by chrismedrela** [comment]
@maneesha does anybody uses revisions? Has it ever been used? If not, we could remove this feature from frontend.

**Comment by maneesha** [comment]
I use this feature and would like to fix and keep it.
