### ISSUE TITLE
Delete button doesn't work in edit views

### ISSUE THREAD

**Issue by chrismedrela** [swcarpentry/amy#1085]
This is because delete views redirects to URL with appended `/delete`, i.e. `workshops/training_progress/1172/edit/delete` instead of `https://amy.software-carpentry.org/workshops/training_progress/1172/delete`.

A workaround is to delete objects from detailed view. This workaround doesn't work for TrainingProgresses, because they don't have detailed view (see #1084).

**Comment by narayanaditya95** [comment]
FWIW, I believe that the delete button should be displayed on the detail view and not the edit view. That is what I have observed most of the times.

**Comment by gvwilson** [comment]
@pbanaszkiewicz ?

**Comment by pbanaszkiewicz** [comment]
I lean towards "Delete" button on the detail view (and in some cases on the list view).

**Comment by narayanaditya95** [comment]
@pbanaszkiewicz Do you propose we add a detail view for training progress objects?

**Comment by pbanaszkiewicz** [comment]
@narayanaditya95 yes if it's not too much work. If someone is lazy, fixing just the URL on the edit view would be fine too.

**Comment by narayanaditya95** [comment]
That seems to be the easiest way out. +1

**Comment by chrismedrela** [comment]
:+1: for having delete buttons on detail views and removing them from edit views.
