### ISSUE TITLE
Email senders of training request form

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#1088]
Thank you for your application for Software Carpentry/Data Carpentry instructor training.  Due to high demand, the waiting time for open instructor training events is currently 8-12 months as we try to clear our backlog.  If you are affiliated with one of our institutional partners (listed at http://software-carpentry.org/scf/partners), we will do our best to prioritize your application; if you or your institution would like to discuss partnership, we would welcome an opportunity to speak with you.

**Comment by maneesha** [comment]
Broader than this - I'd like an autoresponder to any form (instructor application, workshop request, etc.)

**Comment by chrismedrela** [comment]
@maneesha let's narrow the scope of this issue only to training request form. I've created an issue (#1160) for other external forms.
