### ISSUE TITLE
Permissions system: "admin"-considered groups don't grant template-scope permissions

### ISSUE THREAD

**Issue by pbanaszkiewicz** [swcarpentry/amy#1095]
In [`models.py:545`](https://github.com/swcarpentry/amy/blob/develop/workshops/models.py#L545) we have a `is_admin` function that determines if person should have admin privileges based on groups they're in. For example, any trainer is considered admin.

In the templates, however, we explicitly check for permissions, like `workshops.change_person` in [`workshops/templates/workshops/person.html`](https://github.com/swcarpentry/amy/blob/develop/workshops/templates/workshops/person.html#L10). The issue is, this check fails for people in `trainers` group because, even though `trainers` is considered an admin group, it doesn't have the `workshops.change_person` permission.

**Comment by narayanaditya95** [comment]
Just to be clear, we intend on allowing trainers to edit their individual profile only, right?

**Comment by gvwilson** [comment]
Yes.

**Comment by narayanaditya95** [comment]
My exams concluded yesterday evening.
I am working on a refactor. I hope you like it.

**Comment by gvwilson** [comment]
Thanks Aditya - hope the exams went well.

**Comment by pbanaszkiewicz** [comment]
> My exams concluded yesterday evening.

Congrats!
