### ISSUE TITLE
Incorrect redirect on deleting an award from person detail page

### ISSUE THREAD

**Issue by narayanaditya95** [swcarpentry/amy#1097]
On the `person_detail` page, deleting an award from the _Awards_ tab takes you to the `badge_detail` page.

Should it be redirected back to the `person_detail` page?

**Comment by gvwilson** [comment]
Yes please.

**Comment by chrismedrela** [comment]
But if you delete an award from `badge_detail`, you should be redirected back to `badge_detail`.

**Comment by narayanaditya95** [comment]
@chrismedrela I will ensure that. Thanks!
