### ISSUE TITLE
AMYDeleteView and RedirectSupportMixin achieve different redirection

### ISSUE THREAD

**Issue by narayanaditya95** [swcarpentry/amy#1101]
The `next` param to the `AMYDeleteView` is a POST param while to any view subclassing the `RedirectSupportMixin` mixin, the `next` param is a GET param. The two achieve the same thing, but differently.

I propose that we strip the `AMYDeleteView` of any redirect support and use `RedirectSupportMixin` along with `AMYDeleteView`.

**Comment by pbanaszkiewicz** [comment]
Sounds good to me (y)
