### ISSUE TITLE
Require everyone to agree to confidentiality

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#1108]
Reviving old issue: we need a page that requires people to agree to the confidentiality agreement, and a database entry recording who has agreed to it.

**Comment by pbanaszkiewicz** [comment]
> Reviving old issue: we need a page that requires people to agree to the confidentiality agreement, and a database entry recording who has agreed to it.

What people do you specifically have in mind?

**Comment by gvwilson** [comment]
Everyone who has access to other people's data - someone who can only 
view/update their own profile doesn't need to, but anyone who can 
view/modify someone else's information does.

**Comment by chrismedrela** [comment]
@gvwilson is it enough if we just add BooleanField (to Person model) indicating whether they agreed and make the field editable in Person edit view?

**Comment by gvwilson** [comment]
It's @maneesha's call.

**Comment by pbanaszkiewicz** [comment]
I think recent changes for GDPR cover this.
