### ISSUE TITLE
Comment box on discarding requests

### ISSUE THREAD

**Issue by gperu** [swcarpentry/amy#1112]
Event-requests should be normally accepted and thus recorded, even though not always a real workshop will follow.
However, there are cases when a request may be dicarded and this functionality is already given. 
It would be opportune to complement this functionality with a comment box in which we can add a reason for discarding.

**Comment by maneesha** [comment]
No event request should be discarded unless it is spam or otherwise inappropriate.  

All requests should be accepted. We want to maintain a history of everyone who has ever requested a workshop of us. If a workshop never comes to be, you can tag it as stalled.

**Comment by chrismedrela** [comment]
@gperu So do I understand correctly that you want additional "notes" field added to workshop requests (not training request)? @maneesha do you need that field?

**Comment by maneesha** [comment]
I don't think we need an additional "notes" field.  As noted above, every workshop request should be accepted unless it is spam or otherwise inapproriate.  We want to maintain a record of every request that comes our way.   If the workshop does not end up actually happening, we can mark it as follows (copied directly from AMY):

> - stalled — for events with lost contact with the host or TTT events that aren't running.
> - unresponsive – for events whose hosts and/or organizers aren't going to send us attendance data.
> - cancelled — for events that were supposed to happen, but due to some circumstances got cancelled

.

**Comment by chrismedrela** [comment]
I'm closing it. Each accepted workshops request is associated with an Event record where you have "notes" field.
