### ISSUE TITLE
ReCaptcha not working - Google's fault?

### ISSUE THREAD

**Issue by pbanaszkiewicz** [swcarpentry/amy#1116]
It's been reported that Captcha mechanism stopped working.

I checked and confirmed that it doesn't work with "NOCAPTCHA" setting (Google servers return 400 error), but switch back to old captcha solved that issue.

**Comment by chrismedrela** [comment]
@pbanaszkiewicz I cannot reproduce it, even on production. I've changed `NOCAPTCHA` setting back to True on production and it looks like training request form works. Could you confirm that it works again as expected?

**Comment by pbanaszkiewicz** [comment]
@chrismedrela apparently this bug got fixed on Google's end. Closing.
