### ISSUE TITLE
Merge `MockAwardCreate` and `AwardCreate` classes.

### ISSUE THREAD

**Issue by chrismedrela** [swcarpentry/amy#1122]
Also `MockAwardDelete` and `AwardDelete`. 

To generate proper MRO, you need to put `RedirectSupportMixin` as the very first base class:

```python
class AwardDelete(RedirectSupportMixin, OnlyForAdminsMixin, PermissionRequiredMixin, AMYDeleteView):
    ...
```

**Comment by pbanaszkiewicz** [comment]
@chrismedrela have you tried this solution? Because I did try this for `AwardCreate` and `MockAwardCreate` and it simply doesn't work.

**Comment by chrismedrela** [comment]
@pbanaszkiewicz No, I just compared MROs. You're right, we cannot merge these two classes.
