### ISSUE TITLE
EventQuerySet.unpublished_conditional makes annotating events sometimes wrong

### ISSUE THREAD

**Issue by pbanaszkiewicz** [swcarpentry/amy#1128]
Any event with tag "cancelled" will *sort-of* appear twice in results for Django, therefore making annotation's result double, however finally there will be only *single* event in the query set.

More details:

* https://github.com/swcarpentry/amy/pull/1127#discussion_r95062085
* https://github.com/swcarpentry/amy/pull/1127/commits/0fe717ec78b6fb223065edf871dd60c6807fe8e0

**Comment by chrismedrela** [comment]
@pbanaszkiewicz could you provide an example when it gives wrong result (for example in the production data)?

**Comment by pbanaszkiewicz** [comment]
@chrismedrela this: https://amy.software-carpentry.org/workshops/event/2016-07-14-jackson/

You need to get production database and run [this annotation](https://github.com/swcarpentry/amy/pull/1127/files#diff-ff40cc33cf5228ac8b825f8d4f9ef9b8R187) and compare `num_instructors` with `event.task_set.instructors.count()`.
