### ISSUE TITLE
Generating fake data

### ISSUE THREAD

**Issue by chrismedrela** [swcarpentry/amy#1132]
@gvwilson needs fake data by the end of this week - see [discussion on amy-dev](http://lists.software-carpentry.org/pipermail/amy-dev/2017-January/000216.html).

We have `fake_database` command line tool to generate fake data. Unfortunately, it's out of date and it doesn't generate fake training requests, workshop requests etc.

In my opinion maintaining this tool requires more resources than manually creating a database with fake data, migrating it and adding new records as we add new models. So I propose that:

1) We generate the fake database using the tool and manually add missing entries for fake training requests, workshop requests etc.
2) We migrate the database and add entries for new models as part of release.
3) (optionally) We remove `fake_database` tool.

@pbanaszkiewicz any opinions?

**Comment by pbanaszkiewicz** [comment]
I disagree:

1. with `fake_database` we can for example create events that are time-dependant - for example some that belong to "ongoing" category
2. with `fake_database` we can stay DB-agnostic
3. we don't pollute git repository with blob data that changes frequently; instead we can track what and how changed in the generated database.

**Comment by chrismedrela** [comment]
> with fake_database we can for example create events that are time-dependant - for example some that belong to "ongoing" category

Valid point.

> with fake_database we can stay DB-agnostic

If we store dumped .json (using dumpdata/loaddata commands) instead of binary .sqlite3, we can stay db-agnostic.

> we don't pollute git repository with blob data that changes frequently; 

My point was that we update the database only when doing a release, in order to avoid frequent changes and merge conflicts.

After rethinking, I've changed my mind and I think it's a bit easier to generate _a lot of_ fake entries using `fake_database`, which would be useful for screencasts that gvwilson wants to make.
