### ISSUE TITLE
Remove timeline from dashboard

### ISSUE THREAD

**Issue by chrismedrela** [swcarpentry/amy#1135]
Is the timeline on the admin dashboard used by anybody?

**Comment by maneesha** [comment]
I am not using it.

**Comment by pbanaszkiewicz** [comment]
:+1: for removing the timeline and TODOs if no-one uses them.

**Comment by pbanaszkiewicz** [comment]
@chrismedrela actually I just found out that Giacomo uses TODOs from time to time. Please check with him if he needs the timeline.

**Comment by chrismedrela** [comment]
@gperu do you use timeline?

**Comment by chrismedrela** [comment]
On Jan 22, @pbanaszkiewicz mailed @gperu and added me to cc:

> we're considering removal of the timeline from AMY home page, as well as TODO functionality.
>
> We know that Maneesha doesn't use the timeline, but I found out that you have some TODOs saved in AMY. Can you tell us if this is important to you and we should keep that functionality, or can we remove it?

On Jan 23, @gperu responded:

> please go ahead, none of those functionalities are vital to me. I do use the TODO’s as memos but I will use the comment text box in the future.
