### ISSUE TITLE
Email senders of any external forms

### ISSUE THREAD

**Issue by chrismedrela** [swcarpentry/amy#1160]
This is an extension to #1088. 

@maneesha could you provide us email subjects and bodies for the following forms:
- [SWC Event request](https://amy.software-carpentry.org/forms/swc/request/)
- [DC Event request](https://amy.software-carpentry.org/forms/dc/request/)
- [DC self organized event](https://amy.software-carpentry.org/forms/dc/request_selforganized/)

**Comment by pbanaszkiewicz** [comment]
@maneesha do you want to automatically send confirmation emails to people who submit workshop request form?

**Comment by pbanaszkiewicz** [comment]
Closing since Event Requests, Event Submissions and DC Self-Organized Event Requests are deprecated, Workshop Requests don't require confirmation emails (@maneesha please reopen if you think otherwise) and Training Requests have a responder email.
