### ISSUE TITLE
Navbar wraps and covers content on small screens

### ISSUE THREAD

**Issue by chrismedrela** [swcarpentry/amy#1166]
If you're window is 1130 pixels wide or narrower, the navbar wraps (see picture below):
![image](https://cloud.githubusercontent.com/assets/1645996/24367349/994463ba-131c-11e7-950c-3f8448656c79.png)

I propose to:

1. move "persons" to "more"
2. rename "requests/forms" to "requests"
3. make search textfield narrower

**Comment by chrismedrela** [comment]
Additionally, on pages with fixed template (like Person detailed view), even 1185 pixels is not enough:
![image](https://cloud.githubusercontent.com/assets/1645996/24368643/7b188cc2-1321-11e7-8121-2ede642b259a.png)

**Comment by pbanaszkiewicz** [comment]
Okay, but why? The unwritten rule is that we support 1366 x 768 or something like that, and I do seem to remember us talking about this some time ago.

**Comment by chrismedrela** [comment]
> Okay, but why?

Just for my easy of development. :-P If nobody else has the same issue, I'm willing to just zoom out in my browser.

**Comment by chrismedrela** [comment]
I'm reopening it, because this is an issue on pages with fixed layout, i.e. [all_activity_over_time](https://amy.software-carpentry.org/workshops/reports/all_activity_over_time/):
![image](https://cloud.githubusercontent.com/assets/1645996/25131344/9f696e18-2445-11e7-9d27-4acce4dfed32.png)

**Comment by chrismedrela** [comment]
The PR renames "requests/forms" to "requests".
