### ISSUE TITLE
Add ability to merge workshop request into existing workshop

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#1179]
Sometimes a host emails info about a workshop and staff enters that in AMY.  Later someone at the host site submits an actual request form.  I'd like to be able to merge that form into the existing event.

**Comment by chrismedrela** [comment]
@maneesha when you say "actual request form", do you mean:

1. "workshop submission" 
2. or both "workshops request" and "DC self-organized workshop request"?

And, by the way, what's the difference between 1. and 2.?

**Comment by maneesha** [comment]
I would like the ability to merge any of these submissions in to an existing event:

https://amy.software-carpentry.org/workshops/requests/
https://amy.software-carpentry.org/workshops/submissions/
https://amy.software-carpentry.org/workshops/dc_selforganized_requests/

**Comment by pbanaszkiewicz** [comment]
Currently there's not much overlap between actual `Event` model, and one of event "request" models: `EventRequest`, `EventSubmission`, `DCSelfOrganizedEventRequest`. #1329 provided two ways to solve this issue:
1. It's possible to connect one request with one event; they become related and it's possible to see the relations on event's details page; one event can be related to one `EventRequest` and one `EventSubmission` and one `DCSelfOrganizedEventRequest`.
2. When accepting an `EventRequest` or `EventSubmission`, or `DCSelfOrganizedEventRequest`, it's possible to simultaneously fill out an event creation form; the view is split into two columns, the left column contains details of selected request, and the right column contains the form. After filling out and submitting the form, the newly created event is automatically linked to the request (using the feature from bullet 1.).
