### ISSUE TITLE
Search/submit button on the search page does not seem to work

### ISSUE THREAD

**Issue by anenadic** [swcarpentry/amy#1190]
Submit button on search page does not seem to have any affect (https://amy.software-carpentry.org/workshops/search/) - as in does not fire off the search it seems (Chrome 58, Mac OS X). The little search box in the header seems to work fine.

**Comment by maneesha** [comment]
Closing as this duplicates issue https://github.com/swcarpentry/amy/issues/1175
and is being worked on with PR https://github.com/swcarpentry/amy/pull/1182
