### ISSUE TITLE
User should be able to edit occupation and ORCID in profile

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#1196]
When a user logs in to view/edit their own profile currently they can not edit the ORCID or occupation fields.  This should be fixed so these fields can be edited.

**Comment by twitwi** [comment]
I cannot try this right now, but it is probably a matter of adding two lines ('occupation, 'orcid') to
https://github.com/swcarpentry/amy/blob/develop/workshops/forms.py#L1201

**Comment by pbanaszkiewicz** [comment]
Fixed in e7644fb9f454b92d250b56269b5dea9f1e358359.
