### ISSUE TITLE
Redirect index page

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#1197]
https://amy.software-carpentry.org/ should redirect to https://amy.software-carpentry.org/workshops rather than returning a 404.

**Comment by maneesha** [comment]
Reopening as this only works with the trailing slash.
https://amy.software-carpentry.org/ will redirect but https://amy.software-carpentry.org will not.
We can't expect that users will type in the trailing slash.

**Comment by pbanaszkiewicz** [comment]
@maneesha I can't reproduce. I did some tests and I can see that `https://amy.software-carpentry.org` is too being redirected to `https://amy.software-carpentry.org/workshops/`.

Are you sure the bug is still present? Maybe it was a different domain or different protocol?

**Comment by maneesha** [comment]
Looking into this more yes, it is my local settings :-(
Closing.
