### ISSUE TITLE
Change your own permission

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/amy#1199]
Looks like you can change your own permissions, include giving you superuser permission.

**Comment by maneesha** [comment]
Emailed @pbanaszkiewicz @chrismedrela @narayanaditya95  as this is an urgent fix.

**Comment by pbanaszkiewicz** [comment]
This view is accessible by people who are superusers or belong to any of the groups: administrator, steering committee, invoicing, trainers. All these people are considered admins in AMY and therefore are able to change other people's permissions.

**Comment by maneesha** [comment]
OK.  To be clear, regular users (who log in just to view/edit their own profiles) can not do this -- correct?

**Comment by chrismedrela** [comment]
> OK. To be clear, regular users (who log in just to view/edit their own profiles) can not do this -- correct?

Yes, they can't -- they don't have even access to the person edit view.

**Comment by rgaiacs** [comment]
> This view is accessible by people who are superusers or belong to any of the groups: administrators, steering committee, invoicing, trainers.

But non-administrators trainers can self-assign administrators.

**Comment by chrismedrela** [comment]
@rgaiacs I tried to reproduce it, but I cannot. If a person doesn't belong to `administrators` group and is not a superuser, then "change permissions" button is disabled and you cannot change your own or sb's else permissions. Could you provide me specific instructions how to reproduce it?

**Comment by pbanaszkiewicz** [comment]
Closing because it's not possible to change permissions by non-admin user. Additionally, a user considered admin needs to have `change Person` permission.
