### ISSUE TITLE
Responsive CSS issue

### ISSUE THREAD

**Issue by jduckles** [swcarpentry/amy#1210]
At intermediate window sizes it seems the login and + widgets flow to a second row and overlap half the person name. Very minor, but mildly annoying if you're at an intermediate window size.

![image](https://user-images.githubusercontent.com/119403/28947484-3a3b5a88-7904-11e7-81f7-7912e788782d.png)

**Comment by pbanaszkiewicz** [comment]
@jduckles I'm deferring this issue for now, because I want to make a slight redesign of AMY in near future. However, if this issue is very annoying, please let me know and I'll reopen @askingalot's PR #1235 and merge it.

**Comment by jduckles** [comment]
No worries.
