### ISSUE TITLE
Bulk upload persons - do not refresh page after "use existing person"

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#1216]
After doing a bulk upload persons,  often times there are many people who are already in the database.  The option to use existing person is useful for this.  However, it's tedious when you have to refresh the page after each update.  It would be better check of each person that has an existing record, and update them all at once.

**Comment by pbanaszkiewicz** [comment]
According to [this comment](https://github.com/swcarpentry/amy/pull/1301#issuecomment-407059034), if the provided in #1301 fix is insufficient, we'll revisit this issue.
