### ISSUE TITLE
Rackspace Hosting Won't be free in 2018

### ISSUE THREAD

**Issue by jduckles** [swcarpentry/amy#1218]
I just got word that our $2,000 per month credit for being an Open Source project from Rackspace will be going away in 2018.

We will need to review our hosting strategy and decide how to use these services more efficiently. Our current bill (which is completely credited) is $1,700/month for the services we're utilizing.

**Comment by jduckles** [comment]
FYI: @tracykteal @maneesha @swcarpentry/board

**Comment by k8hertweck** [comment]
What exactly is hosted on Backspace currently? Anything else besides AMY?

**Comment by jduckles** [comment]
Our website, mailing lists and etherpads are hosted (each on their own VM) there as well. Since we have a credit we're running much larger servers than we really need for some of the things. We also have amy-dev and amy production servers.

**Comment by ChristinaLK** [comment]
I assume our options are: 
- look for free server access elsewhere
- pay to stay on Rackspace
- pay elsewhere

**Comment by jduckles** [comment]
Well guess we don't have to worry for now. They just retracted the move:

> We apologize for any confusion yesterday’s communication may have caused. While we’re no longer accepting new applicants to the Open Source Discount (OSS) program, all existing OSS program customers will keep their credits. Rackspace is committed to open source technology, and we look forward to continuing to support you and your Open Source project.
