### ISSUE TITLE
Obligatory checkboxes in instructor training sign up form

### ISSUE THREAD

**Issue by tracykteal** [swcarpentry/amy#1219]
In our instructor training sign up form, at the bottom there are boxes that you have to check that you agree to in order to submit the form.

We had someone in an instructor training who isn't sure they can commit to these things, so doesn't want to check the button and formally commit to that obligation.

Those boxes are:

"
*I agree to complete this training within three months of the Training Course
The completion steps are described at http://swcarpentry.github.io/instructor-training/checkout/ and take a total of approximately 8-10 hours.

*I agree to teach a Software Carpentry or Data Carpentry workshop within 12 months of this Training Course
"

While we do want this to happen, we're not following up to make sure it happens, so having those as obligations might not make sense. So, we could consider changing those to optional or phrasing them a different way.

**Comment by karinlag** [comment]
....not sure I agree on this. However, this brings up the discussion (yet again) what the aims of our training is - are we training people to solely be instructors for us (and, if they're training as part of a partnership, the partner they belong to), or are we training people for a wider range of purposes. I could for instance readily see people wanting to join an instructor training, not to actually teach, but to do advocacy work and other things. I think that at present, something half of our instructors never teach (uncertain of the stats), but I still think good things come from it. Also, in the context of a partner training, shouldn't the partner be the one to decide whether they want to send only people who will teach for them, or if they want to include others too? 

A bit rambling, but anyhow.

**Comment by tracykteal** [comment]
Yeah, it does bring up bigger questions. Just wanted to pin it as an issue for future discussion.

**Comment by lexnederbragt** [comment]
Noted down as an (important) issue to be discussed by the Carpentries Executive Council. OK to close?

**Comment by tracykteal** [comment]
Yes, fine to close. I'll close.
