### ISSUE TITLE
Download selected trainee applications

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#1227]
From here (https://amy.software-carpentry.org/workshops/training_requests/) we can download a csv of all training applications.  If a filter or selection has been applied then we should also have the option of downloading only filtered or selected applications. 

(meaningless test edit)

**Comment by pbanaszkiewicz** [comment]
This was actually partially implemented in #1278: there now exists an API endpoint to filter and download applications. The only issue is that the button "Download all requests as CSV" doesn't apply filters to it; this will be an easy fix.
