### ISSUE TITLE
add curriculum identifier

### ISSUE THREAD

**Issue by ErinBecker** [swcarpentry/amy#1228]
In a workshop object, it would be good to know what curriculum was taught (e.g. DC Ecology, SWC with R) and be able to pull out that information so that we can track how often each curriculum is taught and link specific curricula to assessment.

**Comment by pbanaszkiewicz** [comment]
@ErinBecker some questions for you:
1. Can you provide me with a list of all curricula?
2. Is this list going to change frequently? How often / when?
3. Is workshop curriculum available via workshop page metadata (`<meta>` tags)?

**Comment by fmichonneau** [comment]
first drafts at:
- https://carpentries.github.io/curriculum-feed/carpentries_curricula.json
- https://carpentries.github.io/curriculum-feed/carpentries_lessons.json

**Comment by pbanaszkiewicz** [comment]
Thanks @fmichonneau, this clears things up for me. Unfortunately, I don't see curriculum/lessons in `<meta>` tags in [workshop template](https://raw.githubusercontent.com/carpentries/workshop-template/gh-pages/index.md). Without this tag, entering this additional information is admin's responsibility.

**Comment by fmichonneau** [comment]
I see. I'll add this info to the meta tags and report back here. Thanks.

**Comment by fmichonneau** [comment]
@pbanaszkiewicz after discussion, we decided that we would obtain more reliable data if this was entered by the workshop administrators. Current curriculum tags should be:

- swc-python
- swc-r
- swc-es-python
- swc-es-r
- swc-other
- dc-ecology-r
- dc-ecology-python
- dc-genomics
- dc-geopsatial
- dc-socsci-r
- dc-socsci-python
- dc-other
- lc

it would be nice if there was some validation (e.g., the swc-python curriculum tag could only be added if it was a SWC workshop).

These tags will change regularly (every ~6 months, mostly new ones will be added). Would having a regularly updating JSON feed (as mentioned above) be useful? would it be better to have an interface where Maneesha and Sher could create/update them?

**Comment by pbanaszkiewicz** [comment]
@fmichonneau:

I can add an entry in Django's Admin interface allowing admins to add/edit curriculum tags whenever necessary. Additionally we can have "active" field for the tags, which, when set to False, would not allow to apply this tag to any workshop. This way we'd preserve "old" tags and still be able to work easily with newer tags.

**Comment by fmichonneau** [comment]
That sounds perfect. Thanks @pbanaszkiewicz!

**Comment by pbanaszkiewicz** [comment]
@fmichonneau can you please provide me with human-readable names for these curricula? It turns out we're going to use them in one other place, but it requires showing them to the user, so friendlier language is preferred. I matched some, but not all:

slug | name
------|--------
`swc-python` | Software Carpentry (shell, git, Python)
`swc-r` | Software Carpentry (shell, git, R)
`dc-ecology-python` | Data Carpentry (Ecology with Python)
`dc-ecology-r` | Data Carpentry (Ecology with R)
`dc-genomics` | Data Carpentry (Genomics)
`dc-geospatial` | Data Carpentry (Geospatial)
`dc-socsci-python` | Data Carpentry (Social Sciences with Python)
`dc-socsci-r` | Data Carpentry (Social Sciences with R)

**Comment by fmichonneau** [comment]
Coming back from leave, @pbanaszkiewicz do you still need this info?

**Comment by pbanaszkiewicz** [comment]
@fmichonneau no, I used your list and one provided by @maneesha elsewhere and combined them together. Go to https://amy.software-carpentry.org/workshops/events/add/ and see "Curricula taught at the workshop" field for the results!

**Comment by fmichonneau** [comment]
Great, thank you!
