### ISSUE TITLE
Running make dev_database fails with "TypeError: 'gender' is an invalid keyword argument for this function"

### ISSUE THREAD

**Issue by askingalot** [swcarpentry/amy#1233]
Looks like changes to the `TrainingRequest` model were not reflected in the `fake_database.py` file.

Specifically, `gender`, `gender_other` and `additional_skills` were removed from the model and not removed from the fake_database.py file. Also `underresourced`, `underrepresented`,`nonprofit_teaching_experience`, `training_completion_agreement`, `workshop_completion_agreement` and `notes` were not being set in the `fake_databse.py` file

**Comment by pbanaszkiewicz** [comment]
Closing via #1234.
