### ISSUE TITLE
AMY and GDPR

### ISSUE THREAD

**Issue by lexnederbragt** [swcarpentry/amy#1242]
Should we be concerned with [GDPR](https://www.eugdpr.org)?

**Comment by maneesha** [comment]
@jduckles  is reviewing what we need to do & can provide an update.

**Comment by lexnederbragt** [comment]
Thanks. No need for details, I just wanted to make sure we don't oversee this...

**Comment by jduckles** [comment]
@lexnederbragt we'll be updating our privacy policy in light of GDPR and working to make sure the little bit of PID (Personally IDentifiable) info we do have on people is well protected. Thanks for bringing it up.
