### ISSUE TITLE
Google's switching Maps API to pricing model

### ISSUE THREAD

**Issue by pbanaszkiewicz** [swcarpentry/amy#1248]
Link: https://cloud.google.com/maps-platform/user-guide/

Let's consider updating AMY's maps to Open Street Maps. Apparently these are used by number of providers: https://help.openstreetmap.org/questions/9367/can-i-use-openstreetmaps-openstreetmaps-api-for-commercial-apps-on-android/9371
And some server bandwidth restrictions apply.

Does Carpentries website need to switch too? /cc @jduckles 

EDIT: https://wiki.openstreetmap.org/wiki/Deploying_your_own_Slippy_Map

**Comment by jduckles** [comment]
Are there maps anywhere in AMY? Or are you talking about the maps with date fed by amy on `swcarpentry/website`?

**Comment by maneesha** [comment]
@jduckles  in any event view, "validate event" returns a map (assuming location data is entered in)

**Comment by rgaiacs** [comment]
This is now a problem for us!

**Comment by pbanaszkiewicz** [comment]
I guess AMY website doesn't attract nearly as much traffic as SWC/DC/TC website. We're still able to access Google Maps, see for example: https://amy.software-carpentry.org/workshops/event/2015-10-03-Krakow-techspace/ (click on "Show preview").

**Comment by BernhardKonrad** [comment]
Do we have an estimate of how much traffic we get in an average month? If we're over the free budget we could consider applying at https://www.google.com/nonprofits/.

**Comment by jduckles** [comment]
@BernhardKonrad Unfortunately, as a fiscally sponsored project, we have to have the parent non-profit apply and then hopefully be able to pass on the credit to our project Google Cloud account. We've tried with Google in the past and are unable to qualify for Non-profit pricing on Google apps without being our own standalone 501(c)3. Our parent non profit runs 100 other projects other than ours. In my internal calculations, this would take more time than us figuring out the Leaflet, OSM, JS necessary for our limited use of maps.

It is more the fact that Google turned us off by default and wants us to tie a credit card to any and all possible future costs from surges in API usage, bad actors etc. That is the noose we don't want to tie around our neck in the new business model for the Google Maps API.

**Comment by jduckles** [comment]
#1319 closes this.
