### ISSUE TITLE
SWC tags have disappeared?

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#1252]
Looking at workshop list (https://amy.software-carpentry.org/workshops/admin-dashboard/?assigned_to=all) of published workshops, this used to display a tag for SWC or DC.  It looks like LC has been added to the display, but now SWC workshop tags are not displaying.  In the options to select  workshop tags, SWC is no longer an option so all the SWC tags seem to have disappeared.

![image](https://user-images.githubusercontent.com/829690/40491157-57b310c4-5f3b-11e8-9eba-a89c554c7144.png)

**Comment by pbanaszkiewicz** [comment]
Thanks for bringing this to my attention. It's really bizarre. Can you tell me if "SWC" tag was available yesterday? Did you notice any missing workshops?

**Comment by pbanaszkiewicz** [comment]
It seems like a very recent bug (max last two hours). I'm going to shut down AMY for now.

**Comment by pbanaszkiewicz** [comment]
Fixed via #1253.
