### ISSUE TITLE
Matched Training isn't working

### ISSUE THREAD

**Issue by sheraaron** [swcarpentry/amy#1255]
When I try to match applicant(s) to a particular training the "Matched Training" option doesn't allow me to type in the box, or it doesn't list any of the worskhops for me to select.

**Comment by pbanaszkiewicz** [comment]
For some reason, Select2 (drop-down) widget is not rendering for `MatchTrainingRequestForm` and `BulkMatchTrainingRequestForm`. Thanks @sheraaron for reporting this issue!
