### ISSUE TITLE
Implement Mailgun API for sending emails

### ISSUE THREAD

**Issue by pbanaszkiewicz** [swcarpentry/amy#1257]
In #1250 @jduckles suggested to change email address for AMY emails; we can take the opportunity and:
1. switch to Mailgun API instead of SMTP
2. implement sending emails in more places in AMY

**Comment by pbanaszkiewicz** [comment]
Tests went okay - Mailgun API works really well. Now I'm going to make a list of actions that require email notification and then go forth and implement Mailgun emails instead of Django SMTP.

**Comment by jduckles** [comment]
Great to hear! Let me know if you need anything.
