### ISSUE TITLE
What does Person.active mean?

### ISSUE THREAD

**Issue by wking** [swcarpentry/amy#127]
It landed with cba8d659 (Adding more information about people, 2014-12-01), but we don't seem to use it for anything.

**Comment by gvwilson** [comment]
People (including instructors) occasionally ask to have participation 
suspended (e.g., don't mail me for the next few months, I'm busy), and 
we need to respect that.

**Comment by wking** [comment]
On Thu, Jan 08, 2015 at 04:56:09PM -0800, Greg Wilson wrote:
> People (including instructors) occasionally ask to have
> participation suspended (e.g., don't mail me for the next few
> months, I'm busy), and we need to respect that.

So it means “do not contact”?

**Comment by gvwilson** [comment]
> So it means “do not contact”?
Yes - "do not contact for now"
