### ISSUE TITLE
Crop down API

### ISSUE THREAD

**Issue by pbanaszkiewicz** [swcarpentry/amy#1273]
API endpoints for creating/reading persons, awards, tasks, organizations, and airports are not being used at all. Maybe it's time to remove them.

**Comment by pbanaszkiewicz** [comment]
@fmichonneau can you please describe which parts of API you're using?

**Comment by fmichonneau** [comment]
At this time, I need the "persons" endpoint (only reading).  I'm working on a way to automate the workshop website creation, and need to validate (through the GitHub username) that the user is in AMY. I don't anticipate needing the other endpoints.

**Comment by jduckles** [comment]
@pbanaszkiewicz are you basing this on logs of access to these endpoints? We've got a plan afoot to use a periodically updated cache of AMY data to drive our instructors page (read-only).  The capabilities I need are mostly contained in the output of `api/v1/persons` right now.

**Comment by pbanaszkiewicz** [comment]
@jduckles:
> @pbanaszkiewicz are you basing this on logs of access to these endpoints?

No, but I know that some endpoints are linked with a feature that will be removed (e.g. user-todos); some other endpoints (like `person-list`, `airport-list`, `event-list`, etc.) were created with JS frontend in mind, but this is not going to happen (soon). If you and @fmichonneau have ideas how you can use these endpoints, then there's no point in removing them.

**Comment by pbanaszkiewicz** [comment]
I'm deferring this for now.
