### ISSUE TITLE
What does Cohort.active mean?

### ISSUE THREAD

**Issue by wking** [swcarpentry/amy#128]
It landed with 4633837 (Recording training cohorts, 2014-12-01), but we don't seem to use it for anything.  I expect it means “this cohort is still taking training classes”, but I'd rather represent that with Cohort.end (like we do with Event).  In fact, I'd rather use `Event` to represent instructor-trainging classes (#63).

**Comment by gvwilson** [comment]
I set Cohort.active to False to signal that work with this Cohort is now 
done, i.e., everyone who signed up either has a badge or should now be 
marked incomplete.  End dates could work, but they're often 
ill-defined.  Integrating with Event is appealing, but we need to figure 
out how to handle calendaring for that, both in the DB and in the 
workshop template.

**Comment by wking** [comment]
On Thu, Jan 08, 2015 at 04:57:35PM -0800, Greg Wilson wrote:
> I set Cohort.active to False to signal that work with this Cohort is
> now done, i.e., everyone who signed up either has a badge

This is already in the database as:

  not cohort.trainee_set.exclude(person__award__badge__name='instructor').exists()

> or should now be marked incomplete.

What's the cutoff for “they should all be marked incomplete”?  As I
understand it, cousework wraps up and then folks have to land a PR
somewhere.  If that's it, then I don't see the need for a hard
end-date to that PR.

> End dates could work, but they're often ill-defined.

End-of-coursework should be well defined.  Or do folks sign up for
instructor training in situations where you can't even estimate the
end-of-coursework date?

> Integrating with Event is appealing, but we need to figure out how
> to handle calendaring for that, both in the DB and in the workshop
> template.

Just record the current estimated (or actual) end-of-coursework date,
and handle it like all the other Event instances, right?

**Comment by gvwilson** [comment]
I think you think the instructor training is much more structured and 
much better managed than it actually is :-)
> Just record the current estimated (or actual) end-of-coursework date,
> and handle it like all the other Event instances, right?
How do we represent a workshop that runs on four consecutive Tuesday 
afternoons?  And how do we represent it in the hand-edited YAML headers 
of the index.html pages in workshop websites?  I can do a database 
schema for the first, but getting admins to update it will be painful.  
We're not going to include blobs of iCal in our YAML headers to handle 
the latter...
Thanks,
Greg

**Comment by wking** [comment]
On Thu, Jan 08, 2015 at 07:42:48PM -0800, Greg Wilson wrote:
> > Just record the current estimated (or actual) end-of-coursework
> > date, and handle it like all the other Event instances, right?
>
> How do we represent a workshop that runs on four consecutive Tuesday 
> afternoons?

The same way you handle it for Events: machine-readable start and end
dates, with free form human-readable descriptions
(swcarpentry/workshop-template#122).

> And how do we represent it in the hand-edited YAML headers of the
> index.html pages in workshop websites?

You have workshop websites for instructor training?  For Events of all
categories, I think a version of your humandate (with whatever name we
settle on) would work fine.  But that's a separate issue from
Cohort.active, which is even *less* informative about scheduling than
Event.end.

**Comment by wking** [comment]
On Sat, Jan 10, 2015 at 05:43:19AM -0800, Greg Wilson wrote:
> Closed #128.

Presumably in favor of #132.
