### ISSUE TITLE
Add search by github handle to API persons endpoint

### ISSUE THREAD

**Issue by fmichonneau** [swcarpentry/amy#1282]
Would it be possible to add the functionality to search for people using their github handle through the API? i.e. `https://amy.software-carpentry.org/api/v1/persons/?github=fmichonneau`

**Comment by pbanaszkiewicz** [comment]
Hello @fmichonneau. It's possible to add another filter to this endpoint, but with #1273 I was going to remove unused parts of API. I thought `/persons/` was unused.

Let's make this issue in current release (v1.12), and let's postpone #1273 to the next release.

**Comment by fmichonneau** [comment]
It might not be used within AMY, but I'd like to be able to use it in other external tools/services. Thanks for implementing it!
