### ISSUE TITLE
Add Country to Person record

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#1294]
Right now we have location by airport which makes it difficult to immediately know the country the person is based in.  Airport may also be inaccurate for people who live near national borders.

**Comment by pbanaszkiewicz** [comment]
Hello @anenadic. `country` field was populated from person's airport.

We can expose `country` in API, can you please add an issue for that?

**Comment by anenadic** [comment]
Brilliant, thank you @pbanaszkiewicz. Will add a separate issue!
