### ISSUE TITLE
"Dutch Flemish" should be "Dutch/Flemish"

### ISSUE THREAD

**Issue by steltenpower** [swcarpentry/amy#1298]

**Comment by marwahaha** [comment]
@steltenpower - where is this listed?

**Comment by pbanaszkiewicz** [comment]
Languages were included in AMY through a script. See https://github.com/swcarpentry/amy/blob/develop/data/registry.json for language source, and migrations https://github.com/swcarpentry/amy/blob/develop/workshops/migrations/0097_auto_20160519_0739.py and https://github.com/swcarpentry/amy/blob/develop/workshops/migrations/0139_fix_language_names.py for a way to parse & load the data into DB.

The space in `Dutch Flemish` is result of concatenation a description list; this issue might apply to other languages as well, e.g. Spanish. As a solution, we can do a migration to re-import languages and fix the names.
