### ISSUE TITLE
Count workshops by membership year, not calendar year.

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#1306]
For any given organization we  can see a list of workshops they have run, and any memberships they have.
For example: https://amy.software-carpentry.org/workshops/organization/stanford.edu/

The memberships section lets us see how many workshops they are allowed and how many are completed.  The completed counts for the calendar year, but this should count for a membership year.  If a a membership goes from July 1 2017 to June 30 2018, workshops within that time period should be counted, not for either calendar year.

@pbanaszkiewicz How difficult is this fix? Would we be able to prioritize it?

**Comment by pbanaszkiewicz** [comment]
@maneesha currently the logic is to count workshops for the year of "membership start", as you noticed. Do you want me to completely change it to only count workshops for the membership duration? Or rather enhance so that we have both methods (calculations) available?
