### ISSUE TITLE
XXX-unset-variable-XXX shows up at bottom of screen after submitting workshop request

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#1308]
XXX-unset-variable-XXX shows up at bottom of screen after submitting workshop request

![image](https://user-images.githubusercontent.com/829690/43150516-1f1433d8-8f38-11e8-9407-1680731ba5a7.png)

**Comment by pbanaszkiewicz** [comment]
This will be fixed as part of #1261.
