### ISSUE TITLE
Email notifications for workshop requests

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#1309]
Email notifications for workshop requests are not coming through.  See a couple of test ones I just put in.  I don't know if this is due to us changing email lists.

admin-all@software-carpentry.org should forward to admin-all@carpentries.org
so even if something in AMY was not updated, the forwarding should still work but I haven't seen any email notifications since July 4.

Not sure if this is a fix on the AMY end, with our email servers or both so I'm tagging @pbanaszkiewicz  and @jduckles

**Comment by pbanaszkiewicz** [comment]
I think I deployed the new version of AMY around July 4, and in the current release there was a change of mailing service provider, as well as some additional dependency in Django to support it.

The strange thing is that I tested sending emails to myself using this new provider and it worked (just confirmed it still works). I need confirmation from any admin (cc @maneesha) that admin-all@carpentries.org is receiving my emails (I sent one from AMY noreply@carpentries.org, and one from my private email address).

**Comment by jduckles** [comment]
Might be that you need to add noreply@carpentries.org as an approved sender to admin-all@carpentries.org

**Comment by jduckles** [comment]
Yep, I think that was it. Have added noreply@carpentries.org to the list and set it to web-only to not bounce emails back its way:
![image](https://user-images.githubusercontent.com/119403/43168301-f0d778f4-8ff0-11e8-9950-fa71d7b311be.png)

**Comment by pbanaszkiewicz** [comment]
I sent an email entitled "Testing if sending emails from Django now works - sorry for interruption", can any of admins confirm if the email went through to admin-all? /cc @maneesha

**Comment by jduckles** [comment]
Confirmed. I saw it come through.

**Comment by maneesha** [comment]
Yes, I saw it as well.

**Comment by pbanaszkiewicz** [comment]
Thanks @maneesha and @jduckles. This issue is resolved.
