### ISSUE TITLE
 workshop request view page shows 1 page of requests only

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#1315]
Regardless of the filter chosen only one page of 25 requests is shown.
There is no ability to go to prev/next page.

**Comment by pbanaszkiewicz** [comment]
@maneesha there's no pagination widget on that page, but it's easy to add. The real issue here that I can see is that the filter form doesn't work correctly. I'll fix that and add pagination.

**Comment by maneesha** [comment]
@pbanaszkiewicz   Re-opening this issue.  It looks like this still is not working.  We only see one page, with no option for pagination.

**Comment by pbanaszkiewicz** [comment]
@maneesha it's been fixed in v2.1, which has not been released yet.

**Comment by pbanaszkiewicz** [comment]
Closing since this was fixed.
