### ISSUE TITLE
Fault in how requests are matched to event

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#1316]
Some requests look like they are associated with an event but clicking on "related event" gives a not found error.  See this [example](https://amy.software-carpentry.org/workshops/request/12/) takes you to [this page](https://amy.software-carpentry.org/workshops/request/12/XXX-unset-variable-XXX)

**Comment by pbanaszkiewicz** [comment]
@maneesha this message is (wrongly) displayed when event has been discarded. If it had been accepted, the link would have worked.

In the current (v2.0) release, the message only shows up if the link works, ie. when a new event was created through workshop request acceptance form (the funny one that's two columns).

I can see a field for improvement here:
1. it would be handy for admins to manually change events related to workshop requests
2. it makes sense to distinguish between "discarded", "accepted", and "active" states. Currently it's only "active"/"inactive",
3. finally, we should display different messages based on the status from point 2. above.

@maneesha let me know what you think.

**Comment by pbanaszkiewicz** [comment]
Ref #1179
