### ISSUE TITLE
Request: list of Trainers by time period, remove from Instructors report

### ISSUE THREAD

**Issue by karenword** [swcarpentry/amy#1320]
The "list of instructors by time period" feature under "Reports" is currently used to generate an email list for reminders about Instructor Discussion sessions. However, a) this list includes Trainers who have taught Instructor Training workshops, which are not discussed at these sessions, and b) the Trainers group needs a comparable list of people who have taught Instructor Training workshops for Trainer discussion meetings.

Currently, Martin (who sends the Instructor emails) has agreed to manually remove Trainers from his list (looking for the TTT on the workshop slug in the browser report, since Trainers do also teach regular workshops), while I will perform the opposite task to obtain a list of Trainers who have recently taught. This is time consuming and error prone, so it would be ideal for AMY to separate these lists instead, if possible. :)

**Comment by pbanaszkiewicz** [comment]
@karenword this is definitely possible. Just to be clear we're on the same page: you're requesting to change "List instructors by time period" to not return instructors for TTT workshops, and add a new page "List TTT instructors by time period".
Alternatively we'd have a select/radio buttons on the "List instructors by time period" page saying "List only TTT events" and "List only non-TTT events".

This is also a good time to make adjustments in the way output is generated, so if you want me to change styling, or display more fields please let me know.

**Comment by pbanaszkiewicz** [comment]
@karenword can you please check if the event slug is for sure not added to the CSV output? It looks to me that it's in the first column.
