### ISSUE TITLE
Header Freeze

### ISSUE THREAD

**Issue by sheraaron** [swcarpentry/amy#1326]
hey @pbanaszkiewicz  is it possible to have the header tabs ( Dashborad, events, organizations, etc)  in AMY to be frozen and move with the scrolling? 

Please let me know if this makes sense?

**Comment by pbanaszkiewicz** [comment]
@sheraaron yes, it's possible. It actually was implemented like this before v2.0 release, but I changed it due to some small errors (#1210).

**Comment by sheraaron** [comment]
@pbanaszkiewicz I thought it was that way before, but couldn't remember if that was something or I just wished it would do 😄
