### ISSUE TITLE
Update from URL 

### ISSUE THREAD

**Issue by sheraaron** [swcarpentry/amy#1339]
When I select the Update from URL the information is provided 2x.

**Comment by pbanaszkiewicz** [comment]
What information doubles? For example, is this only "Notes" or only workshop slug, or is it all data?

**Comment by sheraaron** [comment]
Any information in the notes is doubled.

**Comment by pbanaszkiewicz** [comment]
This mechanism will be changed once we implement #1342. I'm aiming for something similar to GitHub system, where you have comments and events interchanging.
