### ISSUE TITLE
Merge workshop request with existing event

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#1346]
Sometimes someone will submit a workshop request after we've already recorded the event because they notified us through another channel.  We should be able to merge that request into the existing event.

This may need to be resolved after the new workshop request form (#1344) is implemented.  

(This may be duplicating an existing issue; I can't find that now)

**Comment by pbanaszkiewicz** [comment]
There's been multiple requests for this functionality (#800, #1179). I closed them as a result of #1329, here's the explanation: https://github.com/swcarpentry/amy/issues/1179#issuecomment-417752985

@maneesha if you feel this is not enough, please reopen this issue.
