### ISSUE TITLE
Email notifications not coming through

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#1347]
Notifications when there are new workshop requests submitted are supposed to come to the admin-all@lists.software-carpentry.org  or admin-all@carpentries.org lists.  These notifications have not been coming through.

**Comment by pbanaszkiewicz** [comment]
AMY currently only sends to `admin-all@carpentries.org`, but there's been some reports about the notifications not working. I sent out a testing message, and received it correctly at my private email. @maneesha please let me know if you got it on admin-all.

**Comment by maneesha** [comment]
@pbanaszkiewicz   No notifications have come through  to admin-all@carpentries.org  since 2018-08-29

**Comment by pbanaszkiewicz** [comment]
@jduckles can you check Mailgun settings?

**Comment by jduckles** [comment]
No problems on the Mailgun side: 
![image](https://user-images.githubusercontent.com/119403/45778899-df81f400-bcad-11e8-84f6-f40eddb64bdd.png)

**Comment by maneesha** [comment]
I just tried submitting a test request on https://amy.software-carpentry.org/forms/swc/request/ and https://amy.software-carpentry.org/forms/dc/request/
but when I hit submit, the page (with the form still filled out) just reloads.  Should I create another issue for this @pbanaszkiewicz ?

**Comment by pbanaszkiewicz** [comment]
Hello Maneesha,

Yes please add an issue for that. Can you provide me with data you used for that test request? Maybe there was some error on the form.

Dnia 19 września 2018 23:03:58 CEST, maneesha sane <notifications@github.com> napisał(a):
>I just tried submitting a test request on
>https://amy.software-carpentry.org/forms/swc/request/ and
>https://amy.software-carpentry.org/forms/dc/request/
>but when I hit submit, the page (with the form still filled out) just
>reloads.  Should I create another issue for this @pbanaszkiewicz ?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/swcarpentry/amy/issues/1347#issuecomment-422957816

-- 
Z poważaniem / With regards,
Piotr Banaszkiewicz

**Comment by maneesha** [comment]
Will do.  I just filled in each line of the form with something like "Fake request, ignore"
I did not get an error message; the form just refreshed with the data still filled in.  Someone else reported this happening to them last week -- and when I tried it then, it looked OK so we thought it may have been user error.  However now I'm having the same issue.

**Comment by maneesha** [comment]
As noted in #1348 the form is going through.  However there are no new notifications coming through admin-all@carpentries.org

**Comment by maneesha** [comment]
@pbanaszkiewicz  Any update on this?

**Comment by pbanaszkiewicz** [comment]
@maneesha I added my personal email to the list of request notification recipients and submitted profile update request. I received the notification email shortly. Similarly, I submitted SWC workshop request and shortly afterwards I received notification email.

Can anyone check if those emails went through to admin-all@carpentries.org?

**Comment by jduckles** [comment]
They're making it to our @carpentries.org Google Apps service, @maneesha I'd look at the admin-all@carpentries.org group settings to see if something isn't right there. 

![image](https://user-images.githubusercontent.com/119403/46586087-d2e70380-cad5-11e8-9b0c-48a2407cf2db.png)

**Comment by jduckles** [comment]
@pbanaszkiewicz Is that sender something configured in AMY, it might be the problem. I think emails will bounce unless the sender is postmaster@mg.carpentries.org.

**Comment by pbanaszkiewicz** [comment]
@jduckles we're sending as `no-reply@carpentries.org` (see #1250). It's set up for both [`SERVER_EMAIL`](https://docs.djangoproject.com/en/2.1/ref/settings/#server-email) and [`DEFAULT_FROM_EMAIL`](https://docs.djangoproject.com/en/2.1/ref/settings/#default-from-email).

**Comment by jduckles** [comment]
Ok, it most likely is a problem where mailgun can't DKIM sign any emails from an @carpentries.org. Since we enforce DKIM and SPF,  on @carpentries.org (Google hosted) I think this may be the cause of bounces. Can you please reconfigure the sender to no-reply@**mg.carpentries.org** (note the subdomain).

**Comment by maneesha** [comment]
Just got one real request in, and put a test one in which also went through.  Looks like things are working now.

**Comment by jduckles** [comment]
It was the fact that `noreply@carpentrries.org` was the list subscriber, not `no-reply@carpentries.org` 🤦‍♂️.
