### ISSUE TITLE
Workshop request form does not go through

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#1348]
When filling out a workshop request form at https://amy.software-carpentry.org/forms/swc/request/ or https://amy.software-carpentry.org/forms/dc/request/  upon hitting submit the page just refreshes with the input data still filled in. The form does not appear to submit and does not appear in the [list of requests](https://amy.software-carpentry.org/workshops/requests/).

See also #1347

**Comment by maneesha** [comment]
I just tested this again and it went through.  Someone else reported this happening to them last week -- and when I tried it then, it looked OK so we thought it may have been user error. Not sure why this is happening inconsistently.

**Comment by pbanaszkiewicz** [comment]
Recently @ErinBecker reported that one of AMY users got this error message right after submitting this form:

> Forbidden (403)
> CSRF verification failed. Request aborted.

This should not happen and I will investigate. @maneesha can you remember seeing something similar?

**Comment by maneesha** [comment]
I have not seen the CSRF error.  I have seen it simply reload the form (with all the fields still filled in) rather than going to a confirmation page.

**Comment by pbanaszkiewicz** [comment]
I'm still unable to reproduce this error. Maybe once I start receiving AMY server error messages, I will be able to look more into this issue.

**Comment by pbanaszkiewicz** [comment]
Closing this for now, as we're switching to a different form. We'll revisit if someone has issues with the new form.
