### ISSUE TITLE
500 Server Error when filtering on Events API

### ISSUE THREAD

**Issue by anenadic** [swcarpentry/amy#1351]
https://amy.software-carpentry.org/api/v1/events/published/ API throws 500 Server error when using parameters to filter the call. 

For example: https://amy.software-carpentry.org/api/v1/events/?completed=&tag=SWC&start=&start_before=&start_after=&end=&end_before=&end_after=&order_by=start

I tried with several parameter combinations and all threw 500 Server error.

**Comment by pbanaszkiewicz** [comment]
@anenadic you're linking two different API endpoints:
1. Published events (doesn't support much filtering) https://amy.software-carpentry.org/api/v1/events/published/
2. Just events (supports filtering through Filter button) https://amy.software-carpentry.org/api/v1/events/

The bug corresponds only to the latter link, as for the former endpoint filtering capabilities are much lower (to see filtering options, click the events published link and click "options"; the page reloads and you can read what GET parameters are accepted).

**Comment by pbanaszkiewicz** [comment]
@anenadic one little change, after #1364 is merged, published events API endpoint will gain the same filtering as "normal" events endpoint.
