### ISSUE TITLE
New Workshop Tags

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#1352]
As our curriculum offerings expand we'd like to add the following new tags to AMY:

ITT = Instructor Trainer Training (Trainer Training)
LMO = Lesson Maintainer Onboarding
LSO = Lesson Specific Onboarding 

This is not urgent enough for the current release; it can be included in the next release.

**Comment by pbanaszkiewicz** [comment]
@maneesha tags are treated very specifically in AMY (in a lot of places). LMO/LSO look benign, but what is the function of ITT? Is it really close to TTT?

**Comment by maneesha** [comment]
We have two programs - one where we train our instructors (that we have been tagging TTT).
A newer program is where we train our Instructor Trainers, which we would like to tag TTT.

So the three tags noted above should be in addition to all the existing tags.
