### ISSUE TITLE
bulk update of training request applicant scores

### ISSUE THREAD

**Issue by ErinBecker** [swcarpentry/amy#1353]
Related to https://github.com/swcarpentry/amy/issues/1327

As we discussed at our meeting today (@pbanaszkiewicz, @elizabethwilliams8, @sheraaron, @maneesha, @karenword), it will be very useful to be able to bulk update the manual scores and notes field for training requests. This would work by uploading a single csv file that has three fields: 
1) a request ID (I'm not sure what the name for that field is in AMY)
2) manual score
3) notes for manual score

This would also trigger a change in the manual score from NULL to whatever value is set in the manual score column. 

Please let me know if you have any questions! We're looking forward to this in a later release (October), not for the current release.

**Comment by karenword** [comment]
I’m not sure if this helps I will be creating two CSV files for reviewers. These will contain:

File 1: request ID, all columns to be manually scored, manual score, and manual scoring notes. While I will need to do some processing to average reviewer scores and merge comments, It would be great to be able to upload this file directly back to AMY without re-formatting, and even better to be able to download it with this content only. (Also, I think we have discussed filtering to get only applications with an empty GroupID field instead of using R to eliminate these from the download as we currently do, but I can’t recall what we decided to do about that.)

File 2: names & maybe institutions only. This will not need to be re-uploaded.

**Comment by ErinBecker** [comment]
Thanks for the question @pbanaszkiewicz. When we export the CSV for doing application review, we will only have the reviewers looking at specific questions. As Karen mentioned, it would be nice (but not essential) to be able to download a CSV file that has only the questions that will be manually scored, and only the requests that have the GroupID field filled out with a particular range of options. Right now, we do that second step (filtering for GroupID), with an R script that has a set of options covering e.g. "NA", "none", "" (blank), "na", "N/A", "no group" and some other variations on that theme. @karenword - can you please add the complete list of responses that we filter on in that field so @pbanaszkiewicz knows exactly what to export. 

I do want to caution us here - it is MUCH easier to change the filtering conditions in the R script (for example, if we find out that people are putting in "No Group" or something else that isn't in our current matching set) than it will be for @pbanaszkiewicz to change the download options in AMY. I would actually recommend that we continue to do that filtering in R.

**Comment by pbanaszkiewicz** [comment]
Hello @karenword and @ErinBecker - thank you both for input.

I can understand that you want to upload a manual-scores file with minimum changes, preferably downloaded directly from AMY (and probably filtered in R later on).  What I can do is to look for `request_id`, `score_manual` and `score_notes` columns in CSV and ignore all others.

Now I need to know if you:
1. want to keep current CSV download for training requests as it is, or
2. extend current CSV download file with additional columns, or
3. add a different CSV download made specifically for manual scoring, or
4. 2 and 3 combined, or
5. something entirely different?

Thanks in advance for clarification.

**Comment by karenword** [comment]
For now it sounds like the most straightforward thing would be to add these columns (Option 2), and be able to upload a more minimal version that only contains the three new columns.

**Comment by ErinBecker** [comment]
@pbanaszkiewicz - I think we actually want option 3 (and I will confirm with @karenword to be sure this will work with her workflow). 

The easiest thing for our end (Karen and me) would be to be able to download a CSV that includes ONLY the columns that are needed for manual scoring (I will add a list of these shortly to this thread) and the name and institution. 

@karenword and I will use an R script to filter the downloaded CSV for requests that are not associated with a member site.

We will also use an R script to split the downloaded CSV into two files (with the name and institution in a separate file, for data privacy and scoring objectivity reasons). 

I will add another comment with the specific columns to include in the download.

**Comment by ErinBecker** [comment]
These are the columns we need included in the CSV:

- Group Name 
- Personal 
- Middle 
- Family
- Underrepresented   (reason)
- Affiliation
- Non-profit teaching   experience
- Previous Training   (other)
- Previous Training   (explanation)
- Previous Experience   (other)
- Previous Experience (explanation)
- Teaching Frequency   Expectation (other)
- Max Travelling   Frequency (other)
- Reason for   undertaking training
- Comment

It would also be useful to include the columns `request_id`, `score_manual` and `score_notes` in the CSV download.

@karenword - please let me know if you have any additions or changes to this workflow.

**Comment by karenword** [comment]
I am down with the less-straightforward-but-more-valuable Option 3! Are categories like `Previous Experience (explanation)` going to be interpretable without the associated answers or points already automatically assigned in these areas?

**Comment by pbanaszkiewicz** [comment]
Closed via #1374.
