### ISSUE TITLE
Readme is outdated

### ISSUE THREAD

**Issue by pbanaszkiewicz** [swcarpentry/amy#1365]
1. it could mention "Python 3" near Django in second paragraph, or even better - it could include [some badges](https://shields.io/#/examples/platform-support) 
2. code of conduct link is broken
3. if we mention Python 3 compatibility, then it's not necessary to put `python3` instead of `python` in the Getting Started point 2 and 5, and Upgrading point 4
4. Getting Started point 3: we're not using Bower anymore ([Yarn](https://yarnpkg.com/) instead)
5. Getting Started point 6: we could link to the frameworks listed
6. Getting Started point 7: use `127.0.0.1` instead of `localhost`

**Comment by marwahaha** [comment]
6 is no longer relevant, since #1358 is merged.

**Comment by pbanaszkiewicz** [comment]
@marwahaha actually it is still relevant, because Django by default uses `127.0.0.1` (https://github.com/django/django/blob/master/django/core/management/commands/runserver.py#L30).
