### ISSUE TITLE
Add Submit Button to top of Screen

### ISSUE THREAD

**Issue by sheraaron** [swcarpentry/amy#1369]
@pbanaszkiewicz  could we add the Submit button to both the top and the bottom of the screen? This would help when I am adding information to the top of a profile instead of having to scroll all the way to the bottom being able to submit without scrolling. 

Thanks!

**Comment by karenword** [comment]
+1!

**Comment by pbanaszkiewicz** [comment]
@sheraaron @karenword this is quite straightforward change, but I need to know which pages would you like to have the top+bottom buttons?

**Comment by karenword** [comment]
In my experience the training request page is the main problem. Manually changing a status at the top (e.g. accept), then clicking ‘submit’ at the bottom involves a lot of scrolling!

**Comment by sheraaron** [comment]
@pbanaszkiewicz also adding "submit" on the adding organizations, adding persons, accept and create event, workshop request form (event and task). 

Thanks!
