### ISSUE TITLE
Training Request list selection not preserved between operations

### ISSUE THREAD

**Issue by karenword** [swcarpentry/amy#1375]
A couple of observations on features/bugs of the select boxes on the Training Requests list pages:

1. Selected boxes are not preserved between list screens. This means that no more than the number of displayed records may be selected for a bulk action at one time (unless an entire filtered set is desired in which case box selection is unnecessary). This is ok, but at least for my workflow it would be preferable to have selections carry over between search screens for a single bulk action. 

2. The box at the top that selects all records behaves unpredictably. If it is selected on a freshly displayed output screen, the "download selected to CSV" feature downloads ALL applications (not just that screen, not just filtered, ALL applications). If, however you select this box, then alter selections below (say, deselect and select a box) THEN the download includes only those selected on the display screen. This is manageable when you're aware of it, but might cause trouble down the road.

**Comment by pbanaszkiewicz** [comment]
Hello @karenword,

The issue 2. was fixed as part of #1374.

The issue 1. is quite hard for me to implement for now, but it was raised a few times before. I have some general ideas, but for v2.2 it cannot happen. I'll keep the issue concentrated on this matter, though.

**Comment by karenword** [comment]
Is there any fix for problem 1 on the horizon? I have a new workflow that requires iteratively selecting, emailing, and removing (via status change) applicants from a results list. Without the ability to preserve check-boxes across screens it is quite inefficient, with the first page having new (but fewer) select-able applicants with each iteration until I can finally move on to page 2. If preserving selection across results screens is unlikely in the near term, I can try to suggest a set added search/filter conditions that would avoid the need for manual selection instead.

**Comment by pbanaszkiewicz** [comment]
@karenword if this has high priority for you, I can work on it for point-release v2.5.1, which should be released sometime in first two weeks of February.

Can you point me to the workflow you mentioned? I'd like to take a look and think about possible solutions.

**Comment by karenword** [comment]
Thank you @pbanaszkiewicz!  Keep in mind that this workflow is still under development. Link is here, procedure in question is currently Part 2, steps 3-5. You will be able to see why it's challenging to work this out entirely through filters vs manual selection.

**Comment by karenword** [comment]
Oops: workflow here: https://docs.google.com/document/d/1bBOxupUrHculfuG_QJJMu6JjtLUubtdjzJDU1BUVVJQ/edit?usp=sharing
