### ISSUE TITLE
Bulk email and approval of training requests

### ISSUE THREAD

**Issue by ErinBecker** [swcarpentry/amy#1383]
Continuation of https://github.com/swcarpentry/amy/issues/1327 

Issue https://github.com/swcarpentry/amy/issues/1327 implemented new features for tracking training request scores and made it possible to perform some actions with requests based on those scores.

While @karenword and I were testing this new workflow, we noticed a couple of issues that we hadn't realized would be problematic for implementing this new workflow.

In the training requests page, we would like to select (using the checkboxes) a certain number of the top-scoring applicants and convert them from "Pending" to "Accepted" and also send them an email. What we forgot to consider, was that we only care about open training applicants for this workflow (not member associated applicants). 

1) To enable us to select only open training applicants, we would like to be able to see group names as a column in the list. We are not able to use the filter function for group name, as applicants enter a number of different values into this field: "NA", "na", "N/A", "none", "unaffiliated", "" (blank), etc.

2) We would also like to see affiliation listed in the training requests list. This will enable us to avoid awarding training seats to many people from the same institution. If we see multiple people from the same institution applying, we will want to contact them about membership. 

3) The "mail selected trainees" button is pulling email addresses from the matched trainee record. Most of these requests do not yet have matched trainees. We need to be able to pull email addresses from the request record. 

Please let me know if there are any questions.

**Comment by pbanaszkiewicz** [comment]
@ErinBecker:
1. when do you need this?
2. is seeing two additional columns going to fix your problem of telling open training applicants from membership applicants?
3. regarding point 3 above, when a training request is matched to the person, the person's data is overwritten with request's data (this includes email address). Do you want me to change "mail selected trainees" so that it pulls email address from the request's data if there isn't a matched person?

**Comment by pbanaszkiewicz** [comment]
@ErinBecker these are easy changes, and will make to the next release (end of October).

**Comment by ErinBecker** [comment]
That's fantastic news! Thanks @pbanaszkiewicz!! 🎉 

@karenword for the good news.
