### ISSUE TITLE
Persons API bug - duplicate entries returned

### ISSUE THREAD

**Issue by anenadic** [swcarpentry/amy#1395]
Think I discovered a possible bug in persons API - possibly other parts of the API are affected. Certain number of duplicated entries are returned, e.g. when searching for UK instructors at page 2 of results there are two entries for "m.wallis@leeds.ac.uk", on page 3 there are 2 entries for "m.croucher@sheffield.ac.uk", and so on.

See for example page 2 of results:
https://amy.software-carpentry.org/api/v1/persons/?country=GB&email=&family=&github=&is_instructor=true&may_contact=&middle=&order_by=&page=2&personal=&publish_profile=&username=

**Comment by pbanaszkiewicz** [comment]
Thanks @anenadic for reporting this issue. Similar erratic behaviour may be found in other places, but it's not the same bug. Please report if you spot something like this again. Thanks a lot!

**Comment by anenadic** [comment]
No problem and thank you for fixing it.
