### ISSUE TITLE
Hide fee/invoice from event view

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#1408]
@elizabethwilliams8  is tracking all fees and invoices separately.  We do not need to track this in AMY.

**Comment by pbanaszkiewicz** [comment]
@maneesha by "fee" do you mean "Admin fee" field?

**Comment by maneesha** [comment]
Yes - "Admin fee" and "Invoice" can be hidden from view.

**Comment by pbanaszkiewicz** [comment]
@maneesha do you want to hide "admin fee" from event add/edit form as well?

**Comment by pbanaszkiewicz** [comment]
@maneesha another question: memberships can also include number of admin-fee-free workshops allowed per membership (+ keep track of admin-fee free workshops), but if I remove admin-fee option from event add/edit form, this might become useless for you/Elizabeth. Should I change memberships or leave admin fee option as it is?
