### ISSUE TITLE
Add "LC instructor" as a badge

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#1417]
Since Library Carpentry is officially a Carpentries lesson program, we would like to include it as a choice for instructor badge.

**Comment by pbanaszkiewicz** [comment]
Ref. #1232.

**Comment by pbanaszkiewicz** [comment]
@maneesha I'm going to add LC instructor badge only; if you want to extend instructor training with LC-specific requirements for this instructor badge, please create a separate issue.
