### ISSUE TITLE
Remove deprecated requests

### ISSUE THREAD

**Issue by pbanaszkiewicz** [swcarpentry/amy#1432]
These models, corresponding views, forms, templates and tests are deprecated and, honestly, just mess up the codebase:
* ProfileUpdateRequests,
* InvoiceRequests,
* ~~EventRequests,~~
* ~~EventSubmissions,~~
* ~~DCSelfOrganizedEventRequests.~~

UPDATE: we're not removing the old event requests or submissions.

**Comment by maneesha** [comment]
@pbanaszkiewicz   Will this mess up the corresponding data?  Even though all those request forms are deprecated I want to be sure we can view the submissions.

**Comment by pbanaszkiewicz** [comment]
@maneesha yes, my goal was to remove these from the code completely, so that I don't have to maintain it anymore. It's okay if you need it, though.

Are InvoiceRequests needed as well? I think almost no-one used this feature.

**Comment by maneesha** [comment]
I don't think we need to keep InvoiceRequests.
However I would like to keep all the old workshop requests/submissions.

**Comment by pbanaszkiewicz** [comment]
@maneesha okay. What about old ProfileUpdateRequests?

**Comment by maneesha** [comment]
We don't need to keep old ProfileUpdateRequests.
