### ISSUE TITLE
Problems building site locally

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#1443]
When following the directions in the repo's readme to build the site locally and build a fake database, there are a number of errors, likely due to changes in the database model. I've put in temporary fixes in the [fix_local_build branch](https://github.com/swcarpentry/amy/tree/fix_local_build).

 For now I have [commented out](https://github.com/swcarpentry/amy/commit/6f439088f17e412718de57cd277339c24903857a) the lines causing errors.  I could probably hunt around to fix these but @pbanaszkiewicz  likely knows all the changes and is in a better position to fix them.

The location of the `git_version.py` file has also changed.  I've made this correction in the [Makefile](https://github.com/swcarpentry/amy/commit/ed617881a49bbb9cf80eba0c0ca1645c17d0601b).

**Comment by pbanaszkiewicz** [comment]
@maneesha the last issue (`git_version.py`) was fixed in (pending) PR #1441.

Can you please create a PR from `fix_local_build` branch?

**Comment by pbanaszkiewicz** [comment]
Fixed in #1447.
