### ISSUE TITLE
Search workshops, instructors, etc. by continent

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#1444]
We currently have the feature to search by country.  It would also be useful to search by continent or other larger global region.  For example - Europe, Asia, Africa, South America, Central America, Middle East, etc.  Are there existing libraries that define these geographic regions? Can we have user-defined regions?

Can we use a library like what's used to define Africa in this issue (https://github.com/swcarpentry/amy/issues/1368)?

**Comment by pbanaszkiewicz** [comment]
@maneesha:

Currently we obtain list of countries from `django-countries` application. It's easy and works with all databases. The country list is poor in terms of 

There are some nicer applications, that provide more geopolitical data (e.g. https://github.com/cordery/django-countries-plus mentioned in #1368), but they require special spatial databases. With SQLite it's hard to achieve this, but not impossible - https://docs.djangoproject.com/en/2.1/ref/contrib/gis/install/spatialite/

There is also an application providing list of airports worldwide, but it too requires spatial database.

Here are my propositions:

1. Maintain our own continents list. Pros: fast to set up, works on SQLite and PostgreSQL, we can configure continents as we want (e.g. [add Central America, even if it's not considered a continent](https://en.wikipedia.org/wiki/Continent#Number)). Cons: Not feature-rich (doesn't provide any other data), maintenance burden falls on us.
2. Wait for [PostgreSQL+PostGIS support](https://github.com/swcarpentry/amy/issues/716) (I'm hoping for it to happen in the upcoming months), and then for migration to django-countries-plus or django-cities.

@maneesha what do you think?
