### ISSUE TITLE
add LC demo and LC homework as training progress objects

### ISSUE THREAD

**Issue by ErinBecker** [swcarpentry/amy#1460]
Library Carpentry is now an official Lesson Program within The Carpentries. This new status is partially reflected in AMY (with the addition of the [lc-instructor badge](https://amy.software-carpentry.org/workshops/badge/lc-instructor/)). However, there are a few other places LC needs to be integrated in order to track trainee progress towards lc-instructor badging. 

1) Addition of "LC Demo" and "LC Homework" training progress objects. These should behave identically to the counterpart SWC and DC Demo and Homework objects (e.g. Homework should require a URL, but Demo should not). 

2) The logic for the query to identify trainees who are eligible for badging, but not yet badged needs to be updated. It should now parse to 

`(LC Demo | SWC Demo | DC Demo) + (LC Homework | SWC Homework | DC Homework) + Discussion` in any order. 

3) In the Trainees view, in the Eligible column, an LC tag option should be added. Alternatively, we may want to consider getting rid of that column entirely.

Tagging @libcce - please let me know if you can think of anything I'm missing.

**Comment by libcce** [comment]
Nothing to add @ErinBecker. Like you say, it mirrors SWC and DC. Thanks for creating this issue!

**Comment by sheraaronhurt** [comment]
I would have to agree with @ErinBecker we do need to add this. When person's go to their AMY profile, if they did a LC demo/HW, it would not say it, it would say SWC or DC. If we want to be inclusive of LC we would need for this to happen and it could eliminate confusion from people wanting to know if their LC work counted. 

@ErinBecker I would not want to get rid of the column unless we are just going to give an overall "Carpentries" Badge. Which is another discussion :) When deciding which badge to grant I gauged based on their demo/HW.

**Comment by tracykteal** [comment]
Right, this could be a broader discussion about a general badge. For now though, let's implement adding LC. @pbanaszkiewicz how difficult would this be to do, and can we prioritize this? Thanks!

**Comment by pbanaszkiewicz** [comment]
@tracykteal it's on a priority list now! But I don't think I can manage to implement this feature tonight, as I fear some "hidden" dependencies in the code. You can however expect this in v2.6 release (this~next week).

**Comment by tracykteal** [comment]
Thank you, that's great! No need for tonight. This/next week is great.

**Comment by libcce** [comment]
Thanks @pbanaszkiewicz and @tracykteal !!!

**Comment by tracykteal** [comment]
Thanks @pbanaszkiewic! Got your update that this in the new version release, and that it will go live on Friday, March 8.
