### ISSUE TITLE
Note that it's OK if all training progress steps are not recorded

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#1464]
We started recording steps towards training progress in 2017(?) so people who were certified before that may not see all three checkout steps recorded.  Even people who got certified in the past few years may not see all steps recorded as this is a manual process and something may have been missed.  

This section:
![image](https://user-images.githubusercontent.com/829690/52535673-436d8d80-2d1f-11e9-9cee-810c87c21525.png)

should include a note that says:

"Due to the structure of our checkout tracking progress, all steps towards checkout may not be included here.  If your instructor badge (DC, LC, and/or SWC) is correctly displayed, you are in good standing."

**Comment by pbanaszkiewicz** [comment]
@maneesha this screenshot corresponds to person profile details displayed in person details page (this is admin-only view).

For any other trainee, the view with training progress details is this one: https://amy.carpentries.org/dashboard/trainee/training_progress/

I'll add a note in there.
