### ISSUE TITLE
issue with CAPTCHA

### ISSUE THREAD

**Issue by fmichonneau** [swcarpentry/amy#1472]
@pbanaszkiewicz possibly tied to the server switch, it looks like the captcha used (at least for instructor training requests) isn't working.

**Comment by pbanaszkiewicz** [comment]
@fmichonneau you're right, and this is high priority bug, and I can't do anything about it. Can you, or @jduckles or @tracykteal generate a new keypair from Google Captcha? Or change domain for existing one?

**Comment by fmichonneau** [comment]
I've created new keys. I placed them in the AMY lastpass folder. I've also listed you as an owner for these keys in the google reCAPTCHA interface.

**Comment by pbanaszkiewicz** [comment]
@fmichonneau I created another keypair, because apparently we have to use v2. I'm leaving the keypair you created (renamed it to `carpentries.org`).

I also added you and others as owners to `amy.carpentries.org` reCAPTCHA keys, and replaced them in Last Pass folder.
