### ISSUE TITLE
Trainee dashboard contains misleading information

### ISSUE THREAD

**Issue by karenword** [swcarpentry/amy#1477]
Despite correcting information in multiple channels, we continue to have instructors completing checkout twice to obtain SWC and DC certifications because they believe these are necessary to be able to teach the different lesson programs. 

The following sentence at the bottom of the page has been identified as misleading: "Register for Demo Session on this Etherpad. If you want to become both SWC and DC Instructor, you have to teach two 5-minutes sessions during one or two sessions." 

The simplest solution is simply to remove the second sentence and direct trainees to the etherpad. Note that etherpad links on this page are also out of date -- the current demos etherpad is here: https://pad.carpentries.org/teaching-demos-recovered.

**Comment by maneesha** [comment]
Which page has the misleading text on it?

**Comment by karenword** [comment]
Oops sorry! This one: https://amy.carpentries.org/dashboard/trainee/training_progress/

**Comment by pbanaszkiewicz** [comment]
@karenword @maneesha  what's current link for instructor discussion etherpad?

**Comment by maneesha** [comment]
Community discussion etherpad:
https://pad.carpentries.org/community-discussions
