### ISSUE TITLE
Missing copyright/licensing information

### ISSUE THREAD

**Issue by wking** [swcarpentry/amy#148]
I'd suggest the MIT license for the whole thing, since that's what SWC uses for code in lesson content.

**Comment by gvwilson** [comment]
+1 - please add.

**Comment by wking** [comment]
On Sat, Jan 17, 2015 at 06:39:09PM -0800, Greg Wilson wrote:
> +1 - please add.

Added in #149.

**Comment by wking** [comment]
Closed by #149.
