### ISSUE TITLE
Events should be ordered by start date, not by insertion order

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#150]
The default display of events should sort them by start date (or equivalently slug), not by table insertion order.  (Right now, training cohorts are converted to events after actual events have been added, so all the training cohorts show up out of time order.)

**Comment by sburns** [comment]
> sort them by start date

Ascending or descending?

**Comment by gvwilson** [comment]
Most recent first, since that's most likely to be interesting.
Thanks,
Greg
