### ISSUE TITLE
Link to tasks by ID

### ISSUE THREAD

**Issue by wking** [swcarpentry/amy#153]
Since a70f8f7a (Adding display of tasks - editing still fails, 2014-12-11, #55), we've been linking to tasks with:

    task/{event_slug}/{person_id}/{role_name}

This seems uneccessarily complicated to me, resulting in templated links like:

    {% url 'task_details' task.event.slug task.person.id task.role.name %}

which could be just:

    {% url 'task_details' task.id %}

How do we feel about simpler ID-based URLs here?

**Comment by gvwilson** [comment]
I don't want to lose the mnemonic URLs - I'd be happy if two different 
URLs (one mnemonic, one by task ID) went to the same place.

**Comment by wking** [comment]
On Sun, Jan 18, 2015 at 12:18:22PM -0800, Greg Wilson wrote:
> I don't want to lose the mnemonic URLs - I'd be happy if two
> different URLs (one mnemonic, one by task ID) went to the same
> place.

Is it a mnemonic URL if there's a person ID in it?  If we were using:

  task/{event_slug}/{person_slug}/{role_name}

I think that argument would have more weight, but then we'd have to
require person slugs, and we're not doing that now [1].

[1]: https://github.com/swcarpentry/amy/pull/125#issuecomment-69143688

**Comment by gvwilson** [comment]
Good point.  Sure, make the change.
G

On 2015-01-18 4:12 PM, W. Trevor King wrote:
> On Sun, Jan 18, 2015 at 12:18:22PM -0800, Greg Wilson wrote:
> > I don't want to lose the mnemonic URLs - I'd be happy if two
> > different URLs (one mnemonic, one by task ID) went to the same
> > place.
>
> Is it a mnemonic URL if there's a person ID in it? If we were using:
>
> task/{event_slug}/{person_slug}/{role_name}
>
> I think that argument would have more weight, but then we'd have to
> require person slugs, and we're not doing that now [1].
>
> [1]: https://github.com/swcarpentry/amy/pull/125#issuecomment-69143688
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/swcarpentry/amy/issues/153#issuecomment-70426207>.
>

-- 
Dr. Greg Wilson    | gvwilson@software-carpentry.org
Software Carpentry | http://software-carpentry.org
