### ISSUE TITLE
Rename Person.active to show that it's about allowing contact

### ISSUE THREAD

**Issue by wking** [swcarpentry/amy#159]
Spun off from #147.  See also, #127 and #130.

On Wed, Jan 21, 2015 at 06:35:50AM -0800, Scott Burns wrote:
> > The "active" flag in the Person class indicates whether they're
> > currently interested in being contacted, taking part in workshops,
> > etc.
>
> @wking the help text on this field is good, but we need to make sure
> future selves/others don't mix this up w/ the `is_active` attr that
> subclassing `AbstractUser` requires that the django auth machinery
> uses behind the scenes.

I'm fine renaming the field to something else. `contactable` sounds like “is it possible to contact them?” to me. How about `away` (or `away_until`) as a DateField, with the following
semantics:

* `away == Null`, for “feel free to contact me”
* `away > today()`, for “I expect I'll be away until ‘away’.  Don't
    contact me”
* `away <= today()`, for “I thought I'd be back by now, but I'm not.
    Don't contact me”

If we want to stick with the boolean, maybe `open_to_communication`?

**Comment by gvwilson** [comment]
I don't know the dates for any of the people marked as "don't contact".  
`participating` ?  (I think were over-thinking this :-)

**Comment by wking** [comment]
On Wed, Jan 21, 2015 at 12:28:22PM -0800, Greg Wilson wrote:
> I don't know the dates for any of the people marked as "don't
> contact".

Ok, so we'll stick with a boolean.

> `participating` ?  (I think were over-thinking this :-)

I think so far I like your ‘may_contact’ best [1].  I'd missed that
suggestion when writing up the initial post for this issue.

[1]: https://github.com/swcarpentry/amy/pull/147#issuecomment-70853436

**Comment by wking** [comment]
On Wed, Jan 21, 2015 at 12:28:22PM -0800, Greg Wilson wrote:
> I think were over-thinking this :-)

And this issue is because we think ‘active’ is too easily confused
with ‘in_active’, not because the code doesn't work.  If we're going
to bikeshed for clarity, we might as well try and find a most-popular
color.  At least that reduces the chance of a “Rename
Person.<whatever> …” issue later ;).

**Comment by gvwilson** [comment]
+1 for 'may_contact' - shall I do the PR?
G

**Comment by wking** [comment]
On Wed, Jan 21, 2015 at 01:36:24PM -0800, Greg Wilson wrote:
> +1 for 'may_contact' - shall I do the PR?

Sure.  I wouldn't bother about migrations though, since #147 is
blowing them away (currently in commit 1125402a).  Alternatively, this
can be our first migration after landing #147 (once we finish writing
it ;).
