### ISSUE TITLE
Should we use Continuous Integration & coverage reporting?

### ISSUE THREAD

**Issue by pbanaszkiewicz** [swcarpentry/amy#166]
Hi everyone,

a couple of issues arouse recently that could've been easily discovered before code review phase.

From my point of view, GitHub integration with CI can show me (without me pulling the PR branch) if new PRs pass our test suite (which is a necessity).

Incorporating coverage reporting also helps keeping the newly introduced code covered by tests.

I think we should:

* bring AMY to [Travis-CI](https://travis-ci.org/)
* run [coverage](https://pypi.python.org/pypi/coverage/) during `python manage.py test`

What do you think?

Cheers,
Piotr

**Comment by wking** [comment]
On Mon, Jan 26, 2015 at 09:20:15AM -0800, Piotr Banaszkiewicz wrote:
> * bring AMY to [Travis-CI](https://travis-ci.org/)
> * run [coverage](https://pypi.python.org/pypi/coverage/) during
>   `python manage.py test`

I haven't setup Travis for my own repositories because of their
permission requirements [1].  Since 2014-02-26 these are less
intrusive (see travis-ci/travis-ci#1390, especially [2]), so I expect
we'll be ok with enabling them for SWC.

If we're not ok with those permissions, I'm happy to use and
continuous integration tooling folks are comfortable with.  There's no
sense in having a test suite if you don't run it ;).

[1]: http://docs.travis-ci.com/user/github-oauth-scopes/
[2]: https://github.com/travis-ci/travis-ci/issues/1390#issuecomment-36107410

**Comment by pbanaszkiewicz** [comment]
Great!

Now, is there any webservice free for open source projects that measures coverage upon pull requests? Something like [Code Climate](https://codeclimate.com/) for Python?

**Comment by wking** [comment]
On Mon, Jan 26, 2015 at 11:33:29AM -0800, Piotr Banaszkiewicz wrote:
> Now, is there any webservice free for open source projects that
> measures coverage upon pull requests?

You can use coverage.py with any CI service [1].  If you want a hard
limit for coverage, you can use:

  $ coverage report --fail-under=70

to require at least 70% coverage.

[1]: https://docs.djangoproject.com/en/1.7/topics/testing/advanced/#integration-with-coverage-py

**Comment by gvwilson** [comment]
Can this please be worked on *after* authentication and CSV upload are 
both in?

**Comment by wking** [comment]
On Mon, Jan 26, 2015 at 02:33:30PM -0800, Greg Wilson wrote:
> Can this please be worked on *after* authentication and CSV upload
> are both in?

Fine with me.  I should have time to finish off #147 this week, but
other folks are welcome to pick it up (either entirely, or via PRs
against my branch) if they want to chip in.  Rebasing onto the new
master to pick up #160 and resolve conflicts with #161 should be
fairly easy to do.

**Comment by pbanaszkiewicz** [comment]
We can use [coveralls.io] (https://coveralls.io/) for measuring our code coverage. The Github integration is pretty neat (see https://coveralls.io/features#github).

**Comment by pbanaszkiewicz** [comment]
@gvwilson have you tried switching on travis-ci for `@swcarpentry/amy`?

**Comment by pbanaszkiewicz** [comment]
Up and running: https://travis-ci.org/swcarpentry/amy

**Comment by wking** [comment]
On Wed, May 13, 2015 at 07:07:12AM -0700, Piotr Banaszkiewicz wrote:
> Up and running: https://travis-ci.org/swcarpentry/amy

:)
