### ISSUE TITLE
Test deployment on server

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#167]
We need to test deployment on amy.software-carpentry.org.

**Comment by pbanaszkiewicz** [comment]
@gvwilson @drio what's up with the experimental deployment? http://amy.software-carpentry.org/ is 404-ing.

**Comment by wking** [comment]
On Tue, Feb 10, 2015 at 02:08:34PM -0800, Piotr Banaszkiewicz wrote:
> @gvwilson @drio what's up with the experimental deployment?
> http://amy.software-carpentry.org/ is 404-ing.

Now it's 500-ing.  I'm happy to step in and help with the deploy and
related issues [1], but I'd need SSH access to
amy.software-carpentry.org.

[1]: https://github.com/swcarpentry/amy/labels/deployment

**Comment by drio** [comment]
On Sat, 21 Feb 2015 at 13:16:09 -0800, W. Trevor King wrote:
>    On Tue, Feb 10, 2015 at 02:08:34PM -0800, Piotr Banaszkiewicz wrote:
>    > @gvwilson @drio what's up with the experimental deployment?
>    > http://amy.software-carpentry.org/ is 404-ing.
>    Now it's 500-ing. I'm happy to step in and help with the deploy and
>    related issues [1], but I'd need SSH access to
>    amy.software-carpentry.org.

You have to use port 8080

http://amy.software-carpentry.org:8080

-drd

**Comment by wking** [comment]
On Sat, Feb 21, 2015 at 01:27:09PM -0800, David Rio Deiros wrote:
> You have to use port 8080
> 
> http://amy.software-carpentry.org:8080

Ah, that works.  Thanks :).  Not much I can do there without a
superuser account in Django, but it's good to see it up.

**Comment by pbanaszkiewicz** [comment]
Currently Amy is (again) hosted on http://amy.software-carpentry.org:8080.
