### ISSUE TITLE
Implement backups of data on server

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#168]
Very frequent, since new code.

**Comment by pbanaszkiewicz** [comment]
@gvwilson what is required for backups? Does future AMY server have some backups configured already?

**Comment by gvwilson** [comment]
Nothing in place yet; we'll need backups very, very frequently during 
deployment (like, every 15 minutes if there's been a change to the DB).

**Comment by wking** [comment]
On Tue, Feb 10, 2015 at 02:18:01PM -0800, Greg Wilson wrote:
> Nothing in place yet; we'll need backups very, very frequently
> during deployment (like, every 15 minutes if there's been a change
> to the DB).

I'd dump the “if there's been a change to the DB” requirement, and
just setup a cron job to copy db.sqlite3 to a date-stamped file every
15 minutes (e.g. /var/lib/amy/backup/2015-02-10T14:15-db.sqlite3).
I'd use a COW filesystem like btrfs (with ‘cp --reflink …’) to avoid
using extra space (besides the metadata entry) when the content didn't
change.

**Comment by wking** [comment]
On Tue, Feb 10, 2015 at 02:28:13PM -0800, W. Trevor King wrote:
> I'd use a COW filesystem like btrfs…

And you could fake this on filesystems without copy-on-write by using
Git to store the backups with a single filename and commits for each
15-minute interval.  It would be harder to remove old versions (you'd
need to make the repository more shallow, and a quick search didn't
turn up an obvious command to do that.  With the COW filesystem, you
could just use ‘rm’).  In any case, I think it's best to handle this
sort of per-installation issue outside of amy, using an
amy-independent approach.

**Comment by pbanaszkiewicz** [comment]
@wking is btrfs safe enough?

I'm unable to set up such configuration on a file system. Personally I'm using [duplicity](http://duplicity.nongnu.org/) with software RAID - kind of an easy solution.

**Comment by wking** [comment]
On Tue, Feb 10, 2015 at 02:55:05PM -0800, Piotr Banaszkiewicz wrote:
> @wking is btrfs safe enough?

I've been using it since January 2011 without any data loss.

> I'm unable to set up such configuration on a file system.

Why not?  Btrfs is fairly widely adopted, and I've never had a problem
setting it up.

> Personally I'm using duplicity with software RAID - kind of an easy
> solution.

How does that handle de-duplication?  With snapshots every fifteen
minutes, the current 2 MB db.sqlite3 will use about 1.3 GB per week of
backups unless you've got another de-duplication strategy up your
sleeve.

**Comment by pbanaszkiewicz** [comment]
> I've been using it since January 2011 without any data loss.
> > I'm unable to set up such configuration on a file system.
>
> Why not? Btrfs is fairly widely adopted, and I've never had a problem setting it up.

[Looking through Phoronix](www.google.pl/cse?cx=partner-pub-0253814508491313:1305299758&ie=UTF-8&q=btrfs&gws_rd=cr&gsc.q=btrfs&gsc.page=1#gsc.tab=0&gsc.q=btrfs&gsc.page=1) I can see a lot of decent-good articles about btrfs.  However, something about btrfs and data loss still rings a bell to me.

> How does that handle de-duplication? With snapshots every fifteen minutes, the current 2 MB db.sqlite3 will use about 1.3 GB per week of backups unless you've got another de-duplication strategy up your sleeve.

It's using incremental backups. I'm running it weekly, and every 2 months there's a full backup.
I'd not consider duplicity a proper solution for backup on Amy's server.

**Comment by gvwilson** [comment]
@codersquid any thoughts on backups?  And would this all be simpler if 
Amy was hosted on a numfocus.org server instead of on 
software-carpentry.org ?

**Comment by codersquid** [comment]
@gvwilson no thoughts on backups yet. Things would be the same, as far as I know, but I'll check with numfocus.org to see where things are. I just joined and I don't know yet where they have things hosted.

**Comment by wking** [comment]
On Wed, Feb 11, 2015 at 02:13:34AM -0800, Piotr Banaszkiewicz wrote:
> However, something about btrfs and data loss still rings a bell to
> me.

Regardless of how stable btrfs is, it's probably still not a great
idea to trust sensitive data to a single filesystem or physical
location.  I think we can all agree that btrfs is reliable enough to
trust for high-frequency backups.  Then every 24 hours we can copy off
a database snapshot to a remote location.  That way if btrfs acts up
(or a meteor hits the hosting facility, etc.) we'll never lose more
than 24 hours of work.  In the more likely event that someone does
something silly using the amy interface or hits a data-destroying bug
in amy itself, we can use the btrfs backups and we'll never lose more
than 15 minutes of work.

**Comment by pbanaszkiewicz** [comment]
Here's the simple solutions we're trying with Greg:

```bash
#!/bin/bash

REMOTE_PATH="~/sites/amy.software-carpentry.org/db.sqlite3"
REMOTE="swc@software-carpentry.org:$REMOTE_PATH"
TIMESTAMP=`date +"%FT%T"`
LOCAL_PATH="$TIMESTAMP-db.sqlite3.backup"
LOCAL="/home/piotr/workspace/SwC/backup_amy/$LOCAL_PATH"

echo "[$TIMESTAMP] starting backup ($REMOTE to $LOCAL)"
scp $REMOTE $LOCAL
```

When invoked manually (`./amy_backup.sh`), it simply works.

This is what I have in crontabs (general and for my user `crontab -e`):
```
0  0    * * *   piotr   /home/piotr/workspace/SwC/backup_amy/amy_backup.sh >> /home/piotr/workspace/SwC/backup_amy/backup.log 2>&1
```
```
0   0   *   *   *    /home/piotr/workspace/SwC/backup_amy/amy_backup.sh >> /home/piotr/workspace/SwC/backup_amy/backup2.log 2>&1
```

As you can see, they dump logs to different files.

The logs show (`cat backup*.log`):
```
[2015-05-05T00:00:01] starting backup (swc@software-carpentry.org:~/sites/amy.software-carpentry.org/db.sqlite3 to /home/piotr/workspace/SwC/backup_amy/2015-05-05T00:00:01-db.sqlite3.backup)
[2015-05-05T00:00:01] starting backup (swc@software-carpentry.org:~/sites/amy.software-carpentry.org/db.sqlite3 to /home/piotr/workspace/SwC/backup_amy/2015-05-05T00:00:01-db.sqlite3.backup)
```

(Notice how scp output is not appended to the logs.)

No backups are downloaded, though…

Manual invocation:
```
[2015-05-06T21:18:06] starting backup (swc@software-carpentry.org:~/sites/amy.software-carpentry.org/db.sqlite3 to /home/piotr/workspace/SwC/backup_amy/2015-05-06T21:18:06-db.sqlite3.backup)
stdin: is not a tty
db.sqlite3                                                       100% 2796KB 699.0KB/s   00:04    
```

I have Anacron 2.3, and some cron is installed, too - not sure which one is being used by the OS (Ubuntu 14.04).

**Comment by wking** [comment]
On Wed, May 06, 2015 at 12:19:29PM -0700, Piotr Banaszkiewicz wrote:
> (Notice how scp output is not appended to the logs.)

I'm not sure where your system cron is logging, but with vixie-cron on
Gentoo I get logs to syslog by default:

  # grep cron /var/log/messages
  …
  May  4 06:00:01 {hostname} cron[26698]: (root) CMD (/usr/bin/mlmmj-maintd -F -d /var/spool/mlmmj)
  …

Do you see anything interesting there?  For example “Ahh!  I can't scp
because …!” ;)

**Comment by pbanaszkiewicz** [comment]
`grep -i 'cron' /var/log/syslog`:
```
May  6 15:30:14 zenbook anacron[16530]: Job `cron.daily' terminated
May  6 15:30:14 zenbook anacron[16530]: Normal exit (1 job run)
May  6 16:17:01 zenbook CRON[10714]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
May  6 16:54:58 zenbook anacron[1132]: Anacron 2.3 started on 2015-05-06
May  6 16:54:58 zenbook cron[1065]: (CRON) INFO (pidfile fd = 3)
May  6 16:54:58 zenbook cron[1136]: (CRON) STARTUP (fork ok)
May  6 16:54:58 zenbook cron[1136]: (CRON) INFO (Running @reboot jobs)
May  6 16:54:58 zenbook anacron[1132]: Normal exit (0 jobs run)
May  6 16:55:01 zenbook anacron[1848]: Anacron 2.3 started on 2015-05-06
May  6 16:55:01 zenbook anacron[1848]: Normal exit (0 jobs run)
May  6 17:17:01 zenbook CRON[3780]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
May  6 18:16:58 zenbook anacron[4640]: Anacron 2.3 started on 2015-05-06
May  6 18:16:58 zenbook anacron[4640]: Normal exit (0 jobs run)
May  6 18:17:01 zenbook CRON[4711]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
May  6 19:17:01 zenbook CRON[5519]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
May  6 20:17:01 zenbook CRON[6455]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
May  6 21:11:26 zenbook crontab[7565]: (piotr) BEGIN EDIT (piotr)
May  6 21:12:01 zenbook crontab[7565]: (piotr) END EDIT (piotr)
May  6 21:16:31 zenbook cron[7712]: (CRON) DEATH (can't open or create /var/run/crond.pid: Permission denied)
May  6 21:17:01 zenbook CRON[7762]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
May  6 21:56:17 zenbook anacron[10186]: Anacron 2.3 started on 2015-05-06
May  6 21:56:17 zenbook anacron[10186]: Normal exit (0 jobs run)
```

The 21:16:31 DEATH was probably caused by me running `cron` without sudo.

The log may show more once the actual backup jobs are run.

**Comment by wking** [comment]
On Wed, May 06, 2015 at 01:19:18PM -0700, Piotr Banaszkiewicz wrote:
> The log may show more once the actual backup jobs are run.

You can kick up the job frequency (e.g. run every five minutes) while
you're debugging things.  I usually find easier to debug with a
shorter feedback cycle ;).

**Comment by pbanaszkiewicz** [comment]
I believe I've found the root of error. I had to specify an identity file (private key) for `scp`.

I'll close once I confirm that the backup script is working correctly.

Here's the current version of the script:
```bash
#!/bin/bash

REMOTE_PATH="~/sites/amy.software-carpentry.org/db.sqlite3"
REMOTE="swc@software-carpentry.org:$REMOTE_PATH"
TIMESTAMP=`date +"%FT%T"`
LOCAL_PATH="$TIMESTAMP-db.sqlite3.backup"
LOCAL="/home/piotr/workspace/SwC/backup_amy/$LOCAL_PATH"
IDENTITY="/home/piotr/.ssh/…"

echo "[$TIMESTAMP] starting backup ($REMOTE to $LOCAL)"
scp -i $IDENTITY $REMOTE $LOCAL
```

**Comment by pbanaszkiewicz** [comment]
Aaaand… it worked.
