### ISSUE TITLE
Add "Add new" link also at the top of the page

### ISSUE THREAD

**Issue by r-gaia-cs** [swcarpentry/amy#170]
I know that user interface isn't a priority right know but what about add "Add new" link also at the top of the page, e.g.

![s](https://cloud.githubusercontent.com/assets/1506457/5910992/b743f306-a5a7-11e4-8c55-23a7f70657a6.jpg)

Do that should be easy. If all agree to it I can open a pull request to it tomorrow.

**Comment by gvwilson** [comment]
Post-v1.0 please.

**Comment by wking** [comment]
On Mon, Jan 26, 2015 at 04:35:29PM -0800, Greg Wilson wrote:
> Post-v1.0 please.

We're not at v1.0 yet [1] and this is tagged v1.1, but it's also
tagged essential?  Shouldn't all of the v1.1 issues have the same
priority?  Should we be dealing with them now, or waiting for v1.0?

**Comment by pbanaszkiewicz** [comment]
Added in #222
