### ISSUE TITLE
Crash when viewing upcoming event

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#171]
This is either a data import error or a bug in Amy; either way, Amy should give something better than a stack trace when something goes wrong.

1.  `make clean`
2.  `make database` to import faked data.
3.  `make serve` to run.
4.  go to http://127.0.0.1:8000/workshops/
5.  fifth event down under 'upcoming events' is labelled 2015-04-xx-ttt-nih - click on it.
6.  boom: "ObjectDoesNotExist at /workshops/event/2015-04-xx-ttt-nih"

Other upcoming events display properly, and occurs as of b2e0c6058.

**Comment by pbanaszkiewicz** [comment]
Regexp here: https://github.com/swcarpentry/amy/blob/a3db9535a289d44c3cf429f61c3a1beca1665d63/workshops/models.py#L234 fails to catch YYYY-MM pattern, I'll provide a PR for that soon
