### ISSUE TITLE
Fixtures for development

### ISSUE THREAD

**Issue by pbanaszkiewicz** [swcarpentry/amy#184]
As mentioned in #183 it's probably high time we get rid of anonymized `db.sql` for development and switch to [fixtures](https://docs.djangoproject.com/en/1.7/howto/initial-data/#providing-initial-data-with-fixtures) - a well established way of introducing initial data for database.

For loading fixtures we can use `./manage.py loaddata` [command](https://docs.djangoproject.com/en/1.7/ref/django-admin/#django-admin-loaddata).

What do you think? Do you have any other ideas? Or do you perhaps disagree with me? :)

**Comment by pbanaszkiewicz** [comment]
Related discussion: https://github.com/swcarpentry/amy/issues/158 (where we basically agreed to use fixtures).

Here we are working out a way to use them in `Makefile`.

**Comment by gvwilson** [comment]
We're going to keep `db.sql` for the foreseeable future - it's as close 
to the real data we need to work with as I can safely get, so it's what 
I use for manual testing.

**Comment by pbanaszkiewicz** [comment]
Bummer… Guess I'll make myself a stripped-down version of your anonymized data as a fixture.

**Comment by gvwilson** [comment]
On 2015-02-09 5:34 PM, Piotr Banaszkiewicz wrote:
>
> Bummer… Guess I'll make myself a stripped-down version of your 
> anonymized data as a fixture.
>
Can SQLite dump data as JSON?  Or if not, can Python + Django load it 
all then dump as JSON?

**Comment by pbanaszkiewicz** [comment]
> Can SQLite dump data as JSON? Or if not, can Python + Django load it all then dump as JSON?

Yes, we can dump from Django `./manage.py` as suggested by @sburns [here] (https://github.com/swcarpentry/amy/issues/158#issuecomment-71167315):

```
$ ./manage.py dumpdata model --format=json --indent=2 --pk=... > fixture.json
```

**Comment by gvwilson** [comment]
So we could modify the Makefile to run `migrater.py`, then dump to JSON, 
all in one step?

**Comment by pbanaszkiewicz** [comment]
Yes. We can have, for example, a `Makefile` entry that:

* runs `migrater.py`
* creates fixtures (using anonymized database)

One issue is that the anonymized data you're using is BIG:

```
(amy3k) ~/workspace/amy   master  ./manage.py dumpdata workshops --settings=amy.settings --format=json --indent=2 > fixture.json
(amy3k) ~/workspace/amy   master  ls -lh fixture*
-rw-rw-r-- 1 piotr piotr 5.7M Feb 10 00:19 fixture.json
(amy3k) ~/workspace/amy   master  wc -l fixture*
314901 fixture.json
```

**Comment by wking** [comment]
On Mon, Feb 09, 2015 at 02:23:54PM -0800, Greg Wilson wrote:
> We're going to keep `db.sql` for the foreseeable future - it's as
> close to the real data we need to work with as I can safely get, so
> it's what I use for manual testing.

Instead of using fuzzed manual data, why not just use the test
fixtures for testing (Ironman, Spiderman, etc.)?  As I mentioned in
#158 [1], it shouldn't be hard to explicitly hit any corner cases we
want to hit.  And hitting corner cases should really be done in
automated testing.  Anyhow, only time I think we want manual use is
for working on UI design, and then it doesn't really matter what the
test data is.  I don't see a need to keep *two* sets of fixtures (one
for automatic testing and a separate set for UI design) when it seems
like the automatic test fixtures could serve both purposes.

[1]: https://github.com/swcarpentry/amy/issues/158#issuecomment-71155251

**Comment by gvwilson** [comment]
If you'd like to create fixtures big enough to exercise pagination, fire 
away.

**Comment by wking** [comment]
On Mon, Feb 09, 2015 at 03:50:14PM -0800, Greg Wilson wrote:
> If you'd like to create fixtures big enough to exercise pagination,
> fire away.

Will do, although once #134 lands we will be outsourcing pagination to
an external library, so I don't think exercising it now is
particularly important.

**Comment by pbanaszkiewicz** [comment]
I think we're sticking to blurred data with `anonymizer.py`. It's quite easy to forget about some fields (like history of changes, user passwords) or run `./manage.py createinitialrevisions` on the blurred database, so anyone preparing that database has to be cautious.
