### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#188]
We need a user's guide - please add comments to this issue to collect things that should be in it.

**Comment by gvwilson** [comment]
Use local names (e.g., Uniwersytet w Białymstoku) for locations rather than anglicized names (e.g., University of Bialystok), but stick to something close to the Latin alphabet (no Cyrillic or kanji).

**Comment by gvwilson** [comment]
Only people with admin privileges should be able to log in, so when you create a new user, even though you've specified a password, you shouldn't be able to log in.

**Comment by gvwilson** [comment]
The "may contact" box on the Person record indicates whether we're allowed to mail people - some people don't want to be contacted.

**Comment by pbanaszkiewicz** [comment]
That are event "tags" for?

**Comment by wking** [comment]
On Sat, May 23, 2015 at 01:57:13AM -0700, Piotr Banaszkiewicz wrote:
> That are event "tags" for?

Looking through the history gives some background and points to #126:

  $ git blame workshops/models.py | grep -A10 'class Event(' | grep tags
  97be0d9c (W. Trevor King      2015-01-03 14:56:15 -0800 268)     tags       = models.ManyToManyField(Tag)
  $ git show 97be0d9c
  …
    workshops/models.py: Rename Project to Tag and make Event.tags many-to-many
    
    We want to tag events for groupings beyond projects.  For example,
    some students and instructors may have a particular interest in WiSE
    (Women in Science and Engineering) events.  I think this covers the
    Event.project use case in a more general way, so I've just renamed
    'Project' to 'Tag' and 'Event.project' to 'Event.tags'.  Event.tags is
    many-to-many so we can assign several tags to the same event, both our
    traditional projects (e.g. SWC) and additional tags (e.g. WiSE).
  …
  $ git log --graph --topo-order --oneline --decorate origin/master | grep -B10 97be0d9
  | |/ / / /  
  * | | | |   80744d9 Merging changes, but need to fix migrater
  |\ \ \ \ \  
  | |/ / / /  
  |/| | | |   
  | * | | | 0b36e0d (origin/pr/126) workshops/templates/workshops: Transition from Event.project to Event.tags
  | * | | | 60884d2 workshops/test: Remove obsolete references to Project
  | * | | | 7e4055c db.sql: Migrate to event.tags
  | * | | | 8ee2f2b workshops/migrations/0035_auto_20150107_1205.py: Add data migration
  | * | | | 71e8ad1 workshops/migrations/0035_auto_20150107_1205.py: Rename Project to Tag
  | * | | | 97be0d9 workshops/models.py: Rename Project to Tag and make Event.tags many-to-many

**Comment by pbanaszkiewicz** [comment]
I think we need to clear up what are tags for both here, and in the `tags` field help text.

**Comment by pbanaszkiewicz** [comment]
**Publicating events**: events that have specified both starting date and URL are considered "published". This does not affect main Software Carpentry website, only the dashboard in AMY. "Published" events with starting date in future are shown as "Upcoming".

**Comment by wking** [comment]
On Fri, Jun 19, 2015 at 09:58:15AM -0700, Piotr Banaszkiewicz wrote:
> **Publicating events**: events that have…

“Publicating” → “Publishing”.

**Comment by pbanaszkiewicz** [comment]
Thanks!

**Comment by amyrbrown** [comment]
We/I need more clarification for "may contact". I am interpreting it as "this person has specifically agreed to receive unsolicited email from us", so the default is "no", but that means I don't see the person's email address when they are listed under an event.

So is the default "yes" -- we assume everyone we add to the database is willing to receive email from us?  That is to say, "may contact" actually means "has not specifically requested that we do not email  them"?

**Comment by pbanaszkiewicz** [comment]
@amyrbrown:
Greg said a long time ago that we sometimes have people (instructors, maybe admins too) who explicitly tell us not to contact them.

I'm not sure what is law saying about that, also I'm not sure which country's law we should follow. In Poland for example advertising contact is always opt-in, but "normal" contact not necessarily.

**Comment by gvwilson** [comment]
"May contact" should be TRUE by default; the FALSE option is there 
because a handful of instructors and others have said "please no more 
email for now" (typically while they're busy with other things).

**Comment by amyrbrown** [comment]
Okay, so it should NOT be regarded as any kind of mailing list opt-in.
