### ISSUE TITLE
Add alphabetized "jump to" links for sites and people

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#189]
The "all sites" and "all events" pages should have alphabetized links A..Z at the top that jump to the page with those sites or people. People should be alphabetized by surname; don't know what to do about alphabetizing institutions (since so many start with the word 'University').

**Comment by pbanaszkiewicz** [comment]
Wouldn't it be better to just use DataTables lookup for this? https://github.com/swcarpentry/amy/issues/129

**Comment by gperu** [comment]
@gvwilson : On Amy there are 11 pages of sites; of these only 2 start with 'Universit....', therefore alphabetising the name of institution wouldn't be so pointless. But personally, I'd alphabetise based on the domain of the institution.

@pbanaszkiewicz : I'm sure you have a point there.

**Comment by pbanaszkiewicz** [comment]
This might be done using specific filter in django-filters. Shifting to v0.5 for now.

**Comment by gvwilson** [comment]
Can this be closed now that we've upgraded pagination?

**Comment by pbanaszkiewicz** [comment]
Sure!
