### ISSUE TITLE
Event details page should allow validation of Eventbrite link

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#19]
If Eventbrite is being used to handle registration for an event, the event details page should allow the admin to validate the key.  This should not happen automatically (since it takes a while, and some events don't use Eventbrite), but should be a single-button operation.

**Comment by pbanaszkiewicz** [comment]
@gvwilson What's the status on this issue?

**Comment by gvwilson** [comment]
Not needed for 1.0.

**Comment by pbanaszkiewicz** [comment]
Should we include this in v1.1 or later?

**Comment by gvwilson** [comment]
Let's worry about that after this is deployed.

**Comment by gvwilson** [comment]
@maneesha @pbanaszkiewicz can this one be closed as stale?

**Comment by pbanaszkiewicz** [comment]
Will reopen if necessary.
