### ISSUE TITLE
Make sure new events can be added *without* a URL.

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#190]
We need to be able to add events (so that we can start collecting data) before we have a date (which means we won't yet have a URL or slug). Check that this works, and if it doesn't, fix it.

**Comment by wking** [comment]
On Wed, Feb 18, 2015 at 09:19:38AM -0800, Greg Wilson wrote:
> We need to be able to add events (so that we can start collecting
> data) before we have a date (which means we won't yet have a URL or
> slug). Check that this works, and if it doesn't, fix it.

Can this be closed now that #195 has landed proving that we can do
this?

**Comment by gvwilson** [comment]
Yes - thanks.
