### ISSUE TITLE
Match by email address when uploading CSV

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#192]
We need to match people by email address during bulk upload of attendance data and give the admin the option of saying, "Yes, re-use this person" rather than rejecting the upload because it contains email addresses that are already in the database.

**Comment by pbanaszkiewicz** [comment]
This will land in #201.

**Comment by wking** [comment]
On Sat, Feb 28, 2015 at 01:48:58PM -0800, Piotr Banaszkiewicz wrote:
> This will land in #201.

#201 has landed, so I think we should close this issue.  #211 is
related, but we can track it's state in #211 ;).

**Comment by pbanaszkiewicz** [comment]
Agreed :)
