### ISSUE TITLE
Language and character sets for names?

### ISSUE THREAD

**Issue by wking** [swcarpentry/amy#197]
Spun off from #188, so it doesn't distract from the search for other documentation.

On Wed, Feb 18, 2015 at 09:16:16AM -0800, [Greg Wilson wrote][1]:
> Use local names (e.g., Uniwersytet w Białymstoku) for locations
> rather than anglicized names (e.g., University of Bialystok), but
> stick to something close to the Latin alphabet (no Cyrillic or
> kanji).

Local names makes sense to me, but I'm not clear on why we should avoid the local character set (e.g. Cyrillic, kanji, etc.).  It makes sense to me to just go completely native.  I wouldn't restrict this to locations either.  I don't see why people can't use their native character set for their personal names, or for site names, etc.  Python 3 won't have a problem with the Unicode data, and it's easy for users to install a free font (like [DejaVu][2] or [Unifont][3]) if they are missing the non-Latin glyphs.

Previous discussion on `amy@`:

On Tue, Feb 17, 2015 at 10:08:27PM -0800, [W. Trevor King wrote][4]:
> On Tue, Feb 17, 2015 at 13:40:55 +0000, [Giacomo Peru wrote][5]:
> > - Should the full name of a site in English or in the local language
> > (University of Bialystok or Uniwersytet w Białymstoku)? I guess in
> > English.
>
> Heh, I'd have guessed in the local language :p.  I think we do want
> Event.language using ISO 639 alpha-2 or alpha-3 codes [1].  If/when we
> have multi-language workshops, we'll want separate language model
> (maybe [django-languages-plus][6]?) and a many-to-many table
> connecting the Event and language tables.

So:

* Do we have a reason to prefer almost-Latin characters?
* Do we (or will we) have any multi-language workshops?  This touches on swcarpentry/workshop-template#160, where we could use both "[en][]" and "[ase][]" codes to mark a workshop as speaking both English and American Sign Language (e.g. if there was an ASL interpreter or the instructors and helpers spoke ASL and English).
* Do we want to list language-skills for the instructors?  I think we should, which would make it easier to do things like find Portuguese-speaking instructors for a Portuguese-language event.  I wouldn't worry about scoring fluency, just let instructors list the languages they'd feel comfortable teaching in.

[1]: https://github.com/swcarpentry/amy/issues/188#issuecomment-74904954
[2]: http://dejavu-fonts.org/wiki/Main_Page
[3]: http://unifoundry.com/unifont.html
[4]: http://lists.software-carpentry.org/pipermail/amy_lists.software-carpentry.org/2015-February/000042.html
[5]: http://lists.software-carpentry.org/pipermail/amy_lists.software-carpentry.org/2015-February/000041.html
[6]: https://pypi.python.org/pypi/django-languages-plus/0.1.2
[en]: http://en.wikipedia.org/wiki/List_of_ISO_639-2_codes
[ase]: http://www-01.sil.org/iso639-3/documentation.asp?id=ase

**Comment by gvwilson** [comment]
On 2015-02-19 12:03 AM, W. Trevor King wrote:
> Local names makes sense to me, but I'm not clear on why we should 
> avoid the local character set (e.g. Cyrillic, kanji, etc.).
Because almost every scientist can read things written in the Latin 
alphabet (or some close to it), but most of us can't read other alphabets.

**Comment by wking** [comment]
On Thu, Feb 19, 2015 at 02:35:12AM -0800, Greg Wilson wrote:
> 2015-02-19 12:03 AM, W. Trevor King:
> > Local names makes sense to me, but I'm not clear on why we should
> > avoid the local character set (e.g. Cyrillic, kanji, etc.).
>
> Because almost every scientist can read things written in the Latin
> alphabet (or some close to it), but most of us can't read other
> alphabets.

If the workshop isn't in a language you speak, do you need to read the
name?  For the odd times that you do need a pronounceable name, you
can always paste the native form into a translation service.  I'm also
fine restricting the slug to ASCII, and having non-native-readers
refer to the event by its slug.

**Comment by gvwilson** [comment]
Slug in ASCII + title on Software Carpentry website in extended Latin == 
workable compromise?

**Comment by wking** [comment]
On Thu, Feb 19, 2015 at 09:34:28AM -0800, Greg Wilson wrote:
> Slug in ASCII + title on Software Carpentry website in extended
> Latin == workable compromise?

“title on Software Carpentry website in extended Latin” sounds like
your starting position ;).  I'd rather “Slug in ASCII + title on
Software Carpentry website in the event-native language and charset”.
I don't think we need to enforce this policy in amy though, I'm happy
leaving the title charset up to the admins and convention.  That would
let us experiment with both approaches and see which was more popular.

**Comment by pbanaszkiewicz** [comment]
At my university we have a special [resolution](http://www.dwz.agh.edu.pl/pl/home/wspolpraca-miedzynarodowa/nazwa-uczelni-w-j-obcych) (you can run it through Google Translator if you want) that says "in English you should call this university: AGH University of Science and Technology (abbreviation: AGH UST)".

In Poland we do keep English names when setting up workshop repositories. I think that, at least in Poland, we don't have problems with using only English names of universities for two reasons:

1. English is our second most-common language -- virtually everyone knows at least a little bit of it.

2. We know that Software Carpentry is US (or Canada) based and we don't expect anyone from the Foundation (maybe except for @apawlik) to be able to read and write Polish.

I would not force you to use Polish name of my university ("Akademia Górniczo-Hutnicza im. Stanisława Staszica w Krakowie") and I know people from other Polish universities feel similar. I encourage using English names.

**Comment by gvwilson** [comment]
I'm making a call on this one for Version 1: Latin-like names (i.e., Latin characters, possibly accented) for site names, in whatever language the host chooses (so either Uniwersytet w Białymstoku or University of Bialystok).  Ditto for personal names and everything else, and we'll revisit after CSV upload is working and this is in production.
