### ISSUE TITLE
Must not require people to fill in 'Notes' when creating new sites and events

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#198]
The `notes` field in `Site` and `Event` is optional - people must not be required to fill it in when creating new sites or events.

**Comment by wking** [comment]
On Thu, Feb 19, 2015 at 06:14:57AM -0800, Greg Wilson wrote:
> The `notes` field in `Site` and `Event` is optional - people must
> not be required to fill it in when creating new sites or events.

I'd expect this to be covered (at least for Event) by #195, and I
can't reproduce the problem in local Event testing.
