### ISSUE TITLE
Event details page should include links to assessment forms

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#20]
1. The event details page should link to pre- and post-assessment forms for learners and the post-assessment form for instructors.

2. There should be a way to validate those forms' existence from the event details page. This shouldn't happen automatically, but shouldn't require more than a single button click.

3. Admins should be able to create these forms from the event details page, again with a single button click.

4. There should be a simple way to send the forms' links to the event's instrutors (and hosts?).

**Comment by pbanaszkiewicz** [comment]
Ref #213

**Comment by maneesha** [comment]
This is an old issue -- now that we are using Survey Monkey I'd like fields that just hold the survey results.  This would be 5 fields for the 5 surveys we're planning on using:
Learner pre & post
Instructor pre & post
Learner Longterm

**Comment by pbanaszkiewicz** [comment]
@maneesha I looked into this issue some time ago. From what I saw, the links don't have a predictable form, and I didn't seem to be able to get them via API - but I need to check again.

**Comment by maneesha** [comment]
I was thinking these would be manually entered.  So we'd just need 5  text fields validated to hold hyperlinks.

**Comment by pbanaszkiewicz** [comment]
Closing this issue in favor of #578 (see https://github.com/swcarpentry/amy/issues/578#issuecomment-169625263).
