### ISSUE TITLE
Bulk-upload: no-op if Person and their Task exist

### ISSUE THREAD

**Issue by pbanaszkiewicz** [swcarpentry/amy#211]
After #201 gets merged in, we'll need to alter it's behavior a little.

Currently if Person and their Task already exist in the DB, an error is raised ("can't have duplicated enries"). @wking suggested in https://github.com/gvwilson/amy/pull/2#issuecomment-76458963 that we should simply do nothing in such cases.

I'm considering an UI extension (new column titled "Notes") that would indicate what's going to happen with the uploaded user.

**Comment by wking** [comment]
On Mon, Mar 02, 2015 at 01:42:01AM -0800, Piotr Banaszkiewicz wrote:
> I'm considering an UI extension (new column titled "Notes") that
> would indicate what's going to happen with the uploaded user.

As I mention in the comment you linked, I don't think we need this
extra UI.  My suggested fix is outlined here [1].

[1]: https://github.com/gvwilson/amy/pull/2#issuecomment-76465279

**Comment by pbanaszkiewicz** [comment]
Fixed in #228.
