### ISSUE TITLE
Support debriefing sessions

### ISSUE THREAD

**Issue by r-gaia-cs** [swcarpentry/amy#213]
What about add a button to generate a list of instructors that taught in the last n weeks so we could send a invitation for the debriefing session?

**Comment by wking** [comment]
On Tue, Mar 03, 2015 at 06:15:21PM -0800, Raniere Silva wrote:
> What about add a button to generate a list of instructors that
> taught in the last n weeks so we could send a invitation for the
> debriefing session?

This (and #214) sound good to me, but should probably wait until after
v1.0.  That doesn't mean we can't start working on the specs now
though ;).  Do we want a special view for this particular feature, or
should we just add more flexibility to /workshops/instructors/?
Personally, I'd rather collapse all the person searching into a single
view, but I've only seen “flexible search with a single field” work
with some well-documented search strings (vs. checkboxes and other
non-text widgets for building queries).  That didn't get rave reviews
the last time I suggested it [1,2,3], but maybe there's a tipping
point that makes the approach simpler than remember the set of
special-purpose search pages ;).

[1]: https://github.com/swcarpentry/amy/issues/24#issuecomment-67971632
[2]: https://github.com/swcarpentry/amy/issues/24#issuecomment-67974983
[3]: https://github.com/swcarpentry/amy/issues/24#issuecomment-67983074

**Comment by r-gaia-cs** [comment]
> > What about add a button to generate a list of instructors that
> > taught in the last n weeks so we could send a invitation for the
> > debriefing session?
> 
> This (and #214) sound good to me, but should probably wait until after
> v1.0.  That doesn't mean we can't start working on the specs now
> though ;).

=)

> Do we want a special view for this particular feature, or
> should we just add more flexibility to /workshops/instructors/?

In this case and #214 I don't see the need for a flexibility search.
In this case the input should be only a time range for workshops date.

**Comment by wking** [comment]
On Wed, Mar 04, 2015 at 02:44:33AM -0800, Raniere Silva wrote:
> > Do we want a special view for this particular feature, or should
> > we just add more flexibility to /workshops/instructors/?
> 
> In this case and #214 I don't see the need for a flexibility search.
> In this case the input should be only a time range for workshops
> date.

Do you want to add that to the /workshops/instructors search?  That
page already has a lot of widgets for finding instructors for future
workshops, and I don't think those widgets would help with this case
or #214.  Would you just add more widgets, and trust users to not mix
and match?  Or do all the combinations actually mean something?  For
example:

  10 Matlab instructors around YVR {assigned to|available for} a
  workshop after 2015-03-04 and before 2015-04-01.

Maybe both the “assigned to” and “available for” forms make sense?
Then we'd just need one additional checkbox to toggle between them.
We'd probably also want a threshold widget for times-taught, rather
than the current bare list or the sortable tables from #134, and then
an “email matches” button to push a notification out to the matching
instructors.

**Comment by r-gaia-cs** [comment]
I have a pull request for it
just need to clean it up tonight.

**Comment by wking** [comment]
On Wed, Mar 04, 2015 at 09:04:08AM -0800, Raniere Silva wrote:
> I have a pull request for it just need to clean it up tonight.

Ah, good :).

**Comment by pbanaszkiewicz** [comment]
This is already working nicely since #216.
