### ISSUE TITLE
Support first workshop session

### ISSUE THREAD

**Issue by r-gaia-cs** [swcarpentry/amy#214]
I'm thinking in run once a month a session for instructors that will teach their first workshop. What about generate this list?

**Comment by gvwilson** [comment]
Rayna Harris and Sheldon McKay are running a session every two weeks for 
instructors who have recently taught; I'd like those to start including 
people who are about to teach (particularly new instructors).  
Generating this report would therefore be v. useful.
Cheers,
G

**Comment by r-gaia-cs** [comment]
When I use `workshops/debrief` I would like to know who taught their first workshop. Feedbacks from everyone are important but the ones from someone that taught for the first time can help us avoid drop outs.

**Comment by gvwilson** [comment]
Excellent idea - display count of number of workshops taught beside each 
person's name?

**Comment by r-gaia-cs** [comment]
> display count of number of workshops taught beside each person's name?

It can be.
