### ISSUE TITLE
Idea: "events with no instructors" on the main page

### ISSUE THREAD

**Issue by pbanaszkiewicz** [swcarpentry/amy#224]
While working on the #221 I had an idea: we're highlighting events that do not have any instructors assigned in `all_events` view. We could put these events in the dashboard.

@gvwilson do you think this would be helpful?

**Comment by wking** [comment]
On Mon, Mar 09, 2015 at 10:19:45AM -0700, Piotr Banaszkiewicz wrote:
> … we're highlighting events that do not have any instructors
> assigned in `all_events` view. We could put these events in the
> dashboard.

For my earlier ideas on recording an event's instructor slots, see
[1].  I'm not sure how useful it is to single out events with no
instructors when you're also interested in events that don't have
their desired complement of instructors.

[1]: http://lists.software-carpentry.org/pipermail/amy_lists.software-carpentry.org/2015-February/000064.html

**Comment by pbanaszkiewicz** [comment]
Closing because we don't have space on index page anymore. And we show events without instructors for unpublished events.
