### ISSUE TITLE
Bulk-upload: Not checking whether it is a valid csv file

### ISSUE THREAD

**Issue by darshan95** [swcarpentry/amy#231]
When a file with first line in valid .csv format and if the following lines are not in a valid format, 

for example if the file uploaded is :
"""
personal,middle,family,email
This is a test file
"""

There is no error being displayed for the wrong file uploaded, instead a ticket is being displayed. I think there should be a check to validate csv file before trying to upload the data.
Am I right?
![screenshot from 2015-03-17 13 28 34](https://cloud.githubusercontent.com/assets/6889955/6683386/8f7ff0ec-ccab-11e4-97af-4f72e51b9d82.png)

**Comment by pbanaszkiewicz** [comment]
Can you provide a traceback for that error? And that error-causing CSV file?

There's a lot going on in the CSV bulk upload and we might have missed something edge case.

**Comment by darshan95** [comment]
Hi @pbanaszkiewicz,
(Sorry for the late reply.)
This is the case when the file uploaded the format of CSV is not followed. Suppose the CSV file is
/*start of file*/
personal,middle,family,email
This is a test file
/*end of file*/
Then the function upload_person_task_csv in util.py assumes that the data in the second line is in  valid CSV format and tries to obtain the data and rather fails.

**Comment by pbanaszkiewicz** [comment]
I pushed a fix to the #228.
