### ISSUE TITLE
Adjust Apache config to not serve the source directory

### ISSUE THREAD

**Issue by wking** [swcarpentry/amy#236]
See [previous discussion in `amy@`][1].

This is an amy-sysadmin issue, and not really an amy issue, but Greg asked me to post it here with the other amy-related TODOs.

[1]: http://lists.software-carpentry.org/pipermail/amy_lists.software-carpentry.org/2015-April/000078.html

**Comment by pbanaszkiewicz** [comment]
Fixed for now (at least until we decide on how Amy should be deployed) via `.htaccess`.

I additionally made sure that `.git` and databases are unreachable even if the listing was re-enabled.
