### ISSUE TITLE
NULL values in forms displayed as text "None"

### ISSUE THREAD

**Issue by pbanaszkiewicz** [swcarpentry/amy#240]
Hi,

as part of my testing for #237 I discovered that our forms display NULL values as a string "None":

![screen shot 2015-04-04 at 17 24 24](https://cloud.githubusercontent.com/assets/72821/6993264/81a63c0e-daef-11e4-8bee-a849cddf579c.png)

(This is a screenshot taken from one of our tests' output - the test fails.)

I didn't find an easy solution to this issue. The only one I found was to display form fields as such:

```html
<input type="text" name="field" id="id_field" value="{{ form.field.value|default:"" }}" />
```

…which would require us to rewrite forms to HTML because we use `{{ form.as_p }}` in templates.

By the way, our forms could benefit from displaying them with Bootstrap markup, so we may hire [django-bootstrap-form](https://github.com/tzangms/django-bootstrap-form) or [django-crispy-forms](https://github.com/maraujop/django-crispy-forms/).

**Comment by wking** [comment]
On Sat, Apr 04, 2015 at 08:25:38AM -0700, Piotr Banaszkiewicz wrote:
> as part of my testing for #237 I discovered that our forms display
> NULL values as a string "None":
> …
> I didn't find an easy solution to this issue.

We could create a custom NullableCharField and set it's default widget
to use the empty string as the default.  For a similar approach with
date fields, see [1].

> By the way, our forms could benefit from displaying them with
> Bootstrap markup, so we may hire django-bootstrap-form or
> django-crispy-forms.

I haven't used either (but I prefer the Django API + Angular approach
anyway ;).  Both look reasonable, but django-crispy-forms seems pretty
stable (last commit 2014-03-19 [2] vs. 2015-03-09 [3]) and it has 3x
as many contributors and 7x as many commits, so I'd lean towards it.
On the other hand, 2014-03-19 may be *too* stable ;).  There hasn't
been much activity recently [4], but that will hopefully change
soonish [5].

[1]: http://stackoverflow.com/questions/660929/how-do-you-change-the-default-widget-for-all-django-date-fields-in-a-modelform
[2]: https://github.com/maraujop/django-crispy-forms
[3]: https://github.com/tzangms/django-bootstrap-form
[4]: https://github.com/maraujop/django-crispy-forms/pulse/monthly
[5]: https://github.com/maraujop/django-crispy-forms/issues/393#issuecomment-81602292

**Comment by pbanaszkiewicz** [comment]
I took `django-cripsy-forms` for a ride.

With a generic code I was able to turn all forms into something like this:

**Comment by pbanaszkiewicz** [comment]
I took `django-crispy-forms` for a ride.

With a very generic code I was able to turn pretty much any form into something like:

![screen shot 2015-04-05 at 22 46 35](https://cloud.githubusercontent.com/assets/72821/6998548/d5d9d01e-dbe5-11e4-8e71-3d33902211df.png)

It's rendering `None`s as empty strings by default :sparkles:

I like it a lot, however `crispy` introduces some warnings in Django 1.8:
```
/home/piotr/workspace/anaconda/envs/amy3k/lib/python3.4/site-packages/crispy_forms/templatetags/crispy_forms_tags.py:202: RemovedInDjango19Warning: memoize wrapper is deprecated and will be removed in Django 1.9. Use django.utils.lru_cache instead.
  whole_uni_form_template = memoize(whole_uni_form_template, {}, 1)
```

If we decide to use `django-crispy-forms`, but we don't like it in the long run, we can revert very easily. Instead of using:
```
{% load crispy_forms_tags %}
{% crispy form form_helper %}
```

…we'd change back to:
```
<form action="" method="post" role="form">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>
```

**Comment by wking** [comment]
On Sun, Apr 05, 2015 at 02:00:03PM -0700, Piotr Banaszkiewicz wrote:
> With a very generic code I was able to turn pretty much any form
> into something like:

Looks good to me :).

> I like it a lot, however `crispy` introduces some warnings in Django 1.8:
> ```
> …memoize wrapper is deprecated …. Use django.utils.lru_cache instead.

That looks like maraujop/django-crispy-forms#364.  Since there's
already a PR to fix it, I'm optimistic that this gets dealt with once
Miguel Araujo gets back on top of things [1].

Let's do it.

[1]: https://github.com/maraujop/django-crispy-forms/issues/393#issuecomment-81602292

**Comment by pbanaszkiewicz** [comment]
> Let's do it.

Great!

I have one concern, though. I'm making all these changes because Amy isn't compatible with Django 1.8.

So when I make a PR it will resolve #237, #240, incorporate additional dependencies, add crispy to all forms, and display of some `None` values as "—".

If I split this PR, then we have a broken application at each of smaller PRs.

Personally I'd not split, because all these changes depend on each other. What is your opinion, @wking?

**Comment by wking** [comment]
On Sun, Apr 05, 2015 at 02:41:11PM -0700, Piotr Banaszkiewicz wrote:
> So when I make a PR it will resolve #237, #240, incorporate
> additional dependencies, add crispy to all forms, and display of
> some `None` values as "—".
>
> If I split this PR, then we have a broken application at each of
> smaller PRs.

The “None” breakage doesn't seem particularly serious to me.  I don't
mind if you want to go with a single PR, but I'd suggest:

* Switch to crispy forms.
* Migrate [1] to Django 1.8 with template changes, etc (links from [2]).

The crispy form business shouln't need Django 1.8, should it?  Was
there anything else you were proposing for the big PR?

[1]: https://github.com/swcarpentry/amy/issues/237#issuecomment-89671806
[2]: https://github.com/swcarpentry/amy/issues/237#issuecomment-89408945

**Comment by pbanaszkiewicz** [comment]
> The crispy form business shouln't need Django 1.8, should it?

It's a nice solution for our issue caused by "None" values in forms. Prior to Django 1.8 it was not causing our tests to fail, now it is.

I'll go with this order:

1. Switch to crispy forms
2. Make the templates work nicer with None values (ie. represent None as "—", "maybe" or "unknown")
3. Add migration
4. Upgrade to `TEMPLATES` in `settings.py`

Sounds good?

**Comment by wking** [comment]
On Sun, Apr 05, 2015 at 03:57:09PM -0700, Piotr Banaszkiewicz wrote:
> I'll go with this order:
> 
> 1. Switch to crispy forms
> 2. Make the templates work nicer with None values (ie. represent
>    None as "—", "maybe" or "unknown")
> 3. Add migration
> 4. Upgrade to `TEMPLATES` in `settings.py`
> 
> Sounds good?

Yeah, although if it's possible I'd prefer to stick with empty strings
to represent None.  Since 3 and 4 are both part of the 1.8 transition,
I'd put them in a single PR with a bump to requirements.txt.

**Comment by pbanaszkiewicz** [comment]
Hi @wking,

> I'd prefer to stick with empty strings to represent None

Let me summarize how's None going to be stored and displayed:

* database: for example in `Person` model fields that are both `blank` and `null` will save empty string or None as `NULL`
* form: None value will generate a form with `value=""` or, in case of BooleanField, a select with three values ("unknown", "yes", "no")
* object details template / object list template: None will be displayed as "—" in CharFields and IntegerFields and DecimalFields (e.g. `Event.attendance`, `Event.admin_fee`), or as "unknown" in BooleanFields

Does that work for you?

> Since 3 and 4 are both part of the 1.8 transition, I'd put them in a single PR with a bump to requirements.txt.

So if I understand correctly you want to have two PRs:

1. crispy forms, template changes
2. Django version bump, migration, template settings update

It's fine, I can do that thanks to you: I know how to split a branch with `git rebase -i` and `git cherry-pick` :-)
