### ISSUE TITLE
Use Bower for JS, CSS dependencies

### ISSUE THREAD

**Issue by pbanaszkiewicz** [swcarpentry/amy#241]
We need something to manage our JavaScript (and perhaps CSS) dependencies and this tool is called [Bower](http://bower.io).

@wking [wrote](https://github.com/swcarpentry/amy/pull/239#issuecomment-89585714) some handy instructions on getting Bower up and running.

Bower packages we'd use for now:

* `bootstrap`
* `bootstrap-datepicker`

(This should land after #239)

**Comment by pbanaszkiewicz** [comment]
We now have an additional dependency: a jQuery UI Combobox. @neon-ninja do you have a link to the source of that jQ plugin?

@wking do you perhaps have any opinions on https://github.com/nvbn/django-bower?

**Comment by wking** [comment]
On Sat, Apr 18, 2015 at 05:36:28AM -0700, Piotr Banaszkiewicz wrote:
> @wking do you perhaps have any opinions on
> https://github.com/nvbn/django-bower?

I don't think it's worth the trouble of a separate layer [1].  Just
have Bower install to workshops/static [2] before doing any
static-manipulation in Django.

[1]: https://github.com/swcarpentry/amy/pull/105#issuecomment-67906486
[2]: https://github.com/swcarpentry/amy/pull/239#issuecomment-89585714
