### ISSUE TITLE
Global Science Sprint

### ISSUE THREAD

**Issue by neon-ninja** [swcarpentry/amy#244]
Would amy like to be a project for Mozilla's global sprint?

http://www.mozillascience.org/announcing-our-global-sprint-2015

**Comment by pbanaszkiewicz** [comment]
I cannot say for sure if I'm available in June (a tough month for me). July could work better.

But the idea of a global sprint appeals to me. If we could get @wking, @neon-ninja, @shapiromatron, me and maybe @gvwilson to work on Amy, it would be great.
