### ISSUE TITLE
Turn `views.py` into Python package

### ISSUE THREAD

**Issue by pbanaszkiewicz** [swcarpentry/amy#246]
`views.py` has gotten very big. It'd be handy to turn it into a Python package, for example with this structure:

```
views
→ __init__.py
→ base.py
→ persons.py
→ events.py
→ index.py
→ sites.py
→ airports.py
→ tasks.py
→ badges.py
→ extra.py
```

**Comment by wking** [comment]
On Sun, Apr 19, 2015 at 02:02:16AM -0700, Piotr Banaszkiewicz wrote:
> → extra.py

What's this for?  My personal preference would be “have a single
module for each model class named after the model's class name
(e.g. Site in workshops/models/site.py, Airport in
workshops/models/airport.py, …).  But regardless of how you break it
up, I think this is a good idea.

**Comment by gvwilson** [comment]
If we don't need to turn things into packages for deployment right now, 
I'd rather push this off until after we get something up and running 
that the admins can use.

**Comment by codersquid** [comment]
You don't want to turn `views.py` in to a package. The lengthy view file is a side effect of having everything in one django app. What you can do is take a look at what exists in the `workshops` app and see what makes sense to break out in to different apps.

**Comment by wking** [comment]
On Wed, Apr 22, 2015 at 02:34:05PM -0700, Sheila Miguez wrote:
> You don't want to turn `views.py` in to a package. The lengthy view
> file is a side effect of having everything in one django app. What
> you can do is take a look at what exists in the `workshops` app and
> see what makes sense to break out in to different apps.

+1 to this.  And for reusing existing packages where possible
(e.g. #62).  But even if we stay with our home-rolled models and
views, this would be easier to manage if it were diced up into
digestible pieces.

**Comment by pbanaszkiewicz** [comment]
Hey everyone,

@wking:
>> On Sun, Apr 19, 2015 at 02:02:16AM -0700, Piotr Banaszkiewicz wrote:
>> → extra.py
>
>What's this for?  My personal preference would be “have a single
module for each model class named after the model's class name
(e.g. Site in workshops/models/site.py, Airport in
workshops/models/airport.py, …).  But regardless of how you break it
up, I think this is a good idea.

We have a few view that don't belong to "CRUD":

* `instructors` (for finding instructors)
* `search`
* `debrief` (for finding instructors who taught in specific date range)
* `export`

For me, more or less all 4 of these views can land in `extra.py`.

@gvwilson:
> If we don't need to turn things into packages for deployment right now,
> I'd rather push this off until after we get something up and running
that the admins can use.
This issue is just a [reminder](https://github.com/swcarpentry/amy/pull/239#issuecomment-89516864). Not high on TODO list (take a look at open PRs).

@codersquid and @wking:
Yes, the goal I want to achieve is ultimate legibility and manageability ;)

We have about 33 views, out of them about 29 are CRUD views. So a natural step here is to separate view mixins (and view helpers) and split `views.py` logically (based on model their operate on).

We may use "an app per Model" style. Or do you have other ideas?

**Comment by wking** [comment]
On Thu, Apr 23, 2015 at 05:31:47AM -0700, Piotr Banaszkiewicz wrote:
> We have a few view that don't belong to "CRUD":
> 
> * `instructors` (for finding instructors)
> * `search`
> * `debrief` (for finding instructors who taught in specific date range)
> * `export`
> 
> For me, more or less all 4 of these views can land in `extra.py`.

Maybe split those into their own modules?  The problem with ‘extra.py’
and other generically named files is that you have to open them up to
figure out what they're about.  It's better if the filenames are
descriptive enough for you to guess what's inside without looking.

**Comment by pbanaszkiewicz** [comment]
@wking
> Maybe split those into their own modules?  The problem with ‘extra.py’
and other generically named files is that you have to open them up to
figure out what they're about.  It's better if the filenames are
descriptive enough for you to guess what's inside without looking.

You're right && that works for me, too.

**Comment by gvwilson** [comment]
Close? We seem to be managing OK.

**Comment by pbanaszkiewicz** [comment]
We've crossed 2k lines in `views.py`, which is a lot and I would like this file to be split. Except that I can keep track of the views pretty easily thanks to Sublime Text 3 features… Closing for now, anyone feeling bad about current state of `views.py` please reopen.
