### ISSUE TITLE
Generate list of instructors for debriefing sessions

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#254]
We need a view that does what `make instructors-debrief` did in the old admin repo: list all the instructors of workshops that have run in the past three weeks, or are due to run in the coming three weeks.  For bonus marks, allow query parameters on the URL to allow the start/end dates to be specified in absolute terms and/or relative terms (i.e., `?start=2015-02-05&end=2015-07-02` and/or `?past=21&future=21` (in days)).

**Comment by wking** [comment]
On Wed, May 06, 2015 at 11:38:01AM -0700, Greg Wilson wrote:
> We need a view that does what `make instructors-debrief` did in the
> old admin repo: list all the instructors of workshops that have run
> in the past three weeks, or are due to run in the coming three
> weeks.  For bonus marks, allow query parameters on the URL to allow
> the start/end dates to be specified in absolute terms and/or
> relative terms (i.e., `?start=2015-02-05&end=2015-07-02` and/or
> `?past=21&future=21` (in days)).

Don't we have this already?  #213, #216, #239.

**Comment by gvwilson** [comment]
M'gosh, so we do - thanks.
