### ISSUE TITLE
Filter workshops by organizing institution

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#256]
@gperu would like to be able to filter workshops by the organizing institution (i.e., find all those being organized by SSI).

**Comment by r-gaia-cs** [comment]
Can you provide a example of [tags](https://github.com/swcarpentry/amy/blob/master/workshops/models.py#L259) so that I can comment the proposal?

**Comment by gvwilson** [comment]
"Filter by organizer" should allow us to filter by the organization 
identified by the name of the organization identified by 
`workshops_event.organizer_id.`  `tags` for events include SWC, DC, 
WiSE, TTT (for "Train the Trainers") and other flavors of workshops.

**Comment by pbanaszkiewicz** [comment]
This will probably land in v0.4 when we implement DataTables. Postponed then.
