### ISSUE TITLE
Use object IDs for internal links in Amy

### ISSUE THREAD

**Issue by pbanaszkiewicz** [swcarpentry/amy#259]
We can accept slugs and IDs in links, but the former should redirect to the latter with 301/302.

The cases:
* sites (use domains)
* airports (use IATA codes)
* events (use slugs)
* badges (use names)

For more details and discussions, see #258 and #121.

**Comment by gvwilson** [comment]
I strongly prefer semantically meaningful links where possible: arbitrary numeric IDs (like 259) should only be used as a last resort, particularly when something meaningful (like fix-slugs) is available.  I therefore strongly prefer that we keep using slug-based URLs wherever possible, and only use URLs based on numeric IDs as a last resort, when meaningful URLs aren't available.

**Comment by wking** [comment]
On Thu, May 07, 2015 at 03:15:06AM -0700, Greg Wilson wrote:
> I strongly prefer semantically meaningful links where possible:
> arbitrary numeric IDs (like 259) should only be used as a last
> resort, particularly when something meaningful (like fix-slugs) is
> available.

But our slugs are mutable, not fixed.  I think it's better to use an
immutable identifier where possible, with redirects and similar
handling to allow folks to use the less-reliable slugs where they
prefer slugs.  I don't understand why the URLs used for internal
linking need to be pretty, but I *do* think we want to provide
something robust for folks copy-pasting out of their address bar.

Of course, I've made these arguments before [1,2,…], so I expect this
is just going to come down to the maintainer's personal balance
between stable template-generated URLs and pretty template-generated
URLs ;).  If we do go with the slug-based URLs, I think we should make
it really easy for folks to find the stable, ID-based URLs for
copy/pasting.

[1]: https://github.com/swcarpentry/amy/pull/121#issuecomment-68649840
[2]: https://github.com/swcarpentry/amy/pull/258#issuecomment-99593654

**Comment by gvwilson** [comment]
On 2015-05-07 12:35 PM, W. Trevor King wrote:
> I expect this
> is just going to come down to the maintainer's personal balance
> between stable template-generated URLs and pretty template-generated
> URLs ;).

I expect you're right :-)

> If we do go with the slug-based URLs, I think we should make
> it really easy for folks to find the stable, ID-based URLs for
> copy/pasting.
+1 to that - what do you recommend?

**Comment by wking** [comment]
On Thu, May 07, 2015 at 09:52:14AM -0700, Greg Wilson wrote:
> 2015-05-07 12:35 PM, W. Trevor King:
> > If we do go with the slug-based URLs, I think we should make
> > it really easy for folks to find the stable, ID-based URLs for
> > copy/pasting.
>
> +1 to that - what do you recommend?

I recommend putting the stable, ID-based URL in the browser's address
bar ;).  I'm just saying that if the slug-based internal URL approach
wins out, someone will have to find another place to put the stable,
ID-based URL.

**Comment by pbanaszkiewicz** [comment]
We stick to using human-readable identifiers for now.
