### ISSUE TITLE
What should we use for fee payment status when no fee is owed?

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#262]
We need to be consistent in how we represent workshops that don't have an admin fee, and how we distinguish them from workshops whose admin fee status we don't yet know.What we *want* is a single field that can be NULL (we don't know the status), False (no fee owed), $0 (we know that no fee is owed), or >$0 (the amount owed).  The two fields in `event` are `admin_fee` (currency) and `fee_paid` (boolean, possibly null).

**Comment by wking** [comment]
On Thu, May 07, 2015 at 07:29:42AM -0700, Greg Wilson wrote:
> False (no fee owed), $0 (we know that no fee is owed), or >$0 (the
> amount owed).

That sounds like “we're adjusting admin_fee to be the outstanding
balance for this event”, which I'm still against [1].  Are my earlier
reasons unclear?  How much accounting is amy supposed to handle?

[1]: https://github.com/swcarpentry/amy/pull/253#discussion_r29797954

**Comment by gvwilson** [comment]
admin_fee is supposed to always be the total amount that was agreed - 
we're not going to adjust in real time, and we're certainly not going to 
try to use this as an invoicing system.  But we do need to distinguish 
these cases reliably so that we know who to talk to about what:

* don't know status
* know status - fee is zero
* know status - there is/was a fee, but it hasn't been paid yet
* know status - there is/was a fee, and it *has* been paid

**Comment by wking** [comment]
On Thu, May 07, 2015 at 09:43:49AM -0700, Greg Wilson wrote:
> * don't know status

admin_fee is NULL.  fee_paid is irrelevant.  I'd probably set it
false, but you could use NULL or true if you like.  I don't think this
really matters.

> * know status - fee is zero

admin_fee is 0.  fee_paid is still irrelevant.

> * know status - there is/was a fee, but it hasn't been paid yet

admin_fee is > 0.  fee_paid is false.

> * know status - there is/was a fee, and it *has* been paid

admin_fee is > 0.  fee_paid is true.

That's how the currently proposed [1]:

  self.filter(admin_fee__gt=0).exclude(fee_paid=True)

finds unpaid fees anyway.

[1]: https://github.com/swcarpentry/amy/pull/253/files#diff-3b0217a13be276910bf6a8f396309d2dR234

**Comment by gvwilson** [comment]
OK, where/how can we implement checks to make sure that these 
constraints are always obeyed?  And is there an easy way in Django to 
combine two values into a single displayed field?  I think non-technical 
users will find it easier to work with one widget (since fee is 
conceptually one thing) than keeping two widgets in sync.

**Comment by wking** [comment]
On Thu, May 07, 2015 at 09:55:10AM -0700, Greg Wilson wrote:
> OK, where/how can we implement checks to make sure that these
> constraints are always obeyed?  And is there an easy way in Django
> to combine two values into a single displayed field?  I think
> non-technical users will find it easier to work with one widget
> (since fee is conceptually one thing) than keeping two widgets in
> sync.

What we're charging and whether you've paid seem like two conceptual
things to me.  Maybe just some JavaScript to hide the fee_paid field
if admin_fee is 0?

**Comment by pbanaszkiewicz** [comment]
What about something like this:

![screenshot from 2015-05-08 14 31 00](https://cloud.githubusercontent.com/assets/72821/7536285/e31601f4-f58e-11e4-8d31-c53c05f39590.png)

**Comment by wking** [comment]
On Fri, May 08, 2015 at 05:31:32AM -0700, Piotr Banaszkiewicz wrote:
> https://cloud.githubusercontent.com/assets/72821/7536285/e31601f4-f58e-11e4-8d31-c53c05f39590.png

Looks good to me.  Not sure how easy it will be to wire up on the
Django side, but since it's your proposal I expect your comfortable
figuring that out ;).

**Comment by pbanaszkiewicz** [comment]
It's really easy in pure HTML, but yeah - not sure how to do this in Django (yet). Btw, as soon as one highlights the text input on the right ("Value in USD"), the corresponding radio box selects - no JavaScript required.

If you know a better description than "Other" (maybe "Value"?), let me know.

**Comment by wking** [comment]
On Fri, May 08, 2015 at 10:42:13AM -0700, Piotr Banaszkiewicz wrote:
> If you know a better description than "Other" (maybe "Value"?), let me know.

I like “Value” more than “Other”.  I'm split between “Value” and “Yes”…

**Comment by pbanaszkiewicz** [comment]
As @wking predicted, I have some troubles implementing this in Django.

Let's postpone it to v0.4.

**Comment by gvwilson** [comment]
Now that we've renamed the field to indicate that it's "have we invoiced", I think we can close this.

**Comment by pbanaszkiewicz** [comment]
Okay, good for me, because I had hard time making [this](https://github.com/swcarpentry/amy/issues/262#issuecomment-100218268) widget in Django…
