### ISSUE TITLE
Add debriefing session as a event

### ISSUE THREAD

**Issue by r-gaia-cs** [swcarpentry/amy#263]
I want to add debriefing sessions as a event so that I can

- assign a time and date for the debriefing session
- assign workshops to a debriefing session (e.g. `2015-05-04-lbl` should attended debriefing session on `2015-05-12`)
- check instructors that attended the debriefing session (e.g. `Dani Ushizima` attendend debriefing session on `2015-05-12` for `2015-05-04-lbl`)

**Comment by gvwilson** [comment]
I'd rather *not* add debriefing sessions as events until we're sure 
we're actually going to record the information.  I therefore propose 
that we create a new task type (instructor, workshop, debriefed), and 
see if we enter those - if we actually do, then we can come back and 
make this more complicated.

**Comment by pbanaszkiewicz** [comment]
What would 'workshop' task be for?

**Comment by r-gaia-cs** [comment]
> I'd rather *not* add debriefing sessions as events until we're sure 
> we're actually going to record the information.  I therefore propose 
> that we create a new task type (instructor, workshop, debriefed), and 
> see if we enter those - if we actually do, then we can come back and 
> make this more complicated.

OK.

**Comment by pbanaszkiewicz** [comment]
@gvwilson I think you actually meant a new "Role". I added one in production, you can start adding people with role "debriefed" to the events.

**Comment by gvwilson** [comment]
right - thanks.

**Comment by pbanaszkiewicz** [comment]
Is that sufficient to close this issue?

**Comment by pbanaszkiewicz** [comment]
Is the proposed solution working or do we need something else?

**Comment by gvwilson** [comment]
I'm -1 on on having debriefing sessions as "events" - we're not teaching 
people at them, and honestly, the people we collect attendance figures 
for aren't going to care about them.

**Comment by pbanaszkiewicz** [comment]
No no, I meant "debriefed" role — is it working good for marking people who took part in debriefing sessions?

**Comment by gvwilson** [comment]
I haven't been using it yet - @r-gaia-cs, have you?

**Comment by r-gaia-cs** [comment]
> I meant "debriefed" role — is it working good for marking people who took part in debriefing sessions

I used it this week, adding this role for people that attend last debriefing session. I think that we can close this issue.

**Comment by pbanaszkiewicz** [comment]
We'll revisit if you decide that the role-based solution doesn't work.
