### ISSUE TITLE
Improve debriefing session interface

### ISSUE THREAD

**Issue by r-gaia-cs** [swcarpentry/amy#264]
Can we have the query using "date of the debriefing session" and "backward time frame"? Will be good to say: "debriefing session on `2015-05-12` for workshops in the last `2` weeks".

**Comment by gvwilson** [comment]
I believe you can enter any start/end date you want for the debriefing 
range, no?

**Comment by r-gaia-cs** [comment]
> I believe you can enter any start/end date you want for the debriefing 
> range, no?

Yes. I want to avoid calculate the dates but OK if I need to.

**Comment by pbanaszkiewicz** [comment]
I just found out that our datepicker widget does not work. It should help you select proper dates, but somehow invocation of that widget got lost. I'll submit a fix soon.

**Comment by pbanaszkiewicz** [comment]
@r-gaia-cs now the datepicker is working. I think it's a decent solution that has both usability (to get last two weeks you'd count rows in the pop-up calendar widget) and flexibility.

Try it out and decide if that's enough or not. Cheers!

**Comment by r-gaia-cs** [comment]
@pbanaszkiewicz Thanks a lot. :sparkles:
