### ISSUE TITLE
Update development-ready database data with production database

### ISSUE THREAD

**Issue by pbanaszkiewicz** [swcarpentry/amy#269]
The anonymizing script (`migrater.py`) @gvwilson wrote is not compatible with our production database. We're at the point when it's easier to gather development data from the Amy production database.

We can either update `migrated.py` or use something like [django-anonymizer](http://pythonhosted.org/django-anonymizer/) to blur our production data.

I'd like for this update to be the last big item on the TODO list for v0.2.

I'm looking for insight on either of two options I mentioned above.

**Comment by wking** [comment]
On Tue, May 12, 2015 at 01:44:52AM -0700, Piotr Banaszkiewicz wrote:
> We can either update `migrated.py` or use something like
> django-anonymizer to blur our production data.

Or we can explicitly code up fixtures for testing (#184).  It looks
like I volunteered to write those fixtures once #134 lands, but that's
still open…

**Comment by pbanaszkiewicz** [comment]
@wking:
> Or we can explicitly code up fixtures for testing (#184).

Yes. I liked the idea of anonymizer (since that's something similar to what Greg wrote), but was a little unsatisfied that we can unintentionally [erase our production database](http://pythonhosted.org/django-anonymizer/commands.html#anonymize-data) when using django-anonymizer.

> It looks like I volunteered to write those fixtures once #134 lands, but that's still open…

Which way do you like more?

**Comment by wking** [comment]
On Tue, May 12, 2015 at 09:10:08AM -0700, Piotr Banaszkiewicz wrote:
> > It looks like I volunteered to write those fixtures once #134
> > lands, but that's still open…
> 
> Which way do you like more?

I'd like having fixtures that were just big enough to support our test
cases.  It looks like I cited #134 from #184 because I didn't feel
like excercising pagination was particulary important.  In that case,
I'm happy to start working on fixture-based tests this weekend or so,
if that sounds good to you.

**Comment by pbanaszkiewicz** [comment]
@wking:
>I'd like having fixtures that were just big enough to support our test
cases.  It looks like I cited #134 from #184 because I didn't feel
like excercising pagination was particulary important.  In that case,
I'm happy to start working on fixture-based tests this weekend or so,
if that sounds good to you.

That actually sounds great!

Having fixtures:
1) would enable us to get rid of `migrater.py` and `db.sql`
2) would make each version release easier to handle (no need to update huge `db.sql`, just fixtures)
3) would be no risk (compared to having django-anonymizer)

I like it a lot. Thanks!

**Comment by gvwilson** [comment]
migrater.py is essentially dead now - we have data in the production 
database that isn't in the old admin repo's database, and we're never 
going to backport, and there's no easy way to merge.  I like being able 
to run tests on real-as-possible data, so I'll explore the django 
anonymizer route tomorrow and Thursday and see how far it will get us.

**Comment by pbanaszkiewicz** [comment]
Solved with #273. I'll do some testing and if everything seems fine I'll release Amy v0.2.
