### ISSUE TITLE
Allow addition of new skills

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#28]
Admins should be able to add a new skill to the set of skills instructors are able to teach.  There should be an easy way for the admin adding the skill to indicate which of the people already in the database are qualified to teach it.

**Comment by gvwilson** [comment]
Note: we need bulk addition from a CSV (can be a command-line tool).

**Comment by pbanaszkiewicz** [comment]
What's the status on this issue? Do we postpone it to v0.4?

**Comment by gvwilson** [comment]
We postponed it, but it should be early in v0.4.
Thanks,
Greg

**Comment by pbanaszkiewicz** [comment]
@gvwilson what's the status on this?

**Comment by gvwilson** [comment]
Let's move this to 0.5, since it ties into getting instructors' responses to the skills form into the database.
