### ISSUE TITLE
Allow admins to Cc: email to Amy site records

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#287]
A lot of information about workshops is locked up in personal or institutional email accounts.  Rather than expecting everyone to copy that over to Amy, we could allow admins to Cc: an address like `msu.edu@amy.software-carpentry.org`, archive the mail in the appropriate folder on the serve, and make those archives visible through Amy.

1.  Why Cc the site rather than the workshop?  (i.e., why `msu.edu@...` rather than `2015-06-01-msu@...`)?  Because we often want to start archiving before the dates and slug have been settled, and we want to be able to find previous conversations easily.

2.  Who can send?  We'd have to implement whitelisting of admins' addresses to avoid accumulating spam.

**Comment by wking** [comment]
On Thu, May 21, 2015 at 04:10:58PM -0700, Greg Wilson wrote:
> msu.edu@amy.software-carpentry.org

Is the idea to use the Mailman API to auto-generate per-site lists and
keep the list-poster config in sync with Amy's admin list?

**Comment by gvwilson** [comment]
This is separate from Mailman integration - I just want to be able to 
add a Cc to messages that are going out to workshop hosts or instructors 
and know that those messages will be visible in an easily-findable place 
within Amy.  Amy's just archiving, not forwarding...

**Comment by wking** [comment]
On Thu, May 21, 2015 at 07:11:56PM -0700, Greg Wilson wrote:
> Amy's just archiving, not forwarding...

I think building an SMTP server into Amy is probably too
feature-creepy ;).  I'd like to have an external SMTP server that's
designed for that purpose and written by someone who understands that
sort of thing, and have our only interaction with it be pushing out
the list of known admins whenever Amy updates a person's admin status
(or adds a new admin).  That could just be “setup a local Postfix
delivering through procmail, and have Amy write the ~/.procmailrc.
But if we are already doing Mailman API manipulation I don't see why
we wouldn't reuse that infrastructure for this task.

**Comment by gvwilson** [comment]
I don't think we need an SMTP server - a cron job that looks at the 
@amy.software-carpentry.org spool dir and copies messages into an 
archive dir every 10 minutes, then adds a DB record with date and 
subject will be enough to start.

**Comment by wking** [comment]
On Fri, May 22, 2015 at 03:44:22AM -0700, Greg Wilson wrote:
> I don't think we need an SMTP server - a cron job that looks at the
> @amy.software-carpentry.org spool dir and copies messages into an
> archive dir every 10 minutes, then adds a DB record with date and
> subject will be enough to start.

And performs the admin-sender filtering while deciding what to copy?
Why not just use Mailman to manage access and serve those archives?

**Comment by gvwilson** [comment]
Because as someone who's juggling 30+ workshops at a time, I'd like to 
have everything in one place.

**Comment by wking** [comment]
On Fri, May 22, 2015 at 10:10:36AM -0700, Greg Wilson wrote:
> Because as someone who's juggling 30+ workshops at a time, I'd like
> to have everything in one place.

Is that “one archive for all the workshop-related mail” or “one
archive for each workshop” or “searchable in Amy (one UI)”?  It seems
like a link from the Amy workshop to the relevant Mailman archive
would give you what you need in all of those cases.  I don't see what
you could do natively in Amy with just subjects and dates that you
can't do in a Mailman archive.

**Comment by gvwilson** [comment]
I can see a list of recent messages on the site's or event's page inside 
Amy, which will immediately tell me if there's been recent traffic.

**Comment by wking** [comment]
On Fri, May 22, 2015 at 10:50:27AM -0700, Greg Wilson wrote:
> I can see a list of recent messages on the site's or event's page
> inside Amy, which will immediately tell me if there's been recent
> traffic.

It seems like Mailman 3 archives to HyperKitty (which is also written
in Django) [1,2,3].  The installation here [4] is using an API
endpoint [5] to get JSON with a list of message-counts per day for
recent days.  Does that sound like it would cover your use-case?

[1]: http://wiki.list.org/HyperKitty
[2]: https://lwn.net/Articles/638090/
[3]: https://lwn.net/Articles/596049/
[4]: https://lists.stg.fedoraproject.org/archives/
[5]: https://lists.stg.fedoraproject.org/archives/list/users@lists.fedoraproject.org/recent-activity

**Comment by gvwilson** [comment]
That could work - nice find.
Thanks,
Greg

**Comment by wking** [comment]
On Fri, May 22, 2015 at 11:19:40AM -0700, Greg Wilson wrote:
> That could work - nice find.

Research is usually cheaper than development ;).
