### ISSUE TITLE
Need a way to delete things

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#289]
We need to be able to delete airports, badges, tasks, etc.

**Comment by pbanaszkiewicz** [comment]
Would that be actual deletion or just "mark as deleted" (similarly to events, tasks)?

**Comment by gvwilson** [comment]
In this case, I'm happy with pure deletion - the cost of lost data is pretty small.  But we should start logging changes to the DB in a recovery file somewhere.

**Comment by pbanaszkiewicz** [comment]
Closed via #357.
