### ISSUE TITLE
Remove duplicate and redundant forms

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#291]
These are essentially duplicates, and can be folded together:

* workshops/templates/workshops/airport_form.html
* workshops/templates/workshops/event_create_form.html
* workshops/templates/workshops/person_form.html
* workshops/templates/workshops/site_form.html
* workshops/templates/workshops/task_form.html

This is no longer needed at all:
* workshops/templates/workshops/cohort_form.html

**Comment by pbanaszkiewicz** [comment]
Closed via #292.
