### ISSUE TITLE
Notes about people and events should be broken into dated sections

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#299]
Each addition to the `notes` field of a `Site` or `Event` should automatically be timestamped, so that we can know when notes like "Waiting to hear about invoice" were written.  Don't know what this should mean for edits to old notes (maybe the notes field becomes append-only?), but the timestamps should always be visible when the notes are displayed - users shouldn't have to click separately to bring up history.

**Comment by pbanaszkiewicz** [comment]
We could:

1. make a `Note` model with [`GenericForeignKey`](https://docs.djangoproject.com/en/1.8/ref/contrib/contenttypes/#generic-relations). Each note would have timestamp, maybe author, and corresponding GenericFK object (`Award`, `Site` or `Event`), or

2. force a specific markup to be added to the current `notes` fields upon saving (and, as @gvwilson suggested, probably append-only mode).

Not sure if it's possible to timestamp-annotate old notes.

Any thoughts, @gvwilson, @wking?

**Comment by gvwilson** [comment]
This isn't a high priority right now...

**Comment by wking** [comment]
On Sun, May 24, 2015 at 02:50:01PM -0700, Greg Wilson wrote:
> Each addition to the `notes` field of a `Site` or `Event` should
> automatically be timestamped, so that we can know when notes like
> "Waiting to hear about invoice" were written.

The notes functionality sounds like it should get rolled into per-site
mail archives (#287).  Then you get timestamps for free by mailing
comments like this to the per-site list.  Adding a UI to send that
mail from Amy (or embed the HyperKitty poster [1]) would be fine, but
I don't like the idea of splitting notes between a mailing list and a
timestamped notes field.

[1]: https://lwn.net/Articles/596049/
     “Obviously, list subscribers can already reply via their email
     client, but HyperKitty allows them to respond through the web
     interface as well, first authenticating them against the Mailman
     server.”

**Comment by gvwilson** [comment]
Interesting idea...

**Comment by gvwilson** [comment]
Discarding, but see #309.
