### ISSUE TITLE
Deal with breadcrumbs

### ISSUE THREAD

**Issue by pbanaszkiewicz** [swcarpentry/amy#302]
As Greg mentioned in #296, he hadn't liked the way breadcrumbs repeat current page title (or header) in their last element, for example: page "Event 2015-05-25-something" will have breadcrumbs "Amy / All events / Event 2015-05-25-something".

I took a look at other big websites and how they do breadcrumbs and @gvwilson was right. They don't repeat current site at the end of breadcrumbs.

This means we'd only have breadcrumbs at most 3 links long: Amy / All * / * [ / action ], for example:

Was:
* Amy / All events / Event 2015-05-25-something / Edit

Will be:
* Amy / All events / Event 2015-05-25-something

But this does not bug me. In case of `All *` pages, we can just as well drop breadcrumbs (because they'd look like "Amy / ").

So I don't really know what to do:

1. Display breadcrumbs on the same pages as now, but hide the last item.
2. Display breadcrumbs on the pages that would have more than 1 breadcrumbs.
3. Drop breadcrumbs completely.

**Comment by wking** [comment]
On Mon, May 25, 2015 at 01:11:00AM -0700, Piotr Banaszkiewicz wrote:
> 3. Drop breadcrumbs completely.

I'm fine with this.  Between the nav bar and the back button I think
we cover everything we'd use the breadcrumbs for.
