### ISSUE TITLE
Remove ID column from Unpublished workshop list on home page

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#304]
No need any longer to show numeric identifier.

**Comment by pbanaszkiewicz** [comment]
`Event.slug` can be blank and null, which means someone can add an event without a slug by accident.

So: either make slug non-null, non-blank (and perhaps unique), or don't remove ID column from unpublished workshops.

Which do you want, @gvwilson?

**Comment by gvwilson** [comment]
Leave as is.
