### ISSUE TITLE
Remove numeric ID column from all_events display

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#305]
No longer any need to show numeric ID.

**Comment by pbanaszkiewicz** [comment]
Same comment as in #304.

**Comment by pbanaszkiewicz** [comment]
Marked as unresolved?

**Comment by gvwilson** [comment]
Sure.

On 2015-06-12 7:12 AM, Piotr Banaszkiewicz wrote:
>
> Marked as unresolved?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/swcarpentry/amy/issues/305#issuecomment-111455137>.
>

-- 
Dr. Greg Wilson    | gvwilson@software-carpentry.org
Software Carpentry | http://software-carpentry.org
