### ISSUE TITLE
Add 'next' and 'prev' links at the tops of all displays that are paginated

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#308]
We have next/prev at the bottom of paginated displays - should have them at the top too for convenience.

**Comment by pbanaszkiewicz** [comment]
It will work autonomously once we incorporate DataTables (see #129 #293) - I played with them a couple of minutes and I liked them very much. They'd solve some of our issues (like #189, #256).

**Comment by gvwilson** [comment]
Can this be closed now that we've upgraded pagination?

**Comment by pbanaszkiewicz** [comment]
Sure!
