### ISSUE TITLE
Add 'last updated' field to person, site, and event

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#309]
We should keep track of when changes were last made to our key entries (person, site, and event), and display them where appropriate.

**Comment by wking** [comment]
On Wed, May 27, 2015 at 10:44:01AM -0700, Greg Wilson wrote:
> We should keep track of when changes were last made to our key
> entries (person, site, and event), and display them where
> appropriate.

I've inherited a system that does this at $DAYJOB, but it's not very
useful without details about who made the change or what the change
was.  Unless you have a clear idea of how the last-changed date
*would* be useful in isolation, I'd just recommend logging change
information to syslog.

**Comment by gvwilson** [comment]
This is for admins who want to know when something's happened that they 
need to pay attention to - "sort by last modified" will be really 
important as we grow.

On 2015-05-27 1:48 PM, W. Trevor King wrote:
> On Wed, May 27, 2015 at 10:44:01AM -0700, Greg Wilson wrote:
> > We should keep track of when changes were last made to our key
> > entries (person, site, and event), and display them where
> > appropriate.
>
> I've inherited a system that does this at $DAYJOB, but it's not very
> useful without details about who made the change or what the change
> was. Unless you have a clear idea of how the last-changed date
> *would* be useful in isolation, I'd just recommend logging change
> information to syslog.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/swcarpentry/amy/issues/309#issuecomment-106010923>.
>

-- 
Dr. Greg Wilson    | gvwilson@software-carpentry.org
Software Carpentry | http://software-carpentry.org

**Comment by wking** [comment]
On Wed, May 27, 2015 at 11:36:50AM -0700, Greg Wilson wrote:
> This is for admins who want to know when something's happened that
> they need to pay attention to - "sort by last modified" will be
> really important as we grow.

I dunno.  Last-modified site or last-modified instructor sound like
“places/people that are probably no longer interested”.  Especially
with communication getting stored in the external archive (#287), I
think we'd need a different way to flag folks who may be worth a bump.
“Time since the last event” seems useful for both sites and people.  I
can't think of when sorting events by last-modified times would be
useful.

**Comment by pbanaszkiewicz** [comment]
In my opinion something like "last modified" does not clearly mark that something needs attention.

What are potential workflows for this feature, @gvwilson?

Depending on your answer we may need to take a look at something that keeps track of changes made to our models (https://www.djangopackages.com/grids/g/model-audit/).

**Comment by gvwilson** [comment]
If I can sort the displays of sites, events, and persons by most 
recently modified, so that I can see what's changed in the past few 
days, it'll be much easier for me to track what other people are doing.

**Comment by pbanaszkiewicz** [comment]
@gvwilson do you want to know what changes have been made in addition to when they have been made?

**Comment by gvwilson** [comment]
Yes, but I can probably get that by eyeballing - mostly, this is a "what 
do I need to pay attention to?" mechanism.

On 2015-06-12 9:12 AM, Piotr Banaszkiewicz wrote:
>
> @gvwilson <https://github.com/gvwilson> do you want to know what 
> changes have been made in addition to when they have been made?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/swcarpentry/amy/issues/309#issuecomment-111487018>.
>

-- 
Dr. Greg Wilson    | gvwilson@software-carpentry.org
Software Carpentry | http://software-carpentry.org

**Comment by pbanaszkiewicz** [comment]
In that case something like django-reversion is too heavy machinery…

**Comment by gvwilson** [comment]
We definitely need a "last updated" flag for Person records, so that when people fill in the instructor information request form, we can compare the timestamp of their entry with the timestamp on their record in our database to see if we need to import the information or not.

**Comment by wking** [comment]
On Thu, Jun 18, 2015 at 03:41:44AM -0700, Greg Wilson wrote:
> We definitely need a "last updated" flag for Person records, so that
> when people fill in the instructor information request form, we can
> compare the timestamp of their entry with the timestamp on their
> record in our database to see if we need to import the information
> or not.

How would this comparison work?  Is there a queue of received
information request forms that we work through?  Can't we just remove
those from the queue as we process them?  So “you need to import the
information on this form” is just “is the form still in the queue”.

Personally I'm still hoping we can have instructors edit this
information directly in AMY [1].  Then we don't need to waste admin
time copying information from one form to another.

[1]: https://github.com/swcarpentry/amy/issues/70#issuecomment-67493077

**Comment by gvwilson** [comment]
On 2015-06-18 5:18 PM, W. Trevor King wrote:
> On Thu, Jun 18, 2015 at 03:41:44AM -0700, Greg Wilson wrote:
> > We definitely need a "last updated" flag for Person records, so that
> > when people fill in the instructor information request form, we can
> > compare the timestamp of their entry with the timestamp on their
> > record in our database to see if we need to import the information
> > or not.
>
> How would this comparison work? Is there a queue of received
> information request forms that we work through? Can't we just remove
> those from the queue as we process them? So “you need to import the
> information on this form” is just “is the form still in the queue”.
>
My concern is that with multiple admins, information is likely to be 
left in the spreadsheet (rather than being deleted prematurely).  We can 
do this by comparing the spreadsheet information with what's already in 
the database, but I would personally still find it useful and 
interesting to be able to get a list of people whose information has 
changed recently, for the same reason that I'd like to be able to get a 
list of events or sites that have changed recently - if I've been busy 
with other things for a week, I'd like to know what might require attention.

**Comment by wking** [comment]
On Fri, Jun 19, 2015 at 12:12:18PM -0700, Greg Wilson wrote:
> … but I would personally still find it useful and interesting to be
> able to get a list of people whose information has changed recently,
> for the same reason that I'd like to be able to get a list of events
> or sites that have changed recently - if I've been busy with other
> things for a week, I'd like to know what might require attention.

I like that sort of information too, but I'd rather also log
information about what changed [1].  And there are several ways you
could store information like that, including pushing it to an email
archive [2,3] (you don't have to actually mail it to anyone, just put
it in the archive and have JavaScript query the HyperKitty API from an
event/person/… page).

[1]: https://github.com/swcarpentry/amy/issues/309#issuecomment-106010923
[2]: https://github.com/swcarpentry/amy/issues/299#issuecomment-105280089
[3]: https://github.com/swcarpentry/amy/issues/323#issuecomment-106897399

**Comment by gvwilson** [comment]
Having Amy email to a logging account and then using JavaScript query 
the HyperKitty API seems a lot more complicated than adding a 
'last_updated' field of type date to the Person, Event, and Site models...

**Comment by wking** [comment]
On Fri, Jun 19, 2015 at 01:46:13PM -0700, Greg Wilson wrote:
> Having Amy email to a logging account…

It's probably just posting via HyperKitty's email-submission API.

> …and then using JavaScript query the HyperKitty API…

A lot of UI stuff gets simpler if you use JavaScript queries to build
the page dynamically.  We're reasonably serious about going that route
anyway [1].  Offloading the information to HyperKitty means there are
a few more API endpoints that we don't have to implement (because
they're already written in HyperKitty).

> …seems a lot more complicated than adding a 'last_updated' field of
> type date to the Person, Event, and Site models...

It is more complicated, but a date-stamped log of
per-person/event/site changes and other comments is a lot more useful
than a single last_updated timestamp.  When I get a Git repository, I
want the commit logs, not just the date when the last commit was made
;).

[1]: https://github.com/swcarpentry/amy/issues/341#issuecomment-109645713

**Comment by gvwilson** [comment]
See also #392 - @amyrbrown and @gvwilson would both like this.
