### ISSUE TITLE
Default display of 'all airports' should only show airports used in the database

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#317]
If we have 9000+ airports from django-airports, our default displays should show those we know about.  This means a custom control with a toggle switch to turn on/off "all used" or "all in DB".

**Comment by wking** [comment]
On Wed, May 27, 2015 at 07:11:16PM -0700, Greg Wilson wrote:
> If we have 9000+ airports from django-airports, our default displays
> should show those we know about.  This means a custom control with a
> toggle switch to turn on/off "all used" or "all in DB".

Hmm, do we really need an all-airport view?  What's the workflow
around this?  I expect we just need an autocomplete combobox or some
such to pick a person/site's airport, and that should land in #285
(which I need to review again after the reroll).

**Comment by gvwilson** [comment]
I guess it depends how well the auto-complete works - if airport IATA 
codes are displayed first, and we're matching left-to-right and 
character-by-character for auto-complete, it'll be helpful for people 
who know the code, but really annoying for those who don't. (I couldn't 
tell you the codes for most airports in Australia or Europe, for 
example.)  Scrolling through 9000 airports to find Orange County (which 
is filed under "John Wayne") will be annoying...
But I'm probably over-thinking: we can do the simple thing, then see how 
it works, then fix it.

**Comment by pbanaszkiewicz** [comment]
> I guess it depends how well the auto-complete works […]

If you go to the `/workshops/instructors` (Find Instructors), you should be able to check out the autocomplete for airports.

I typed in "jo", and Orange County was third out of 4 entries that matched.

**Comment by amyrbrown** [comment]
I have a question. Are admins supposed to add airports, or are we only supposed to use ones that the app already knows about? 

I tried to use Fort Wayne (FWA) as someone's airport (closest international airport to  Notre Dame) and it wasn't in the list, so I added it with the New Airport button. I guess since the button is there, we're supposed to use it, but does that mean that FWA wasn't in the  django-airports list?

**Comment by pbanaszkiewicz** [comment]
> I have a question. Are admins supposed to add airports, or are we only supposed to use ones that the app already knows about? 

We are not using django-airports because of technical difficulties.

If you find some airports missing, I'd say you're welcome to add new ones to the database.

**Comment by gvwilson** [comment]
+1 - please add airports as needed.  I'm trying to find a decent list of 
airports with lat/long and readable country designations to upload.

**Comment by gvwilson** [comment]
Close as irrelevant now that we're not using django-airports ?
