### ISSUE TITLE
"Find instructors" should lay out skills horizontally, not vertically

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#318]
current layout eats up more real estate than it should.

**Comment by narayanaditya95** [comment]
This seems to be an easy fix. Can I please work on it as a starter?

**Comment by gvwilson** [comment]
Yes please and thank you.

**Comment by pbanaszkiewicz** [comment]
@narayanaditya95 that would be awesome. You can use a separate [form helper](http://django-crispy-forms.readthedocs.org/en/latest/form_helper.html) for [Bootstrap](https://github.com/swcarpentry/amy/blob/master/workshops/forms.py#L22) for that.

**Comment by narayanaditya95** [comment]
@gvwilson @pbanaszkiewicz I think of dividing the existing ```InstructorsForm``` into two and using different form helpers for them. We can then render both forms together on the same page. Is it right to proceed?

**Comment by pbanaszkiewicz** [comment]
@narayanaditya95 you can divide it, however handling two forms in Django is a little bit tricky.

You can also manually "compose" the form using [Layouts](http://django-crispy-forms.readthedocs.org/en/latest/layouts.html), and that's the way I'd try to use first.

**Comment by narayanaditya95** [comment]
@pbanaszkiewicz Sure!

**Comment by gvwilson** [comment]
+1 to using Layouts - better odds of it being responsive to screen size 
changes that way.

**Comment by pbanaszkiewicz** [comment]
Closed via #347.
