### ISSUE TITLE
search fails because we search fields separately

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#319]
A search for 'Greg Wilson' turns up nothing, because 'Greg Wilson' isn't found in forenames, surnames, or site names.  A search for 'Wilson' finds Greg Wilson, plus other Wilsons, because 'Wilson' is found in a surname field.

**Comment by wking** [comment]
On Wed, May 27, 2015 at 07:12:32PM -0700, Greg Wilson wrote:
> A search for 'Greg Wilson' turns up nothing, because 'Greg Wilson'
> isn't found in forenames, surnames, or site names.  A search for
> 'Wilson' finds Greg Wilson, plus other Wilsons, because 'Wilson' is
> found in a surname field.

Another reason for #66 ;).  But baring that, I guess we need a
tokenizer to split search terms (maybe shlex.split? [1]) and then
build a set of or'ed Q objects?  Fun, fun :p.  Alternatively have
separate search widgets for each searchable field, so folks can put
“Wilson” in the surname-search box and “Greg” in the forename search
box.

[1]: https://docs.python.org/3/library/shlex.html#shlex.split

**Comment by gvwilson** [comment]
Yeah, eventually we have to do real search.  For now, understanding that 
it works field by field will let admins do what they need to, and we 
don't have so much data that it's impossible to find things (yet).

**Comment by pbanaszkiewicz** [comment]
I think we could try ouy the [Haystack](http://haystacksearch.org/) + [Whoosh](https://bitbucket.org/mchaput/whoosh/wiki/Home) combo. @wking what do you think about that?

I used H+W for some complex task on a big database once and it was really slow compared to Solr, but for our needs it could work, I think.

**Comment by gvwilson** [comment]
My past experience with Haystack + Whoosh wasn't inspiring - as you 
said, it's slow.  Let's defer this until 0.5 at the earliest.
Thanks,
Greg

On 2015-06-05 12:15 PM, Piotr Banaszkiewicz wrote:
>
> I think we could try ouy the Haystack <http://haystacksearch.org/> + 
> Whoosh <https://bitbucket.org/mchaput/whoosh/wiki/Home> combo. @wking 
> <https://github.com/wking> what do you think about that?
>
> I used H+W for some complex task on a big database once and it was 
> really slow compared to Solr, but for our needs it could work, I think.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/swcarpentry/amy/issues/319#issuecomment-109347852>.
>

-- 
Dr. Greg Wilson    | gvwilson@software-carpentry.org
Software Carpentry | http://software-carpentry.org

**Comment by wking** [comment]
On Fri, Jun 05, 2015 at 09:15:25AM -0700, Piotr Banaszkiewicz wrote:
> I think we could try ouy the Haystack + Whoosh combo. @wking what do
> you think about that?

I haven't used Haystack + Whoosh myself, but for work I'm probably
going to be working on moving out full-text search into our main
PostgreSQL database in the next few weeks [1,2].  I'm not sure which
database we're using in production, or whether we need to keep SQLite
support for local testing (I'm fine just not testing the search
support if we don't have a local PostgreSQL database), but if
PostgreSQL is an option that will be a full-text search approach that
I'll be familiar with soon ;).

[1]: http://blog.lostpropertyhq.com/postgres-full-text-search-is-good-enough/
[2]: http://www.postgresql.org/docs/9.4/static/textsearch.html

**Comment by pbanaszkiewicz** [comment]
@wking:
>  I'm not sure which database we're using in production

We're using SQLite in production (both Small Orange and Rackspace).

> whether we need to keep SQLite support for local testing

For now I'd say yes for SQLite locally. We could maybe use PostgreSQL for development if Vagrant / Docker / Hyper solution would be very easy to set up on devs machines (which consist of MacOS X and Linux as far as I know).

I'll try to not forget about testing haystack + whoosh locally. Maybe they can perform well for our relatively small needs.

**Comment by pbanaszkiewicz** [comment]
Update:

I worked on a auxiliary function that builds a query from tokenized terms:
```python
terms = re.split('\s+', 'piotr banaszkiewicz')
def build_OR_query(model, terms, *fields):
    query = Q()
    for term in terms:
        for field in fields:
            arg = {
                field + '__contains': term
            }
            query |= Q(**arg)
    return model.objects.filter(query)
```

But the results are kind-of disappointing:

1. Searching for 'greg wilson' will yield everyone named Greg or Wilson.
2. We have no result rating (like real full-text search does) so it's hard to pick a result with good value for the user

The bottom line is: with this code searching for "Greg Wilson" it's no different from searching for "Greg" (or "Wilson").

**Comment by gvwilson** [comment]
Bummer :-(
