### ISSUE TITLE
Add a "checkpoint this" button

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#321]
It would be reassuring to have a "make a backup of the database" button that we could press before doing big chunks of work (like uploading attendance figures from multiple workshops).

**Comment by pbanaszkiewicz** [comment]
I'm not sure about this. Wouldn't you rather run manually the backup scipt (#168)?

**Comment by gvwilson** [comment]
Sure, but the admins need to be able to launch it, and they're not going 
to have shell access to the server.  If the 'checkpoint' button just 
kicks off the script, that should be fine (?).

**Comment by wking** [comment]
On Thu, May 28, 2015 at 04:19:26AM -0700, Greg Wilson wrote:
> It would be reassuring to have a "make a backup of the database"
> button that we could press before doing big chunks of work (like
> uploading attendance figures from multiple workshops).

“Every 15 minutes” from #168 seems frequent enough for me, so I'm not
sure we need a way to fire off additional backups manually.

**Comment by gvwilson** [comment]
If it actually is every 15 minutes, yes - is it now?

**Comment by wking** [comment]
On Thu, May 28, 2015 at 12:07:18PM -0700, Greg Wilson wrote:
> If it actually is every 15 minutes, yes - is it now?

In the example @pbanaszkiewicz posted it looks like it's “every day at
midnight” [1].  You can bump that up to “every 15 minutes” with:

  */15 * * * * …

but as I mention in #168, I think it's better to use Btrfs snapshots
or some other de-duping approach at that frequency.  Still, time spent
in that direction seems more useful to me than time spent adding and
using a manual trigger.

[1]: https://github.com/swcarpentry/amy/issues/168#issuecomment-99579041

**Comment by pbanaszkiewicz** [comment]
Greg wants to have 96 backups per day for next 2 weeks.

I proposed this solution:

1. Set up 2 Rackspace VPS (in different locations) to gather backups every 15 minutes (I don't have enough space on my laptop for that)
2. Keep getting full backups every day to my and Greg's computer (assuming he's still running the cronjob for that).

I'm thinking about setting `rsync --backup` for point 1 (faster solution for me than getting to know Btrfs).

**Comment by wking** [comment]
On Mon, Jun 01, 2015 at 03:56:28PM -0700, Piotr Banaszkiewicz wrote:
> 1. Set up 2 Rackspace VPS (in different locations) to gather backups
>    every 15 minutes (I don't have enough space on my laptop for that)
> …
> I'm thinking about setting `rsync --backup` for point 1 (faster
> solution for me than getting to know Btrfs).

The benefit of the COW-snapshot approach is that you don't need the
disk space to store multiple identical snapshots.  Creating btrfs
snapshots is pretty straightforward (e.g. [1,2]), with the only
difficulty being that you can only snapshot subvolumes, not arbitrary
directories.  So setup a subvolume for logging (one with the live
data, and another for the snapshots):

  # btrfs subvolume create ~/src/amy/logs
  Create subvolume '/home/wking/src/amy/logs'
  # btrfs subvolume create ~/src/amy/snapshots
  Create subvolume '/home/wking/src/amy/snapshots'

Then dump your logs into the one subvolume, and snapshot that into the
other:

  # echo 'stuff' >~/src/amy/logs/dump.sql
  # btrfs subvolume snapshot ~/src/amy/logs ~/src/amy/snapshots/$(date '+%Y-%m-%dT%H:%M')

[1]: https://btrfs.wiki.kernel.org/index.php/Getting_started#Basic_Filesystem_Commands
[2]: https://btrfs.wiki.kernel.org/index.php/SysadminGuide#Subvolumes

**Comment by pbanaszkiewicz** [comment]
@wking But I guess I need to repartition my FS to Btrfs first, right? Or is it easy (enough) to create a subvolume on the, for example, ext4fs?

**Comment by pbanaszkiewicz** [comment]
Theoretically I set up `rsync` correctly, need to check in tomorrow if the backups are created or not. There might be an issue with [missing identity](https://github.com/swcarpentry/amy/issues/168#issuecomment-100619464) again.

**Comment by wking** [comment]
On Mon, Jun 01, 2015 at 04:28:37PM -0700, Piotr Banaszkiewicz wrote:
> @wking But I guess I need to repartition my FS to Btrfs first,
> right? Or is it easy (enough) to create a subvolume on the, for
> example, ext4fs?

Yeah, it's probably best to have a disk formatted for Btrfs for the
backups (and I've had everything on Btrfs for years without problems).
You could create a several-gig file on ext4 and format and mount
*that* as Btrfs, but ick ;).  Still, formatting a disk as Btrfs is
quick, and it will save a lot of disk space…

**Comment by pbanaszkiewicz** [comment]
Double backups work. Thanks to rsync awesomeness, not much bandwidth will be used.

@wking I didn't want to reformat VMs' partitions. I will consider Btrfs in future when I switch laptops or something :-) unless it's advised not to use Btrfs on SSD driver…?

**Comment by wking** [comment]
On Tue, Jun 02, 2015 at 12:19:56AM -0700, Piotr Banaszkiewicz wrote:
> I will consider Btrfs in future when I switch laptops or something
> :-) unless it's advised not to use Btrfs on SSD driver…?

It works fine with SSDs [1].

[1]: https://btrfs.wiki.kernel.org/index.php/FAQ#Is_Btrfs_optimized_for_SSD.3F
