### ISSUE TITLE
Check that workshop URL is to repo not to site

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#325]
We should at least warn people when they enter a something.github.io/yyyy-mm-dd-site URL instead of the github.com/something/yyyy-mm-dd-site URL that we want.

**Comment by wking** [comment]
On Sat, May 30, 2015 at 12:22:40PM -0700, Greg Wilson wrote:
> We should at least warn people when they enter a
> something.github.io/yyyy-mm-dd-site URL instead of the
> github.com/something/yyyy-mm-dd-site URL that we want.

Hmm.  Why do we care about this distinction?  For building lists of
workshops, links to the rendered website (something.github.io/…) seem
to make more sense.  Are we cloning or performing other Git-based
activity on the event repositories?  I don't think we are, in which
case I don't mind if the event website is versioned in Mercurial (for
example) or not versioned at all.  If we're relying on the presense of
specific files (e.g. the YAML header of index.html), we should be able
to scrape what we need from the meta tags:

  $ curl http://swcarpentry.github.io/2015-05-30-hastac-swc/ | grep 'meta name'
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="venue" content="HASTAC Conference (Software Carpentry)" />
    <meta name="date" content="May 30-31, 2015" />
    <meta name="startdate" content="2015-05-30" />
    <meta name="enddate" content="2015-05-31" />

**Comment by pbanaszkiewicz** [comment]
Not all headers are returned as `<meta>` tags. I think Greg's right about this one.

**Comment by wking** [comment]
On Fri, Jun 05, 2015 at 09:05:48AM -0700, Piotr Banaszkiewicz wrote:
> Not all headers are returned as `<meta>` tags.

So just add (and document) the ones we need [1]?

Alternatively, we could have folks enter the URL to a YAML file with
the required metadata in the first YAML document, so folks using
workshop-template could point us at their [2], and folks using other
websites (or no website at all) could throw up some YAML and point us
there.

[1]: https://github.com/swcarpentry/workshop-template/blob/6c3511a1638f98ae9d7860cadd0845675665286c/_layouts/workshop.html#L12
[2]: https://github.com/swcarpentry/workshop-template/blob/gh-pages/index.html

**Comment by amyrbrown** [comment]
I would actually far prefer having a link to the website, not the repo. The repo is basically useless to me as an admin, and the website is fantastically useful to confirm dates, location, instructors, registration etc. 

If we don't store the website URL, at least can we generate a link to the website on the "event" display page?

**Comment by pbanaszkiewicz** [comment]
> If we don't store the website URL, at least can we generate a link to the website on the "event" display page?

I'll add it tomorrow.

**Comment by pbanaszkiewicz** [comment]
Ooops, forgot to add this to the #373… I'll create a new PR for this.

**Comment by pbanaszkiewicz** [comment]
@amyrbrown would you rather have that link to the website displayed on All Events page, or on event details page?

Right now I have something like this:
![screenshot from 2015-06-19 14 13 40](https://cloud.githubusercontent.com/assets/72821/8253172/7091fc94-168d-11e5-8806-9a395e096f8c.png)

so you have both links on the event details page.

**Comment by amyrbrown** [comment]
On the Event Details page is fine with me -- I don't use the All Events page much. Thank you!
