### ISSUE TITLE
Change name of app

### ISSUE THREAD

**Issue by amyrbrown** [swcarpentry/amy#328]
Having the same name for a person and the app is confusing, especially since we both work in the same areas. Suggest "amybot" for the app.

**Comment by pbanaszkiewicz** [comment]
There's ["AMY - AdMinister Yourself"](https://github.com/swcarpentry/amy/pull/276#issuecomment-107134760) suggestion, too.

Pros:
* no need to rename repositories
* not much work if we switch (we only need to uppercase all mentions in docs)

Cons:
* I'm not 100% sold on the acronym, maybe someone can figure something better

**Comment by amyrbrown** [comment]
Yeah, all uppercase would be fine, I guess -- at least it would disambiguate in text, if not in speech. (When do we ever speak to each other anyway?!)  We don't have to think of an acronym. :)

**Comment by pbanaszkiewicz** [comment]
@gvwilson it's your call, what do we do? Do we change the name from "Amy" to "AMY" after v0.3 release, ie. for v0.4?

**Comment by gvwilson** [comment]
But I *like* calling it Amy... and the confusion is likely to be 
temporary...
