### ISSUE TITLE
Some workshops at the database are missing the Organizer field

### ISSUE THREAD

**Issue by r-gaia-cs** [swcarpentry/amy#330]

**Comment by gvwilson** [comment]
Yup - in many cases, we don't know who to list, and in others we just 
haven't had time to enter the data.

**Comment by r-gaia-cs** [comment]
I just raise this because it is a required field. @gvwilson you can close this if you want.

**Comment by gvwilson** [comment]
Yeah, 'organizer' should be made optional, not mandatory - in the case 
of self-organized workshops, we can guess that the organizer is the same 
as the host institution, but it isn't always, and it doesn't really 
matter.  I'll PR.
Thanks,
Greg
