### ISSUE TITLE
Autocomplete for instructors not working when using two words

### ISSUE THREAD

**Issue by r-gaia-cs** [swcarpentry/amy#331]

**Comment by pbanaszkiewicz** [comment]
Please provide more specific report. What is not working? Where is it happening? What had you typed?

**Comment by pbanaszkiewicz** [comment]
I'm guessing this on is too duplicate of #319, but I'm not 100% sure because you didn't provide more details.

**Comment by r-gaia-cs** [comment]
Closing as duplicate of #319.
