### ISSUE TITLE
Search by intructor using first and last name return nothing

### ISSUE THREAD

**Issue by r-gaia-cs** [swcarpentry/amy#333]
## Steps To Reproduce

1. Go to http://amy.software-carpentry.org:8080/workshops/
2. Type "Greg Wilson" on the search bar.
3. Press RETURN.

## Actual Results

No item on persons list.

## Expected Results

"Greg Wilson" be listed on persons list.

## Additional Information

The same problem happens when using first and last name of other instructor.

**Comment by pbanaszkiewicz** [comment]
Thanks!

This is duplicate of #319.
