### ISSUE TITLE
Improve debrief query

### ISSUE THREAD

**Issue by r-gaia-cs** [swcarpentry/amy#334]
## Summary

Debrief query return workshops still running during the debrief session.

## Steps To Reproduce

1. Go to http://amy.software-carpentry.org:8080/workshops/debrief
2. Select "2015-06-02" as begin date.
3. Select "2015-06-09" as end date.

## Actual Results

`2015-06-09-nih` is present at the result.

## Expected Results

`2015-06-09-nih` not present at the result since it still running during the debriefing session.

**Comment by r-gaia-cs** [comment]
@mckays630 This was one of the bugs that I mention to you.

**Comment by pbanaszkiewicz** [comment]
Fixed through #364.
