### ISSUE TITLE
Make fields in-place editable

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#341]
We're currently using forms for almost everything, which is very old-fashioned - it would really (really) help if events, sites, persons, etc., could be edited in-place without form submission. This is pretty much at the top of Amy-the-person's wishlist.

**Comment by pbanaszkiewicz** [comment]
This is pretty big. @amyrbrown how would this feature help you with your work?

**Comment by amyrbrown** [comment]
The "notes" field is the one I edit most often -- it would be awesome if I could just click in it and edit it (and only it) instead of clicking the "edit" button, which makes everything editable.

Alternately maybe just a button to edit the notes field alone -- kind of like you can edit the title of a Github issue without editing the whole thing?

(I wouldn't say this is at the top of my list, but it would be really really nice. :) )

**Comment by wking** [comment]
On Fri, Jun 05, 2015 at 09:00:41AM -0700, Piotr Banaszkiewicz wrote:
> This is pretty big.

The little “Django API + Angular frontend” bird is singing in my head
;).

**Comment by pbanaszkiewicz** [comment]
> The "notes" field is the one I edit most often -- it would be awesome if I could just click in it and edit it (and only it) instead of clicking the "edit" button, which makes everything editable and is pretty slow.

If it's the edit OBJECT webpage loading slowly, then we have a solution in v0.3; I don't think it's running on the production yet, though.

> Alternately maybe just a button to edit the notes field alone -- kind of like you can edit the title of a Github issue, or just a comment, without editing the whole thing?

That's definitely an easy way to solve this issue, and I like it.

> The little “Django API + Angular frontend” bird is singing in my head ;).

That's the whole release on its own, and I'd like to not go there if we can :-) but yeah, it may be inevitable at some point. (Not saying it's a bad idea, though! It's just a big thing.)

**Comment by narayanaditya95** [comment]
Can we use a wysiwyg editor on the notes field. [django-wysiwyg](https://github.com/pydanny/django-wysiwyg/) is stated to work with django-crispy-forms. It is worth a try or going the AngularJS way is the better option in the long run.

**Comment by pbanaszkiewicz** [comment]
@narayanaditya95 [annotating with dates](https://github.com/swcarpentry/amy/issues/299) is more important than wysiwyg.

**Comment by gvwilson** [comment]
Helpful, but not essential.
