### ISSUE TITLE
add 'domain' field to Persons

### ISSUE THREAD

**Issue by tracykteal** [swcarpentry/amy#342]
Workshops are often for people in a given domain and it would be nice to match instructors to that domain. Could we add a 'domain' field to Persons? People would likely have more than one domain though, i.e. genomics and ecology  

So, people should be able to select multiple domains, but we should also have them be drop down menu choices, or standard words we put in to make sure there's uniformity for search.

**Comment by gvwilson** [comment]
Easy to add - can you provide a list of domains?

**Comment by wking** [comment]
On Fri, Jun 05, 2015 at 04:43:49PM -0700, Tracy Teal wrote:
> So, people should be able to select multiple domains, but we should
> also have them be drop down menu choices, or standard words we put
> in to make sure there's uniformity for search.

I'd consider using the existing skills/qualifications.  It's not the
same application (they aren't teaching genomics), but it is the same
idea (they understand both Git and genomics).

**Comment by tracykteal** [comment]
I don't see skills/qualifications field either. Can you point me at that, I can see if it fits?

**Comment by gvwilson** [comment]
If you go to "More... Find Instructors" on the menu, there are tick-boxes for the skills we currently have in the database.  We're going to replace all of these with particular lessons (see [this form](https://docs.google.com/forms/d/1NA2z3mXnrz4ZfEV02rk6vwdK4M180_sYpVjUQBt-yMc/viewform) for a list); for domains, we could use the list on the [workshop request form](http://software-carpentry.org/workshops/request.html) as a starting point, but nobody has ever been happy with those categories...

**Comment by pbanaszkiewicz** [comment]
I think with recent email to instructors by Greg, we might have missed the opportunity to ask for domain.

Are these domains sufficient?
```
Life sciences
Earth sciences
Chemistry
Physics
Space sciences
Mathematics
Engineering
Healthcare
Library sciences
Education
Computer Science
```

**Comment by gvwilson** [comment]
The new instructor skills form includes these domains:

* Space sciences
* Planetary sciences (geology, climatology, oceanography, etc.)
* Physics
* Chemistry
* Organismal biology (ecology, botany, zoology, microbiology)
* Genetics, genomics, bioinformatics
* Medicine
* Civil, mechanical, or chemical engineering
* Computer science/electrical engineering
* Economics/business
* Social sciences
* Psychology
* Humanities
* Library and information science

You're right, Education should be in the list as well - I'll add it now.
Cheers,
Greg

**Comment by tracykteal** [comment]
I think the domain question was in the form for email to instructors.

**Comment by pbanaszkiewicz** [comment]
@tracykteal ah yes, you're right.

@gvwilson I copied the list from link from https://github.com/swcarpentry/amy/issues/342#issuecomment-110147164

**Comment by gvwilson** [comment]
This has to be a many-to-many - people can indicate multiple fields.
