### ISSUE TITLE
Badge and declaration of presence in PDF for learners

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/amy#343]
Can Amy generate a badge and a declaration of presence in PDF for learners that attended a workshop? This is something that learners always ask me for because founding agencies in Brazil always request some form of declaration.

**Comment by pbanaszkiewicz** [comment]
Yeah, learners in Poland requested something like this, too, however there was a gotcha: sponsors. We had instructor's funding snacks and their companies' logos should be printed on the certificates of attendance. Currently Amy doesn't store such additional info.

We also don't store site logo (ie. site where workshop was hosted), and this should be on the certificate as well.

@gvwilson, any thoughts?

**Comment by pbanaszkiewicz** [comment]
If we implement this, I'd like to do this with #20 perhaps.

**Comment by gvwilson** [comment]
I'm opposed to issuing certificates purely for attendance - we need some 
sort of summative assessment so that "I did Software Carpentry" actually 
*means* something.  That said, I recognize that people in some 
jurisdictions need something to show funders, and we've done it ad hoc 
in the past.  This is something the Steering Committee should decide...

**Comment by pbanaszkiewicz** [comment]
Ping to @r-gaia-cs: when can Steering Committee discuss this matter?

**Comment by r-gaia-cs** [comment]
> Ping to @r-gaia-cs: when can Steering Committee discuss this matter?

We can discuss this in two weeks.

**Comment by pbanaszkiewicz** [comment]
Thanks! It means it will land no sooner than v0.6.

**Comment by gvwilson** [comment]
It would be useful to integrate certificate generation with AMY, but we should only try implementing this feature if we can find a template-to-PDF (e.g., SVG-to-PDF) solution that's easier to set up and more robust than running Inkscape headless.
