### ISSUE TITLE
Need a way to mark status of people who've been through instructor training

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#346]
In the old database, we could track the status of people who'd been through instructor training as:

*   completed training, still hasn't completed the graduation exercise
*   completed training, we've given up on them ever completing the graduation exercise
*   completed training, completed graduation exercise (needs badge)

There's no easy way to do that in the current system, but we need it: we've got a lot of people who've gone through instructor training recently, and I need to know who to chase up to complete the graduation exercise, and who I've given up on.

**Comment by pbanaszkiewicz** [comment]
Hmmm, maybe a choice field:

```
NULL – not applicable (probably not an instructor)
1 – TODO graduation exercise 
2 – no hope
3 – full instructor
```

This way we could easily migrate all current instructors to choice °3.

**Comment by gvwilson** [comment]
Yeah, but where is this stored?  Is it a field of "person"?  Or hm, 
maybe we could create an award for "did instructor training but doesn't 
look like they're going to finish it".  That way, we could find people I 
need to talk to by looking for anyone who's been through a TTT event but 
doesn't yet have either a real instructor badge or a "not likely to 
complete" badge, without adding any new fields.

**Comment by pbanaszkiewicz** [comment]
> Yeah, but where is this stored? Is it a field of "person"?

Yes.

> Or hm, maybe we could create an award for "did instructor training but doesn't look like they're going to finish it".

Yes, having badges for that is another approach, but I'd call it a little bit less simple. The complicated part here is that we can (by accident) award people, for example, both "Instructor" and "no hope" badges.

So this approach would require us to check for excluding badges in the awarding process.

**Comment by gvwilson** [comment]
On 2015-06-07 10:35 AM, Piotr Banaszkiewicz wrote:
>
>     Yeah, but where is this stored? Is it a field of "person"?
>
> Yes.
>
>     Or hm, maybe we could create an award for "did instructor training
>     but doesn't look like they're going to finish it".
>
> Yes, having badges for that is another approach, but I'd call it a 
> little bit less simple. The complicated part here is that we can (by 
> accident) award people, for example, both "Instructor" and "no hope" 
> badges.
>
> So this approach would require us to check for excluding badges in the 
> awarding process.
>
I think we have the same problem with a per-person boolean or status 
flag: we could set the flag to show "given up" and still give them a 
valid instructor badge.  Maybe the simplest thing is to not worry about 
it, and instead have yet another report that lists everyone who's been 
through an instructor training event, but doesn't yet have a badge, most 
recent at the top - that would serve the same effective purpose for now.

**Comment by wking** [comment]
On Sun, Jun 07, 2015 at 04:53:21AM -0700, Greg Wilson wrote:
> There's no easy way to do that in the current system, but we need
> it: we've got a lot of people who've gone through instructor
> training recently, and I need to know who to chase up to complete
> the graduation exercise, and who I've given up on.

See also the earlier discussion about explicitly recording assignment
information [1].

[1]: https://github.com/swcarpentry/amy/issues/132#issuecomment-69462471

**Comment by gvwilson** [comment]
We now have a report that shows people who've been in training but haven't got a badge, most recent first - that'll do for now.
