### ISSUE TITLE
Eventbrite integration: creating events

### ISSUE THREAD

**Issue by pbanaszkiewicz** [swcarpentry/amy#350]
We want to create Eventbrite [events](http://www.eventbrite.com/developer/v3/formats/event/) from AMY event pages.

There's an [`eventbrite`](https://pypi.python.org/pypi/eventbrite/3.1.0) package by awesome Daniel Roy Greenfeld we can use.

There's event a tutorial for using the package with Flask: http://www.eventbrite.com/developer/v3/reference/webhooks-tutorial-flask/.

Anyway, what we need to do:

1. when admin creates an event, ask whether to create Eventbrite event too
2. there's a handful of event properties that are required: http://www.eventbrite.com/developer/v3/endpoints/events/#ebapi-post-events

**Comment by gvwilson** [comment]
See #19.

**Comment by pbanaszkiewicz** [comment]
Closing for the same reason as #525.
