### ISSUE TITLE
Cannot require country for site

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#353]
The "edit site" interface currently requires a country to be specified for a site, but some sites (AAS, WiSE) don't have countries.

**Comment by wking** [comment]
On Mon, Jun 08, 2015 at 05:40:48PM -0700, Greg Wilson wrote:
> The "edit site" interface currently requires a country to be
> specified for a site, but some sites (AAS, WiSE) don't have
> countries.

Sites should have to have countries.  AAS, WiSE, etc. should be hosts,
which shouldn't need countries.  See #120.

**Comment by gvwilson** [comment]
This comes back to the host org/site of workshop split.  Until that is sorted out, I need to be able to add sites that don't have countries.

**Comment by pbanaszkiewicz** [comment]
If this is important, let's have a quick fix (Site.country nullable, blank), and then leave Host/Site split for v0.5 (I like @wking's idea from https://github.com/swcarpentry/amy/pull/120#issuecomment-111562221) with a decent UI (ie. one that doesn't provide more work for admins).

If this is not that important, then let's only have Host/Site split for v0.5 with a decent UI.

Does this sound good, @gvwilson?

**Comment by gvwilson** [comment]
+1 to quick fix.

**Comment by pbanaszkiewicz** [comment]
I hope this is +1 for better fix for v0.5, too :-)

**Comment by pbanaszkiewicz** [comment]
Closing via #373.
