### ISSUE TITLE
Official move to Rackspace server + autostart service + auto SSL

### ISSUE THREAD

**Issue by pbanaszkiewicz** [swcarpentry/amy#355]
We're encountering some severe server issues with Small Orange hosting, so the decision is to:

1. [x] move to Rackspace officially for the v0.4 release
2. [x] include some scripts that autostart uwsgi in case of server restart
3. [x] configure nginx to redirect to SSL by default

**Comment by pbanaszkiewicz** [comment]
°1 is ready, ie. it only need to get fresh database.

**Comment by pbanaszkiewicz** [comment]
Forgot that for °1 we also need to change `amy.software-carpentry.org` domain to point to Rackspace server (104.130.229.225).

**Comment by pbanaszkiewicz** [comment]
We're using SSL-only, ie. to connect to new AMY we'll always have to use `https://`.

**Comment by pbanaszkiewicz** [comment]
We're autostarting AMY in case of server reboot:

Nginx autostart: `/etc/init.d/nginx`

uwsgi autostart: `/etc/rc.local`

**Comment by gvwilson** [comment]
Please check with @pipitone on this one - we have certificate issues 
that took a few days to resolve.

**Comment by pbanaszkiewicz** [comment]
We're running on Rackspace!
https://amy.software-carpentry.org/workshops/

**Comment by wking** [comment]
On Mon, Jun 15, 2015 at 03:02:10PM -0700, Piotr Banaszkiewicz wrote:
> https://amy.software-carpentry.org/workshops/

Checking just now:

  Powered by Amy version 0.3.0 (56e5829 2015-06-15 dirty) 

We probably shouldn't be running a dirty version in production.  What
uncommitted changes have you made, and how can we avoid making them?

**Comment by pbanaszkiewicz** [comment]
@wking I added the `'*'` to the list of allowed hosts in `settings.py`. I'll use only `'amy.software-carpentry.org'` for it when we deploy next time (should be this week).

**Comment by wking** [comment]
On Tue, Jun 16, 2015 at 09:49:50AM -0700, Piotr Banaszkiewicz wrote:
> @wking I added the `'*'` to the list of allowed hosts in
> `settings.py`. I'll use only `'amy.software-carpentry.org'` for it
> when we deploy next time (should be this week).

I'd recommend reverting to the pre-4e6a1de6a (Previous method was
yielding a 400 in production, 2015-03-06) behavior and setting that up
with a `HOSTNAME` environment variable.  I was never clear on why
David had trouble with that approach [1].

[1]: https://github.com/swcarpentry/amy/pull/217#issuecomment-77609525

**Comment by pbanaszkiewicz** [comment]
@wking thanks for the pointer, I'll do that on the soonest deployment.

**Comment by pbanaszkiewicz** [comment]
Hi @wking,

I forced ALLOWED_HOSTNAME to be only 'amy.software-carpentry.org', no reading from envvar because it did not work for some reason. Probably something was wrong between `uwsgi` and Django, but I don't have time to check today. Cheers
