### ISSUE TITLE
Line wrapping on event notes (and other notes)

### ISSUE THREAD

**Issue by amyrbrown** [swcarpentry/amy#369]
Would be nice to have line wrapping on notes fields so you don't end up with a wide field and horizontal scroll bar, as in https://amy.software-carpentry.org/workshops/event/2015-08-21-northwestern

**Comment by gvwilson** [comment]
Switching to Markdown rendering will solve this (?).

**Comment by pbanaszkiewicz** [comment]
> Switching to Markdown rendering will solve this (?).

Yes, since we'll display in `<div>` rather than `<pre>`.
