### ISSUE TITLE
Allow award of new badges

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#37]
There should be a way to award someone a badge, either through a stand-alone form or by adding a row to the page showing everyone who has that badge.

**Comment by wking** [comment]
On Mon, Dec 29, 2014 at 10:33:11AM -0800, W. Trevor King wrote:
> On Sat, Dec 27, 2014 at 02:39:06PM -0800, Greg Wilson wrote:
> > 1. I think the simplest thing to start with is to show checkboxes
> >    for all as-yet-unawarded badges on the "person details" page,
> >    so that when editing the person, the admin can give that person
> >    badges.
> 
> I'd rather stick with an autogenerated many-to-many UI (which
> django-extra-views gives us)…

This may not be the most stable dependency.  We should wait to see how
the maintainer transition [1] works out before moving forward with it.
I'm still in favor of anything that keeps *us* from re-implementing
this sort of logic locally though.

[1]: https://github.com/AndrewIngram/django-extra-views/issues/96

**Comment by gvwilson** [comment]
Further discussion:

1. The "edit this person" page should allow us to multi-select badges that the person *doesn't* yet have and award them.  The date of the award will be the date that the selection was done.

2. The page displaying badges (http://amy.software-carpentry.org:8080/workshops/badges) should have an "award badge" button that lets me select a person and a badge (via pulldowns).  When submitted, the page displays the newly-awarded badge and offers me the same pair of pulldowns so that I can add another.

**Comment by pbanaszkiewicz** [comment]
Point 2. from the comment above is now resolved via #303.

Point 1. from the comment above will be resolved via #110.

**Comment by r-gaia-cs** [comment]
@pbanaszkiewicz Can we close this? #303 was merge.

**Comment by pbanaszkiewicz** [comment]
@r-gaia-cs we'll close as soon as we implement awarding badges from user edit page. I have something for it, and I'll submit a PR soon.

**Comment by pbanaszkiewicz** [comment]
#345 fulfills all requirements now.
