### ISSUE TITLE
Markdown for Event notes

### ISSUE THREAD

**Issue by amyrbrown** [swcarpentry/amy#370]
It would be lovely to be able to use Markdown for Event notes. (Probably not necessary for other notes?)

**Comment by gvwilson** [comment]
Ditto for Site notes - if we support it in one place, we should be able 
to support it everywhere.

**Comment by pbanaszkiewicz** [comment]
Moving to v0.7 since I don't want to include untested solutions on a deadline day. :-)

**Comment by pbanaszkiewicz** [comment]
Not going to happen.
