### ISSUE TITLE
Events with xx date placeholder are listed out of order

### ISSUE THREAD

**Issue by amyrbrown** [swcarpentry/amy#371]
If I do a search on "northwestern" (for example), the returned list of events is like this:

- 2015-08-21-northwestern
- 2015-04-17-nw
- 2014-10-31-nw
- 2015-xx-xx-northwestern

The workshop with the xx placeholders in the slug is listed at the bottom, instead of somewhere in the 2015's (before? after? I don't think it matters.) Workshops with xx are always listed at the bottom.

**Comment by pbanaszkiewicz** [comment]
So what order do you suggest? Ascending by slug name?

**Comment by amyrbrown** [comment]
Thank you! For this and the other fixes. :)
