### ISSUE TITLE
Need to track Membership status for sites

### ISSUE THREAD

**Issue by amyrbrown** [swcarpentry/amy#375]
We need a way to track [Membership](http://software-carpentry.org/scf/membership.html) status for Sites.

**Comment by pbanaszkiewicz** [comment]
@amyrbrown would you like to track some membership requirements, too?

For example, on a site that's our Partner we could display number of workshops organized within last year. (Not sure if we can affiliate instructors with sites, though.)

**Comment by gvwilson** [comment]
I propose a Member model that has a foreign key to a Site, a start date, 
a duration, an enumeration for kind, a foreign key to Person as 
principal contact, and a Notes field (because all of our partnerships 
and affiliations have special cases right now).

**Comment by pbanaszkiewicz** [comment]
I think we could get Sites split into Hosts/Sites and then have Member 1-to-1 relationship with Host.

**Comment by amyrbrown** [comment]
Could we associate Events with Members, too? So we can see how many Events a Member has run since their start date?

**Comment by pbanaszkiewicz** [comment]
We have event's organizer and event's site.

If Member is linked to the Host [organizer] or Site (if we don't migrate to Host/Site) then we'll easily have the events organized by a Member.

**Comment by gvwilson** [comment]
How much extra effort will it be for admins to keep all of this 
straight?  I already don't like the host-vs-site split: I agree it's a 
better semantic model, but it's also more work to input everything.

**Comment by pbanaszkiewicz** [comment]
How do you input data for events with different site and organizer?

For example, this event: [2014-12-06-wise-krakow](https://amy.software-carpentry.org/workshops/event/2014-12-06-wise-krakow) is almost completely wrong. It was organized by WiSE, but the organizer field is empty. The site actually was [AGH UST](http://www.agh.edu.pl/en), not [Jagiellonian University](http://www.uj.edu.pl/en_GB/). The one person mentioned as organizer was KN and he's affiliated with [Cyfronet](http://www.cyfronet.krakow.pl/), which is affiliated with AGH UST. But there's no AGH UST or Cyfronet in our sites.

10% (44 out of 447) of our workshops is organized by sites with no country (like WiSE, online or SwC).
366 workshops don't have organizer.

If we don't care about the site where event is taking place, maybe we should drop it completely, and have only the "host" (I assume it's the same as "organizer") field? Otherwise I'm not sure what we need site for, especially if we're going to store wrong information in it.

**Comment by wking** [comment]
On Sun, Jun 21, 2015 at 03:29:52AM -0700, Greg Wilson wrote:
> I propose a Member model that has a foreign key to a Site, a start date, 
> a duration, an enumeration for kind, a foreign key to Person as 
> principal contact, and a Notes field (because all of our partnerships 
> and affiliations have special cases right now).

That's basically what Host is, right?  In #120 I even asked about
linking to Person for contact information [1].  I'd suggest just
adding a membership link to the Host model pointing to a Membership
model that enumerates our different association levels (partner,
affiliate, … [2]).  I'm still not clear on why adding host data is a
high bar.  We could even offload it to the organizer themselves and
parse it into Amy when reading the event website's metadata [3].

[1]: https://github.com/swcarpentry/amy/pull/120#issuecomment-68650259
[2]: https://github.com/swcarpentry/board/blob/master/membership.md#membership-categories
[3]: http://lists.software-carpentry.org/pipermail/amy_lists.software-carpentry.org/2015-June/000126.html

**Comment by amyrbrown** [comment]
Okay, I'm lost. @pbanaszkiewicz says:
>For example, this event: 2014-12-06-wise-krakow is almost completely wrong. It was organized by WiSE, but the organizer field is empty. The site actually was AGH UST, not Jagiellonian University. The one person mentioned as organizer was KN and he's affiliated with Cyfronet, which is affiliated with AGH UST. But there's no AGH UST or Cyfronet in our sites.

1. I don't see how "WiSE" can be an organizer. WiSE is a kind of workshop -- it should be listed under tags.
2. `Site` should refer to the location a workshop is being held, either physically or logically (i.e., if it's being presented by Berkeley but is physically located at a nearby restaurant, then logically the `Site` is Berkeley).

> 10% (44 out of 447) of our workshops is organized by sites with no country (like WiSE, online or SwC). 366 workshops don't have organizer.

But `Sites` don't organize --- the `Organizer` organizes (usually us or SSI, and not the person with the "organizer" task --- we used one word for two different things). Sites are where something is held. It doesn't make sense for WiSE to be a Site *or* an Organizer -- again, WiSE should be a tag. If WiSE is listed as a Site, that's bad data. 

"online" can be a `Site`, and SWC can be an `organizer`.

The conflation between Sites as physical locations and Sites as entities which host workshops is addressed in @wking's PR #120 but as an admin I haven't felt a burning need for that functionality yet. If a workshop is hosted by ORGANIZATION A but presented at ORGANIZATION B I'm happy to have it listed with ORGANIZATION A as the `Site` -- the physical location is usually irrelevant (and if it isn't it's likely such a special case (e.g., ORGANIZATION B is doing us a big favour) that it will be addressed in the Notes anyway).

I think `Site` is very important since it's how we keep track of who we have worked with when, and it's how we determine whether a workshop is the second or later in the calendar year (and is therefore eligible for a reduced fee). If some of the data in `Site` is wrong, that's a problem with the data, not the structure of the database.

**Comment by gvwilson** [comment]
I think the simplest notion is to record 'Host' (who's paying the bill) 
and 'Location' (lat/long or address) separately for each event, and not 
try to connect the two beyond that:

1.  We need to know the Host because that's who we invoice/give credit 
to/whatever.
2.  The workshop website records the Location, so we have that 
information (and can use null for telepresence workshops without confusion).

Thoughts?

**Comment by amyrbrown** [comment]
What are we going to do with the "Location" information?

And again, can we not reuse the "Host" terminology? Either rename the Task or rename the other thing. I think renaming the Task makes the most sense, but that might be a discussion for another thread.

**Comment by gvwilson** [comment]
On 2015-06-23 1:26 PM, Amy Brown wrote:
>
> What are we going to do with the "Location" information?
>

If the host organization is something like iPlant (which has several 
physical locations), we probably want to keep track of which of those 
locations the workshop was at.  We also need it to find nearby 
instructors (maybe?).

> And again, can we not reuse the "Host" terminology? Either rename the 
> Task or rename the other thing. I think renaming the Task makes the 
> most sense, but that might be a discussion for another thread.
>
I'm happy with that.

-- 
Dr. Greg Wilson    | gvwilson@software-carpentry.org
Software Carpentry | http://software-carpentry.org

**Comment by wking** [comment]
On Tue, Jun 23, 2015 at 10:19:03AM -0700, Greg Wilson wrote:
> I think the simplest notion is to record 'Host' (who's paying the
> bill) and 'Location' (lat/long or address) separately for each
> event, and not try to connect the two beyond that:

My Site model also includes a name, country, airport, and notes
(#120).  I'm ok dropping airport (we can query nearby airports on the
fly, but that may miss, e.g. intervening impassible geographic
features).  I don't think having a name, country information, or notes
is a large cost ;).

> 2.  The workshop website records the Location, so we have that
> information (and can use null for telepresence workshops without
> confusion).

I'd still pull it into Amy, since you don't want to query workshop
websites for every query like “what previous events have been in
$CITY?”.

I think having accurate site/location information is important.  We're
putting pins for these things on a map, and we don't want to be
sending folks to the wrong place, or searching for instructors in the
wrong town.

I agree that nulling the site (or having a sentinal Site) for online
events makes sense.

**Comment by amyrbrown** [comment]
Okay, I am still slightly suspicious about the utility of the Location (apart from pins in maps [1] and finding instructors[2]) but I agree that having a logical Host and a physical Location for each Event is tidy and sensible. (In terms of terminology, I prefer "Location" to "Site" because Location is more concrete -- Site has figurative/metaphorical associations which I think lead to confusion with "Host".)

I would ask that Location be stored as not just lat/lng but as a named entity (including lat/lng). As an admin, a set of coordinates means nothing and I don't fancy spending a lot of time looking up coordinates on a map and trying to guess which building the event was held in and what that means in terms of our relationships with the denizens of said building. (Sorry, Piotr, that was a very difficult sentence. (And sorry again if that seems patronizing. I try to write plainly but [sometimes I just don't have time](http://quoteinvestigator.com/2012/04/28/shorter-letter/).))

[1] Do we (or do we plan to) generate the map on the website using data from the AMY database? 
[2] I don't typically hunt for instructors automatically, but I suppose that's something that might be semi-automated in the future.

**Comment by wking** [comment]
On Tue, Jun 23, 2015 at 10:51:50AM -0700, Amy Brown wrote:
> In terms of terminology, I prefer "Location" to "Site" because
> Location is more concrete -- Site has figurative/metaphorical
> associations which I think lead to confusion with "Host".

Sounds good to me.

> [1] Do we (or do we plan to) generate the map on the website using
> data from the AMY database?

I don't know if we've reached a consensus on this yet, but my
preferred information flow is [1]:

1. Instructors/organizers pass an event URL to AMY (possibly via AMY
   admins).
2. AMY grabs the event information from that URL (and occasionaly
   polls for updates).
3. Consumers (such as swcarpentry/site) get information about
   published events from AMY.

That centralized the collection of information in AMY, so the
consumers don't have to worry about collecting a URL list, polling for
updates, or parsing the event-website-stored metadata.

> [2] I don't typically hunt for instructors automatically, but I
> suppose that's something that might be semi-automated in the future.

We're tracking a lot of information about instructors (nearest
airport, lessons they feel comfortable teaching, counts of previous
events).  I expected that the goal there was to semi-automate
instructor/event matching, but I guess I haven't seen explicit plans
for that sort of functionality.

[1]: http://lists.software-carpentry.org/pipermail/amy_lists.software-carpentry.org/2015-June/000114.html

**Comment by pbanaszkiewicz** [comment]
Hi everyone,

> [1] Do we (or do we plan to) generate the map on the website using data from the AMY database? 

[We're going to](http://lists.software-carpentry.org/pipermail/amy_lists.software-carpentry.org/2015-June/000114.html), I believe.

> Sorry, Piotr, that was a very difficult sentence.

No, it wasn't. Don't worry, I'll ask if I don't understand something ;)

Okay, I'll let you go on with discussion, but I'm going back to preparing for tomorrow. Cheers!

**Comment by gvwilson** [comment]
bump

**Comment by pbanaszkiewicz** [comment]
I'll start working on this and #546, but without proper feedback from @jduckles, @maneesha and @gvwilson I don't think I'll be able to finish this one in time for v1.2.
