### ISSUE TITLE
Private repo for API and server credentials

### ISSUE THREAD

**Issue by pbanaszkiewicz** [swcarpentry/amy#379]
Hi,

on a call today with @apawlik we decided that we need a private repository with developer or system admin credentials:

* Eventbrite API token (we'll use that for generating registration forms, or for getting attendance info)
* Google API tokens (we'll use that for generating assessment forms for events)
* AMY server passwords (account password, future database password, SECRET_KEY, etc)

All this data is not related to SwC or its users, but rather to developers and sysadmins, so we think it should be stored in GH private repo, because
* admins and devs have accounts here
* it's easy to add someone to / remove someone from the repo access list

@wking, @gvwilson any thoughts? Or any other solutions?

Cheers,
Piotr

**Comment by gvwilson** [comment]
Sure.

**Comment by wking** [comment]
On Sat, Jun 20, 2015 at 04:11:24AM -0700, Piotr Banaszkiewicz wrote:
> on a call today with @apawlik we decided that we need a private
> repository with developer or system admin credentials…

I think it makes a lot of sense to separate the generic application
(currently mostly stuff in workshops) from the
amy.software-carpentry.org deploy (currently mostly stuff in amy/).
One repository (swcarpentry/amy?)  should have the open-source code
that anyone can use to run their own instance, and another repository
(swcarpentry/amy-deploy?) can have the private secrets and other
deploy-specific information needed for the amy.software-carpentry.org
instance.  If we're good about loading this stuff from environment
variables, we can keep the example amy/ site unchanged and just set
HOSTNAME, EVENTBRITE_TOKEN, etc. before launching the generic site.

**Comment by pbanaszkiewicz** [comment]
> If we're good about loading this stuff from environment variables, we can keep the example amy/ site unchanged and just set HOSTNAME, EVENTBRITE_TOKEN, etc. before launching the generic site.

Loading HOSTNAME didn't work for some reason (I didn't investigate, just forced 'amy.software-carpentry.org').
SECRET_KEY, EVENTBRITE_TOKEN are/will be loaded from envvar.

The issue starts with Google API integrations. @apawlik has some tokens that are stored in the text files because of their size (>3kB). I wouldn't put them in the envvar.

The current deployment directory structure allows us to easily add other dependant projects next to AMY within the same logical place for configuration. This may change after I talk to Sheila who once provided us with some deployment configuration.
