### ISSUE TITLE
Warn before deleting awards when deleting event

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#383]
Right now, deleting an event results in all tasks associated with the event being deleted (good), but also deletes all awards associated with the event (very probably bad - someone shouldn't lose their Instructor badge because a training workshop was accidentally deleted).  We should get stronger confirmation, or at the very least warn the deleter about all the awards that are about to go away and/or provide an option to change their Event link.

**Comment by pbanaszkiewicz** [comment]
Our thinking was that an award should be null if the event did not happen. Here are details: https://github.com/swcarpentry/amy/pull/357#issuecomment-111178538

Our options:

1. We have a confirmation dialog we could extend with warning about related awards and tasks being removed: https://github.com/swcarpentry/amy/blob/master/workshops/templates/workshops/event.html#L68

2. We can add a page-in-the-middle that displays the warning in a more verbose way, probably listing soon-to-be-deleted tasks and awards

3. We can add a page that's showed in case the event has related tasks/awards and prevents that event from removal while the tasks/award exist.

4. We can add a page-in-the-middle that allows user to select what should happen with related awards/tasks.

@gvwilson which one do you prefer?

@wking any comments?

**Comment by gvwilson** [comment]
Nullifying the award is better than deleting it.

**Comment by wking** [comment]
On Sun, Jun 21, 2015 at 05:44:00AM -0700, Greg Wilson wrote:
> Right now, deleting an event results in all tasks associated with
> the event being deleted (good), but also deletes all awards
> associated with the event (very probably bad - someone shouldn't
> lose their Instructor badge because a training workshop was
> accidentally deleted).  We should get stronger confirmation, or at
> the very least warn the deleter about all the awards that are about
> to go away and/or provide an option to change their Event link.

We should just PROTECT Award.event then [1], so the database protects
you from deleting Events with dependent Awards.  No need for lots of
ignorable user-side confirmation levels.

[1]: https://docs.djangoproject.com/en/1.8/ref/models/fields/#django.db.models.PROTECT
