### ISSUE TITLE
Couple filters issues

### ISSUE THREAD

**Issue by pbanaszkiewicz** [swcarpentry/amy#385]
1. The elements shown within select for foreign key (like Event.site or Event.organizer) should be ordered by name, not by database ID

2. ~~Default ordering for All Events page should be "soonest first"~~ One filter applied by default should show only 'upcoming' events, with option to switch to 'past', 'unpublished' or 'no filter' (see comment below: https://github.com/swcarpentry/amy/issues/385#issuecomment-114146212)

3. Add filtering by roles to the All Persons page (requires adding explicit relationship Person↔Role through Task; we can consider adding Person↔Event through Task, too)

**Comment by gvwilson** [comment]
On 2015-06-22 10:15 AM, Piotr Banaszkiewicz wrote:
>
> 1.
>
>     Default ordering for All Events page should be "soonest first"
>

Where are past events shown?  Under all upcoming events?

> 1.
>
>     Add filtering by roles to the All Persons page (requires adding
>     explicit relationship Person↔Role through Task; we can consider
>     adding Person↔Event through Task, too)
>

Do you understand @gperu's use case for this?

**Comment by pbanaszkiewicz** [comment]
> Where are past events shown?  Under all upcoming events?

Good question. In a simplest case we would only use "distance" from the current date and sort by it. This would probably mean upcoming and past events intertwining.

> Do you understand @gperu's use case for this?

I think it's:

> New person comes, and they want to teach at a workshop. So I need to be able to know about their past: if they were helping or teaching, or none.

I think his use case is easily solved by looking at the person details page.

**Comment by gvwilson** [comment]
On 2015-06-22 10:33 AM, Piotr Banaszkiewicz wrote:
>
>     Where are past events shown? Under all upcoming events?
>
> Good question. In a simplest case we would only use "distance" from 
> the current date and sort by it. This would probably mean upcoming and 
> past events intertwining.
>

Strong -1 on that (it would be confusing as hell).  I think "upcoming 
only" as a filter (perhaps on by default?) accomplishes what Giacomo wants.

>     Do you understand @gperu <https://github.com/gperu>'s use case for
>     this?
>
> I think it's:
>
>     New person comes, and they want to teach at a workshop. So I need
>     to be able to know about their past: if they were helping or
>     teaching, or none.
>
> I think his use case is easily solved by looking at the person details 
> page.
>

I agree.

-- 
Dr. Greg Wilson    | gvwilson@software-carpentry.org
Software Carpentry | http://software-carpentry.org

**Comment by pbanaszkiewicz** [comment]
>Strong -1 on that (it would be confusing as hell). I think "upcoming only" as a filter (perhaps on by default?) accomplishes what Giacomo wants.

Okay. Good idea.

**Comment by gvwilson** [comment]
bump

**Comment by pbanaszkiewicz** [comment]
This is marked as 0.7. Do you need it in 0.6?

**Comment by gvwilson** [comment]
Nope, just wondering if we need further discussion.
