### ISSUE TITLE
Add "last modified" timestamp to Person, Event, and Site

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#392]
Just spoke with @amyrbrown - it would be really helpful to add a 'last modified' timestamp field to our three major entities (Person, Event, and Site) so that we can tell:

*   when was this instructor's info last updated?
*   when was information about this event last changed?

etc.

**Comment by wking** [comment]
On Wed, Jun 24, 2015 at 08:47:39AM -0700, Greg Wilson wrote:
> Just spoke with @amyrbrown - it would be really helpful to add a
> 'last modified' timestamp field to our three major entities (Person,
> Event, and Site) so that we can tell:

Duplicate of #309?

**Comment by gvwilson** [comment]
Yup, was looking for that on a slow line but couldn't find it.

Duplicates #309.
