### ISSUE TITLE
Filter for instructors that taught remotely

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/amy#393]
I think that we already have a small number of workshop that at least one instructor taught remotely. Can we have a filter for the instructors that taught remotely?

**Comment by pbanaszkiewicz** [comment]
As far as I remember, we don't mark instructor tasks as remote.

There are two ways to solve this:
1. add role "RemoteInstructor" (we already have "Instructor", "Helper", etc.)
2. add "remote" boolean field to the Task / Role object

**Comment by gvwilson** [comment]
Let's defer this for now.
