### ISSUE TITLE
Only allow end date after start date

### ISSUE THREAD

**Issue by r-gaia-cs** [swcarpentry/amy#397]
I used as input `2015-06-22` as begin date and `2015-07-07` as end date I got `2015-09-01-ttt-online` into the filter. The filters is fine but `2015-09-01-ttt-online` is inconsistent since the end date is before the start date **when it should be after**.

Can we have something to avoid this inconsistency?

**Comment by pbanaszkiewicz** [comment]
This is not an issue with debrief query, it's an issue with `2015-09-01-ttt-online` event. It has end date in the past (2015-04-20), and start date in future (2015-09-01).
