### ISSUE TITLE
Number of learners

### ISSUE THREAD

**Issue by gperu** [swcarpentry/amy#400]
I think we need a place to store the number of participants of a certain event (learners, I mean). This is especially important in cases when we are not given - for privacy reasons - the list of participants.

Of course we can add a note. But if there's a field for this then we can produce reports easily.

**Comment by gvwilson** [comment]
Event has an "Attendance" field that we use to store this - is that what 
you need?

**Comment by gperu** [comment]
Indded! That is what I need :)
