### ISSUE TITLE
Use better icon for "view this"

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#402]
The display of multiple tasks uses "..." for "view this" and a proper pencil icon for "edit this".  We should use an icon for "view this".
![screen shot 2015-07-05 at 3 43 29 pm](https://cloud.githubusercontent.com/assets/911566/8513129/b4ca36a0-232c-11e5-9477-a04da30edf6e.png)

**Comment by pbanaszkiewicz** [comment]
The ellipsis is actually a [glyphicon](http://getbootstrap.com/components/#glyphicons-glyphs) (look for "glyphicon-option-horizontal").

**Comment by gvwilson** [comment]
Right, but it's still not intuitive - isn't there a magnifying glass 
icon or something else that will more clearly say "view"?

**Comment by pbanaszkiewicz** [comment]
There's a magnifying glass (indicates search), similar glass with "+" and "-" sign for zooming in and out.

Can you take a look at "share" and "share-alt" icons?

**Comment by gvwilson** [comment]
How about eye-open ?

On 2015-07-05 4:12 PM, Piotr Banaszkiewicz wrote:
>
> There's a magnifying glass (indicates search), similar glass with "+" 
> and "-" sign for zooming in and out.
>
> Can you take a look at "share" and "share-alt" icons?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/swcarpentry/amy/issues/402#issuecomment-118663183>.
>

-- 
Dr. Greg Wilson    | gvwilson@software-carpentry.org
Software Carpentry | http://software-carpentry.org

**Comment by pbanaszkiewicz** [comment]
eye-open is creepy, what do you think about new-window?

**Comment by gvwilson** [comment]
Nope, that means "new window" to me.  @amyrbrown, what icon should we 
use for "view this thing"?  See 
https://marcoceppi.github.io/bootstrap-glyphicons/ for possibilities.

**Comment by amyrbrown** [comment]
eye-open is fine by me -- I don't mind the creepiness, but actually ... was fine too -- it must be an idiom from some other app I use, because to mean it means "more".

If @gvwilson  insists it be changed and @pbanaszkiewicz  doesn't like the eyeball, how about sunglasses?

**Comment by pbanaszkiewicz** [comment]
You're deciding here, Amy, so we can go with eye-open.

**Comment by gvwilson** [comment]
If Amy's happen with the ellipsis, let's stick with that - this is a 
pretty small thing.
- G

On 2015-07-05 4:48 PM, Piotr Banaszkiewicz wrote:
>
> You're deciding here, Amy, so we can go with eye-open.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/swcarpentry/amy/issues/402#issuecomment-118666850>.
>

-- 
Dr. Greg Wilson    | gvwilson@software-carpentry.org
Software Carpentry | http://software-carpentry.org

**Comment by pbanaszkiewicz** [comment]
Amy's right, "…" (or [hamburger](https://en.wikipedia.org/wiki/Hamburger_button)) means "more" in mobile UI.

Here are our options:

1. Ellipsis (current)
![screenshot from 2015-07-06 08 53 34](https://cloud.githubusercontent.com/assets/72821/8517092/12ab8590-23bd-11e5-92dd-e7a645be185e.png)

2. Sunglasses
![screenshot from 2015-07-06 08 54 12](https://cloud.githubusercontent.com/assets/72821/8517099/1cac7284-23bd-11e5-87d5-c3a9951d520d.png)

3. Eye-open
![screenshot from 2015-07-06 08 59 24](https://cloud.githubusercontent.com/assets/72821/8517119/58116618-23bd-11e5-844b-9676c81b46e7.png)

4. Info sign
![screenshot from 2015-07-06 08 54 46](https://cloud.githubusercontent.com/assets/72821/8517122/600a25b2-23bd-11e5-9fa2-3b4767e10a48.png)

5. Hamburger icon
![screenshot from 2015-07-06 08 58 29](https://cloud.githubusercontent.com/assets/72821/8517125/66a5a0cc-23bd-11e5-9ea3-9b6227fda993.png)

Personally I'd use 1, 4 or 5.

1: we know its function
4: clearly indicates showing information
5: easy to click (big)

What are your opinions, @amyrbrown and @gvwilson?

**Comment by gvwilson** [comment]
Hamburger.

On 2015-07-06 3:03 AM, Piotr Banaszkiewicz wrote:
>
> Amy's right, "…" (or hamburger 
> <https://en.wikipedia.org/wiki/Hamburger_button>) means "more" in 
> mobile UI.
>
> Here are our options:
>
> 1.
>
>     Ellipsis (current)
>     screenshot from 2015-07-06 08 53 34
>     <https://cloud.githubusercontent.com/assets/72821/8517092/12ab8590-23bd-11e5-92dd-e7a645be185e.png>
>
> 2.
>
>     Sunglasses
>     screenshot from 2015-07-06 08 54 12
>     <https://cloud.githubusercontent.com/assets/72821/8517099/1cac7284-23bd-11e5-87d5-c3a9951d520d.png>
>
> 3.
>
>     Eye-open
>     screenshot from 2015-07-06 08 59 24
>     <https://cloud.githubusercontent.com/assets/72821/8517119/58116618-23bd-11e5-844b-9676c81b46e7.png>
>
> 4.
>
>     Info sign
>     screenshot from 2015-07-06 08 54 46
>     <https://cloud.githubusercontent.com/assets/72821/8517122/600a25b2-23bd-11e5-9fa2-3b4767e10a48.png>
>
> 5.
>
>     Hamburger icon
>     screenshot from 2015-07-06 08 58 29
>     <https://cloud.githubusercontent.com/assets/72821/8517125/66a5a0cc-23bd-11e5-9ea3-9b6227fda993.png>
>
> Personally I'd use 1, 4 or 5.
>
> 1: we know its function
> 4: clearly indicates showing information
> 5: easy to click (big)
>
> What are your opinions, @amyrbrown <https://github.com/amyrbrown> and 
> @gvwilson <https://github.com/gvwilson>?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/swcarpentry/amy/issues/402#issuecomment-118747293>.
>

-- 
Dr. Greg Wilson    | gvwilson@software-carpentry.org
Software Carpentry | http://software-carpentry.org

**Comment by amyrbrown** [comment]
I like 4 (information) best. Hamburger suggests menu to me -- in fact I always assumed it was supposed to depict a list of options.

**Comment by gvwilson** [comment]
Option 4 it is.
