### ISSUE TITLE
Link to "New Airport" page from "New Person" page?

### ISSUE THREAD

**Issue by amyrbrown** [swcarpentry/amy#407]
It would be handy to have a link to the "New Airport" page near the Airport field on the New Person page, since you often need to add a new airport once you realize the one you need is not there.

**Comment by pbanaszkiewicz** [comment]
I'll fix it by adding a link under the "+" menu in topbar.

The alternative way is to add an inline form, ie. a new-airport form embedded on the new-person page, but I don't think this is a good idea (depends how often admins have to add a new airport when creating a person).

**Comment by amyrbrown** [comment]
That sounds good. I agree that an inline form wouldn't be a good idea.
