### ISSUE TITLE
Add administrative page

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#41]
The application needs an administrative page so that we can add admin accounts, etc.

**Comment by gvwilson** [comment]
Note that this connects with other authentication issues.

**Comment by pbanaszkiewicz** [comment]
@gvwilson is adding admin accounts from command line enough for v1.0?

**Comment by gvwilson** [comment]
Yes.

**Comment by pbanaszkiewicz** [comment]
Then this is deferred to v1.1 for now.

**Comment by gvwilson** [comment]
Still needed?

**Comment by pbanaszkiewicz** [comment]
We have some admin stuff enabled, but I think we can get rid of it, at least for now. Let me submit a PR.
