### ISSUE TITLE
Import requests for instructor training

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#419]
We get ~10 requests/week for instructor training. They're currently stored in the Google Docs spreadsheet that the Google Form puts them in; we should build something similar to the 'import instructor data' tool to import that data, but then we need to figure out how to store it:

1.  Add a flag to `Person` to indicate that they want instructor training?  (I don't like this.)
2.  Create a dummy `Event` with unspecified dates and location and register wannabe instructors in it?  (I don't much like this either.)
3.  Create a new table that's just a list of people who want instructor training?  (I could live with this.)

We will also then need something to track people who've asked for instructor training and have:

1.  Been in a training event.
2.  Completed training.

Thoughts on UI and implementation?

**Comment by gvwilson** [comment]
This one will become less important once we change the way we do instructor training, so it is no longer essential.

**Comment by gvwilson** [comment]
After some more thought, I think it would be useful to have this.

**Comment by gvwilson** [comment]
Will this one be ready for V1.2?

**Comment by pbanaszkiewicz** [comment]
@gvwilson do you have some idea how you want this implemented?

**Comment by gvwilson** [comment]
It's a lower priority right now - we're not going to take more 
instructor training applications until 2016.

**Comment by gvwilson** [comment]
I'd like to revive this one - a form that people can fill in to request instructor training for themselves or a group would be useful.

**Comment by gvwilson** [comment]
This has become a higher priority...

**Comment by shubhsingh594** [comment]
@gvwilson @pbanaszkiewicz  I would like to work on this one, this is something along the lines of my GSOC proposal, and would only help in the long run.

**Comment by gvwilson** [comment]
We will want something similar to the form used to request a workshop 
[1] that creates an "I would like instructor training" record for an 
individual, and another for requesting training for groups.  Please do 
HTML-only mockups and post for us to review the appearance, and then 
we'll talk workflow.

Thanks!

[1] https://amy.software-carpentry.org/workshops/swc/request/

**Comment by shubhsingh594** [comment]
@gvwilson 
extending from the idea in https://github.com/numfocus/gsoc/issues/99 , would you like to have a form field for username and password , for them to login later.

**Comment by gvwilson** [comment]
Not initially - I can't see them needing to log in until they're accepted.

**Comment by shubhsingh594** [comment]
okay thankyou, will be posting mockups soon :)

**Comment by shubhsingh594** [comment]
![individual1](https://cloud.githubusercontent.com/assets/15982349/13724250/33d70c90-e8a6-11e5-8846-c985df3f8424.png)

when an individual is applying 


![group](https://cloud.githubusercontent.com/assets/15982349/13724340/3fd6dd20-e8a8-11e5-9b4a-d6b6e1d42f89.png)

when applying as a group, dynamic tabs each containing forms to be filled.

we will be using django formset for this, although handling multiple forms on the backend for a group registration could be a little tricky to handle.
@gvwilson

**Comment by gvwilson** [comment]
Groups could be larger than 3 people, so we'll need an "add another 
person" option.  We also need to know where they are, and a bunch of 
other things (why they want to, etc.), but those are all implementation 
details.

Cheers,
Greg

On 2016-03-12 1:01 PM, shubhsingh594 wrote:
>
> individual1 
> <https://cloud.githubusercontent.com/assets/15982349/13724250/33d70c90-e8a6-11e5-8846-c985df3f8424.png>
>
> when an individual is applying
>
> group 
> <https://cloud.githubusercontent.com/assets/15982349/13724340/3fd6dd20-e8a8-11e5-9b4a-d6b6e1d42f89.png>
>
> when applying as a group, dynamic tabs each containing forms to be filled.
>
> we will be using django formset for this, although handling multiple 
> forms on the backend for a group registration could be a little tricky 
> to handle.
> @gvwilson <https://github.com/gvwilson>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/swcarpentry/amy/issues/419#issuecomment-195781588>.
>

-- 
Dr Greg Wilson
Director of Instructor Training
Software Carpentry Foundation

**Comment by shubhsingh594** [comment]
@gvwilson 
yeah it is dynamic, when we click oh the add person button , another tab will open -> person4

like so:

![before](https://cloud.githubusercontent.com/assets/15982349/13728831/eb1ccf12-e94a-11e5-946c-55caa0d1a548.png)

after clicking on the add person button

![after](https://cloud.githubusercontent.com/assets/15982349/13728833/fb34adfc-e94a-11e5-9c24-b4cd9ba7bae7.png)

**Comment by gvwilson** [comment]
We don't need to import old data: we'll ask people to re-apply.
