### ISSUE TITLE
Email list co-management with hosts

### ISSUE THREAD

**Issue by apawlik** [swcarpentry/amy#42]
This is probably not the issue for here but I don't know where to record it so that it doesn't get lost.
As suggested by @gperu (see excerpt from his email below) it would be great if we could allow the hosts to co-manage the mailing lists for the workshops (just like they can have access to their particular registration on Eventbrite). Not sure if cPanel (I think this is what we use?) allows for that, but if it could be sorted somehow, that would make the admin's life easier. The hosts then add helpers or anyone else they need to the mailing list themselves. Right now is the admins that do that.

*Today, when adding a helper to a mailing list (upon request of the host contact) I noted that there is a ‘Delegation’ function (along with ‘Delete’, ‘Change Password’ and ‘Manage’ functions, last cell of each mailing list row). For the first time today I clicked on it and saw who has administrative access to the mailing lists (us) and thought we could give admin access to each host for its relevant list.*

**Comment by brainwane** [comment]
I think this is where I should leave information about a way to integrate with Mailman mailing lists -- once you're using Mailman 3 (which is in beta right now; hoping to release in April 2015).

Mailman 3 exposes a REST API and [mailman.client](https://launchpad.net/mailman.client) (Python) will be the official way to interact with that API. Some docs: http://mailman-cli.readthedocs.org/ You'll be able to use these Python bindings to add or remove list owners or moderators.

**Comment by pbanaszkiewicz** [comment]
Mailman 3 was released (https://mail.python.org/pipermail/mailman-announce/2015-April/000210.html). @gvwilson who's responsible for upgrade?

**Comment by gvwilson** [comment]
I think we have to ask A Small Orange to upgrade Mailman - @pipitone and 
@drio, is that your understanding?

**Comment by drio** [comment]
@gvwilson Yes, it is linked to the cpanel "distribution", I'd advice against upgrading manually.

**Comment by gvwilson** [comment]
@gperu @pbanaszkiewicz @maneesha can this one be closed as stale?

**Comment by pbanaszkiewicz** [comment]
As far as I know, we're still not running Mailman 3 (issues with installation). Closing for now…
