### ISSUE TITLE
Events calendar

### ISSUE THREAD

**Issue by gperu** [swcarpentry/amy#443]
Could we have a calendar automatically updated once we enter the dates of an event?

And can the events on the calendar be filtered too?

**Comment by gvwilson** [comment]
1. Once we are getting information for the main web site from AMY, the 
calendar at http://software-carpentry.org/workshops/index.html will 
automatically update.

2. What would you like the calendar filtered by?

**Comment by gvwilson** [comment]
1. I believe the calendar on the main web site is now updated correctly - @gperu can you please confirm?
2. What kinds of filtering do you want? (I believe we can add labels to iCal events for calendar-level filtering.)

**Comment by gvwilson** [comment]
@gperu can you please confirm that the calendar on http://software-carpentry.org/workshops/ is displaying correctly?
