### ISSUE TITLE
Easier access to "New *"

### ISSUE THREAD

**Issue by amyrbrown** [swcarpentry/amy#444]
I feel like I often go to the "Events" or "Sites" or "Persons" page just to click on the "New $WHATEVER" button. Can we have, perhaps, a "New..." menu with Event, Site, and Person options? Or add "New Event", "New Site" and "New Person" to the More menu?

**Comment by pbanaszkiewicz** [comment]
Hi Amy,

there's a "+" button in top-right corner of AMY, and it covers "New *" for persons, events, airports and sites (I believe).

Is that enough to solve your problem?

Cheers,
Piotr

**Comment by amyrbrown** [comment]
Yes! I didn't know that was there. Awesome, thanks!

**Comment by pbanaszkiewicz** [comment]
Great!
