### ISSUE TITLE
 Find instructors: filter by European Countries

### ISSUE THREAD

**Issue by gperu** [swcarpentry/amy#445]
Is it possible to have the instructors finder search all European Coutries? [Use case: I'm looking for female instructors in Europe - I don't dare asking for a filter by gender also :)]

**Comment by pbanaszkiewicz** [comment]
I think generally we could have a filter for continent and for gender. I'm not sure how easy is the former, but you can expect the latter to be implemented.

**Comment by gvwilson** [comment]
On 2015-07-23 7:43 AM, Piotr Banaszkiewicz wrote:
>
> I think generally we could have a filter for continent and for gender. 
> I'm not sure how easy is the former, but you can expect the latter to 
> be implemented.
>
Filter by country should be straightforward, since we know the countries 
airports are in.

**Comment by pbanaszkiewicz** [comment]
@gvwilson we have 'filter by country', but we need to filter by continent.

**Comment by gperu** [comment]
What about filter by multiple countries, if by continent doesn't work?

**Comment by maneesha** [comment]
Filter by continent may be tricky... In many cases this is a political
division, not just geographic.  Is Russia in Europe or Asia? What about the
Middle East?

**Comment by gperu** [comment]
If the purpose is to select contries where flying is not too expensive, then filtering by country will do.

**Comment by pbanaszkiewicz** [comment]
I think I can get you filtering by multiple countries.

**Comment by gperu** [comment]
Thanks Piotr :)
