### ISSUE TITLE
Set correct administrators for historical events

### ISSUE THREAD

**Issue by pbanaszkiewicz** [swcarpentry/amy#446]
v0.7 will include changes to the internals in the database. `Event.organizer` will become `Event.administrator` and will have specific meaning. From now on, the adminsitrator is the organization responsible for administrative work for that specific event (that would be DataCarpentry for Tracy, Software Carpentry for Amy/Maneesha, Compute Canada for John, SSI for Giacomo, etc.).

If the event is self-organized, the administrator has to be empty.

Many of our events (366 as of today) currently don't have an administrator set. Therefore a change to historical events is required.

**Comment by gvwilson** [comment]
This will have to be done by hand - I'll do it some time in the next few weeks.

**Comment by gvwilson** [comment]
Does this still need to be done?

**Comment by pbanaszkiewicz** [comment]
I don't think we care about these anymore. @maneesha can we close this
issue?

**Comment by maneesha** [comment]
If there is no missing/unknown/null data then I think it is fine to let those go.

If there is any missing data I think it should be assigned to the current admin for that geographic area (even if the workshop predates them, they are the ones building relationships in that geographic area) so they can follow up.

**Comment by pbanaszkiewicz** [comment]
Fixed manually. (Almost got them all: 24 from 360 have no administrator.)
