### ISSUE TITLE
Crash with workshops over time

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/amy#447]
Visit `http://localhost:8000/workshops/reports/workshops_over_time` raise

> TypeError at /workshops/reports/workshops_over_time
>
> unorderable types: NoneType() < datetime.date()

**Comment by pbanaszkiewicz** [comment]
Hi @rgaiacs.

Unfortunately I'm unable to reproduce this and #448. Can you:

1. Check if it still exists with newest `develop` branch?
2. Show me the traceback (on the error's page there's "switch to copy-and-paste view" or something like that).

Thanks,
Piotr

**Comment by rgaiacs** [comment]
Probably I did something wrong when migrated the database. **Not a bug**.
