### ISSUE TITLE
Some page using old layout

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/amy#449]
`http://localhost:8000/workshops/`:

![h](https://cloud.githubusercontent.com/assets/1506457/8850495/e5d65f8a-311e-11e5-9f62-2ed5f0eb15fd.jpg)

Pages with old layout:

- [ ] `http://localhost:8000/workshops/badges`

![Screenshot of badges](https://cloud.githubusercontent.com/assets/1506457/8850627/fad07730-311f-11e5-8b5b-54c259bae29f.jpg)

- [ ] `http://localhost:8000/workshops/persons/bulkadd/`

![Screenshot of bulkadd](https://cloud.githubusercontent.com/assets/1506457/8850523/156700ba-311f-11e5-839a-145f6ac0b1b2.jpg)

- [ ] `http://localhost:8000/workshops/persons/merge/`
- [ ] `http://localhost:8000/workshops/debrief`
- [ ] `http://localhost:8000/workshops/export/badges`
- [ ] `http://localhost:8000/workshops/export/instructors`
- [ ] `http://localhost:8000/workshops/search`
- [ ] `http://localhost:8000/workshops/reports/problems`.
- [ ] `http://localhost:8000/workshops/reports/instructors_over_time`

**Comment by pbanaszkiewicz** [comment]
We didn't discuss switching to wide layout, and I don't think it would look okay on empty pages like badges or bulk upload.

**Comment by rgaiacs** [comment]
> We didn't discuss switching to wide layout, and I don't think it would look okay on empty pages like badges or bulk upload.

I don't have a strong position on this. Is just that the change of header position bugs me. =)

**Comment by gvwilson** [comment]
Are we going to fix or close?

**Comment by pbanaszkiewicz** [comment]
Not a bug.
