### ISSUE TITLE
Change "export badges" to deliver a YAML file rather than displaying JSON

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#454]
"Export badges" currently presents an HTML page with the text needed for site's config/badges.yml as JSON.  To get what we actually need, we have to run a command-line 'make badges' to get the YAML.  The web site should generate YAML and return it (for download) to the user.

Alternatively, we can/should make an API call so that when 'site' is rebuilding, it grabs the YAML from AMY, eliminating the need for the manual step.  Or both.  Probably both.  Definitely both.

See also #455.

**Comment by pbanaszkiewicz** [comment]
Solved via #459.
