### ISSUE TITLE
Change "export instructors" to deliver YAML instead of displaying JSON

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#455]
"Export instructors" currently prints information about instructors as JSON text in an HTML page. It should instead return a YAML file that can be downloaded and dropped into site's config/airports.yml.  (We should probably change the name of the menu item as well to reflect what it actually does.)

Alternatively, we can/should make an API call so that when 'site' is rebuilding, it grabs the YAML from AMY, eliminating the need for the manual step.  Or both.  Probably both.  Definitely both.

See also #454.

**Comment by pbanaszkiewicz** [comment]
Solved via #459.
