### ISSUE TITLE
integrate workshop requests in to Amy

### ISSUE THREAD

**Issue by tracykteal** [swcarpentry/amy#457]
I was just talking to Giacomo and sharing our workshop request form with him, and an idea came up. This might be beyond the scope of Amy, but I wonder if we can integrate workshop requests in to Amy. 

The idea would be that there would be a front facing form for a workshop request, then instead of the information going in to another database or Google doc, that info would go in to Amy. That would let us better consolidate workshop coordination, and get workshops in to the system right at the start. Then we could just add the instructors and URLs as we went along.

**Comment by rgaiacs** [comment]
@tracykteal Thanks to bring this up.

I, @pbanaszkiewicz and @gvwilson had discussed that (probably in private, sorry for that). @gvwilson's biggest concern was with spam.

**Comment by pbanaszkiewicz** [comment]
@rgaiacs I addressed similar security concerns in #456.

I like the idea proposed by @tracykteal. I think Greg won't mind this feature, because he proposed #456.

**Comment by gvwilson** [comment]
+1 (at least)

**Comment by tracykteal** [comment]
I see this is listed as a milestone, so great to see that it will be implemented. Let us know if there's anything we can do to help.

**Comment by maneesha** [comment]
+1 a million times.  
A couple of workshops slipped through the cracks as things transitioned to me & this would be a big step towards preventing this.

**Comment by maneesha** [comment]
One other thing - for the email notifications this sends to admin@software-carpentry.org, can the subject line be customized - perhaps with the institution name?  Right now I have dozens of emails all with the subject line "Bootcamp Request"  making them hard to quickly scan.

It would be easier if each subject line was  "Bootcamp Request - University Name"

**Comment by pbanaszkiewicz** [comment]
I didn't think about notifications in this way, but this is a good idea. We have a pending email account for AMY so that it can send notification emails from something like "amy-noreply@software-carpentry.org".
When we get the account, having nice notification title will be a piece of cake.

**Comment by gvwilson** [comment]
+1 - please keep the suggestions coming.
