### ISSUE TITLE
Add info about workshop assessment forms

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#460]
Can we have an option (yes/no/unknown) for whether pre- and post- workshop assessment forms have been sent out?  (similar to the one for the invoice)

It would be great to have this along with a text box for the link to the google drive location of the assessment forms.

**Comment by pbanaszkiewicz** [comment]
The assessment forms integration is put on hold temporarily because of:
* me being busy with other matters
* Aleksandra being on vacation

That said, I am not against such options, but the actual implementation may depend on the "Share" feature (do we have access to the list of shared-with?). I need to talk to Aleksandra about that, though…

**Comment by gvwilson** [comment]
See #20.

**Comment by tracykteal** [comment]
We're going to be using SurveyMonkey for the assessment software, so maybe there's a way to integrate  this.

**Comment by pbanaszkiewicz** [comment]
Hi @tracykteal,

is this specific to DC or are both SWC and DC switching to Survey Monkey?

Thanks,
Piotr

**Comment by gvwilson** [comment]
We're both switching - integration would be great.

**Comment by pbanaszkiewicz** [comment]
Any ETA on the Survey Monkey forms?

**Comment by gvwilson** [comment]
@JasonJWilliamsNY ?

**Comment by pbanaszkiewicz** [comment]
@maneesha @JasonJWilliamsNY please confirm that this issue becomes obsolete.

**Comment by pbanaszkiewicz** [comment]
@maneesha any way I can help with workshop assessment forms now that we use Survey Monkey?

I can for example generate a link to pre/post assessment forms for you.

**Comment by pbanaszkiewicz** [comment]
Postponing to v1.3 since nobody can say what AMY is required to do in terms of SurveyMonkey integration…

**Comment by maneesha** [comment]
Sorry, the past couple of days have been holidays in the US so I've been travelling.
I do have some ideas that I need to look into more. I will follow up in the next few days.

**Comment by pbanaszkiewicz** [comment]
> Sorry, the past couple of days have been holidays in the US so I've been travelling.

Sure.

>  I do have some ideas that I need to look into more. I will follow up in the next few days.

Great, thanks. :)

**Comment by pbanaszkiewicz** [comment]
@maneesha I'm closing this one, please do the follow up in the thread #578.
