### ISSUE TITLE
Allow "N/A" & other options for "Invoiced"

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#469]
Looking at amy/workshops/models.py it looks like this defined as bool.
However, there are cases when the actual use case is not bool.  Invoiced = No/False may be the case because we need to invoice but we haven't yet, but it may also be the case because they don't need to be invoiced because they are self-organized or other arrangements were made.  We need to differentiate among  these situations.

**Comment by pbanaszkiewicz** [comment]
We may switch to text-based choice field. But I need to know what possible situations there are?

* Invoiced
* Not invoiced
* Not applicable because self-organized
* Unknown

Anything else?

**Comment by maneesha** [comment]
In my few weeks here this is what I've seen:

Not applicable because self-organized
Not applicable because partner organization
Not applicable because developing country
Not applicable because other arrangements made 

Perhaps people who have been here longer than me can comment.

**Comment by gvwilson** [comment]
I propose using "because waiver granted" rather than "because developing 
country" since we waive fees for several reasons. Otherwise, looks good 
to me.

**Comment by maneesha** [comment]
looks good
