### ISSUE TITLE
Bool field for events=closed

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#471]
Can we have a T/F field so that we can mark events as "closed" -- meaning that there's no more work to be done with them... surveys done, invoicing done, etc.

**Comment by gperu** [comment]
I agree. And also a way of excluding the closed events from one's default view (mine being: UK events administered by software.ac.uk).

**Comment by pbanaszkiewicz** [comment]
Adding this switch is not hard, but reworking our other mechanics to use it isn't as trivial as it seems. I'm moving this to v1.1

**Comment by pbanaszkiewicz** [comment]
Greg says: "completed", not "closed".
