### ISSUE TITLE
Links to open in new tab

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#473]
Links for github page, eventbrite, and others (like pre/post surveys if they get added in) should open in new tab so I can keep working on that record in AMY.

**Comment by pbanaszkiewicz** [comment]
I don't think we should implement this. If you need to open a link in new tab, just use CTRL+click or middle mouse button or similar shortcut in Mac.

**Comment by gvwilson** [comment]
Any downside to implementing it?  "User wants, user gets..."

**Comment by pbanaszkiewicz** [comment]
The downside is: "I wanted it to open in the same tab, but it didn't". The rare (or possible to fix) downside may be: "That other link opened in the same new tab" (I'd need to check if this still happens).

**Comment by maneesha** [comment]
Open in new tabs would be my preference for any *external* links -- internal links should open in same tab. Maybe we can poll the most frequent AMY users to decide?

**Comment by pbanaszkiewicz** [comment]
@maneesha it's a good idea to ask everyone for their preference. I'll do that.

**Comment by pbanaszkiewicz** [comment]
The smart poll decided to use `target="_blank"` for external URLs. Will do this for v1.0.
