### ISSUE TITLE
Event: TODO item, TODO due date

### ISSUE THREAD

**Issue by pbanaszkiewicz** [swcarpentry/amy#483]
@gperu requested a "TODO next", "TODO due date" fields for an event.

They would indicate what's next to do for that event ("contact organizer", "send pre assessment forms", etc.), so that admins don't have hard time remembering what they needed to do.

**Comment by gvwilson** [comment]
Would a checklist per event serve the same purpose?  Maneesha suggested 
that a while back...

**Comment by pbanaszkiewicz** [comment]
Checklist is not flexible enough (and both Giacomo and Maneesha voted for a flexible solution). This solution can be like a drop-down with option to type in own TODO text.

When admin needs some standard TODO item, they just select it. When they need something extraordinary, they just type it in. Like a combo-box widget.

**Comment by maneesha** [comment]
Following up on our meeting earlier today, just to be clear... the tasks
involved in workshop organization are not always ordered, serial tasks but
are often unordered and parallel.  It is never the case where there is one
finite pending task, and then when that's complete the next one will be up,
and so on.  So this will be a one-to-many relation, where we can continue
adding to-do tasks to each event. Correct?

**Comment by pbanaszkiewicz** [comment]
Hello, @maneesha.

I think the original idea was some sort of "soonest TODO item" and "soonest TODO item's due date".

Do you think you'd use the 1-to-many relation for any TODO items?
Ie. @gperu and @maneesha, do you think you would keep more than one TODO item for a workshop?

Cheers,
Piotr

**Comment by maneesha** [comment]
Yes -  I definitely want more than one TODO for any workshop.  Steps
involved in workshop organization are typically unordered (or just roughly
ordered)  and parallel, not ordered and serial, so having just one next
TODO wouldn't make a lot of sense.

**Comment by tracykteal** [comment]
Agree with @maneesha that multiple TODOs are needed. Maybe a checklist that's split up by general time frame? e.g.

Start:
-[ ] Set up workshop website
-[ ] Find instructor 1
-[ ] Find instructor 2
-[ ] Set date with host

Middle:
-[ ] Follow up that instructors have booked travel
-[ ] Set up pre-workshop survey

Just before workshop:
-[ ] Make sure instructors are set with materials

After workshop:
-[ ] Submit invoice
-[ ] Make sure instructors are getting reimbursed

I'm not sure if AMY is the system for this or if it would just be better to use Trello or Insight.ly or another to do system.

**Comment by gperu** [comment]
I'm happy with whatever is decided and I'm sure it'll be good.

From my point of vew, I would have liked to have a simple free text box, to appear in my dashboard, reminding me what I have to do, e.g. tomorrow, for a workshop. Like a post-it. Very easy and flexible.
