### ISSUE TITLE
Ask "what human language do you want?" in workshop request forms

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#490]
Brought here from https://github.com/swcarpentry/site/issues/1048: we should ask what human language the workshop should be run in.

**Comment by pbanaszkiewicz** [comment]
All right, this won't be a drop-down list, but rather a text field. I may leave "English" as default, because most of the workshops are in this language.

@gvwilson any comments?

**Comment by gvwilson** [comment]
@maneesha @gperu your call...

**Comment by pbanaszkiewicz** [comment]
@gvwilson I decided to go my way. The fix to this issue is already in #476, and on the dev server.

**Comment by maneesha** [comment]
I prefer a text field to a drop down field -- what languages to include in
the drop down field is a really politically loaded decision that I don't
want us to make.

**Comment by pbanaszkiewicz** [comment]
Hi Maneesha,

On Thu, Sep 10, 2015 at 1:55 PM, maneesha sane <notifications@github.com>
wrote:

> I prefer a text field to a drop down field -- what languages to include in
> the drop down field is a really politically loaded decision that I don't
> want us to make.
>

Okay. Is prefilling the text field with "English" fine to you or not?


>
> On Thu, Sep 10, 2015 at 6:01 AM, Piotr Banaszkiewicz <

**Comment by gvwilson** [comment]
Maybe we should offer a choice for that:
![english](https://cloud.githubusercontent.com/assets/911566/9788772/dcd8223a-57c3-11e5-8b3c-8af075bbaead.png)

**Comment by maneesha** [comment]
Ouch. :)
