### ISSUE TITLE
Representing online courses

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#492]
1. Create a "country" for the World-Wide Web in AMY.
2. Add a flag (icon to be chosen) to represent that "country" on the main website.
3. Make sure the two agree on the 2-letter ISO code for "online" :-)

**Comment by pbanaszkiewicz** [comment]
1. Done (via 3.)
2. It's hard to do a 16px by 11px flag
3. I went with 'W3'.

**Comment by pbanaszkiewicz** [comment]
2: I decided to use a black-white oblate globe for that.

The PR is coming…

**Comment by gvwilson** [comment]
Is that globe in the 'site' repository?  We'll need it in several sizes 
(img/flags/[16,24,32,48]/w3.png)
Thanks,
Greg

**Comment by pbanaszkiewicz** [comment]
Darn, I just removed all the source images. I'll get other sizes for you. Are these sizes 48x48, 32x32, 24x24 and 16x16?

**Comment by gvwilson** [comment]
Yes please and thank you.

On 2015-09-11 5:08 PM, Piotr Banaszkiewicz wrote:
>
> Darn, I just removed all the source images. I'll get other sizes for 
> you. Are these sizes 48x48, 32x32, 24x24 and 16x16?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/swcarpentry/amy/issues/492#issuecomment-139587137>.
>

-- 
Dr. Greg Wilson    | gvwilson@software-carpentry.org
Software Carpentry | http://software-carpentry.org
