### ISSUE TITLE
Wrong link being sent to main website

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#501]
(Amended) use event.get_website_url to fetch the URL for a workshop when building the main website in order to prevent problems of the kind described below.

----

1. Go to http://software-carpentry.org/workshops/index.html#future
2. Look at the Sept 28-29 workshop at Oxford
3. The link is to the GitHub repository, *not* to the GitHub Pages website.
4. But if you look in AMY at https://amy.software-carpentry.org/workshops/event/2015-09-28-oxford, the website URL and repository URL fields look correct.

Same issue shows up with several other workshops (e.g., Sept 17-18 at Western University Sydney links to the repo, not to the gh-pages site).

**Comment by pbanaszkiewicz** [comment]
@gvwilson 

The event's URL (`Event.url`) is this: "https://github.com/jpallen/2015-09-28-oxford". You can see that when you go to Edit event: https://amy.software-carpentry.org/workshops/event/2015-09-28-oxford/edit

In the event details page we don't display `Event.url` (at least not directly). We display `event.get_repository_url()` and `event.get_website_url()`.

Events are exported with their URL, not the translated version from `get_repository_url` or `get_website_url`.

**Comment by gvwilson** [comment]
So do I fix this by changing this URL (and all others that are 
github.com) to their github.io gh-pages equivalents?

**Comment by pbanaszkiewicz** [comment]
That's one possible fix.

Other is to make `get_repository_url` and `get_website_url` properties and in API return `event.website_url` instead of `event.url`.

**Comment by gvwilson** [comment]
What's simplest and most reliable?

**Comment by pbanaszkiewicz** [comment]
The best for now is to manually change `event.url` to the website URL. The proper solution long-term would be making a property out of `event.get_website_url` and using it in API.
