### ISSUE TITLE
Automatic email reminders about upcoming workshops to admins

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#51]
Software Carpentry staff should be mailed automatically a few days before a workshop (so that they can wish instructors good luck), on the last day (so that they can ask how it went), and a week later (to debrief).

**Comment by pbanaszkiewicz** [comment]
Ref #213

**Comment by tracykteal** [comment]
Generally having the ability to automate emails coming from AMY would be terrific. We could also automate emails to go out to the lead instructor at designated times before a workshop, to remind them of things to do. This has been on the dream wish list for a while.

**Comment by pbanaszkiewicz** [comment]
@tracykteal email reminders are now possible because we hooked AMY up with an email account.

**Comment by gvwilson** [comment]
Possible to do in the next round?

**Comment by pbanaszkiewicz** [comment]
Closing this in favor of #516.
