### ISSUE TITLE
Unable to merge two people

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#519]
1. Go to the production version of AMY.
2. Search for 'duckles': result shows two records for Jonah Duckles.
3. Try to merge the one without an email address (which just shows him being a learner at one workshop where he was actually an instructor) into the main 'duckles.jonah' record that has all his other info.
4. Unable to select 'duckles.jonah.2' as the "from" for merge - since it doesn't have an email address (?).

**Comment by pbanaszkiewicz** [comment]
Oops, I guess we don't have any data to work on now. I tried to reproduce your steps, @gvwilson, but I simply merged both entries…

**Comment by pbanaszkiewicz** [comment]
Closing as outdated.
