### ISSUE TITLE
Forms should also display original data when invalid data entered

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#52]
When invalid data is entered in a form produced by Django, the form is redisplayed with an error message, but the incorrect data is pre-filled in the offending box rather than the original pre-edit value.  (For example, if you try to change the domain name for a site to a domain name that's already in use, the new domain name --- the one already in use --- is displayed instead of the original.)  It would be helpful if the form displayed both what the user typed and the original data somehow.

Low priority.

**Comment by gvwilson** [comment]
I think we can close this one.

**Comment by pbanaszkiewicz** [comment]
Then let's close :-)
