### ISSUE TITLE
Include links to external documents

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#522]
Sometimes we get scanned sign in sheets, other reports that the hosts or instructors put together, etc. about these workshops.  I'd like to start saving them in google drive (unless there's a better place) and link to the file location on the workshop page in AMY.

**Comment by gvwilson** [comment]
What would you think about a private GitHub repo rather than Google Drive?

**Comment by maneesha** [comment]
A private GitHub repo would work too.

**Comment by pbanaszkiewicz** [comment]
@gvwilson @jduckles @maneesha is this issue solved (ie. does the private repo for this kind of data exist)?

**Comment by jduckles** [comment]
I'm happy to create it, @maneesha just give me a name you'd like it to have and I'll make sure all admins can access it.

**Comment by maneesha** [comment]
I think something like "workshop_documents" would be fine.  It should have folders named for each workshop's slugs as necessary.

**Comment by jduckles** [comment]
Done: https://github.com/swcarpentry/workshop_documents
