### ISSUE TITLE
Add "Create EventBrite page" buttom

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/amy#525]
## Summary

Is possible to script the creation of the EventBrite page. \o/

## Motivation

Implement this should be easy (one morning or one afternoon of work) and will save hours from program coordinators and instructors that will have the EventBrite page with one click.

@maneesha Can you comment on this?

## Technical details

We need to use [OAuth2 for authentication](https://www.eventbrite.com/developer/v3/reference/authentication/) and [this call](https://www.eventbrite.com/developer/v3/endpoints/events/#ebapi-post-events).

**Comment by pbanaszkiewicz** [comment]
# Technical details

We have the tokens ready.

# My comment

We didn't previously implement this because Amy reported that she used to copy some existing event rather than create a new one. By creating a new one, she'd have to fill up some fields that weren't able to fill via API call @rgaiacs linked to.

We can try this out this time, maybe it will work out better?

**Comment by maneesha** [comment]
Give me some time to look in to this more.   Eventbrite's interface is really annoying.  You have to go into a few different panels to update everything necessary for a workshop.  And sometimes even though you think you're changing a setting for just one event, the change ends up global.   An automated API call will either make this way easier or be disastrous.

**Comment by pbanaszkiewicz** [comment]
@maneesha with API call we're very limited. Take a look at @rgaiacs's [link](https://www.eventbrite.com/developer/v3/endpoints/events/#ebapi-post-events) - there's a list of what we can set up. I think we could set up tickets for an event, too, in a separate API call, but nothing more.

**Comment by pbanaszkiewicz** [comment]
We're not doing this, at least for now. Let's see what #628 brings.
