### ISSUE TITLE
Some fields shown as "XXX-unset-variable-XXX' when updating instructor record

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#531]
1. Go to the current production instance of AMY.
2. Click on 'Profile update requests'.
3. Select someone.
4. Old airport is shown as 'XXX-unset-variable-XXX' (screenshot).

![screen shot 2015-10-10 at 10 45 57 am](https://cloud.githubusercontent.com/assets/911566/10410528/2ab45c6e-6f3c-11e5-9d3e-d59184de6b3b.png)

**Comment by pbanaszkiewicz** [comment]
This is fixed in #528.

**Comment by pbanaszkiewicz** [comment]
Forgot to mention that this bug doesn't affect anything, it's just a representation glitch - it happens when instructors don't have an airport assigned.
