### ISSUE TITLE
Improve development database (use [auto generated] fixtures of some sort)

### ISSUE THREAD

**Issue by datakid** [swcarpentry/amy#534]
The data that is loaded in the development database is pleasingly non identifying, but tries so hard to not break privacy that it breaks brains. 

I have downloaded and installed the test data as recommended. It's very hard to get an idea of what the software does because the names and emails are so appallingly random. Maybe try [fake factor](https://pypi.python.org/pypi/fake-factor) instead? Also, [a good wordlist can be found here](http://web.archive.org/web/20090918202746/http://tothink.com/mnemonic/wordlist.html) to make random words (like for "slug").

**Comment by pbanaszkiewicz** [comment]
@datakid you're right, and I hope to get rid of the `db.sql` for version v1.1 or v1.2. Let me change this issue so that I don't forget. Thanks for the pointers, too!
