### ISSUE TITLE
Add field "Admin assigned"

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#537]
Add field for "Admin assigned"  (Maneesha, Giacomo, Katarzyna, anyone else).

Add view to filter by Admin assigned (so I only see my workshops).

**Comment by pbanaszkiewicz** [comment]
This was an idea for "Admin organization": @maneesha can sort by "Software Carpentry", Giacomo by SSI, Katarzyna by Cyfronet, etc.

Something not working correctly with this solution?

**Comment by maneesha** [comment]
I meant to say I wanted a  *dashboard* view to only include my workshops.  

Also, administrator = software carpentry  is not quite the same thing as what I'm looking for.  Right now for self-organized workshops, administrator is null (which I also really want changed - see #484) but there's still a lot of work I need to do for those workshops so I still want to see them on my dashboard.

**Comment by pbanaszkiewicz** [comment]
So you propose to change all admins' dashboards, not only yours? I'm fine with that, let me ask other admins if they like this change too.

**Comment by pbanaszkiewicz** [comment]
Assign to in workshop requests too.
