### ISSUE TITLE
Change Instructor profile request display to use 3 columns

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#538]
"Has instructor badge" is getting overwritten from "yes" to "NA"

I haven't accepted any instructor profile updates yet because of this.

**Comment by pbanaszkiewicz** [comment]
@maneesha how do you know it's getting overwritten?

**Comment by maneesha** [comment]
OK... so I guess I made that assumption by looking at the instructor profile update screen, but not actually trying to accept an update.

I was assuming that *every* field in the "old" column was getting overwritten by the corresponding field in the new column.  Now I know this does not apply to instructor badge.  Are there any other fields that don't get overwritten?

**Comment by gvwilson** [comment]
I also found the mixture of blank, -, and N/A confusing.  Maybe a 
three-column display (old, current, what the new will look like)?

**Comment by maneesha** [comment]
+1 @gvwilson

**Comment by maneesha** [comment]
When will this go live?  There are a bunch of profile update requests that I'm reluctant to approve because I'm not confident about which fields get overwritten & which don't.

**Comment by pbanaszkiewicz** [comment]
@maneesha things that must happen:

1. I must submit my work upon new TODO feature (#483)
2. Greg must review my code (for unclosed PRs)
3. I must release v1.1.

I'll do step 1 before weekend ends, but I don't know when does @gvwilson have time to review PRs…

If I was to guess, no later than 2015-11-09 we should have AMY v1.1 deployed, but I really hope for this to happen sooner.
