### ISSUE TITLE
Generate a list of SCF members

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#539]
According to our rules, everyone who has taught at least once in the last two years is a member, as is anyone who has been specifically appointed a member for other services. We need a report page in AMY that generates this list. Any chance of getting it sooner rather than later?

**Comment by maneesha** [comment]
Can we add a "member" field (bool) to the db?
Finding out who's taught at least 1x in the past two years is a simple SQL query & this can automatically be set to True.
We can then also manually check off anyone who's been specially appointed a member.

**Comment by gvwilson** [comment]
I don't think we need a field: we can do the query and merge the result 
with people who have a 'member' badge for special work to regenerate the 
members list on the fly.

**Comment by maneesha** [comment]
Of course... I forgot about the badges.

**Comment by maneesha** [comment]
In that case... we can *view* everyone with a member badge if you go to "Badges" under "More" but we should run an update query on that for everyone who's taught in the past 2 yrs.... right now we only have 29 members.

**Comment by gvwilson** [comment]
Yup, I'm going to construct a page for this - should have it in the next 
release.

**Comment by pbanaszkiewicz** [comment]
@gvwilson @maneesha what's current policy on members? If someone taught 2 years ago, will he be still considered a member in 6 months?

**Comment by gvwilson** [comment]
From http://software-carpentry.org/scf/governance.html :

~~~
2.  The Membership is made up of:

     a.  Every qualified instructor who has taught at least twice in the
         past two calendar years.

     b.  Anyone who has done 30 days or more work for the SCF in the past
         calendar year.

     c.  Anyone who has, in the opinion of the Steering Committee, made
         a significant contribution in the past year.
~~~

**Comment by pbanaszkiewicz** [comment]
@gvwilson but time changes, so if someone taught exactly 2 years ago, tomorrow they won't be a member?

**Comment by gvwilson** [comment]
In 2015, "previous two calendar years" means any of 2013 or 2014. If you 
last taught on Jan 1, 2013, you stop being a member at midnight on Dec 
31, 2015.

**Comment by maneesha** [comment]
So if someone last taught Dec 31, 2013, they'll also stop being a member on Dec 31, 2015?

**Comment by gvwilson** [comment]
Yup.  Anything less than a three year gap, they're still officially a 
member.  But they have to have taught twice in that interval.

**Comment by pbanaszkiewicz** [comment]
@gvwilson what's the status on this issue?

**Comment by pbanaszkiewicz** [comment]
Reassigning to me, I'll improve @gvwilson's work.

**Comment by gvwilson** [comment]
Cool - when's the next deployment?

**Comment by pbanaszkiewicz** [comment]
@gvwilson probably around 2015-12-02 :)

**Comment by gvwilson** [comment]
Thanks.
