### ISSUE TITLE
Flag people who have done instructor training but are unlikely to complete

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#545]
We now have a way to find people who have done instructor training but have not yet completed; what we need is a way to mark some of them as "don't worry about it, they're unlikely to ever finish". This could be a property of the Task object, so that we could filter by it when selecting who to display.

**Comment by pbanaszkiewicz** [comment]
What does it take to finish a training? What does it mean that someone is unlikely to finish it?

**Comment by gvwilson** [comment]
This will have to be done manually - talk Monday about details?

**Comment by pbanaszkiewicz** [comment]
Sure!

**Comment by gvwilson** [comment]
Err, by "Monday" I mean "Tuesday", because I'm in a workshop all day Monday :-)  But question: how hard would it be to:
1. Add three new tasks "learner_in_progress", "learner_incomplete", and "learner_complete".
2. Turn everyone who's marked as a "learner" in a TTT event into "learner_complete" if they've got an instructor badge, "learner_incomplete" if they don't but their TTT finished more than six months ago, and "learner_in_progress" otherwise.
3. Modify the award tab on the Person page to make it easy to replace one kind of task with another.

**Comment by pbanaszkiewicz** [comment]
1. By tasks you meant "roles". Not hard.
2. By a migration, sure, not that hard. If you want an automatic mechanism then it's not trivial.
3. By award you meant "tasks"? :-) Not impossible.

On Tuesday I'll be available around 17:00 my time, 16:00 your time.

**Comment by pbanaszkiewicz** [comment]
In chat, @gvwilson got a nice idea for this issue: "let's not mess with roles, but rather tag stalled TTT events".

**Comment by pbanaszkiewicz** [comment]
@gvwilson after talking with admins we agreed that having "stalled" tag would be super useful for other purposes too.

In John and Maneesha's cases, they'd like to use "stalled" to tag workshops with no contact from the organizer.

Any stalled workshop would then be thrown out of their "Unpublished" workshops.

**Comment by gvwilson** [comment]
What the admins want, the admins get :-)

**Comment by gvwilson** [comment]
This one's becoming more important - I need to know who to chase about completing instructor training.
