### ISSUE TITLE
Indicate host membership status

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#546]
Can we note for each host whether they're a member & info on terms of membership agreement?  Dates, how many workshops they get at no cost, etc.

**Comment by jduckles** [comment]
Once I get our members.csv updated we should figure out how to do a periodic ingest of that data and make sure it is structured for use in AMY.

**Comment by pbanaszkiewicz** [comment]
Ref #375.

**Comment by pbanaszkiewicz** [comment]
I'll start working on this and #375, but without proper feedback from @jduckles, @maneesha and @gvwilson I don't think I'll be able to finish this one in time for v1.2.

**Comment by pbanaszkiewicz** [comment]
@jduckles @maneesha @gvwilson as I understand these are the thing we want to track:

* type of membership (Partner, Affiliate, Sponsor)
* start of agreement
* end of agreement
* type of contribution (financial, person-days)
* number of workshops without administrative fee
* probably general notes

As I understand this, agreements with organizational members are often *tailored*, so we won't be able to gather all specific information because they won't be useful in other membership cases.

So… anything else you'd like AMY to keep track of?

**Comment by maneesha** [comment]
Adding to @pbanaszkiewicz 's list above:

* number of workshops without admin fee (total due, completed, remaining)
* number of self organized workshops (total due, completed, remaining)

* instructor training obligations ( @gvwilson can probably share how to best enumerate this)

 Once this is in place, if an Event gets created in AMY where Host membership status is current I'd like to see some kind of flag on Invoice Status that they may have a modified or waived admin fee.

**Comment by pbanaszkiewicz** [comment]
Hello @maneesha.

> * number of workshops without admin fee (total due, completed, remaining)

This would be a one field (number of workshops without admin fee) and two calculated properties.

> * number of self organized workshops (total due, completed, remaining)

The same.

> * instructor training obligations ( @gvwilson can probably share how to best enumerate this)

This seems like a field without one type of value, so I'd guess it should be a text field? But let's wait for Greg to comment on that.

**Comment by pbanaszkiewicz** [comment]
@maneesha @jduckles @gvwilson is "number of workshops without admin fee" per year or per whole agreement?

Is this number imposed through the agreement?

**Comment by jduckles** [comment]
Per year

Yes, it is in the text of the agreement. Which I've recently templated using jinja2 and a yaml document to feed the values. So eventually we might think about an integration to make AMY the authoritative source for member agreement data fields and I can fill the template from the values in AMY.

**Comment by pbanaszkiewicz** [comment]
@jduckles @maneesha is there a possibility that some hosts have more than one membership (for example an old one and a renewed one), and you want to track all the history of former memberships?

**Comment by maneesha** [comment]
@jduckles can speak more about this - but I'd think that we do want to track history of memberships.

@jduckles and @tracykteal - Now DC does not have a membership model but as you move towards that, will it also be possible to have concurrent SWC or DC memberships?

**Comment by jduckles** [comment]
@pbanaszkiewicz Yes we want to track the history of memberships. Typically only one per organization will be active at any one time. They can all have a startdate and an enddate. 

@maneesha I think we'll know more about this after DC's in-person meeting next week. Don't want to speculate until they come back and we all have a chance to talk.

**Comment by tracykteal** [comment]
It will likely be possible to have concurrent SCF and DC memberships. There will likely also be different types of memberships. Like SCF has Affiliates and Partners now, there might be other categories. 

Maybe input could be 'interested in association'. Then we can update that record as we learn more what people are interested in and their status as to 'in progress' or 'signed'. 

Is this too much, or is it possible?

**Comment by pbanaszkiewicz** [comment]
@tracykteal each Host in AMY allows for storing notes. I'd use this field for describing needs or progress of signing an agreement.

Variants of agreements can change any time (they're only hard-coded).
