### ISSUE TITLE
Empty workshop titles showing up

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#547]
At 09:28 UK time on 2015-10-16, two workshops were showing up blank in the "upcoming" list on the web site:
![screen shot 2015-10-16 at 9 28 18 am](https://cloud.githubusercontent.com/assets/911566/10537241/592ed9ba-73e8-11e5-9187-c9553256dff9.png)
I *think* this was because "Venue" was blank for 2015-11-11-northwestern and 2015-11-11-nyu-med; I've added venue names for both, but:

1. AMY should complain about missing venue names (or we should use something else as the title of the event when displaying on the website).

2. Our build script should check for empty venue names and... skip the workshop?  Report an error?  Something.

**Comment by gvwilson** [comment]
Hm - the two workshops at the University of Miami (2015-11-19-umiami-R and 2015-11-05-umiami-Python) were also missing venue information.  The former was showing up as one of the blank lines; the latter didn't appear in the upcoming workshop list at all.  I've filled in venue information for both - @maneesha please check that all four of the workshops mentioned in this issue are actually supposed to be published.

**Comment by pbanaszkiewicz** [comment]
The issue has multiple sides to it.

1. In AMY, we mark events as published when they have URL and starting date.
2. In site, we trust whatever AMY gives us…

Maybe we should only publish workshops that have a full location as well?

**Comment by pbanaszkiewicz** [comment]
@gvwilson 2015-11-05-umiami-Python is missing URL that's why it's not showing up on the site.

**Comment by gvwilson** [comment]
1. Mark as published with URL, start date, and venue
2. Better checking in web site as well.
3. Something big and bright on the Event page and in the dashboard and 
on `all_events` to show published/unpublished.

**Comment by gvwilson** [comment]
@maneesha is there a website for 2015-11-05-umiami-Python yet?

**Comment by pbanaszkiewicz** [comment]
@gvwilson: can you elaborate on 2. and 3.?

For the list of unpublished events we have "Unpublished" in the dashboard, and "Status - Unpublished" filter in "All Events".

**Comment by maneesha** [comment]
2015-11-05-umiami-Python does not yet have a github page.  It's in the "unpublished" column in AMY as it should be.

AMY is set up to publish once it has a github page and a date.  However, sometimes we get a github page before the exact location is confirmed.  I'll record the github page in AMY knowing the instructor will update it once the host confirms the location.  I think this is why this is happening.

Maybe we can a third condition (has location) to published?

**Comment by pbanaszkiewicz** [comment]
> Maybe we can a third condition (has location) to published?

I think this is a good idea. However, there's slight implementation issue. We have 5 fields for location: venue, address, latitude, longitude, country. Should we require all 5 of them to be filled up (+ start date + URL)?

**Comment by maneesha** [comment]
Sorry I missed this earlier.  
Lat/Lon are calculated fields, yes?  
So I would say the other three should be filled in and lat/lon should be generated in order for a workshop to be published.

**Comment by pbanaszkiewicz** [comment]
@maneesha no, lat/long aren't calculated, but they are populated from the workshop's website by "import/update from URL" feature. Does that change your opinion?

Missing lat/long means no marker on the workshops map.

**Comment by maneesha** [comment]
Then I think I'd say that Location must have all 5 fields to be complete.

A related question - if the 2 character country code is on the github page can that be used to populate the `Country` field when doing the import from URL?

**Comment by pbanaszkiewicz** [comment]
@gvwilson do you agree to include `Event.address`, `Event.latitude` and `Event.longitude` to the list of fields that must be complete in order for the event to be considered published?

@maneesha that feature (filling up `Country` with "Import from URL") is already implemented, but I just found out that there's a number of bugs related to it. Let me add a GH issue for that.

The "Update from URL" part works as long as the remote URL is reachable.

**Comment by gvwilson** [comment]
I think it's up to @maneesha and @jduckles - when do they want workshops 
to show up on the main website?
