### ISSUE TITLE
Note when giving up on workshop counts

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#549]
We have space in each event to record how many people attended. 
#514 already asks to break this out to track attrition - some people have actually been providing that.

Some, however, don't respond at all after 3-4 requests at which point I give up asking.  I want to record this but I'm not sure how.  Any ideas?

**Comment by gvwilson** [comment]
Hm - can you send me a list of workshops and I'll chase them? Sending us 
a head count is a condition of using the name and logo.

**Comment by maneesha** [comment]
I'll start making a list and share it with @gvwilson 
It's not many but enough to note.

**Comment by maneesha** [comment]
Of the workshops listed here (https://amy.software-carpentry.org/workshops/reports/workshop_issues), everyone from Aug 1, 2015 up until one week from present day has been asked at least 1-2 times, some more often.   I typically send a "How'd it go? Send us counts/other data" email within a week after the workshop ends.

I'll continue to go farther back through the rest of 2015.

**Comment by gvwilson** [comment]
I've mailed the instructors of every workshop for which we don't have 
attendance figures up to the end of September 2015.  Responses are 
starting to come back (as are bounced messages); I'll update AMY as I 
get stuff.

**Comment by gvwilson** [comment]
OK, I agree with @maneesha that we need a way to mark a workshop as "giving up on collecting data". I think this should be the same tag that we use for instructor training events that are so far in the past that people who attended them are officially deemed unlikely to ever complete.  "stalled" doesn't seem like the right tag, so how about "closed"?  We used to use that term to mean "closed enrolment", i.e., only people from a particular institution could enrol, but I don't think we're doing that any more. @pbanaszkiewicz thoughts as well?

**Comment by pbanaszkiewicz** [comment]
@gvwilson we can't use `attendance` field to indicate the fact that we'll not going to get any numbers for these particular workshops.

I think we need to add one more tag just for that…

* `stalled` is available but should be used in two other contexts, I don't want it to be used here as well
* `closed` brings ambiguity since we have a `Event.completed` field
* `no updates`? Or is there a single word in English that means "no chance getting new data"?

**Comment by gvwilson** [comment]
I think we're going to wind up using *all* the synonyms.  @maneesha any 
thoughts?

**Comment by maneesha** [comment]
I'm not sure what word to use.  We are using `stalled` to refer to Events where contact was initiated but then went nowhere and Instructors who started training but aren't going to finish.  We could use `stalled` if it applied *attendance count* and not the event itself.  

@pbanaszkiewicz I think the closest to a single word in English is the phrase "lost cause."

**Comment by wking** [comment]
On Tue, Nov 24, 2015 at 09:20:58AM -0800, Piotr Banaszkiewicz wrote:
> * `no updates`? Or is there a single word in English that means "no
>    chance getting new data"?

Unresponsive?

**Comment by gvwilson** [comment]
+1 to "unresponsive" for workshops that we were negotiating with but 
that don't look like they're going to materialize.

I suggest "finalized" for instructor training events that are old enough 
that we're giving up on participants, and for regular workshops where 
we're giving up on collecting information about attendance.

**Comment by maneesha** [comment]
"Unresponsive" might be right for workshops where we aren't going to get an attendance count.

It's not quite right for the workshops where we were negotiating but nothing's going to happen.  Many times it's not that they were unresponsive, but we were in contact and it's that timing, budget, etc. wasn't working out and they backed out.  So I prefer "stalled" there.

**Comment by pbanaszkiewicz** [comment]
Okay, I'll add "unresponsive" to the #581 as well as a `help_text` with meanings of some of the options there ("stalled", "unresponsive").
