### ISSUE TITLE
"Not Invoiced" dashboard column not populating correctly

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#550]
For example 2015-10-05-ucalgary and 2015-10-12-vt are marked  not invoiced on their respective event pages but don't show up in that column on dashboard.

**Comment by pbanaszkiewicz** [comment]
@maneesha the rule for uninvoiced workshop to show up is that they have some admin fee assigned to them. 2015-10-05-ucalgary currently doesn't and thus it won't show up on the dashboard.

Do you want to change that rule?

**Comment by maneesha** [comment]
So the "not invoiced" column on the dashboard is not populated by the event's invoice status being "not invoiced"? 

This is confusing.  I'd want this column to list all events with status = "not invoiced" -- then I know I have to process the invoice or change the status to something else.

**Comment by pbanaszkiewicz** [comment]
@maneesha sure. The rule for now is "anything with not-invoiced status and non-NULL admin fee", but I'll change that for you for v1.1.

**Comment by maneesha** [comment]
Another example:

2015-06-24-gatech shows up in the Not Invoiced column on dashboard but in event details 
admin fee:	1250.00
invoice:	Not applicable because other arrangements made

They raised all but ~$60 of their $1250 via registration fees so we waived the remainder.

If I change the admin fee to 0, it disappears from the dashboard Not Invoiced column.  However if we want to use this as a tool to track what sites owe us we may need to change how this works.  In this case, the site owes $1250 but paid it all via eventbrite so there is nothing to invoice.  So making the admin fee be $0 is not accurate.
