### ISSUE TITLE
Modify "send us attendance figures" email to include host (if any)

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#553]
The mailto: list for the message asking for attendance figures should include the hosts as well as the instructors.

**Comment by pbanaszkiewicz** [comment]
@gvwilson:

1. We don't have any contact details in the Host object
2. But we do have Event.contact - text field for storing contact point(s) for the event
3. And yet it doesn't have a specified format, so it can even be a telephone number.

So I can see 3 options here:

1. Add contact to the Host model, or
2. Enforce some format on the Event.contact field, or
3. Find email addresses in the Event.contact field and add them to the attendance email

Any thoughts, @gvwilson?

**Comment by gvwilson** [comment]
We should have at least one Person awarded an Organizer badge for each 
Event.  I've been slack about doing this, but if we can get in the 
habit, that'll be simpler than trying to record contact info in Host 
organizations.

**Comment by pbanaszkiewicz** [comment]
So what do you decide on this issue, @gvwilson?

**Comment by maneesha** [comment]
I need to be better at doing this consistently but....

* for standard workshops I have been adding names to Persons in AMY and listing their tasks as Host for specific events.   This Person is not connected to the Host model though. I've been wanting to put in an issue for that.

* for self-organized workshops I've been naming the Organizer (usually also the instructor).

**Comment by gvwilson** [comment]
If we include everyone marked as Instructor or Organizer for an Event, that'll be good enough.

**Comment by maneesha** [comment]
I'd actually like it to include Host as well.  Sometimes they are the ones managing registration & attendance and so they're the ones who actually have that information.
