### ISSUE TITLE
Remove slider widget from attendance count & invoice amount

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#559]
Just let it accept a inputted number.
I've never used it, and actually had it cause problems when my scroll wheel activates it and changes the value.

**Comment by pbanaszkiewicz** [comment]
@maneesha Can you show me a screenshot? I have never seen such thing in AMY, so it may be browser-dependend.

**Comment by maneesha** [comment]
Sorry... meant "spinner" not "slider"  

![image](https://cloud.githubusercontent.com/assets/829690/10823404/fab4fe24-7e31-11e5-991b-5e11673d6ca1.png)

**Comment by pbanaszkiewicz** [comment]
@maneesha is this still an issue?

Unfortunately & probably, it's not possible to switch only one field to non-HTML5 mode – I think it's "all or nothing". But I'll check.

**Comment by pbanaszkiewicz** [comment]
@maneesha ping on this issue

**Comment by maneesha** [comment]
See the image in my comment on Oct 29.  The spinner (up/down arrows) mean that if I hit my mouse scroll wheel while in that field, I change the value. 
I'd like to disable the spinner so the only way to enter a value in any numeric field (attendance, admin fee, etc) is to key it in.
