### ISSUE TITLE
Bugs with "Import/Update from URL"

### ISSUE THREAD

**Issue by pbanaszkiewicz** [swcarpentry/amy#571]
1. "Import from URL" has wrong `country` field ID in JavaScript
2. Something's wrong with for example this event: https://amy.software-carpentry.org/workshops/event/2015-02-09-ucdavis (it uses remote that redirects to somewhere else, plus when we use the remote after redirection we get some errors). The officially saved URL is https://datacarpentry.github.io/2015-02-09-ucdavis/
3. Fix spaces around URLs

**Comment by maneesha** [comment]
Thanks for this - I was just about to put in an issue to strip leading/trailing whitespace around urls.
