### ISSUE TITLE
Person's email address does not show up

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#574]
https://amy.software-carpentry.org/workshops/person/6639

He has a valid email address in his profile.   But if you go to any of the events where he has a task his email address does not show up like it does for everyone else.  Not sure if he's only case but I haven't noticed any others.

**Comment by pbanaszkiewicz** [comment]
@maneesha: Karthik and others opted-out from us being able to contact them (see "May contact" field on the linked page). In some places their emails won't show up, and in some other places they themselves won't show up because, for example, we only show people that we can email.

**Comment by maneesha** [comment]
Got it.  I didn't realize that would make the email not show up internally.  I have no problem with that.
