### ISSUE TITLE
Integration with SurveyMonkey

### ISSUE THREAD

**Issue by pbanaszkiewicz** [swcarpentry/amy#578]
In this issue I want to gather all functionalities users want.

**Comment by maneesha** [comment]
First thought --
I'd like three fields that hold the links to the survey results for that specific event. (pre, post, longterm)

Right now those links themselves have to be manually generated.  I'm not sure if it is possible to automate that -- but that would be ideal.

I'll add more as I think of things.

**Comment by pbanaszkiewicz** [comment]
Posted by @maneesha in older issue:
> […] now that we are using Survey Monkey I'd like fields that just hold the survey results. This would be 5 > fields for the 5 surveys we're planning on using:
> Learner pre & post
> Instructor pre & post
> Learner Longterm

and:
> I was thinking these would be manually entered. So we'd just need 5 text fields validated to hold hyperlinks.
