### ISSUE TITLE
"Import from URL" does not seem to set country

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#584]
Imported two workshops this morning via their URLs (which were http://huguesfontenelle.github.io/2015-12-02-Oslo/ and http://karinlag.github.io/2015-11-20-NVI/). In both cases we got address and lat/long, but *not* country (which should be "Norway").

**Comment by pbanaszkiewicz** [comment]
It does work in `develop`, but there's a bug with converting `None` to `int` in `parse_tags_from_event_website` (`TypeError` is not caught).

Additionally with fallback to the old method of getting tags, a slug should be calculated from event's URL. That's a TODO.
