### ISSUE TITLE
Tagging instructors as DC/SWC instructors

### ISSUE THREAD

**Issue by pbanaszkiewicz** [swcarpentry/amy#596]
There's no such distinction yet.

**Comment by pbanaszkiewicz** [comment]
Another possibility is to change badges to have "SWC instructor" and "DC instructor" badges separately.

**Comment by gvwilson** [comment]
1.  Create new badges 'Software Carpentry Instructor' and 'Data Carpentry Instructor'.
2.  Run a migration to convert all existing 'Instructor' badges to 'Software Carpentry Instructor'.
3.  Get a list of Data Carpentry fast-track instructors from @tracykteal and run a migration to award them all Data Carpentry badges.

**Comment by pbanaszkiewicz** [comment]
@gvwilson:

1. change "Instructor" to "Software Carpentry Instructor" badge
2. add "Data Carpentry Instructor" badge
3. add "Data Carpentry Instructor" badges to people from fast-track (not in migration - I don't want to publish email this way)

Sounds good?

**Comment by gvwilson** [comment]
+1.

**Comment by pbanaszkiewicz** [comment]
@gvwilson should our API return only SWC instructors or DC instructors as well?

**Comment by gvwilson** [comment]
Anyone with either kind of badge who has taught a workshop labelled SWC.
