### ISSUE TITLE
List of people who taught at events of specific type

### ISSUE THREAD

**Issue by pbanaszkiewicz** [swcarpentry/amy#597]
Usecase: Tracy wants to grab list of people who taught at DC workshops, so that she knows who is experienced DC instructor.

**Comment by gvwilson** [comment]
Filter the "Events" display by tag?

**Comment by pbanaszkiewicz** [comment]
@gvwilson and you'll end up with list of events, not instructors.

**Comment by maneesha** [comment]
> @gvwilson and you'll end up with list of events, not instructors.

But we can get the instructors from those events, right?

**Comment by pbanaszkiewicz** [comment]
@maneesha yes, but it requires you to open each workshop and look at the list of tasks.

**Comment by gvwilson** [comment]
Right - we'll probably need to filter people by award ("has instructor 
badge") and then by properties of associated events.

**Comment by pbanaszkiewicz** [comment]
@gvwilson right now it's possible to filter people by their badges on All Persons page. I'm going to add "filter by type of workshop where person taught", which is not the same - some people have 'instructor' task for event but are actually missing the badge.
