### ISSUE TITLE
Add a request form for instructor training events (similar to the form to request regular workshops)

### ISSUE THREAD

**Issue by tracykteal** [swcarpentry/amy#599]
As a way to track the T3 requests that we want to commit to, could we add a 'Train the trainer event' request form that would go into Amy?

If this is possible, I can create the questions that would go in to that form. Thanks!

**Comment by pbanaszkiewicz** [comment]
@tracykteal it's possible, for reference see #419.

I'd like @gvwilson to comment if he wants to only import old TTT event requests, or also a form for them.

**Comment by gvwilson** [comment]
Don't understand the question??

**Comment by tracykteal** [comment]
We'd also like to have a form to enter new ones. So, it would basically be another workshop request form.

**Comment by jduckles** [comment]
I think Tracy is talking about T3 **events**  not interested instructor candidates.  There are two types of data we want to capture. A person wants to become an instructor (done now with a Google Form). An organization (often through a "membership agreement") wants to have several persons become instructors at an event (we have no method to our madness on this front).

This is complicated by the fact that we're changing how this worked. Instructor training events in the past were of two types:

1. Online with individuals at their own desks (~40-50) attending weekly calls over 12-18 weeks.
2. In Person at a fixed location with an instructor trainer in front of a room of 10-20 people for two days.

We're moving toward:

1. Online with 1 to 3 rooms of (3-10) all connected over video conference for 2-days
2. In Person.

It would be nice if the new system would give us the ability to do the multiple-site matching. We'd set an event date and then add groups of instructor candidates to the event as we negotiate dates that are mutually agreeable.

**Comment by gvwilson** [comment]
This has become a higher priority...

**Comment by chrismedrela** [comment]
Isn't the form already implemented [here](http://amy-dev.software-carpentry.org/workshops/request_training/)?

**Comment by gvwilson** [comment]
That form is for an individual to request training - we need something 
to allow an organization make a request for an entire class (for a group 
of people).

**Comment by pbanaszkiewicz** [comment]
This won't happen for v1.7, will it @chrismedrela ?

**Comment by gvwilson** [comment]
Not for 1.7

**Comment by chrismedrela** [comment]
@maneesha do we need this in v1.10? If yes, how the form should look like?

**Comment by maneesha** [comment]
This is an old issue - I don't think we need this now, as instructor trainings are negotiated directly through memberships.  @ErinBecker  @karenword what do you think?

**Comment by ErinBecker** [comment]
Agreed - we can close this. For the (very rare) instances where we run instructor training events outside of memberships, @maneesha is having people fill out a Google form to request the training. There has only been one of those in the past 6 months.
