### ISSUE TITLE
Using underscores instead of periods in user IDs

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#603]
See https://github.com/swcarpentry/website/issues/90.

**Comment by pbanaszkiewicz** [comment]
Okay, I looked into this and there's a huge impact: we're basically changing users' login data.

What I suggest we should do is return an underscored name in the API instead - that's the only way the website talks with AMY, right?

**Comment by gvwilson** [comment]
But how many users have logins?

**Comment by pbanaszkiewicz** [comment]
Well everyone has a username, and 17 people have login access.

**Comment by gvwilson** [comment]
Easy to regenerate user names, and better to do it now with 17 people 
than a year from now with more.  If this cuts one custom build step out 
of the website, I think it's worth doing.

**Comment by pbanaszkiewicz** [comment]
Closing via #645.
