### ISSUE TITLE
Modify members API call so that JSON includes user ID

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#604]
Right now the 'members' API gives us name and email - the JSON should include each person's user ID as well.

**Comment by pbanaszkiewicz** [comment]
@gvwilson and what do you need that ID for? And did you by ID meant username?

**Comment by gvwilson** [comment]
Yes, username - I want to be able to check against _include files, PDF 
certificates on disk, etc.

**Comment by pbanaszkiewicz** [comment]
@gvwilson is the members call used in website generation?

I'm thinking of allowing only logged in users to access this API call.

**Comment by gvwilson** [comment]
Not needed for website generation; it's for things like checking the 
certificates we've generated (which involves comparing to stuff on a 
hard drive somewhere).  Don't want to have to do that on the server, 
don't want to have to copy the database down to my machine to run it.
