### ISSUE TITLE
Use person.name instead of personal, middle, and family names

### ISSUE THREAD

**Issue by wking** [swcarpentry/amy#61]
Parsing names is complicated, and we don't want to get into that business unless we have to.  I don't think we have to, so we should simplify and just have `person.name`.  See [the earlier discussion][1] in swcarpentry/site#701.

[1]: https://github.com/swcarpentry/site/pull/701#issuecomment-66926188

**Comment by gvwilson** [comment]
Close? We seem to be managing fine...

**Comment by pbanaszkiewicz** [comment]
We'll reopen in case more issues emerge.
