### ISSUE TITLE
{workshops,instructors,learners}_over_time to API

### ISSUE THREAD

**Issue by jduckles** [swcarpentry/amy#616]
Would it make sense to move the {workshops,instructors,learners}_over_time to the API. I'd like to be able to auto-generate graphs for these and right now I do a manual cut-paste process.

**Comment by gvwilson** [comment]
Agreed - all info should be provided both in HTML display and as JSON 
through an API call.  Management commands like report_all_activity 
should probably be turned into API calls as well.

**Comment by pbanaszkiewicz** [comment]
Do we want `report_all_activity` to be accessible to everyone?

**Comment by gvwilson** [comment]
Everyone who can log into AMY.
