### ISSUE TITLE
New report: All activity over time

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#631]
I'd like to be able to generate a report where user inputs a date range and output is:

* count workshops: SWC, DC, total  (note total may not equal sum if there are joint SWC-DC workshops)
* count workshops: self-organized, WiSE, TTT
* count total instructors
* count unique instructors
* count total learners
* list workshops missing any of this data (so we know if our counts above are incomplete)

**Comment by pbanaszkiewicz** [comment]
@maneesha:

> * count total instructors
* count unique instructors
* count total learners

What is the meaning of these numbers? Do you want to know how many (distinct or not) people appeared on workshops from specific time period with these roles (instructor, learner)? Or do you want to know how many people became instructors in that time?

> * list workshops missing any of this data (so we know if our counts above are incomplete)

From the specific period or in general?

**Comment by maneesha** [comment]
Good questions - sorry that wasn't clear.
Count instructors would mean instructors who taught in that date range.
Count learners would mean people who were learners in that date range.
List of workshops missing any of that data would be for same date range.

It would probably be nice to also include count people who became instructors although maybe @gvwilson wants to chime in on this.  Would that  be people who went through a TTT? Or people who actually got the badge?
