### ISSUE TITLE
API call to get people associated with event

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#639]
I would like an API call to fetch (role, name, email) for everyone involved with a particular event (optionally filtered by role) - I want it so that I can quickly grab a list of people who were involved in a particular instructor training event to prompt them to finish off.  Bonus marks if we can also filter by award (i.e., subtract the people who are already instructors).

**Comment by pbanaszkiewicz** [comment]
@gvwilson this should be accessible to admins only, right?

**Comment by gvwilson** [comment]
Whoever can view the event should be able to make the call, since it's 
the same info.
