### ISSUE TITLE
Additional event attendance information (slots and applicants)?

### ISSUE THREAD

**Issue by wking** [swcarpentry/amy#64]
As [proposed][1] in swcarpentry/site#701, I think it would be good to have an `event.slots` or similar to count how many seats were available. And maybe `event.applicants` if anyone was waitlisted. Comparing with `event.attendance` will let us see how full the event was, which gives a hint at how soon we'll want to run a follow-up workshop. 

[1]: https://github.com/swcarpentry/site/pull/701#issuecomment-66926188

**Comment by pbanaszkiewicz** [comment]
Do we have historical data for these?

**Comment by gvwilson** [comment]
Mostly not.

**Comment by pbanaszkiewicz** [comment]
Both Giacomo and Amy think this is not a good idea.
