### ISSUE TITLE
Workshop requests coming in multiple times & not via email

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#647]
See 
https://amy.software-carpentry.org/workshops/requests/

Recent requests have come in 4x and are not coming in through admin-all email list.

**Comment by gvwilson** [comment]
By '4x' do you mean each request arrives four times?

**Comment by maneesha** [comment]
Yes - unless something is weird just on my view.  Do you see the last couple of requests four times here?

https://amy.software-carpentry.org/workshops/requests/

**Comment by gvwilson** [comment]
OK, that's definitely a glitch - @pbanaszkiewicz, over to you?

**Comment by pbanaszkiewicz** [comment]
@maneesha @gvwilson the repetition is really bizzarre - I don't think I changed any code regarding EventRequests in v1.3 and v1.3.1.

The "no emails" part might be because of the recent mail server failures.

**Comment by pbanaszkiewicz** [comment]
@maneesha I just submitted a test request. Did you receive the email?

My request was not multiplied, so *maybe* these two multiplied were due to DNS errors we had recently?

**Comment by maneesha** [comment]
Yeah, it looks like server downtime caused these glitches.
