### ISSUE TITLE
Generate certificates from AMY

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#656]
We are presently generating PDF certificates for instructors using a small Python script in the swcarpentry/certification repository (which in turn relies on Inkscape). Doing this by hand means that certificates are always out of step with the list of instructors in the database. We should instead:
1. Have AMY generate certificates.
2. Have it check that a certificate for a user and award already exists.

This will save me a lot of time...

**Comment by pbanaszkiewicz** [comment]
So #343 is meant for attendees certificates?

**Comment by gvwilson** [comment]
Yup - I want to separate generating certificates that we have already 
agreed to create (instructors of both kinds, eventually organizers as 
well) from generating certificates for attendees (still under debate).  
The former is a higher priority.

**Comment by gvwilson** [comment]
I've updated bin/certificates.py in the https://github.com/swcarpentry/certification repository - please use that as a starting point for certificate generation.  (I still really dislike the need for Inkscape for SVG-to-PDF conversion, but don't have anything better.)

**Comment by nikhilweee** [comment]
@gvwilson @pbanaszkiewicz : I'm willing to work on this issue.
As far as I can understand, here is what I've figured out how:

I'll add an option under the `More` tab to generate certificates.
This will then open up a view similar to `Persons` where you can select the recipients. This view will also show whether a certificate has already been generated. The data to be printed will be fetched from the badges awarded to a person, which has the `Date of award` and `Certified by` fields required in the certificate.
Once you confirm and click generate, the certificates will be generated where and available for download.

Responses awaited!
I'll start working based on your inputs.

**Comment by gvwilson** [comment]
This would be great:

1. @pbanaszkiewicz, @nikhilwee has just modified the certificate 
generation program in https://github.com/swcarpentry/certification to 
use Cairo to generate PDFs rather than Inkscape, so we've got the tools 
we need.

2. If we're going to generate PDF certificates in AMY, we should also 
provide a way to view them in AMY (click on certificate link, new tab 
opens, show the PDF) so that people can see what's been generated and 
fix it if necessary.

3. Deleting a badge should automatically delete its PDF certificate.

4. When a PDF certificate is generated, we should auto-populate the form 
from the badge info, but allow that info to be edited before the PDF is 
generated - e.g., some certificates have "Person One and Person Two" as 
the instructors' names, rather than just one person's name.

How does this sound?

Cheers,
Greg

**Comment by nikhilweee** [comment]
@gvwilson : 
* I was initially thinking of bulk generating certificates from AMY, but as the info has to be reviewed, I feel that they should be generated individually.
* Going this way, I'll give a link in the profile page which points to the certificate if generated, or gives an option to generate a new one. 
* Also, the `certificates` tab (let's call it this for now), which was supposed to list all participants with certification options as I planned earlier, will now become redundant. I want your inputs on whether this should be implemented or not.

Thanks,
Nikhil
PS. My username is nikhilweee with a triple 'e' :stuck_out_tongue:

**Comment by pbanaszkiewicz** [comment]
@nikhilweee excellent work! I'm quite short on time for now so if you want you can make a PR with these changes. It's going to be quite big and I must warn you: I'll be picky about it!

Thanks again ;)

**Comment by gvwilson** [comment]
@narayanaditya95 can you please review and merge?

**Comment by narayanaditya95** [comment]
@pbanaszkiewicz I hope you aren't working on this issue. I wish to start working.

**Comment by pbanaszkiewicz** [comment]
@narayanaditya95 so far I only have 5 lines in my notes on how I would go about generating certificates if I started from scratch. Please go ahead :-)

**Comment by gvwilson** [comment]
Thanks Aditya - I'd be very grateful if you could.

**Comment by nikhilweee** [comment]
@narayanaditya95 
Please also go through #724.
Feel free to build upon [my work](https://github.com/nikhilweee/amy/tree/certificates-integration) if you please.

**Comment by narayanaditya95** [comment]
Sure. I will be reusing code snippets from #724.
