### ISSUE TITLE
Show events with missing instructors

### ISSUE THREAD

**Issue by pbanaszkiewicz** [swcarpentry/amy#661]
…in the workshop issues page.

**Comment by maneesha** [comment]
Taking this a step further - can AMY read the workshop website's repository & get len(instructor) and len(helper), then alert if these do not equal count(instructors) and count(helpers) in the database?

Sometimes I put an event in AMY but the organizers add instructors/helpers afterwards and don't tell me.   This will cue the admins to double check that all instructors/helpers have been entered in.  (Or likewise, someone drops off, we want to delete them from our records)

**Comment by pbanaszkiewicz** [comment]
@maneesha such feature should go to #562 I think.
