### ISSUE TITLE
Reporting completion percentages for instructor training

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#667]
Please create a management command that reports:

* instructor training event slug
* total # of attendees
* # of attendees who got their instructor badge from that event
* # of attendees who have an instructor badge (from that event or any other)

for each instructor training event, so that we can see completion rates (both from the event and eventually).

**Comment by pbanaszkiewicz** [comment]
@gvwilson when do you need it? For February or March?

**Comment by pbanaszkiewicz** [comment]
@gvwilson also which instructor badge are we talking here? Will you only train SWC people, or DC too?

**Comment by gvwilson** [comment]
I'm doing this by hand right now, so next week would be a big help.

**Comment by gvwilson** [comment]
Good question - they're all mixed together, so "any instructor badge".
Thanks,
Greg

**Comment by pbanaszkiewicz** [comment]
@gvwilson I'll try to work on this tomorrow.

Also, if in the future someone else may be doing DC instructor training, I'd include a code that looks for a badge of the type of Tag assigned to the specific training. For example:

1. SWC-tagged event: look for `swc-instructor`-badged people
2. SWC- and DC-tagged event: look for either `swc-instructor` or `dc-instructor`-badged people.

**Comment by gvwilson** [comment]
Hm - I don't understand what you have in mind looking for badged people...

**Comment by pbanaszkiewicz** [comment]
That's for calculating number of attendees who received their badge for that event, or for any other event.
