### ISSUE TITLE
Assigning DC instructor Badge

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#668]
There are a bunch of instructors with the text "Data Carpentry instructor" in their profile notes field. I believe these should all have the DC badge.  @tracykteal can you confirm? And if so, @pbanaszkiewicz can you run a script to pull these instructors?  We should manually verify, and then they can be assigned a DC badge.  This should be a one time thing.  From now on we should be using the DC Instructor badge in AMY.

**Comment by tracykteal** [comment]
Yes, everyone with "Data Carpentry instructor" in the notes, should all have the DC Instructor badge, and it would be great if we could script this.

**Comment by pbanaszkiewicz** [comment]
This will be fixed manually (in Django shell).

**Comment by pbanaszkiewicz** [comment]
Fixed manually.
