### ISSUE TITLE
Navigation of Workshop Requests

### ISSUE THREAD

**Issue by gperu** [swcarpentry/amy#679]
Hello Piotr,

WR's contain important information about a workshop which is not transferred to the workshop page. Therefore we need an easy access to them.

Is it possible - when you've time - to either:

- add an 'all' option both to 'status' and to the 'workshop type'

or

- add a link to request from the workshop page?

Thank you
Giacomo

**Comment by pbanaszkiewicz** [comment]
Hi @gperu,

I'll do all these things:
* backlink from event to workshop request which created that event
* filtering option "all" in status field
* filtering option "all" (or "any") in "workshop type"

Cheers,
Piotr

**Comment by gperu** [comment]
Fantastic, thanks!
