### ISSUE TITLE
Modify instructor stats report to include #/% who have taught

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#681]
Please modify trainings_completion_rates to display two more columns: what # and what % of people trained in a session have taught for us at least once since being trained.

**Comment by pbanaszkiewicz** [comment]
@gvwilson You're submitting a PR (#680) against `trainings_completion_rates`, why don't you put these columns in there?

**Comment by gvwilson** [comment]
Because it would take me an hour to figure out how to do the appropriate 
math, and you can do it in five minutes :-)

**Comment by pbanaszkiewicz** [comment]
Yeah I don't think so (it's rather an hour for both of us) :-) anyway I'm not touching this until both:
* you fix https://github.com/swcarpentry/amy/pull/680#discussion_r51589402
* it's Wednesday

**Comment by gvwilson** [comment]
Done.

**Comment by pbanaszkiewicz** [comment]
Fixed in 45b55aa0153156a8c06b2243afa5095508985563.

**Comment by gvwilson** [comment]
Thanks dude.
