### ISSUE TITLE
Add CSV support for API

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#684]
All API calls that deliver JSON and YAML should also deliver CSV.

**Comment by pbanaszkiewicz** [comment]
https://github.com/mjumbewu/django-rest-framework-csv

**Comment by jduckles** [comment]
When trying to download the following from the API as CSV:
https://amy.software-carpentry.org/api/v1/reports/workshops_over_time/

I get a file that makes me think the CSV generate method isn't being run over the object, the object is just getting dumped.
```
<generator object _only_latest_date at 0x7f2f49cdebd0>
```

**Comment by pbanaszkiewicz** [comment]
@jduckles I'll add this as a bug issue.
