### ISSUE TITLE
Migrate views to class-based views

### ISSUE THREAD

**Issue by pbanaszkiewicz** [swcarpentry/amy#698]
Do this wisely.

For now it's enough if list views get migrated.

**Comment by gvwilson** [comment]
Have you ever left yourself a note saying "Do this unwisely"?  If not, 
why not?

**Comment by pbanaszkiewicz** [comment]
@gvwilson can one do something unwisely on purpose? It's rather either "wisely" or "quickly", isn't it?

**Comment by gvwilson** [comment]
Well, I've eaten an entire large bag of salt-and-vinegar potato chips 
more than once - I think that qualifies as "unwise" but "on purpose".

**Comment by pbanaszkiewicz** [comment]
Defer for now, we have more important issues for v1.8.

**Comment by pbanaszkiewicz** [comment]
Closing since we've been switching to CBV for a while now.
