### ISSUE TITLE
Replace Django's auth.User with our workshops.Person?

### ISSUE THREAD

**Issue by wking** [swcarpentry/amy#70]
I expect everyone in the database will want to log in to see their dashboard (listing upcoming workshops that they're on, or workshops in their area that need instructors or helpers), manage their personal information (new email, etc.), or register a new event.  We probably don't *two* person tables with many duplicate entries, so I'd recommend dropping the stock auth.User and [substituting][1] workshops.Person.

[1]: https://docs.djangoproject.com/en/1.7/topics/auth/customizing/#substituting-a-custom-user-model

**Comment by gvwilson** [comment]
I don't understand the scope of changes or resulting fragility if we use `workshops.Person` instead of `auth.User`.  If the answer is "small" and "not much", I'm +1.  If third-party authentication modules like OAuth expect `auth.user`, we should use `auth.User` for logins (since there are only a few) and `workshops.Person` for recording information about people.  @wking @craigmbooth can you please comment?

**Comment by wking** [comment]
On Wed, Jan 14, 2015 at 04:09:14AM -0800, Greg Wilson wrote:
> I don't understand the scope of changes or resulting fragility if we
> use `workshops.Person` instead of `auth.User`.

I haven't used AUTH_USER_MODEL in other projects yet, since the other
Django projects I'm involved were started in older versions of Django.
My understanding is that it will be a simple change, but (as mentioned
earlier in this issue) we can't migrate in or out of it, so we'll have
to ditch our existing migrations.

> If third-party authentication modules like OAuth expect `auth.user`,
> we should use `auth.User` for logins (since there are only a few)
> and `workshops.Person` for recording information about people.

As mentioned in the docs, this change should be transparent to any
libraries using get_user_model [1].  Craig suggested using
python-social-auth [2], which has an example using AUTH_USER_MODEL
[3], so I expect we can get it working for us too ;).

[1]: https://docs.djangoproject.com/en/1.7/topics/auth/customizing/#django.contrib.auth.get_user_model
[2]: https://github.com/omab/python-social-auth#id4
[3]: https://github.com/omab/python-social-auth/blob/v0.2.1/examples/django_example/example/settings.py#L201

**Comment by gvwilson** [comment]
1.  No problem ditching our current migrations.
2.  I'll trust you on everything else.

Thanks,
Greg

**Comment by wking** [comment]
Sane values for REQUIRED_FIELDS [1] are blocked on the blank stuff
that's in a753408 (Allowing several fields in a Person record to be
empty, #125).

[1]: https://docs.djangoproject.com/en/1.7/topics/auth/customizing/#django.contrib.auth.models.CustomUser.REQUIRED_FIELDS

**Comment by gvwilson** [comment]
Note that this is connected to #133 and possibly #41.

**Comment by pbanaszkiewicz** [comment]
Done in #182 and #181.
