### ISSUE TITLE
Instructor report broken

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#702]
1.  Go to https://amy.software-carpentry.org/workshops/reports/instructor_num_taught
2.  The entries in the table are URLs, not people.

**Comment by pbanaszkiewicz** [comment]
I've got some bad news for you… it's a feature, not a bug.

**Comment by gvwilson** [comment]
Fixable?  Because the report is pretty useless as-is.

**Comment by pbanaszkiewicz** [comment]
Depends. How would you like it to be?

The new API is hyperlinked and I'd like to keep it that way. Or really I'd like to have what GitHub [has](https://developer.github.com/v3/): a mix of hyperlinked and included objects (at once), but I'm unable to do it with [django-rest-framework](www.django-rest-framework.org) - or I just didn't find it.

So, Greg, can you go through the API and think what should be done and how? Thanks a lot.

**Comment by gvwilson** [comment]
I'd like to see user IDs rather than object numbers - I think 
`https://amy.software-carpentry.org/api/v1/persons/wilson_g/` should 
work as well as `https://amy.software-carpentry.org/api/v1/persons/8777/`.
