### ISSUE TITLE
Email addresses should not be case sensitive

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#705]
For example, these pairs should have been flagged as duplicates:

https://amy.software-carpentry.org/workshops/person/8955   and
https://amy.software-carpentry.org/workshops/person/8957

or

https://amy.software-carpentry.org/workshops/person/46
https://amy.software-carpentry.org/workshops/person/47

(I am going to merge them soon -- just wanted others to see these first)

**Comment by pbanaszkiewicz** [comment]
Unfortunately according to specs, the part before `@` is case-sensitive.

What about I add matching of similar emails to #624?

**Comment by gvwilson** [comment]
I think we should disregard the spec in this case and do 
case-insensitive matching - it's highly unlikely that 
'Greg@wherever.com' and 'gREG@wherever.com' are different people...

**Comment by narayanaditya95** [comment]
@pbanaszkiewicz @gvwilson 
My solution: Convert the part of email before the '@' to lower case in the `save()` method of the model layer. Run a migration that applies the same logic to all rows in the database.

Is this solution acceptable?

Reference: [17561](https://code.djangoproject.com/ticket/17561)

**Comment by pbanaszkiewicz** [comment]
@narayanaditya95 are there any field types that support case insensitivity? Event database-dependant?

**Comment by narayanaditya95** [comment]
> Event database-dependant?

Can you elaborate on this?

**Comment by pbanaszkiewicz** [comment]
>> Event database-dependant?
> Can you elaborate on this?

Maybe e.g. PostgreSQL can enforce case-insensitive uniqueness on some fields? Maybe it's supported by Django / some Django app?

**Comment by narayanaditya95** [comment]
I will get back to you.

**Comment by narayanaditya95** [comment]
@pbanaszkiewicz 
We can enforce case-insensitive uniqueness on the email field.

```sql
CREATE UNIQUE INDEX case_insensitive_email ON workshop_person (lower(email));
```
However, this enforces case insensitivity on the entire email field. To enforce it on the substring before the last `@` character, we will have to resort to regex.
The above functional index would force Django to throw `django.db.IntegrityError` whenever we try to save a person with the same email of different case.  
**Note:** We will still have to run a migration on the table to ensure that such a unique constraint can be applied on the table, i.e. we will have to filter/merge all emails that are case-insensitive.

**Comment by narayanaditya95** [comment]
@pbanaszkiewicz 

Another way to realize the same thing is using the [citext](http://www.postgresql.org/docs/current/static/citext.html) character string. It has been implemented [here](https://github.com/zacharyvoase/django-postgres/blob/master/django_postgres/citext.py).

**Comment by narayanaditya95** [comment]
@pbanaszkiewicz 
Is the proposed solution acceptable?

**Comment by pbanaszkiewicz** [comment]
@narayanaditya95 thank you for the research! I'm focusing on GSOC for now so let's not change the schema just yet.

**Comment by narayanaditya95** [comment]
Sure.
