### ISSUE TITLE
TODO's and due dates

### ISSUE THREAD

**Issue by gperu** [swcarpentry/amy#710]
When a due date is set for a TODO, then it would also be useful to get some sort of notifications somewhere, otherwise it's not easy to keep track of your TODO's. Even a simple page with an aggreagate list of TODO's would do the job.

**Comment by pbanaszkiewicz** [comment]
@gperu: You can see a list of upcoming TODOs in the timeline on top of the dashboard. Is it not showing up? Or do you perhaps need to view more than two weeks ahead?

**Comment by pbanaszkiewicz** [comment]
@gperu can you update on the status of this issue?
