### ISSUE TITLE
change language on workshop request form where hosts are saying how many learners they'll have

### ISSUE THREAD

**Issue by tracykteal** [swcarpentry/amy#729]
On the DC and SWC workshop request forms there's a section where the host is saying how many people will attend the workshop. It currently says

"This number doesn't need to be precise, but will help us decide how many instructors your workshop will need.

1-20 (one room, one instructor)"
...
"

but we don't have situations where we just send one instructor. We'd like to change that line to

"This number doesn't need to be precise, but will help us with logistics and to determine how many instructors your workshop will need."

1-20 (one room, two instructors)
...
"

**Comment by maneesha** [comment]
See PR #731

**Comment by jduckles** [comment]
Closing as it was addressed by #731
