### ISSUE TITLE
record other events, such as presentations, in Amy

### ISSUE THREAD

**Issue by tracykteal** [swcarpentry/amy#732]
This might be out of scope, but would it be possible to record other events than workshops in Amy. In particular, I'm thinking of talks or presentations that we or others in the community give. 

Then we would have a way of posting 'upcoming events' on our web sites, and also being able to keep track of them for reporting. 

#enhancement

**Comment by gvwilson** [comment]
I think that's out of scope for AMY, but we could echo events from the 
community calendar (a Google Calendar) into the web site.

**Comment by pbanaszkiewicz** [comment]
Anyone else having thoughts on this matter? @jduckles @maneesha @rgaiacs

**Comment by maneesha** [comment]
I agree with @gvwilson that it's out of scope for AMY... unless it's a talk/presentation directly about SWC or DC.  If it's a talk by someone affiliated with SWC or DC we could help promote it on another calendar (which I think does a lot to make our instructors feel supported by us) but I don't see a need for us to track it in AMY.

**Comment by jduckles** [comment]
I agree with @gvwilson. A calendar is the right tool for this kind of thing.

**Comment by pbanaszkiewicz** [comment]
Closing since the general opinion is these kinds of events should be tracked in calendar, not in AMY.
