### ISSUE TITLE
Event_sponsor table 

### ISSUE THREAD

**Issue by apawlik** [swcarpentry/amy#74]
As suggested by @wking in swcarpentry/site/pull/701 it would be useful to keep track of sponsorships for the workshops.

**Comment by pbanaszkiewicz** [comment]
I haven't seen workshops with sponsor details in their Notes field. @maneesha would you like to have an option to save workshop sponsors somewhere?

**Comment by gvwilson** [comment]
@maneesha @pbanaszkiewicz I propose closing this as stale.

**Comment by pbanaszkiewicz** [comment]
Will reopen if needed.
