### ISSUE TITLE
M2M relationship between host & person

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#747]
This is probably a big enhancement but it would be nice for any host to see what people are affiliated with it, and for any person, what host sites they are affiliated with.

**Comment by pbanaszkiewicz** [comment]
It's not that big to add this relationship, but it's a big deal to affiliate people with hosts by hand.

Will admins want to manually add link people with hosts?

**Comment by maneesha** [comment]
I agree it's an extra data entry step but I also think it will be useful to know for any host, what people we've worked with from there.  The  thing that will make this difficult to manage is that affiliations often change.  How do we want to manage this (on a human level & database design level)?

Perhaps @jduckles @tracykteal can weigh in?

**Comment by jduckles** [comment]
I tend to think this is more the purview of a CRM tool. Not necessarily AMY. A linkage between a CRM tool and AMY would be where I suggest we do this kind of thing.  For each host, if we had that as an organization in our CRM tool automatically we could link up related correspondence, negotiations and membership deals, closed or not to keep us abreast of backstory for each organization.

**Comment by gvwilson** [comment]
Keep open or close?

**Comment by maneesha** [comment]
It's up to @jduckles and @tracykteal

**Comment by jduckles** [comment]
Closing for now.
