### ISSUE TITLE
Update from URL should use repo OR site

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#757]
> Use the URL of the event's website, e.g. http://swcarpentry.github.io/workshop-template/, and not the URL of its GitHub repository.

Often the site is not hosted at username.githib.io (for many different reasons).   It would be easier if import from repo was an option.

**Comment by gvwilson** [comment]
We switched to importing data from <meta> elements in the <head> of the 
HTML page so that we could handle sites hosted off GitHub (e.g., EMBL).  
I agree that we should *not* depend on it being username.github.io.

**Comment by pbanaszkiewicz** [comment]
@maneesha and @gvwilson:
>Use the URL of the event's website, e.g. http://swcarpentry.github.io/workshop-template/, and not the URL of its GitHub repository.

This is just an example of URL that should be used. Actual code tries to read `<meta>` tags, as Greg wrote. But if it cannot read these tags, then it tries to guess link to the repository (which can only do from http://username.github.io/workshop/ ).

I'm planning on dropping this "hidden" support for repository tags (ie. from https://raw.githubusercontent.com/username/workshop/gh-pages/index.html) sometime soon, and then we'll only support website meta tags.
