### ISSUE TITLE
Self-organized DC workshop request form

### ISSUE THREAD

**Issue by tracykteal** [swcarpentry/amy#761]
Data Carpentry now has guidelines for self-organized workshops, and we'd like to have a separate self-organized workshop registration form for instructors to register a self-organized workshop and confirm that instructors will meet the self-organized workshop criteria
http://www.datacarpentry.org/self-organized-workshops/

I drafted a form that has the necessary fields. For fields that are the same as in the existing form, that same field is fine. I added a few fields that are just relevant for self-organized workshops and took out some that weren't relevant. 

https://docs.google.com/forms/d/1SHctDIQYLEDy139NNTKkgi0ctbMeh2zdE927hsWh1Ew/viewform

Can we make this a form in Amy, so the information goes in to the Amy system? I imagine some discussion will be needed to make sure the questions can match with the database structure. Let me know if a call would be helpful.

**Comment by pbanaszkiewicz** [comment]
@tracykteal the form you proposed differs from the current similar form for SWC (https://amy.software-carpentry.org/workshops/submit/). The existing form is rather intended for people to tell AMY that they've been running self-organized workshops, however I don't think anyone used that form ever :cry:

@maneesha please decide if you want to stick with the existing form or implement something similar to what @tracykteal proposed for DC.

**Comment by tracykteal** [comment]
Yes, this new form has a slightly different motivation, in that we want to make sure people are prepared to run self-organized workshops and that we get them registered. This is partly in response to the challenges @maneesha has seen with self-organized workshops. It also matches the process approved by the DC Steering Committee for self-organized workshops http://www.datacarpentry.org/self-organized-workshops/

**Comment by tracykteal** [comment]
Any update on this? Anything we can do to help?

**Comment by pbanaszkiewicz** [comment]
@tracykteal just to make sure: this new form is meant to replace https://amy.software-carpentry.org/workshops/submit/, correct?

**Comment by tracykteal** [comment]
No, it would be an additional form. We want to have one for hosts to request workshops and one for self-organized workshops, because they have different sets of questions.

**Comment by pbanaszkiewicz** [comment]
> We want to have one for hosts to request workshops and one for self-organized workshops, because they have different sets of questions.

We currently have 2 different forms for requesting a workshop:
* https://amy.software-carpentry.org/workshops/dc/request/
* https://amy.software-carpentry.org/workshops/swc/request/

We also have 1 form for informing admins about a possibly self-organized workshop that already has a webpage: https://amy.software-carpentry.org/workshops/submit/

I'm asking if the last one should be replaced with the new form since they both cover self-organized workshops and the existing form does not seem to be used.

**Comment by tracykteal** [comment]
Sorry, I was thinking about the regular form. The current 'Tell us about your workshop' form is the one that SWC I think is using, although I'm not sure if they're using it. @maneesha @jduckles?

I think SWC and DC do need different self-organized forms though. SWC is requesting the information either before or after the workshop, but DC is asking that people fill in this form and check the boxes that their workshop meets these requirements before they run the workshop.

**Comment by pbanaszkiewicz** [comment]
@tracykteal question about the form's field "Domain for the workshop". Is it attendees' domain of interest or is it Data Carpentry data set the organizer wants to use?

Question about "I confirm that I will handle registration for this workshop *" and "I confirm that I will distribute the Data Carpentry survey to participants *" fields - do they need to have an "other" as an answer?

I also need the reasons for the fee waiver, if it needs to be a choice list.

Thanks!

**Comment by pbanaszkiewicz** [comment]
@tracykteal is "Data wrangling" a different lesson than shell?

**Comment by tracykteal** [comment]
Thanks @pbanaszkiewicz I update the form at https://docs.google.com/forms/d/1SHctDIQYLEDy139NNTKkgi0ctbMeh2zdE927hsWh1Ew/edit 
to address these questions. 

I also added a question about 'Instructor status' (4th question) and the categories for Self-organized workshop fees. For the workshop waiver section, can we just leave it as free response? I want people to just address the fee waiver with a couple of sentences.

**Comment by pbanaszkiewicz** [comment]
@tracykteal thanks! I left the waiver section as a text box.

**Comment by tracykteal** [comment]
Great, thank you!

**Comment by pbanaszkiewicz** [comment]
Closing because #836 was merged

**Comment by tracykteal** [comment]
Thanks @piotr. I realize I haven't yet updated our website with the new AMY self-organized workshop form that you implemented here. What's the link?

**Comment by pbanaszkiewicz** [comment]
@tracykteal it's https://amy.software-carpentry.org/workshops/dc/request_selforganized/

**Comment by tracykteal** [comment]
Great, thank you!
