### ISSUE TITLE
Feature request: Notification system for newly announced workshops

### ISSUE THREAD

**Issue by simonthelwall** [swcarpentry/amy#763]
Some mechanism to be notified of newly announced Software Carpentry workshops in one's country would be very useful.

**Comment by pbanaszkiewicz** [comment]
@simonthelwall do you want to be notified as an instructor or as a participant?

**Comment by simonthelwall** [comment]
As a participant please. If you are building that functionality into the website, it might as well be added as a choice, perhaps multiselect checkboxes.

**Comment by pbanaszkiewicz** [comment]
@simonthelwall I'm not sure if there are many workshops run that allow anyone to sign in… @jduckles any thoughts on this request?

**Comment by gvwilson** [comment]
Part of #795
