### ISSUE TITLE
Allow instructors to notify admins about self-organizer workshop using AMY

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/amy#767]
Maybe on the lines of https://github.com/swcarpentry/amy/issues/761?

# Workflow

1. Lead instructor goes to https://amy.software-carpentry.org/workshops/.

![screen shot 2016-05-06 at 15 04 31](https://cloud.githubusercontent.com/assets/1506457/15075552/cdb072c2-139c-11e6-8bc3-631f4c601954.png)

2. Copy the address of the workshop page into the field and press "Submit".

3. Admin double check the information and enable the workshop to be available on the map.

**Comment by pbanaszkiewicz** [comment]
We have this feature already but nobody is using it :cry:

https://amy.software-carpentry.org/workshops/submit/

**Comment by rgaiacs** [comment]
I think it isn't well advertise.

**Comment by pbanaszkiewicz** [comment]
Banner on the front page of software-carpentry.org? :-) /cc @jduckles
