### ISSUE TITLE
Find instructors function only finding badged instructors?

### ISSUE THREAD

**Issue by tracykteal** [swcarpentry/amy#773]
In the More -> Find Instructors function, it seems like it's only finding people who are certified. That default makes sense, since instructors require certification. 

Sometimes we want to find all associated people in a given region though, to potentially contact as helpers or let them know a workshop is going on. Is there a way to search for all People associated with a given airport code?

**Comment by pbanaszkiewicz** [comment]
Yeah, we can make this form a little more universal.

**Comment by tracykteal** [comment]
Thanks, I think that would be useful. Maybe taking away the default filters and giving more filter options?

I think main queries are by airport and then we want to know if people are certified instructors, not-yet-certified instructors, helpers or learners. This will probably start to be even more important as we try to foster local communities.

**Comment by tracykteal** [comment]
Thanks!
