### ISSUE TITLE
Must-fix: chart of instructors vs. time is unusable

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#779]
I cannot show https://amy.software-carpentry.org/workshops/reports/instructors_over_time to people: the backward bends in the curve make it unbelievable. This has been raised before, but it must be fixed.
![screen shot 2016-05-15 at 5 26 26 pm](https://cloud.githubusercontent.com/assets/911566/15276884/72cdb658-1ac2-11e6-8624-900998069e88.png)

**Comment by chrismedrela** [comment]
@gvwilson, is using linear interpolation an option? PR: https://github.com/swcarpentry/amy/pull/783

**Comment by gvwilson** [comment]
@narayanaditya95 will tackle this
