### ISSUE TITLE
Add chart to frequency of instruction report

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#780]
https://amy.software-carpentry.org/workshops/reports/instructor_num_taught would be more useful if there were histograms showing how many people have taught how many times.

**Comment by pbanaszkiewicz** [comment]
Only histogram, no names?

**Comment by gvwilson** [comment]
Yup - the histogram is to copy/paste into presentation slides, and we don't want names in that.  If you're feeling adventurous, an option to display with/without names would be welcome :-)
