### ISSUE TITLE
Report on all activity should use hyperlinks for workshops

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#782]
On https://amy.software-carpentry.org/workshops/reports/all_activity_over_time, the references to workshops should be hyperlinks, not just plain-text slugs.

**Comment by gvwilson** [comment]
@narayanaditya95 will tackle this

**Comment by narayanaditya95** [comment]
Found this comment at `api/views.py` L409:

```
        # Workshops missing any of this data.
        # There's no point in using hyperlinks here, because it would:
        # a) require using reverse() unless we somehow managed to switch to
        #    serializer for this view
        # b) make JS part even harder (what is available right now just works)
```

@pbanaszkiewicz How should I proceed in this?

**Comment by narayanaditya95** [comment]
Found this comment at `api/views.py` L409:

```
        # Workshops missing any of this data.
        # There's no point in using hyperlinks here, because it would:
        # a) require using reverse() unless we somehow managed to switch to
        #    serializer for this view
        # b) make JS part even harder (what is available right now just works)
```

@pbanaszkiewicz How should I proceed in this?

**Comment by pbanaszkiewicz** [comment]
The easy fix would be to return links in API and I'd go with it.

**Comment by gvwilson** [comment]
As a human user of the site, I want to be able to click on the slug for a workshop in the list at the bottom of the page reporting problems and be taken to the page for that workshop.

**Comment by narayanaditya95** [comment]
@pbanaszkiewicz 
If we do not plan on extending the all activity report, such that level 3 of the response only corresponds to event slugs, we can construct hyperlinks on the client side (hardcoding here).

Should we go that way?

**Comment by pbanaszkiewicz** [comment]
@narayanaditya95 sorry for not answering to your question earlier. I'm kind of out-of-loop here, so I suggest we postpone this issue to v1.8 and to you I say use your best judgement.

**Comment by chrismedrela** [comment]
PR #1060.
