### ISSUE TITLE
Data access for instructor teaching assessment

### ISSUE THREAD

**Issue by ErinBecker** [swcarpentry/amy#785]
Hi all,

As part of the discussion about how best to get trainees through check-out and instructors into teaching, I'm trying to do a little assessment of where the choke-points are (i.e. where people are getting stuck).

I'd like to be able to pull some data out of amy and have been looking at the reports, but don't see anything that gives me the type of data I want. Was hoping someone could help.

What I'd like to have is:
For each instructor: 
- date of their training (can just be training event slug)
- whether training was online or not (unless this info is already in the slug)
- how many workshops they've taught up to now
- dates and locations of workshops they've taught (again, can be just the event slugs)
- instructor's home location

I'm not sure whether trainees who have gone through IT but not through check-out yet are in amy, but if so, would love to also have the above data for them (would just be date of training and location) + 
- what stages of checkout they've completed with dates

Any guidance/help on how to go about getting this info would be greatly appreciated!

Thanks,
Erin

**Comment by maneesha** [comment]
We do record the first five bullets you listed in AMY (with the caveat that home location = the nearest airport they gave us, if any).  It's not in a prebuilt query but we can generate that query.  @pbanaszkiewicz ?

I believe that the last bullet - stages of checkout - is still being held in Google docs.  @gvwilson can probably verify.

**Comment by ErinBecker** [comment]
Thanks Maneesha. "Home location" doesn't need to be exact. Going to use that to check and see if people mostly teach local workshops, so nearest airport should be fine.

**Comment by gvwilson** [comment]
@pbanaszkiewicz can you please modify an existing report or command extension to get @ErinBecker the data she needs?

**Comment by pbanaszkiewicz** [comment]
@gvwilson sure, I'll do that, but I'm already running out of breath this week – so no sooner than Thursday or even Friday.

BTW I'd like to point out that we don't have a lot of trainees with home locations in the DB (4 right now).

**Comment by gvwilson** [comment]
> BTW I'd like to point out that we don't have a lot of trainees with 
> home locations in the DB (4 right now).
Yup - we're going to start asking them to fill in the personal info form 
*before* training instead of after completion.

**Comment by pbanaszkiewicz** [comment]
@ErinBecker is this issue still valid after you gained the direct access to the database?

**Comment by ErinBecker** [comment]
@pbanaszkiewicz I think I have access to everything I need now. Thanks Piotr!

**Comment by pbanaszkiewicz** [comment]
You're welcome!
