### ISSUE TITLE
Frequency of teaching report is wrong

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#787]
https://amy.software-carpentry.org/workshops/reports/instructor_num_taught reports that Jonah Duckles has taught 26 times - I don't believe that's correct given our current database.

**Comment by jduckles** [comment]
It seems to be doubling everything, I've taught 13 times, or will after the June workshop I'm scheduled to teach.

**Comment by pbanaszkiewicz** [comment]
Some of the records are okay, ie. I taught 4 times according to my profile and that report reports 4 for me.

**Comment by jduckles** [comment]
![image](https://cloud.githubusercontent.com/assets/119403/15410088/880a2bdc-1ddd-11e6-89dc-36cf77642eff.png)

I've taught 13 time, the report double counts. 

![image](https://cloud.githubusercontent.com/assets/119403/15410118/ab3338b0-1ddd-11e6-9db1-6b9cf8f98024.png)

My unfounded hypothesis is it has to do with having both DC and SWC instructor badges and the way you're joining things.

**Comment by pbanaszkiewicz** [comment]
@jduckles you're definitely right. I gave myself a DC badge and my count jumped from 4 to 8.

**Comment by gvwilson** [comment]
@narayanaditya95 will tackle this
