### ISSUE TITLE
#775 lacks all_trainings.html file

### ISSUE THREAD

**Issue by chrismedrela** [swcarpentry/amy#789]
I've accidentally untracked this file when force-updating PR.

**Comment by gvwilson** [comment]
I'm sure you'll know lots more about Git by the time you recover it ;-)

**Comment by chrismedrela** [comment]
:)

PR: https://github.com/swcarpentry/amy/pull/791

**Comment by gvwilson** [comment]
That'll work too - please go ahead and merge.

**Comment by chrismedrela** [comment]
Merged https://github.com/swcarpentry/amy/pull/791.
