### ISSUE TITLE
Should we remove 'null=True' from all CharFields?

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#790]
https://docs.djangoproject.com/en/1.9/ref/models/fields/#django.db.models.CharField suggests that CharField shouldn't use null=True, but instead should use blank=True.

**Comment by pbanaszkiewicz** [comment]
I agree, a default of `''` is better than None for char fields.

**Comment by gvwilson** [comment]
@narayanaditya95 will tackle this

**Comment by narayanaditya95** [comment]
@pbanaszkiewicz 

From `workshops/models.py` L231
```py
    github      = models.CharField(max_length=STR_MED, unique=True, blank=True, default='')
    twitter     = models.CharField(max_length=STR_MED, unique=True, blank=True, default='')
```

Allowing fields to go null while enforcing them to be unique seems contradictory to me. What should we populate the existing rows in the table with the `github` and `twitter` field as null?

**Comment by pbanaszkiewicz** [comment]
@narayanaditya95 is this the only place where we such constraints, ie. `unique=True, null=True, blank=True`?

**Comment by narayanaditya95** [comment]
A preliminary search threw these instances:
`workshops/model.py`
```py
class Event(models.Model):
    slug       = models.CharField(max_length=STR_LONG, null=True, blank=True, unique=True)
    url = models.CharField(
        max_length=STR_LONG, unique=True, null=True, blank=True,
        validators=[RegexValidator(REPO_REGEX, inverse_match=True)],
        help_text=PUBLISHED_HELP_TEXT +
                  '<br />Use link to the event\'s <b>website</b>, ' +
                  'not repository.',
    )

class Person(models.Model):
    email       = models.CharField(max_length=STR_LONG, unique=True, null=True, blank=True)
    github      = models.CharField(max_length=STR_MED, unique=True, null=True, blank=True)
    twitter     = models.CharField(max_length=STR_MED, unique=True, null=True, blank=True)
```

**Comment by pbanaszkiewicz** [comment]
@narayanaditya95, @gvwilson:

1. `Event.slug` should become non-null, non-blank, unique (we have only 1 event with NULLed slug, thanks to @maneesha who keeps them filled)
2. `Event.url` should remain null, blank, unique, validated with custom Regex
3. `Person.email` should probably become non-null, non-blank -- this is standard for non-learners to have an associated email, but we have about 470 people who don't have any email. @gvwilson thoughts?
4. `Person.github` and `Person.twitter` unfortunately will have to remain null and blank, I don't see any other option here…

**Comment by pbanaszkiewicz** [comment]
@maneesha decided that `Event.slug` must not be NULL nor blank.
