### ISSUE TITLE
Add checkbox and link to privacy policy when people fill out `update_profile/`

### ISSUE THREAD

**Issue by jduckles** [swcarpentry/amy#792]
We should have a checkbox that says "I have read and agree to the privacy policy" http://software-carpentry.org/privacy/ when people fill out their profile updates.

**Comment by gvwilson** [comment]
More specifically, wherever people can enter information about themselves (profile update, applying for training), there needs to be a checkbox saying:

~~~
[] I have read and agree to <a href="http://software-carpentry.org/privacy/">the Software Carpentry Foundation's data privacy policy</a>. 
~~~
