### ISSUE TITLE
Invoice status: change some options

### ISSUE THREAD

**Issue by pbanaszkiewicz** [swcarpentry/amy#793]
- Paid - Feedback loop
- Invoiced - Request has been made (change to Invoice requested)
- Not Invoiced - Request has not been made (change to Invoice not requested)

**Comment by chrismedrela** [comment]
Sorry, but I don't understand what this issue is all about? Do you mean changing `InvoiceRequest.STATUS_CHOICES`?

**Comment by pbanaszkiewicz** [comment]
@chrismedrela this is about both `InvoiceRequest` (feedback to "paid" `Event.invoice_status`) and `Event.invoice_status`. Low priority for now.

**Comment by chrismedrela** [comment]
I'm still not sure what exactly changes are requested, so could I reassign this issue to you?

**Comment by maneesha** [comment]
We want to change the labels for the options in invoice status.
Clarifying what @pbanaszkiewicz  noted in his opening comment above:

- Change `Invoiced` to `Invoice requested`
- Change `Not invoiced` to `Invoice not requested`

`Unknown` and all the `Not applicable` options can stay as they are.

Adding `Paid` is not a priority.

**Comment by chrismedrela** [comment]
@maneesha, thank you, that makes it clear.
