### ISSUE TITLE
Numbers of learners, workshops, etc just for SWC or DC?

### ISSUE THREAD

**Issue by tracykteal** [swcarpentry/amy#794]
Is there the capability to get the number of workshops, learners, instructors, etc separated by SWC and DC?  This might be a common need, so worth implementing.

**Comment by pbanaszkiewicz** [comment]
@tracykteal are you asking:

1. for a report?
2. for a separate AMY just for seeing DC-only related data?

**Comment by tracykteal** [comment]
Just a report. Currently there's not a filter for selecting numbers for learners/workshops/instructors of a particular type I don't think. It would be nice to be able to look at reports for how many people went through DC workshop, or SWC workshops or TTT events.

**Comment by gvwilson** [comment]
Replaced by #842.
