### ISSUE TITLE
Show how often taught on instructor page

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#799]
Results of this report https://amy.software-carpentry.org/workshops/instructors_by_date
show often each instructor has taught.

This number should also display at bottom of Task list on each instructor profile page.

**Comment by gvwilson** [comment]
@narayanaditya95 will tackle this

**Comment by narayanaditya95** [comment]
@maneesha Would you like me to list the number of times the person has assumed all possible roles or are we only interested in role of an instructor.

**Comment by gvwilson** [comment]
Please list instructor / helper / learner - the first is the most 
important, the second is useful, and the third tells us how they got 
started.

**Comment by pbanaszkiewicz** [comment]
@narayanaditya95 you can help yourself with this annotation https://github.com/swcarpentry/amy/pull/776/files#diff-ff40cc33cf5228ac8b825f8d4f9ef9b8R1662 however be sure to test if it yields good results because we have issues with it.
