### ISSUE TITLE
Add functionality to merge workshop request with existing workshop

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#800]
So if someone emails an admin about a workshop and they record it in AMY but then submits the same workshop  via the form (https://amy.software-carpentry.org/workshops/swc/request/) I would like to merge them.

See workshop https://amy.software-carpentry.org/workshops/event/2016-05-17-ucsd
and request  https://amy.software-carpentry.org/workshops/request/100
as an example.

**Comment by pbanaszkiewicz** [comment]
Hello @maneesha, having looked at this issue, I have a few questions for you.

1. When a new workshop request comes in, do you accept it and create a new event from this page: "https://amy.software-carpentry.org/workshops/request/XXX/accept/" (screenshot below)?

2. Would it be enough if a link between existing event request and existing workshop was created? There's not many overlapping fields between these models so merging one into the other may not have sense.

**Comment by pbanaszkiewicz** [comment]
See #1179.
