### ISSUE TITLE
Write tests for trainings dashboard

### ISSUE THREAD

**Issue by chrismedrela** [swcarpentry/amy#802]
At least one test that checks that the trainings dashboard loads successfully (status_code == 200).

**Comment by pbanaszkiewicz** [comment]
@chrismedrela why did you close this issue? Is it solved? If so, where?

**Comment by chrismedrela** [comment]
No, it's not solved yet, Greg asked me to close this issue, probably because I'm working on writing tests  for the next few days, so this will be fixed soon. @gvwilson, did I guess correctly or did I misunderstand you?

**Comment by gvwilson** [comment]
My fault for not explaining clearly: I meant "close" as in "do the work to close it". I would say "English is a sloppy language", but in this case, it's operator error.

**Comment by chrismedrela** [comment]
Sorry, I've just realized that we actually do have such test here: https://github.com/swcarpentry/amy/blob/develop/workshops/test/test_landing_page.py#L51, so I'm closing it. :)
