### ISSUE TITLE
Automating emails to instructors about discussion sessions

### ISSUE THREAD

**Issue by tracykteal** [swcarpentry/amy#803]
Somewhat related to https://github.com/swcarpentry/amy/issues/516, @maneesha, @ChristinaLK and I decided that it would be good to automate sending out the emails before and after their workshops letting them know that instructor discussion meetings are coming up. 

@ChristinaLK has proposed these emails 
https://github.com/swcarpentry/board/pull/117

Can we automate this going to out to instructors who will soon be teaching and who have just taught?

@maneesha & @ChristinaLK can you provide what would be the appropriate timing before and after the scheduled workshops?

Also, how will the (date) and (date) sections be automatically filled in? Will we need to enter discussion meeting times in AMY? Currently they are listed on an ether pad: http://pad.software-carpentry.org/instructor-discussion

**Comment by maneesha** [comment]
I think the dates need to be manually filled in.  While we want as consistent a schedule as possible there will occasionally be some adjustments made.

These should go out weekly to everyone who is going to teach in the next 6-8 weeks or has taught in the last 6-8 weeks.

**Comment by ChristinaLK** [comment]
@pbanaszkiewicz , @chrismedrela , what information do you need from me/us to implement this feature?  Let me know and I can try to fill in the blanks here.

**Comment by gvwilson** [comment]
Becomes part of #795
