### ISSUE TITLE
Website validation gives incorrect answer for empty fields

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#813]
1.  Go to https://amy.software-carpentry.org/workshops/event/2016-07-11-ttt-scipy.
2.  Click 'validate event'.
3.  Error message reports 'helper' and 'eventbrite' are invalid.

Both are present, but empty.

**Comment by pbanaszkiewicz** [comment]
If `helper` is empty, it's invalid.

The behavior for `eventbrite` is slightly off, I'll fix it.

**Comment by gvwilson** [comment]
But `helper` can legitimately be an empty list, can't it? If there 
weren't any helpers?
