### ISSUE TITLE
Move user-facing forms to separate URL endpoint amy.swc.org/forms

### ISSUE THREAD

**Issue by pbanaszkiewicz** [swcarpentry/amy#816]
This is to simplify URLs we can use in the administrative part of AMY.

User-facing forms: forms that don't require people to log in, like workshop submission, profile update request, etc.

**Comment by chrismedrela** [comment]
@pbanaszkiewicz , BTW what's the point of using namespaces in URLs? Would not it be simpler if we had a "flat namespace":

- `login` instead of `account/login` 
- `admin-dashboard` instead of `workshops/admin-dashboard`
- and so on.

**Comment by pbanaszkiewicz** [comment]
@chrismedrela I want to have external forms at `amy.swc.org/forms`, AMY-administering stuff under `amy.swc.org/workshops`, account-related perhaps under `amy.swc.org/account`, etc.

We don't use namespaces much since we have very few applications.

**Comment by chrismedrela** [comment]
@pbanaszkiewicz Yes, we don't use namespaces much, so what if we don't use namespaces at all? We have control over all urls, so there is no risk of URL collision.

**Comment by pbanaszkiewicz** [comment]
Okay, I'm confused. What namespaces are you talking about? Did I mention namespaces somewhere? What was the context?

I just want to have a separate "URL subtree" (if you look at the URLs as a tree) for stuff that is accessible by any non-logged in person.

**Comment by chrismedrela** [comment]
When I say namespace, I mean using subtrees in the URLs tree. I propose to change i.e. `WhateverAmyDomainIs.com/account/login` to `WhateverAmyDomainIs.com/login`.
