### ISSUE TITLE
Segfaults when running tests on OS X

### ISSUE THREAD

**Issue by narayanaditya95** [swcarpentry/amy#820]
On OS X El Capitan with the latest SQLite version `3.13.0 2016-05-18 10:57:30`, `make test` throws

```
Creating test database for alias 'default'...
....................................F.......make: *** [test] Segmentation fault: 11
```

The segfaults disappeared for a while when SQLite was upgraded from 3.8 to 3.13.
I have been using my laptop on Ubuntu to run tests.

**Comment by gvwilson** [comment]
Which test causes the segfault?

**Comment by narayanaditya95** [comment]
How do I locate it? The tests exit without any log.

**Comment by pbanaszkiewicz** [comment]
@narayanaditya95 any update on this issue?

**Comment by narayanaditya95** [comment]
@pbanaszkiewicz 
This issue is random. When it starts to fail, it fails for days altogether.
Currently, it does not fail on my machine.

Well, I haven't been able to replicate the issue for a week or two. Lets close the issue.

**Comment by pbanaszkiewicz** [comment]
@narayanaditya95 it may mean that some specific data corrupted your database. That's a very peculiar issue, anyway.
