### ISSUE TITLE
Language support in various forms

### ISSUE THREAD

**Issue by pbanaszkiewicz** [swcarpentry/amy#822]
Some of our forms (profile update form and probably instructor application form) need to be updated after #798 is merged.

**Comment by pbanaszkiewicz** [comment]
@narayanaditya95 @chrismedrela do you perhaps know which forms we need to update to store the language?

**Comment by chrismedrela** [comment]
#798 introduces:
- changes in models:
  - `EventRequest.languages` converted from string to `Language` ref
  - added `Person.languages`
  - added `Event.language`
  - added `EventRequest.language`

- changes in views:
  - `event_details_table.html`
  - `person_details`
  - `workshop_staff` (searching by language)

- changes in forms:
  - added `WorkshopStaffForm.languages`
  - added `PersonForm.languages`
  - added `SWCEventRequestForm.language`

- other:
  - added `LanguageLookup`

So we need to update:
- `PersonsMergeForm` 
- `ProfileUpdateRequestFormNoCaptcha`
- `EventsMergeForm`
- maybe `TrainingRequestForm`?
