### ISSUE TITLE
Person without email causes attribute error

### ISSUE THREAD

**Issue by pbanaszkiewicz** [swcarpentry/amy#840]
In `Person.clean()`, `self.email` can be None.

**Comment by prerit2010** [comment]
@pbanaszkiewicz  Can you  please elaborate how to reproduce this bug ? I created a new person with no email id, but it didn't throw any error.

**Comment by pbanaszkiewicz** [comment]
@prerit2010 I found it when I was changing permissions for a person without email.

**Comment by pbanaszkiewicz** [comment]
Closed via #841.
