### ISSUE TITLE
Parameterize queries with start/end dates and workshop type

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#842]
The reports for workshops over time, learners over time, and instructors over time should take start/end dates and type (SWC vs. DC) as query parameters so that interested parties can fetch the information they want more easily. cc @tracykteal

**Comment by gvwilson** [comment]
See also #794 which requested fetching stats by workshop type (SWC vs. DC).

**Comment by tracykteal** [comment]
I've since found the 'All reports' section and that information is available. @jduckles also showed me the API interface, so we can access other statistics. I think we can close this.
