### ISSUE TITLE
Assign admin when creating new event

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#847]
You should be able to assign admin from this page:
https://amy.software-carpentry.org/workshops/events/add/

Right now you can't assign admin until you save and edit.

**Comment by narayanaditya95** [comment]
@maneesha 
When you say 'admin`, do you refer to the field `administrator` that relates to a host or the `assigned to` field that links to a person?

**Comment by maneesha** [comment]
This refers to `assigned_to`  -- so that I can assign an event to myself when creating it.

**Comment by pbanaszkiewicz** [comment]
The issue here is that current assignment machinery works on existing objects, and @maneesha wants to assign admins when the event is not yet created.

We should be able to achieve that by extending event form with assignment field.
