### ISSUE TITLE
Nav bar on password update page styled differently from elsewhere

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#854]
The navigation bar on the "change password" page is narrow than the bar on all the other pages. Inside the wrong div, maybe?

**Comment by chrismedrela** [comment]
There are other pages where nav bar is narrow. I don't see any rule. @pbanaszkiewicz, when `base_nav_fixed.html` and `base_nav_fluid.html` should be used? Could we stick one with them and get rid of the another?

**Comment by pbanaszkiewicz** [comment]
The rule was "if the page is wide, a wide navbar should be used", e.g. all pages with filters are wide and (probably) all object-details pages use narrow navbar.

**Comment by pbanaszkiewicz** [comment]
I'd dismiss this issue because there are other pages with navbar styled in the same way as on the "change password" page -- @gvwilson ?
