### ISSUE TITLE
Unset variable on Host detail page

### ISSUE THREAD

**Issue by narayanaditya95** [swcarpentry/amy#858]
If a `Membership` object has the field `workshops_without_admin_fee_per_year` set to null, the corresponding `host_detail` page shows `None` in the imposed column and `xxx-unset...` in the remaining column of the Membership table.

**Comment by narayanaditya95** [comment]
@pbanaszkiewicz 
All `Membership` objects have non-null `workshops_without_admin_fee_per_year` field.
Should we enforce `null=False` on the `workshops_without_admin_fee_per_year` field to circumvent the issue?

**Comment by gvwilson** [comment]
Can someone please either close or implement?

**Comment by pbanaszkiewicz** [comment]
@narayanaditya95 I think we need to add a `|default:"—"` to the template so that `xxx-unset…` disappears.
