### ISSUE TITLE
After logout, redirect to the login page with a message

### ISSUE THREAD

**Issue by pbanaszkiewicz** [swcarpentry/amy#867]
I'd work on this for v1.6.1, but as it turns out Django changes auth views (we use them for login / logout) in the v1.11 release, so if we wait a little we may get a better implementation.

**Comment by gvwilson** [comment]
Any progress?

**Comment by chrismedrela** [comment]
Django 1.10 introduces [LOGOUT_REDIRECT_URL](https://docs.djangoproject.com/en/1.10/ref/settings/#logout-redirect-url), so this may be trivial change if we upgrade from Django 1.9.

**Comment by gvwilson** [comment]
@pbanaszkiewicz any thoughts on upgrading to Django 1.10?

**Comment by pbanaszkiewicz** [comment]
Will do, especially since Django 1.10 [was recently released](https://www.djangoproject.com/weblog/2016/aug/01/django-110-released/), but not yet.
