### ISSUE TITLE
Feedback on the training request form

### ISSUE THREAD

**Issue by pbanaszkiewicz** [swcarpentry/amy#873]
Feedback:

- [x] @maneesha: show that mandatory checkboxes are mandatory
- [x] @maneesha: fix wording on the confirmation page ("thank you for applying")
- [x] @jduckles: drop "institutional" from "institutional affiliation"
- [ ] @jduckles: fix intro (manage expectations)
- [x] @jduckles, @tracykteal: decide what this form is for (open training / partner training / group training)
- [x] @tracykteal, @ErinBecker: "personal name" → "first name"? "family name" → "last name"? Or "Personal (given) name", "Family name / surname" (**COMMENT** @pbanaszkiewicz: we may want to change this on all our forms / templates)
- [x] @tracykteal: add field for explanations to the "previous training in teaching", "previous experience in teaching"
- [x] @ErinBecker: fix time estimate in the intro ("2h" → "8-10h")
- [x] @ErinBecker: fix wording for location: "please give city, province or state" → "please give city, and
province or state if applicable"
- [x] @ErinBecker: add alphabetical sorting to the areas of expertise (this will affect other forms as well)
- [x] @ErinBecker: "previous training in teaching" should have additional option between "a few days" and "a full degree", for example "a certification or short course"
- [x] @ErinBecker: change options for "How frequently do you program", eg. "hourly/daily/weekly/monthly/not consistently (less than monthly)/never or almost never"  (**COMMENT** @pbanaszkiewicz: I'd go with "every day / a few times a week / a few times a month / a few times a year / never or almost never")
- [x] @ErinBecker: drop "classes" from  "how often would you expect to teach classes . . . or workshops"
- [x] @ErinBecker: add Data Carpentry to the "I agree to abide by" checkbox
- [x] @ErinBecker: help text in the "I agree to complete this training within three months of the Training Course" checkbox uses wrong estimate of 2h again (should be 8-10h)
- [x] @chrismedrela: add GitHub field

**Comment by pbanaszkiewicz** [comment]
@chrismedrela any progress on this issue? The milestone was supposed to be closed on Monday/Tuesday.

**Comment by chrismedrela** [comment]
@pbanaszkiewicz Oops, I didn't notice the milestone deadline and I focused on other stuff. I'll try to do this today. One question: What exactly do I need to change in the intro?

**Comment by pbanaszkiewicz** [comment]
Leave the intro as it is until @jduckles says if he can improve it.

**Comment by chrismedrela** [comment]
Questions:

1) Do we need to link to both SWC and DC Code of Conduct?
2) `add field for explanations to the "previous training in teaching", "previous experience in teaching"` <- I don't understand this; there is already a charfield for "other" option
3)  `decide what this form is for (open training / partner training / group training)` <- right now it's for all kinds of training; what exactly should I do?

**Comment by chrismedrela** [comment]
4) I made "GitHub field" optional, because people may not have GitHub account when they fill in the form. Is it good decision? What will we do with TrainingRequests missing GitHub username when we approve them (we need to somehow let people login into AMY).

**Comment by gvwilson** [comment]
On 2016-07-07 2:41 PM, chrismedrela wrote:

> Questions:
>
> 1) Do we need to link to both SWC and DC Code of Conduct?
>
Yes.
>
> 2) |add field for explanations to the "previous training in teaching", 
> "previous experience in teaching"| <- I don't understand this; there 
> is already a charfield for "other" option
>
@tracykteal would like people to be able to choose one of our pre-set 
options *and* provide a longer text explanation, even if it's one of the 
standard (non-"other") choices.
>
> 3) |decide what this form is for (open training / partner training / 
> group training)| <- right now it's for all kinds of training; what 
> exactly should I do?
>
No action required.
Thanks,
Greg

**Comment by gvwilson** [comment]
On 2016-07-07 2:43 PM, chrismedrela wrote:

> 4) I made "GitHub field" optional, because people may not have GitHub 
> account when they fill in the form. Is it good decision?
>

I think it's a necessary one.

> What will we do with TrainingRequests missing GitHub username when we 
> approve them (we need to somehow let people login into AMY).
>
We tell them to create a GitHub account and send it to us and we add it 
and then they can log in.
Cheers,
Greg

**Comment by chrismedrela** [comment]
@pbanaszkiewicz, I'm sorry for fixing this so late, I've got stuck on fixing tests.

**Comment by gvwilson** [comment]
Always happy to have fixes to tests - thanks.

**Comment by pbanaszkiewicz** [comment]
@gvwilson can you perhaps provide us with a better intro text?

**Comment by gvwilson** [comment]
I'll poke @jduckles again.

**Comment by pbanaszkiewicz** [comment]
@gvwilson should we proceed without the improved text?

If not, @chrismedrela here's what @jduckles said:

> Is this specifically for the open trainings? Or for partner trainings and open trainings?  The tone of the intro makes it seem like you will for-sure eventually get the training if you fill out the form. We should not set that expectation as we know we can't meet it.

@chrismedrela if you can make another intro out of these words, I'd be glad - I want to close v1.6.3 ASAP.

**Comment by gvwilson** [comment]
Hi both,
I'll try to get you something tonight.
Cheers,
Greg

**Comment by jduckles** [comment]
Don't know where you want this, so I'll just put it here.

Our instructor training classes are for people who wish to learn how to teach
Software Carpentry and Data Carpentry workshops. We teach impactful pedagogical
techniques and prepare you to become an instructor in our community. We use this
form to register interest and build new communities of instructors around the
world. 

 If you wish to apply to our open instructor training program, please fill in
 the form below. Tell us about yourself, what excites you about teaching, how
 Software and Data Carpentry can help in your community. Spaces are limited, so
 use this form to share with us what excites you about spreading our teaching to
 your organization. We will notify applicants as limited spaces become
 available. If you have any questions, please mail <a
 href="mailto:training@software-carpentry.org">training@software-carpentry.org</a>.

 If you would like to accelerate the process, check out our <a
 href="http://software-carpentry.org/scf/join/">Partnership</a> program.
 Organizational partners make ongoing commitments to supporting our organization
 and are prioritized for instructor training. If you need help making the case
 at your organization, feel free to contact us at <a
 href="mailto:partnerships@software-carpentry.org">partnerships@software-carpentry.org</a>,
 we'd be happy to help.

**Comment by pbanaszkiewicz** [comment]
Thanks @jduckles!

@chrismedrela can you put that in some PR, please?

**Comment by chrismedrela** [comment]
@pbanaszkiewicz , ping.

**Comment by pbanaszkiewicz** [comment]
Finally!
