### ISSUE TITLE
Steering Committee members aren't allowed into AMY

### ISSUE THREAD

**Issue by pbanaszkiewicz** [swcarpentry/amy#876]
All access apart from AutoUpdateProfile is allowed only for admins, and people from Steering Committee have "steering committee" group which is not considered admin.

The workaround for now is that I'll add SC members to the "administrators" group.

**Comment by chrismedrela** [comment]
@pbanaszkiewicz, so do you want to change `@admin_required` so that it checks if a user belongs to `administator` group or `steering committee` group?

**Comment by pbanaszkiewicz** [comment]
@chrismedrela the `@admin_required` should be extended to cover "steering committee" group as well.
