### ISSUE TITLE
Recording point of contact for organizations

### ISSUE THREAD

**Issue by narayanaditya95** [swcarpentry/amy#888]
PyData records a `contact_name` and `contact_email` for every sponsor organization.

@pbanaszkiewicz @gvwilson How does SWC/DC contact organizations?

**Comment by pbanaszkiewicz** [comment]
@maneesha question for you?

**Comment by narayanaditya95** [comment]
@maneesha Can you provide me with an answer to the above question?

**Comment by maneesha** [comment]
We don't have contacts with organizations documented in AMY now.  I feel like I remember another github issue about this where @jduckles said he didn't want to prioritize this but I could be making this up :) .  I will look for it shortly.

**Comment by maneesha** [comment]
I think this is what I was thinking of: https://github.com/swcarpentry/amy/issues/747

**Comment by jduckles** [comment]
I'm ok with us managing limited contact info up to the point that we don't feel like AMY is our own custom reimplementation of a full-on Customer Relationship Manager (CRM).  

We've been using Highrise as our CRM and I think it might be pretty easy to add extended info for contacts to it. So we could capture name, email for host organizations and store any extended attributes in a CRM record that is linked to the AMY record.

**Comment by narayanaditya95** [comment]
Thank you @jduckles.

**Comment by narayanaditya95** [comment]
@gvwilson @pbanaszkiewicz 
To allow us to record that point of contact for an org in each sponsorship agreement (as required for PyData), I wish to add a `ForeignKey` to a Person object from the Sponsorship model. This would make things simple for PyData hosted AMY.

Is this change acceptable? Your opinions please.

**Comment by gvwilson** [comment]
:+1: from me.

**Comment by pbanaszkiewicz** [comment]
@narayanaditya95 if it doesn't require admins/whoever to manually add `Person` and then manually link to a `Sponsorship`, then it works for me too.
