### ISSUE TITLE
Use Python's logging module for debugging

### ISSUE THREAD

**Issue by wking** [swcarpentry/amy#89]
Instead of sprinking `print` calls around.  For example, see 54dea37 (workshops/templatetags/breadcrumbs.py: Use logging for debugging output, 2014-12-18) and the [Django docs][1].

[1]: https://docs.djangoproject.com/en/1.7/topics/logging/#using-logging

**Comment by gvwilson** [comment]
can this one now be closed?

**Comment by pbanaszkiewicz** [comment]
Yup. Will reopen if necessary.
