### ISSUE TITLE
Blank usernames allowed for the first time

### ISSUE THREAD

**Issue by narayanaditya95** [swcarpentry/amy#896]
`Person.objects.create(personal='name', family='surname', email='person@example.com')` creates a new row in the Person table with blank `username` field.

However, according to Django doc,

>Field.blank
>If True, the field is allowed to be blank. Default is False.

The default behaviour should be false.

Subsequent addition of rows with blank `username` field result in IntegrityError.

**Comment by pbanaszkiewicz** [comment]
That's bizarre, the definition of `Person.username` uses `blank=False` implicitly, right?

**Comment by narayanaditya95** [comment]
Yes, it does.
Adding `blank=True` to the definition does not initiate a migration.

**Comment by pbanaszkiewicz** [comment]
@narayanaditya95 Adding `blank=True` does trigger the migration for me (tested on `master` branch), while `blank=False` doesn't.

**Comment by pbanaszkiewicz** [comment]
Anyway, the issue seems that Django doesn't enforce validation upon `Person.objects.create`, for example in `Person.objects.create(personal='ASD', family='DSA', email='WSAD')` "WSAD" seems to be a perfectly valid email…

**Comment by narayanaditya95** [comment]
@pbanaszkiewicz Sorry I meant the opposite. Yes, adding `blank=False` does not initiate a migration.

Anyway, neither do `save` or `create` methods invoke any validation check, we have to resort to `full_clean()`.
Closing the issue as it is an expected behaviour.
