### ISSUE TITLE
Populate the username of a person in `save` method

### ISSUE THREAD

**Issue by aditnryn** [swcarpentry/amy#897]
Currently, the `username` field is being populated in the `form_valid` method of `PersonCreate` view.

Wouldn't it be better to populate the username field in the `save` method of `Person` model (if username is blank) as we would no longer have to worry about populating it every time before calling save.
@pbanaszkiewicz Should I add it to the `save` method?

**Comment by pbanaszkiewicz** [comment]
-1 on the iterative method of figuring out `username` in the `person.save()` method. You'd be making DB calls from `person.save`, which seems fishy to me (unless you convince me this is not wrong).

If only there was a better way than consecutive `SELECT`s to find out a username…

**Comment by narayanaditya95** [comment]
Yes, I didn't consider that.

**Comment by pbanaszkiewicz** [comment]
@narayanaditya95 can you research on alternative methods than iterative one? If we're stuck with the iterative method, I don't want to put that loop in the `save()` -- having one save do hundreds of saves feels like a bad idea to me.

**Comment by narayanaditya95** [comment]
@pbanaszkiewicz 
I do not intend to change the slug for an event object if it already exists. I wish to add a conditional to the save method when the `slug` field is not populated. This would prevent empty slug fields on executing `Person.objects.create(personal='...', family='...', email='...')`.

The diff is:
```py
class Person(AbstractBaseUser, PermissionsMixin):
     def save(self, *args, **kwargs):
         # save empty string as NULL to the database - otherwise there are
         # issues with UNIQUE constraint failing
+        if self.username:
+            self.username = create_username(
+                personal=form.cleaned_data['personal'],
+                family=form.cleaned_data['family']
+            )
         self.personal = self.personal.strip()
         self.family = self.family.strip()
         self.middle = self.middle.strip()
```
