### ISSUE TITLE
Better format to select tags

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#898]
Can we have a better format to select tags?  The current scrolling list makes it difficult to see which tags are selected when in 'edit' mode.

**Comment by maneesha** [comment]
This could be fixed by just making the box resizable.  Then the user can make it bigger if they wanted to see the whole list at once.

**Comment by pbanaszkiewicz** [comment]
@maneesha we can perhaps make all widgets for multiselection (such as tags) as long as the list of items so that all items are visible at once (ie. no resizing then), would that work?

**Comment by maneesha** [comment]
Yes.

**Comment by pbanaszkiewicz** [comment]
This probably requires some JS magic to automatically set `options.size` to the number of items it contains.

**Comment by maneesha** [comment]
User resizable or auto size -- what ever is easier.
Auto size might get unwieldy if we end up with fields that have many options - the widget could get really big.

**Comment by narayanaditya95** [comment]
I suggest we use buttons as checkboxes to select multiple tags. It is also responsive and works great with touch devices.

[Demo](http://www.bootply.com/iKosQHSrNf)

**Comment by pbanaszkiewicz** [comment]
@narayanaditya95 this might be silly, but if I didn't know AMY internals and how to roll back from a backup, I'd be very afraid to click anything that resembles a button that I didn't click before ;)

From dev point of view, neither of demo'd widgets shows its function (radio or multiselection) clearly.

**Comment by narayanaditya95** [comment]
Yes, it may be tough to distinguish between the selected and the non-selected checkboxes.
What are your views regarding [bootstrap-switch](http://www.bootstrap-switch.org/)? They convey the purpose.

**Comment by maneesha** [comment]
Any progress on this?  I think just having the box be resizable would meet my needs.

**Comment by chrismedrela** [comment]
@maneesha, it's planned for v1.10 and we'll take care of that after releasing v1.9.

This can be easily solved by adding `size="20"` to the `<select>` widget. However, for some reason, this doesn't work:

```python
    tag = django_filters.MultipleChoiceFilter(
        choices=TAG_CHOICES, name='tags', action=filter_tag_by_name,
        widget=SelectMultiple,
        attrs={'size': 10},
        # widget=SelectMultiple(attrs={'size': 10})  # does not work too
    )
```
