### ISSUE TITLE
Missing jquery.stickytabs.js

### ISSUE THREAD

**Issue by chrismedrela** [swcarpentry/amy#906]
Each page contains this line:
```html
<script src="{% static 'jquery-stickytabs/jquery.stickytabs.js' %}"></script>
```
which results in 404.

This bug exists also on amy-dev server.

**Comment by narayanaditya95** [comment]
Did you try `bower install`?

**Comment by chrismedrela** [comment]
No, I forgot. Now it works. ==> Closing.

**Comment by narayanaditya95** [comment]
Shouldn't `make serve` ensure `bower install` is executed?

**Comment by chrismedrela** [comment]
It does, but I run `python3 manage.py runserver`.

**Comment by gvwilson** [comment]
Trust the Makefile... :-)

**Comment by chrismedrela** [comment]
If I only knew how to configure Pycharm to use makefile. :)
