### ISSUE TITLE
Possible leakage of email addresses in "mail everyone"

### ISSUE THREAD

**Issue by chrismedrela** [swcarpentry/amy#907]
In a few places:
- https://github.com/swcarpentry/amy/blob/d9e9c32fea7cf978cf9c264bff50daeabd9e1823/workshops/templates/workshops/event.html#L129
- https://github.com/swcarpentry/amy/blob/d9e9c32fea7cf978cf9c264bff50daeabd9e1823/workshops/templates/workshops/instructors_by_date.html#L25
- https://github.com/swcarpentry/amy/blob/d9e9c32fea7cf978cf9c264bff50daeabd9e1823/workshops/templates/workshops/workshop_staff.html#L46

we use `mailto:bunch_of_emails`. These email addresses may end up in "To" field instead of "BCC" (correct me if I'm wrong). In that case, recipients can see other recipients' email adresses. However, I'm not sure if this is unwanted behaviour. @gvwilson, any opinion?

Fix: use `mailto:?bcc=` instead of `mailto:`.

**Comment by gvwilson** [comment]
:+1: to this change - good catch.
