### ISSUE TITLE
Access for `invoicing` group

### ISSUE THREAD

**Issue by pbanaszkiewicz** [swcarpentry/amy#912]
Person responsible for invoicing is not able to get to the invoicing request views.

@chrismedrela I suggest you to write decorator like `is_in_groups(['grp1', 'grp2'])` and then change `is_admin` to use `is_in_groups` with specified groups (`administrators`, `steering committee` and `invoicing` for now).

**Comment by chrismedrela** [comment]
What views should be accessible to members of `invoicing` group? If all, we can do the same what we did with `steering committee` group.

**Comment by gvwilson** [comment]
For now, please do what you did with the steering committee group.
