### ISSUE TITLE
Automation of deployment 

### ISSUE THREAD

**Issue by chrismedrela** [swcarpentry/amy#917]
So far, every time a contributor wants to deploy something to amy-dev, that person needs to hassle @pbanaszkiewicz and wait while he makes deploy. That has three drawbacks:

1) It's a lot of workload on Piotr.
2) When Piotr is unavailable, we cannot deploy.
3) The contributor needs to wait until Piotr checks mailbox.

I'm wondering if we could automate this process. This could looks like this: `nginx` could be configured to execute deployment script when we hit the server with specific HTTP request (let's say `amy-dev.software-carpentry.org/deploy`). In that case, the script pulls `amy-dev` branch and deploys it. The output of the script could be returned as the HTTP response, so if the deployment fails, you can tell why.

@gvwilson, @narayanaditya95, @pbanaszkiewicz, any opinions?

**Comment by narayanaditya95** [comment]
We might also want to deploy a branch from a fork.
I dont think an automated solution would be as simple as a hitting an endpoint.

**Comment by chrismedrela** [comment]
@narayanaditya95 We can pass repo URL in the HTTP request to the endpoint. Why do you think that it's not as easy as hitting an endpoint?

**Comment by pbanaszkiewicz** [comment]
> I'm wondering if we could automate this process. This could looks like this…

Or I can give you both credentials and instructions how to proceed when deploying on amy-dev. :-)

**Comment by gvwilson** [comment]
Can you write a shell script that does the entire deployment, leaving us 
in a workable state if anything goes wrong along the way?

**Comment by chrismedrela** [comment]
> Or I can give you both credentials and instructions how to proceed when deploying on amy-dev. :-)

Yeah, why didn't I thought about it earlier. :) 

The deployment script proposed by @gvwilson would be very useful. It'd be very nice if I could just execute something like that:
```bash
ssh amy-dev deploy https://github.com/swcarpentry/amy/tree/develop
```

**Comment by pbanaszkiewicz** [comment]
Unfortunately it'll take some time for me to do such a script because the amy-dev is running Django dev server on tmux session -- the easiest thing to set up.

**Comment by chrismedrela** [comment]
@pbanaszkiewicz, could you write down instructions how to deploy and give me credentials to login into AMY? Once you do this, I can write the script. Or we can even defer writing the script if the deployment procedure is easy and quick enough.

**Comment by chrismedrela** [comment]
@pbanaszkiewicz, could you give me credentials to amy-dev and a quick&dirty instruction on deployment? In next few days, I'll probably do a demo of what I've done this summer, and that's a chance for me to learn the deployment process.

**Comment by pbanaszkiewicz** [comment]
@chrismedrela @narayanaditya95 please email me your SSH public keys and I'll add you to the server.

The update procedure:

```bash
$ ssh address
$ tmux attach  # or just "tmux" if it's not running

# tmux is session manager, it should run in two panes side by side, one pane has normal terminal prompt and the other one has devserver running
# use ctrl+b,o (that means press ctrl+b, release, then press o)  to switch active pane
# use ctrl+b,d to deactivate tmux (close & run in background)
# use ctrl+b," to create a new vertical pane (if you accidentally closed one)
# use ctrl+b,% to create a new horizontal pane
```

1. Update code
  1. switch to `develop`
  2. make a new branch, switch to it
  3. pull the code
2. install updates if necessary `make upgrade`
3. prepare database - it is preferred to make a dev database from scratch and add an admin user and then add users, but you may want to only run migrations - depends on you
  1. `make dev_database` to remove database and recreate
  2. `make superuser` to create `admin:admin` superuser account
4. make sure the server is running in the server pane (it may be stuck OR some requests make it change font to some scribble)
  1. recreate pane if necessary (switch to it, ctrl+d to close running server, ctrl+d to close the pane, ctrl+b," to open a new pane)
  2. run server `cd ~/amy_site` and `./run_server.sh`

I hope I didn't forget anything.

**Comment by chrismedrela** [comment]
@pbanaszkiewicz please ping me when we can deploy to amy-dev.

**Comment by pbanaszkiewicz** [comment]
You can now (I'm still waiting for @narayanaditya95 public key).

**Comment by pbanaszkiewicz** [comment]
`amy-dev` server was shut down, but with #1164 and #1167 and #1203 scheduled for this release, I'd like to revisit the idea of continuous deployment of main AMY.

**Comment by pbanaszkiewicz** [comment]
I'd like to consider using a software-automation tool like [Ansible](https://www.ansible.com/) for easy software deployment.

**Comment by pbanaszkiewicz** [comment]
The Ansible playbooks were created for AMY, and will be used for future server deployment over at https://amy.carpentries.org/.
