### ISSUE TITLE
Autocomplete fields don't work on Safari

### ISSUE THREAD

**Issue by chrismedrela** [swcarpentry/amy#919]
These fields don't work for @raynamharris on Safari (but they work on Chrome).

@pbanaszkiewicz, you have mac, could you recreate this bug?

**Comment by chrismedrela** [comment]
These fields don't work for @k8hertweck too.

**Comment by pbanaszkiewicz** [comment]
> @pbanaszkiewicz, you have mac, could you recreate this bug?

Unfortunately I can't help you here -- I don't have a mac. @gvwilson for the rescue!

By the way, searching through https://github.com/mlavin/django-selectable/issues doesn't show anything Safari-related.

**Comment by chrismedrela** [comment]
@raynamharris @k8hertweck could you confirm whether autocomplete fields still don't work?

**Comment by narayanaditya95** [comment]
Works on Safari 10.0.2

**Comment by chrismedrela** [comment]
@narayanaditya95 thank you for your feedback. 

I'm closing this issue. @raynamharris @k8hertweck if you experience this issue again, please reopen it.
