### ISSUE TITLE
Need to be able to merge or delete redundant instructor training requests

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#921]
We now have duplicate instructor training requests (same name, same email address) - need some way to delete or merge these through the web interface.

**Comment by chrismedrela** [comment]
This PR #871 introduces discarding training requests through web interface. You can also delete requests permanently in django-admin. Is it enough?

**Comment by gvwilson** [comment]
Yup.

**Comment by chrismedrela** [comment]
Fixed in #871. You can now:

- discard training requests through admin interface or
- delete them permanently in django-admin.

**Comment by gvwilson** [comment]
Thanks.
