### ISSUE TITLE
Submission of filter forms in left sidebar

### ISSUE THREAD

**Issue by chrismedrela** [swcarpentry/amy#924]
It's not clear that you need to click "submit" button after changing filtering options in the left sidebar. It's also additional work. We could add a bit of JavaScript that automatically sends the form when we change a select, checkbox or radio field. On the other hand, if you want to change more than one field, page reloads may disrupt and slow you down. Any opinions?

**Comment by pbanaszkiewicz** [comment]
My opinion: I'm angry when some page loads very slowly, I need to apply a number of filters (e.g. when looking for a new laptop), and each one triggers a reload.

Unless people gave you feedback that they were confused by sidebar's form behavior, I'd stick to what we have now.

Also idea: maybe it would be enough to rename "Submit" to "Filter"?

**Comment by chrismedrela** [comment]
The current behavior wasn't clear for one user out of four that I had a walkthrough with.

Renaming is a good idea. We can also move the button at the beginning of the form. We can also make it flashing when you change any filter -- I think that this would solve this issue.

**Comment by gvwilson** [comment]
Please check with @maneesha before making changes.

**Comment by maneesha** [comment]
I have not had any problems with this and I haven't heard any complaints about it.  I don't think anything needs fixing.

I'd like to click on something (Filter or Submit, I don't care what the button is called) rather than having the page reload every time I select another field to filter on.

**Comment by chrismedrela** [comment]
OK, so I'm closing this issue.
