### ISSUE TITLE
Make filter sidebar floating

### ISSUE THREAD

**Issue by chrismedrela** [swcarpentry/amy#925]
The filter form in the left sidebar takes a bit of place. During walkthroughs, I noticed that a lot of AMY users use laptops and, therefore, monitors are pretty narrow.

I propose to make the sidebar working in similar way to [django-debug-sidebar](https://github.com/jazzband/django-debug-toolbar):
![image](https://cloud.githubusercontent.com/assets/1645996/17210476/8b9da5d6-54c3-11e6-85af-b16dbff55bde.png)
So that it's hidden by default. And when you open it, it's on top of the webpage.

**Comment by chrismedrela** [comment]
It could make sense to implement it along with #924.

**Comment by pbanaszkiewicz** [comment]
> The filter form in the left sidebar takes a bit of place. During walkthroughs, I noticed that a lot of AMY users use laptops and, therefore, monitors are pretty narrow.

This sidebar takes less than 17% of the horizontal length of the page. It should be enough on 1366x768 screen ([the most popular screen resolution](http://www.rapidtables.com/web/dev/screen-resolution-statistics.htm)):

![screen shot 2016-07-29 at 12 21 08](https://cloud.githubusercontent.com/assets/72821/17245504/165cedee-5587-11e6-83e9-be21df0111ab.png)

What resolutions did people use? What issues with this sidebar they encountered?

**Comment by chrismedrela** [comment]
Unfortunately, I don't remember resolutions. But some people don't maximize browser window which cases problems even when high resolution is available. And some of the AMY views are pretty overloaded (see [trainees list view](http://amy-dev.software-carpentry.org/workshops/trainees) -- and there is one more column now). 

I've just realized that what I proposed has one drawback -- if you want to filter, it requires one more click (to show the sidebar). So I propose something a bit different, that is the sidebar is visible by default and it's not floating (as we are doing now), but you can hide it if you want.

**Comment by pbanaszkiewicz** [comment]
> So I propose something a bit different, that is the sidebar is visible by default and it's not floating (as we are doing now), but you can hide it if you want.

Yeah, I wanted to suggest this solution but instead decided to ask for specific issues with current sidebar. Low priority for now, anyway.

**Comment by gvwilson** [comment]
@maneesha do you want this feature?

**Comment by maneesha** [comment]
I'm happy with it as is.

**Comment by gvwilson** [comment]
Closing since admin is happy.
