### ISSUE TITLE
Notes field in instructor profile update

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#927]
The form https://amy.software-carpentry.org/workshops/update_profile/ 
includes a place for the person to add in notes.  This should populate in the notes field for that person's record.

**Comment by pbanaszkiewicz** [comment]
Hmmm, the `notes` on Person record was intended to use by admins only, ie. perhaps someone wants to write a note "this person was expelled from workshop for CoC violation". If we populate it automatically, anyone could add any note to that field and then admins would not be able to trust any of existing notes.

@maneesha are you really sure you want this feature then?

**Comment by maneesha** [comment]
Perhaps we could have two fields then: one for user-generated notes and one for admin-generated notes.  As it is now, if the user submits notes they are no longer visible once the profile is updated.

**Comment by chrismedrela** [comment]
Ref #865 -- if we decide to turn off the form, this may be not worth implementing.

**Comment by maneesha** [comment]
#865 is waiting on response from @tracykteal

**Comment by gvwilson** [comment]
@tracykteal ping

**Comment by tracykteal** [comment]
I'm reading through this and https://github.com/swcarpentry/amy/issues/865 

What feedback do you need from me?

**Comment by gvwilson** [comment]
Do you think we need separate fields for admin-generated notes and user-generated notes?

**Comment by tracykteal** [comment]
Yes, it sounds like we do.

**Comment by gvwilson** [comment]
OK - Chris/Piotr, can you please add?
