### ISSUE TITLE
Functional tests

### ISSUE THREAD

**Issue by chrismedrela** [swcarpentry/amy#931]
There are two main reasons to introduce functional tests:

1. When you use `self.client` in a test and this tests fails, you can view only raw HTML. Finding form submission errors in raw HTML is not the most pleasant think. It'd be nice

2. You cannot test what happens when you load a webpage with a form, change one field in the form and submit the form. `self.client.post` is not a solution, because it requires to specify all fields' values.

When I was writing tests for #871, I experimented with Selenium on [selenium-experiments branch](https://github.com/chrismedrela/amy/tree/selenium-experiments). I've resigned from integrating Selenium for the following reasons:

- Selenium tests are pretty slow; one test executes in one second when using headless PhantomJS
- Selenium tests require to launch Django server (inheriting from `LiveServerTestCase`) which takes 8 seconds on my machine.
- Selenium is pretty low level and it takes a lot of time to write tests.

So, those two issues that I raised at the beginning still needs consideration. Any opinions?

**Comment by gvwilson** [comment]
Defer until after the summer.

**Comment by narayanaditya95** [comment]
Please consider [django-webtest](https://github.com/django-webtest/django-webtest) over Selenium.

**Comment by chrismedrela** [comment]
I've tested `django-webtest`:

- It's really fast. 

- There is [showbrowser() method](http://webtest.pythonpaste.org/en/latest/api.html#webtest.response.TestResponse.showbrowser) to see webpage in browser. It doesn't loads assets (like css), so the page is unformatted. But it's still better than raw HTML, so this is good enough workaround for the first issue.

- It solves the second issue.

- The API is very simple.

Here is an example test:

```python
from django_webtest import WebTest

class MyTestCase(WebTest):

    def testLogin(self):
        password = "admin"
        self.admin = Person.objects.create_superuser(
            username="admin", personal="Super", family="User",
            email="sudo@example.org", password=password)

        form = self.app.get(reverse('login')).form
        form['username'] = 'admin'
        form['password'] = 'admin'
        c = form.submit().follow().follow()

        c = c.click('Persons', index=0)
        c = c.click('Super User')
        c = c.click('Edit', index=0)

        f = c.forms[1]
        f.get('person-username').value = 'new-username'
        c = f.submit().follow()
        # c.showbrowser()
```
