### ISSUE TITLE
Select people to email from "Find staff" page

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#934]
When I run a search on this page I'd like to be able to select email addresses from the search results.  
Can we have a check box next to each name with a button "Email selected people" or "Select all" that will return a list of all their email addresses?

**Comment by pbanaszkiewicz** [comment]
We may actually look into bulk actions in other places as well -- and implement it the same way Django admin deals with it:
![screenshot from 2016-07-30 21 21 00](https://cloud.githubusercontent.com/assets/72821/17272619/99323f7a-569b-11e6-9fe3-b967c9c7907b.png)
