### ISSUE TITLE
Splitting amy.settings

### ISSUE THREAD

**Issue by narayanaditya95** [swcarpentry/amy#938]
Currently, we use a single settings file.
How about we divide `amy.settings.py` into a hierarchical structure to allow us to easily override settings according to different environments.

```
settings/
    base.py
    local.py
    prod.py
    pydata.py
```

**Comment by pbanaszkiewicz** [comment]
-1 (unless you have other reasons) because the preferred way is to vary params via environment variables.

**Comment by narayanaditya95** [comment]
There exist a lot of conditionals in `settings.py` of the form:

```py
if DEBUG:
     # override something
```

We can move these overrides to `local.py` as:

`local.py`
```py
from .base import *

# override something
```

**Comment by chrismedrela** [comment]
I'm :+1: for having only one `settings.py` file and overriding params via environment variables. This is also recommended by [The Twelve-Factor App](https://12factor.net/config).
