### ISSUE TITLE
Move 'tasks' section directly below 'notes' section in edit mode

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#943]
In view mode for an event, 'tasks' appear directly below 'notes' section.

In edit mode, the 'tasks' section is below the survey results and location section.  Moving it directly below 'notes' will make it easier to see the list of instructors and helpers in the 'notes' that need to be entered in to 'tasks.'

**Comment by pbanaszkiewicz** [comment]
Can we move notes under location section? It's part of the same form while tasks are not, and so it's easier to do.

**Comment by maneesha** [comment]
If the end result is that tasks is directly below notes, then yes, that works.
