### ISSUE TITLE
Hide section for survey results

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#944]
We've used a couple of different survey tools - this was requested in an earlier iteration of survey tools.  We're not recording these here now so I'd like to hide this from the view until we decide what to do.

**Comment by pbanaszkiewicz** [comment]
@maneesha hide in the form or in the event details or both?

**Comment by maneesha** [comment]
Both

**Comment by maneesha** [comment]
Reopening... 
this should also be hidden on the Edit Event view.

**Comment by narayanaditya95** [comment]
@maneesha 
The survey section is hidden on the `event_edit` view. Can you post a screenshot?

**Comment by narayanaditya95** [comment]
@maneesha Ping.

**Comment by maneesha** [comment]
This is from an older release... all looks good now.
