### ISSUE TITLE
Export badge: group by person

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#961]
This link:

https://amy.software-carpentry.org/workshops/export/badges

returns a JSON or YAML file that does not separate DC or SWC badges.

**Comment by gvwilson** [comment]
See also #979.

**Comment by pbanaszkiewicz** [comment]
@maneesha Can you please expand your idea here? The export feature shows separate entries for `dc-instructor` badge and `swc-instructor` badge.

**Comment by maneesha** [comment]
@pbanaszkiewicz  You're right - - it does show separate entries for `dc-instructor` badge and `swc-instructor` badges.  I didn't look closely enough to see the top level grouping is by badge, not person.  Something like this might be useful but not urgent or critical.  

`{"name":"Barack Obama", "user":"obama_barack", "badges" : [{"name":"swc-instructor": "awarded":"2013-08-14"}, {"name":"dc-instructor": "awarded":"2016-08-14"}]}, //...`

**Comment by chrismedrela** [comment]
@maneesha, https://amy.software-carpentry.org/api/v1/persons/ provides data you want in very similar format, except that `badges` is a list of badges' names without any other details like the date when the badge was awarded etc. Does it solve your issue?
