### ISSUE TITLE
Revise unique constraints on Task model

### ISSUE THREAD

**Issue by narayanaditya95** [swcarpentry/amy#966]
Two presentations by the same speaker in a PyData conference would cause an IntegrityError as they have the same `event`, `person` and `role`.
I propose we add `title` to the `unique_together` constraint.

@pbanaszkiewicz Suggestion.

**Comment by narayanaditya95** [comment]
@pbanaszkiewicz Ping

**Comment by narayanaditya95** [comment]
@pbanaszkiewicz This is a bug preventing us from saving multiple tasks belonging to the same speaker at a conference.

**Comment by pbanaszkiewicz** [comment]
@narayanaditya95 sorry for not taking care of this earlier!

I definitely agree with your suggestion.
