### ISSUE TITLE
Update DC self-organized workshops form

### ISSUE THREAD

**Issue by ErinBecker** [swcarpentry/amy#967]
For this form: https://amy.software-carpentry.org/workshops/dc/request_selforganized/ would it be possible to make the following changes?

1) Change the title from "Request" to "Register"
2) Add an "other" option to the question "Domain for the workshop"
3) Change the text in "Topics to be taught" from "... and the other modules in the same domain ..." to "...and three other modules in the same domain..."
4) Add an "other" option to the question "Topics to be taught"
5) For "Attendees' level of data analysis experience", add "Don't know yet" option.

@tracykteal @maneesha @pbanaszkiewicz

**Comment by ErinBecker** [comment]
@tracykteal @maneesha Should we go ahead and update the link for self-organized workshop requests to the current version of this survey in the interim? None of these changes seem super critical to me and the current link goes to the centrally-organized request form which has several unnecessary questions for people doing self-organized.

**Comment by pbanaszkiewicz** [comment]
@ErinBecker sorry for getting so late to this issue. I think I can make the changes today for the v1.8.

**Comment by ErinBecker** [comment]
@pbanaszkiewicz Thanks Piotr!
