### ISSUE TITLE
Bad links in training event display

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#970]
1. Go to https://amy.software-carpentry.org/workshops/trainings?page=2
2. Click on any of the links that supposedly lead to a training event.
3. 404

I understand why we want to retain this view - it's helpful to look at summary stats - but:

1. The links need to resolve.
2. We need to be able to sort chronologically with most recent first.

**Comment by chrismedrela** [comment]
PR: https://github.com/swcarpentry/amy/pull/974
