### ISSUE TITLE
Awkward display of information in trainee page

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#971]
1. Go to https://amy.software-carpentry.org/workshops/trainees

Display of "Progress" column is awkward:

![screen shot 2016-08-25 at 2 24 38 pm](https://cloud.githubusercontent.com/assets/911566/17980997/c08efad4-6acf-11e6-9961-8c364c67efdd.png)

See also this really awkward break that splits the green box around a word:

![screen shot 2016-08-25 at 2 29 15 pm](https://cloud.githubusercontent.com/assets/911566/17981135/585fe92c-6ad0-11e6-924f-4f45b733efa9.png)

**Comment by chrismedrela** [comment]
> Display of "Progress" column is awkward:

Well, if the "progress" column is too narrow to display everything in one line, the progress records wrap. Here is PR to make the column a bit wider: https://github.com/swcarpentry/amy/pull/973

> See also this really awkward break that splits the green box around a word:

I cannot reproduce it. What browser are you using? What is the browser width in pixels?

**Comment by chrismedrela** [comment]
OK, I reproduced it in Firefox with screen width = 1016 pixels. This looks like a bug in bootstrap, but I didn't find any bug report about this issue (although I didn't spend much time on searching).
