### ISSUE TITLE
Strange behavior when filtering events by tag

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#975]
1. Go to https://amy.software-carpentry.org/workshops/persons
2. Select 'TTT' under "Taught at workshops of type'.
3. Submit.

A *lot* of people come up (500 or more), almost none of whom have taught at TTT events.

**Comment by chrismedrela** [comment]
This is caused [here](https://github.com/swcarpentry/amy/blob/develop/workshops/filters.py#L193):

```python
    return queryset.filter(task__role__name='instructor') \
                   .filter(task__event__tags__in=values) \
                   .distinct()
```

We're looking for every person who was instructor on event A and participated in event B, that has appropriate tags. Instead, we want to ensure, that A and B are the same:

```python
    return queryset.filter(task__role__name='instructor',
                           task__event__tags__in=values) \
                   .distinct()
```

**Comment by gvwilson** [comment]
Thanks - can you please PR a fix?

**Comment by chrismedrela** [comment]
PR #1031
