### ISSUE TITLE
Add training status items to person display

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#976]
The page that displays information about a Person should also display their training status items, and allow them to be edited, just like the 'Training' display page does, so that if I search for a person by name and bring up that page, I can edit their information.

**Comment by chrismedrela** [comment]
When editing a person, do you want the progress to be displayed in a new tab, so that there are four tabs: person, awards, tasks and progress?

**Comment by gvwilson** [comment]
Good question - how about "if there is any progress, show it in a 
progress tab, but if there's not, don't show the tab"?
Thx,
G

**Comment by chrismedrela** [comment]
What if there is no progress yet, but we want to add a new one?

**Comment by gvwilson** [comment]
Glad one of us is awake :-)  Yes, please make the "Progress" tab always 
available.

**Comment by chrismedrela** [comment]
@gvwilson, would it be enough if you can edit training progress in person detailed view (and cannot do this in edit person view)? The detailed view would look like that:
![image](https://cloud.githubusercontent.com/assets/1645996/18912576/5e2025ca-8583-11e6-9484-2ecf4a0ed7b6.png)

**Comment by chrismedrela** [comment]
PR #1028

**Comment by gvwilson** [comment]
Sure.
