### ISSUE TITLE
Remove double-counting in display of instructors counts

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#978]
Looking at <https://amy.software-carpentry.org/workshops/reports/instructors_over_time>, there's a big spike early in 2016 when a lot of SWC instructors were given DC badges as well.  That's misleading: people shouldn't be double-counted.  Looking in api/views.py at `instructors_over_time`, it looks like we're counting everything in `self.queryset2` (that member name needs to be changed to something more meaningful...) and only then applying `.distinct()` to remove duplicates

**Comment by gvwilson** [comment]
Has this one been addressed? thx.

**Comment by pbanaszkiewicz** [comment]
@gvwilson so instead of showing when a person is awarded an instructor badge and aggregating that data by date, we should show first time person is awarded an instructor badge and then aggregate by date. Correct?

**Comment by gvwilson** [comment]
Yes please - and if the query specifies SWC, DC, or something else, we 
only show/count those.

**Comment by pbanaszkiewicz** [comment]
@gvwilson unfortunately I'm not sure how to solve this issue. Calling @chrismedrela @narayanaditya95 for help…

**Comment by chrismedrela** [comment]
PR #1043
