### ISSUE TITLE
Querying historical data with parameters

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#979]
Looking in `workshops/views.py` at `instructors_over_time`, it looks like there's no way to pass a particular badge or set of badges to the view.  I need to be able to query with something like `...url?badge=swc` to get instructors of a particular kind, both in the JSON/CSV/whatever data dump and in the graph. I will also be wanting to query workshops over time and learners over time with specific tags so that I can view SWC or DC or TTT workshops over time, participants in instructor training over time, etc.

**Comment by pbanaszkiewicz** [comment]
@gvwilson you need to specify what exactly you want to parametrize.

So far I have:

1. instructor's `badge` (or multiple badges - should they mean "show instructors with ALL these badges" or "with ANY of these badges"?) in `instructors_over_time`
2. event's `tag` in `workshops_over_time`
3. event's `tag` in `learners_over_time`
4. "participants in instructor training over time"? How do you want to parametrize participants?

**Comment by gvwilson** [comment]
1. Definitely need "with this one badge".
2. It would be nice to have both "and" and "or", but I'm not going to ask you to implement a full Boolean expression syntax in the query.  Let's go with "or" unless @maneesha or @tracykteal or @anenadic wants "and" instead.
3. For events, let's go with "and" as well so I can get "all TTT events", "all online TTT events", etc.
4. For participants over time, I think I want "learners over time at events with all of the following tags", so I can get "learners at DC events over time", "participants at TTT events over time", etc.

**Comment by anenadic** [comment]
I'd be happy with 'or' - thanks!

**Comment by maneesha** [comment]
I'm good with 'or'

**Comment by gvwilson** [comment]
"or" it is.

**Comment by chrismedrela** [comment]
@gvwilson what report do you mean whey you say "participants over time"? We have only workshops/learners/instructors over time reports.

**Comment by gvwilson** [comment]
Sorry for the imprecise language - I need to be able to ask for the number of people who took part in instructor training events vs. time. I think that means "give me learners in (workshops with the following tags)".
