### ISSUE TITLE
Filter trainees by "ready to be badged" status

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#980]
On the "Trainees" page, we'd like "Is SWC Instructor?" and "Is DC Instructor?" to have one more option each: "Eligible".  This would filter by people who have fulfilled requirements, but do not yet have the badge.  I know we can calculate this (it's what turns their marker green), and it would be very helpful when one person is marking completion of work and another is issuing badges.

**Comment by chrismedrela** [comment]
@gvwilson, what about combining "is SWC instructor" and "is DC instructor" filters into one choice filter with the following options:

- Unknown
- SWC and DC instructor
- *SWC or DC instructor*
- SWC instructor
- DC instructor
- *Eligible to be certified (SWC __or__ DC)*
- Not an instructor

*Italic choices* are combinations that you can't achieve having two separated fields.

**Comment by chrismedrela** [comment]
PR #1026 (without merging "is SWC instructor" and "is DC instructor" fields).

**Comment by gvwilson** [comment]
Looks good to me - only question is, what is "Unknown"?  Does it mean 
"don't care"?  (If AMY doesn't know, who does?)

**Comment by chrismedrela** [comment]
> Looks good to me

Do you mean the PR or the idea of merging "is SWC instructor" and "is DC instructor" filters?

>  only question is, what is "Unknown"?  Does it mean "don't care"?  (If AMY doesn't know, who does?)

Yes, it means "include every person regardless of their instructor status".

**Comment by gvwilson** [comment]
OK, "Unknown" probably isn't the right word (it means "we don't know" 
rather than "we don't care").

**Comment by chrismedrela** [comment]
> OK, "Unknown" probably isn't the right word (it means "we don't know" rather than "we don't care").

I agree, but on the other side, we use "unknown" in all places where there is BooleanFilter or ChoiceFilter and nobody has reported that it's confusing. If we want to change it, we should change it in all filters at once.

**Comment by gvwilson** [comment]
OK, let's make it "Unknown" and I'll file a PR to come up with a better 
word.

**Comment by chrismedrela** [comment]
I've updated the PR so that the two filters are merged into the one that I proposed.

**Comment by gvwilson** [comment]
Ready for review?

**Comment by chrismedrela** [comment]
Yes.

**Comment by chrismedrela** [comment]
@narayanaditya95 , could you review?
