### ISSUE TITLE
More ways to get to "issue badge"

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#981]
1. When I click on `[+]` in the "Progress" column and am taken to the "New training progress" page, one of the options there should be "issue badge".  I realize this isn't training progress, but it's a natural time and place to issue the badge.

2. Similarly, when I'm on the "Trainees" page, if I see someone is eligible but doesn't yet have a badge (i.e., they have a green box in the "Eligible?" column), I should be able to click on that and be taken to the "issue a badge" page.

**Comment by chrismedrela** [comment]
> 1. When I click on [+] in the "Progress" column and am taken to the "New training progress" page, one of the options there should be "issue badge". I realize this isn't training progress, but it's a natural time and place to issue the badge.

Is it enough to add at "new training progress" page a link redirecting to person edit view?

**Comment by gvwilson** [comment]
I like the automatic redirect back to the training progress page... If 
it's a pain to add "issue badge" to the "add progress" page, then sure.

**Comment by chrismedrela** [comment]
You can be redirected back to the training progress page from person edit view if you went there from "add progress" page.

**Comment by gvwilson** [comment]
Works for me - thanks.

**Comment by chrismedrela** [comment]
Here is PR #1018. This PR solves only the second issue. I have problems with adding a button in "new training progress" page. @pbanaszkiewicz, do you have any idea how I can do that? 

@gvwilson, questions:

1. When a person is eligible, you can click the `SWC` or `DC` label in `eligible` column to be moved to "issue a badge" form. Do you want the label to be clickable in the case when the person is not eligible (that is, when the label is grey)? This may be useful when we want to issue instructor badge in special cases when we don't require the person to go through standard checkout procedure.

2. In the PR, when you click one of the labels, you are moved to the "issue a badge" form with prefilled `badge` and `awarded` fields. Do you want the same for `event` (if the person took part in exactly one training) or/and `awarded by` fields?

**Comment by gvwilson** [comment]
1. Yes, it should be clickable even if the person doesn't yet have the 
official requirements - good thinking.

2. Yes for `event`, but I don't think we can automatically fill the 
`awarded by` field - it could be the person currently logged in, or the 
person who did the last part of their homework, or...

**Comment by chrismedrela** [comment]
> When I click on [+] in the "Progress" column and am taken to the "New training progress" page, one of the options there should be "issue badge". I realize this isn't training progress, but it's a natural time and place to issue the badge.

@gvwilson, I've fixed the second issue (not merged yet), but how important this one is?

**Comment by gvwilson** [comment]
It'll simplify things a little, but it's not essential - move it into a separate issue?

**Comment by chrismedrela** [comment]
I've moved it to a separate issue #1024. I don't know how it can be implemented (without messing with crispy forms templates) and it doesn't provide much value, so I'll focus on other issues first.
