### ISSUE TITLE
Change the way "reset" buttons work

### ISSUE THREAD

**Issue by chrismedrela** [swcarpentry/amy#984]
- Rename button from "reset" to "cancel".
- Make the button white instead of red.
- Redirect back to the last page in history.

**Comment by narayanaditya95** [comment]
Shouldn't a `Cancel` button also redirect back to the last page in history? Most `Cancel` buttons work that way.

**Comment by narayanaditya95** [comment]
I would suggest renaming it to `Discard all changes`.

**Comment by chrismedrela** [comment]
@narayanaditya95 , I'd stick with "cancel", because it's well understood by most people that "cancel" is the safe option when they get lost (thanks to cancel/ok and cancel/no/yes dialogs). I'd be afraid to click any button that includes "discard" verb.

**Comment by narayanaditya95** [comment]
The change you suggest would then not solve the issue @maneesha raised at #881 . Are you sure we want to change the functionality of the `Reset` button to a `Cancel` button?

**Comment by chrismedrela** [comment]
@narayanaditya95 , I don't understand, I think that the change I propose does solve the issue. @maneesha wrote in #881:
>  I'd also like to see a "cancel" button so that any changes accidentally made while in editing mode are not saved.

This is exactly what I propose.

**Comment by narayanaditya95** [comment]
My bad.

**Comment by pbanaszkiewicz** [comment]
@chrismedrela  What's the background for these changes?

**Comment by narayanaditya95** [comment]
@pbanaszkiewicz Please refer to the thread on amy-dev email list titled `two questions about tracking instructor training`

> 4. Nobody understands what the red "Reset" button on the "New training progress" page means.
