### ISSUE TITLE
Speakers at a PyData conference can have empty name field

### ISSUE THREAD

**Issue by narayanaditya95** [swcarpentry/amy#985]
When the `name` field for a speaker is empty, the accordion in the bulk import workflow does not have a header. This leads to a bug wherein we cannot open up the accordion to view the fields within it.

**Comment by pbanaszkiewicz** [comment]
@narayanaditya95 can you fix it during this weekend for the v1.8 or should I schedule for v1.9?

**Comment by narayanaditya95** [comment]
I will submit a fix today.
