### ISSUE TITLE
Headings hierarchy

### ISSUE THREAD

**Issue by pbanaszkiewicz** [swcarpentry/amy#99]
As I said in #98, I think there's an issue with our heading hierarchy on the page.

First we should put navigation, then content. Now we actually put navigation (ie. breadcrumbs) in the middle of the content:
![screenshot from 2014-12-21 19 26 58](https://cloud.githubusercontent.com/assets/72821/5519193/cb32b8e2-8947-11e4-9774-5e4436a6f186.png)

Look at Bootstrap page:
![screenshot from 2014-12-21 19 34 23](https://cloud.githubusercontent.com/assets/72821/5519207/be9114ca-8948-11e4-91ec-3a44f5486b85.png)

On Bootstrap page they start with navigation bar, then they introduce actual content (starting with `<h1>` header). In Amy we have "page title" (as a header), then navigation bar (as breadcrumbs), then content.

Any thought on changing that order?

**Comment by gvwilson** [comment]
See also #10.

**Comment by pbanaszkiewicz** [comment]
A navbar was introduced in #182.

This issue and #170 should be deferred for now - I can provide a PR for them in post-1.0 era.

**Comment by pbanaszkiewicz** [comment]
Amy's looking pretty good, so I think this can be closed now.
