### ISSUE TITLE
Instructors/workshops data export feature request

### ISSUE THREAD

**Issue by anenadic** [swcarpentry/amy#997]
I wanted to look at instructors per country (UK, more specifically) and workshops per country over a period of time (again, for UK) and could not do that either from the Events nor Persons. Also none of the reports available offered what I want. The reason why I need to look into this sort of data is because I want to look at spread of instructors per institution here in the UK as well as which institutions organise the most/least number of workshops per year. Would be good if we could have a spreadsheet export feature or an API endpoint for workshops and people. When you just look via the UI, for example people give you paged results with no country shown (just the nearest airport).

**Comment by chrismedrela** [comment]
> The reason why I need to look into this sort of data is because I want to look at spread of instructors per institution here in the UK as well as which institutions organise the most/least number of workshops per year. 

@anenadic, when you say "institution", do you mean host?

I don't think we can filter instructors by country since we don't track that information. We only track the nearest airport.

**Comment by anenadic** [comment]
Yes, by "institution" I meant "host". Country can be figured out by joining the instructors table with the airports, which has the country info. 'Instructors by country' would be a very useful feature I believe, not just for me.

**Comment by chrismedrela** [comment]
@anenadic, "Find Workshop Staff" let you search for instructors per country and it displays how often the instructors have taught. Does it solve your issue?

**Comment by anenadic** [comment]
Hi, I have already tried that before and "Find Workshop Staff" for country "UK" only returns 6 instructors  - so something is possibly wrong there. Also, I would like a spreadsheet export or an API access that would return all results rather than paged results shown in the UI.

**Comment by maneesha** [comment]
@anenadic  If you choose country == UK and check off DC and SWC badges then yes, you get 6 results.  This means only 6 people have both badges.  

Choosing country == UK and only SWC badge returns about 75 results.

I do agree that export to CSV would be useful.

**Comment by anenadic** [comment]
Oh, a misunderstanding on my part - I wrongly assumed it meant 'or'. Of course not. And it is great that affiliation is shown too (not sure it was being displayed last time I checked). Thank you. So if you want to close this one, we could open another issue about API access or spreadsheet export.

**Comment by chrismedrela** [comment]
@anenadic, do you need both API access and spreadsheet export, or is the latter enough?

**Comment by anenadic** [comment]
@chrismedrela Spreadsheet export is enough, but if you want to allow people to put parameters in (e.g. country=UK, badge=swc, startdate=2014-07-09, etc. for people and events) then there is more work on the UI side I suppose. Which is why I suggested the API approach, which, on the other hand, may be less user friendly for general public. Whatever approach is easier for you.

**Comment by chrismedrela** [comment]
So, to sum up the discussion, there are two new functionalities to be implemented:

1. Export to .csv the table from "find workshop stuff".

2. In "workshops/learners/instructors over time" reports, let people add the following parameters:

        - `badge` (in the case of learners/instructors)
        - `country` (in all three reports)
        - `startdate`, `enddate` (in all three reports)

    @anenadic @maneesha Is there anything else you want to filter by?

**Comment by anenadic** [comment]
@chrismedrela 

Yes, that pretty much sums it up.

1. If you can put name and email in separate columns that would be great.
2. Can we have a .csv export here too please? Startdate/enddate for instructors/learners should include all of them if not specified. For workshops - I'd include the slug and workshop URL and anything else of use.

Many thanks!
