### ISSUE TITLE
 'List of instructors by time period' report does not give a list of instructors

### ISSUE THREAD

**Issue by anenadic** [swcarpentry/amy#998]
'List of instructors by time period' under Reports gives a list of workshops rather than a list of instructors (possible naming error or misunderstanding on my part).

**Comment by maneesha** [comment]
This returns  a two column report display -- workshops and instructors (name, email, count of workshops taught).   You can download this as CSV if you need to manipulate that data in other ways.  You can also click the email link which will open your default email client with an email addressed to everyone in this list.

Is this what you are seeing?

**Comment by anenadic** [comment]
Yes, that is want I see. I was just looking after a list of all instructors with their countries and contact details. So I misunderstood the 'List of instructors by time period' - I thought that would be list of all instructors that became instructors in a certain period of time.

**Comment by maneesha** [comment]
I see.  So yes, this is a list instructors who *taught* in a given time period with their contact info -- not when they became instructors.  It does not include country.

**Comment by pbanaszkiewicz** [comment]
We weren't able to come up with a shorter description than "list of instructors by time period" (previously it was "Debrief" or similar, I believe). I'm closing this issue for now - if you have an idea how to improve this part of AMY, please reopen.
