### ISSUE TITLE
Update from valid URL causes "Network Connection Error"

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#999]
(title says it all)

**Comment by apawlik** [comment]
Same here.

![image](https://cloud.githubusercontent.com/assets/2358535/18492148/dd8400ec-7a5d-11e6-9ab9-518efbc25f14.png)

**Comment by narayanaditya95** [comment]
FWIW, I haven't been able to reproduce the error on either localhost or amy-dev with the same URL. So, it is a deployment issue.

**Comment by pbanaszkiewicz** [comment]
Closing since the error was due to outdated files (see #1003 for details).
